RELIC: src/fpx/relic_fpx_frb.c File Reference
relic_fpx_frb.c File Reference
Extensions of prime fields.
#include "relic_core.h"
#include "relic_pp_low.h"
Functions
void fp2_frb (fp2_t c, fp2_t a, int i)
void fp3_frb (fp3_t c, fp3_t a, int i)
void fp6_frb (fp6_t c, fp6_t a, int i)
void fp12_frb (fp12_t c, fp12_t a, int i)
void fp18_frb (fp18_t c, fp18_t a, int i)
Detailed Description
Implementation of frobenius action in extensions defined over prime fields.
Version
Id:
relic_fpx_frb.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_fpx_frb.c.
Function Documentation
void fp2_frb (fp2_t c, fp2_t a, int i)
Computes a power of the Frobenius map of a quadratic extension field element. When i is odd, this is the same as computing the conjugate of the extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension element to conjugate.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_fpx_frb.c.
References fp2_copy(), fp_copy(), and fp_neg.
Referenced by ep2_frb(), fp12_frb(), fp2_calc(), and fp6_frb().
void fp3_frb (fp3_t c, fp3_t a, int i)
Computes a power of the Frobenius map of a cubic extension field element.
Parameters
[out] c - the result.
[in] a - the cubic extension element to exponentiate.
[in] i - the power of the Frobenius map.
Definition at line 53 of file relic_fpx_frb.c.
References fp3_copy(), and fp3_mul_frb().
Referenced by fp18_frb(), and fp3_srt().
void fp6_frb (fp6_t c, fp6_t a, int i)
Computes a power of the Frobenius endomorphism of a sextic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a sextic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 67 of file relic_fpx_frb.c.
References fp2_copy(), fp2_frb(), fp2_mul_frb(), and fp2_neg().
void fp12_frb (fp12_t c, fp12_t a, int i)
Computes the Frobenius endomorphism of a dodecic extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a dodecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 82 of file relic_fpx_frb.c.
References fp2_copy(), fp2_frb(), fp2_mul_frb(), and fp2_neg().
Referenced by fp12_conv_cyc(), pp_exp_b12(), and pp_exp_bn().
void fp18_frb (fp18_t c, fp18_t a, int i)
Computes the Frobenius endomorphism of a octodecic extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a octodecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 125 of file relic_fpx_frb.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_copy(), fp3_frb(), fp3_free, fp3_mul_frb(), fp3_new, fp3_null, fp_copy(), THROW, and TRY.
Referenced by fp18_conv_cyc().