RELIC: src/bn/relic_bn_factor.c File Reference
relic_bn_factor.c File Reference
Multiple precision integer arithmetic.
#include "relic_core.h"
Functions
int bn_factor (bn_t c, const bn_t a)
int bn_is_factor (bn_t c, const bn_t a)
Detailed Description
Implementation of prime factorization algorithms.
Version
Id:
relic_bn_factor.c 1542 2013-08-28 18:31:47Z dfaranha
Definition in file relic_bn_factor.c.
Function Documentation
int bn_factor (bn_t c, const bn_t a)
Tries to factorize an integer using Pollard (p - 1) factoring algorithm. The maximum length of the returned factor is 16 bits.
Parameters
[out] c - the resulting factor.
[in] a - the integer to fatorize.
Returns
1 if a factor is found and stored into c; 0 otherwise.
Definition at line 38 of file relic_bn_factor.c.
References bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd, bn_is_even(), bn_mxp, bn_new, bn_null, bn_set_dig(), bn_sub_dig(), CATCH_ANY, CMP_GT, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
int bn_is_factor (bn_t c, const bn_t a)
Tests if an integer divides other integer.
Parameters
[in] c - the factor.
[in] a - the integer.
Returns
1 if the first integer is a factor; 0 otherwise.
Definition at line 85 of file relic_bn_factor.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.