RELIC: src/epx/relic_ep2_mul.c File Reference
relic_ep2_mul.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
void ep2_mul (ep2_t r, ep2_t p, bn_t k)
void ep2_mul_gen (ep2_t r, bn_t k)
void ep2_mul_dig (ep2_t r, ep2_t p, dig_t k)
Detailed Description
Implementation of point multiplication on prime elliptic curves over quadratic extensions.
Version
Id:
relic_ep2_mul.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_ep2_mul.c.
Function Documentation
void ep2_mul (ep2_t r, ep2_t p, bn_t k)
Multiplies a point in a elliptic curve over a quadratic extension by an integer scalar.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the scalar.
Definition at line 39 of file relic_ep2_mul.c.
References bn_bits(), bn_test_bit(), CATCH_ANY, ep2_add, ep2_copy(), ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_gen(), ep2_mul_sim_basic(), and ep2_rand().
void ep2_mul_gen (ep2_t r, bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 72 of file relic_ep2_mul.c.
References CATCH_ANY, ep2_curve_get_gen(), ep2_curve_get_tab(), ep2_free, ep2_mul(), ep2_mul_fix, ep2_new, ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_dig (ep2_t r, ep2_t p, dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 94 of file relic_ep2_mul.c.
References CATCH_ANY, ep2_add, ep2_copy(), ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, TRY, and util_bits_dig().