RELIC: src/cp/relic_cp_rsa.c File Reference
relic_cp_rsa.c File Reference
Cryptographic protocols.
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_rand.h"
#include "relic_bn.h"
#include "relic_util.h"
#include "relic_cp.h"
#include "relic_md.h"
Macros
#define RSA_PAD_LEN (11)
#define RSA_PUB (02)
#define RSA_PRV (01)
#define RSA_PAD (0xFF)
#define RSA_PSS (0xBC)
#define RSA_ENC 1
#define RSA_DEC 2
#define RSA_SIG 3
#define RSA_VER 4
#define RSA_ENC_FIN 5
#define RSA_SIG_FIN 6
#define RSA_SIG_HASH 7
#define RSA_VER_HASH 8
Functions
static unsigned char * hash_id (int md, int *len)
static int pad_pkcs1 (bn_t m, int *p_len, int m_len, int k_len, int operation)
int cp_rsa_gen_basic (rsa_t pub, rsa_t prv, int bits)
int cp_rsa_gen_quick (rsa_t pub, rsa_t prv, int bits)
int cp_rsa_enc (unsigned char *out, int *out_len, unsigned char *in, int in_len, rsa_t pub)
int cp_rsa_dec_basic (unsigned char *out, int *out_len, unsigned char *in, int in_len, rsa_t prv)
int cp_rsa_dec_quick (unsigned char *out, int *out_len, unsigned char *in, int in_len, rsa_t prv)
int cp_rsa_sig_basic (unsigned char *sig, int *sig_len, unsigned char *msg, int msg_len, int hash, rsa_t prv)
int cp_rsa_sig_quick (unsigned char *sig, int *sig_len, unsigned char *msg, int msg_len, int hash, rsa_t prv)
int cp_rsa_ver (unsigned char *sig, int sig_len, unsigned char *msg, int msg_len, int hash, rsa_t pub)
Variables
static const unsigned char shone_id []
static const unsigned char sh224_id []
static const unsigned char sh256_id []
static const unsigned char sh384_id []
static const unsigned char sh512_id []
Detailed Description
Implementation of the RSA cryptosystem.
Version
Id:
relic_cp_rsa.c 1571 2013-09-02 05:47:56Z dfaranha
Definition in file relic_cp_rsa.c.
Macro Definition Documentation
#define RSA_PAD_LEN (11)
Length of chosen padding scheme.
Definition at line 50 of file relic_cp_rsa.c.
Referenced by cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), and cp_rsa_ver().
#define RSA_PUB (02)
Identifier for encrypted messages.
Definition at line 60 of file relic_cp_rsa.c.
Referenced by pad_pkcs1().
#define RSA_PRV (01)
Identifier for signed messages.
Definition at line 65 of file relic_cp_rsa.c.
Referenced by pad_pkcs1().
#define RSA_PAD (0xFF)
Byte used as padding unit.
Definition at line 70 of file relic_cp_rsa.c.
Referenced by pad_pkcs1().
#define RSA_PSS (0xBC)
Byte used as padding unit in PSS signatures.
Definition at line 75 of file relic_cp_rsa.c.
#define RSA_ENC 1
Identifier for encryption.
Definition at line 80 of file relic_cp_rsa.c.
Referenced by cp_rsa_enc(), and pad_pkcs1().
#define RSA_DEC 2
Identifier for decryption.
Definition at line 85 of file relic_cp_rsa.c.
Referenced by cp_rsa_dec_basic(), cp_rsa_dec_quick(), and pad_pkcs1().
#define RSA_SIG 3
Identifier for signature.
Definition at line 90 of file relic_cp_rsa.c.
Referenced by cp_rsa_sig_basic(), cp_rsa_sig_quick(), and pad_pkcs1().
#define RSA_VER 4
Identifier for verification.
Definition at line 95 of file relic_cp_rsa.c.
Referenced by cp_rsa_ver(), and pad_pkcs1().
#define RSA_ENC_FIN 5
Identifier for second encryption step.
Definition at line 100 of file relic_cp_rsa.c.
Referenced by cp_rsa_enc().
#define RSA_SIG_FIN 6
Identifier for second sining step.
Definition at line 105 of file relic_cp_rsa.c.
Referenced by cp_rsa_sig_basic(), and cp_rsa_sig_quick().
#define RSA_SIG_HASH 7
Identifier for signature of a precomputed hash.
Definition at line 110 of file relic_cp_rsa.c.
Referenced by cp_rsa_sig_basic(), cp_rsa_sig_quick(), and pad_pkcs1().
#define RSA_VER_HASH 8
Identifier for verification of a precomputed hash.
Definition at line 115 of file relic_cp_rsa.c.
Referenced by cp_rsa_ver(), and pad_pkcs1().
Function Documentation
static unsigned char* hash_id (int md, int * len) static
Returns a pointer to the ASN.1 identifier of a hash function according to the PKCS#1 v1.5 padding standard.
Parameters
[in] md - the hash function.
[in,out] len - the length of the identifier.
Returns
The pointer to the hash function identifier.
Definition at line 223 of file relic_cp_rsa.c.
References ERR_NO_VALID, SH224, sh224_id, SH256, sh256_id, SH384, sh384_id, SH512, sh512_id, SHONE, shone_id, and THROW.
Referenced by pad_pkcs1().
static int pad_pkcs1 (bn_t m, int * p_len, int m_len, int k_len, int operation) static
Applies or removes a PKCS#1 v1.5 encryption padding.
Parameters
[out] m - the buffer to pad.
[out] p_len - the number of added pad bytes.
[in] m_len - the message length in bytes.
[in] k_len - the key length in bytes.
[in] operation - flag to indicate the operation type.
Returns
STS_ERR if errors occurred, STS_OK otherwise.
Definition at line 256 of file relic_cp_rsa.c.
References bn_add(), bn_add_dig(), bn_free, bn_is_zero(), bn_lsh(), bn_mod_2b(), bn_new, bn_null, bn_read_bin(), bn_rsh(), bn_zero(), CATCH_ANY, FINALLY, hash_id(), MD_MAP, rand_bytes(), RSA_DEC, RSA_ENC, RSA_PAD, RSA_PRV, RSA_PUB, RSA_SIG, RSA_SIG_HASH, RSA_VER, RSA_VER_HASH, STS_ERR, STS_OK, and TRY.
Referenced by cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), and cp_rsa_ver().
int cp_rsa_gen_basic (rsa_t pub, rsa_t prv, int bits)
Generates a new key pair for basic RSA algorithm.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] bits - the key length in bits.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 588 of file relic_cp_rsa.c.
References bn_add(), bn_add_dig(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_gen_prime, bn_mul, BN_NEG, bn_new, bn_null, bn_set_2b(), bn_sign(), bn_sub_dig(), CATCH_ANY, CMP_EQ, CMP_LT, FINALLY, STS_ERR, STS_OK, and TRY.
int cp_rsa_gen_quick (rsa_t pub, rsa_t prv, int bits)
Generates a new key RSA pair for fast operations with the CRT optimization.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] bits - the key length in bits.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 647 of file relic_cp_rsa.c.
References bn_add(), bn_add_dig(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_gen_prime, bn_mod, bn_mul, BN_NEG, bn_new, bn_null, bn_set_2b(), bn_sign(), bn_sub_dig(), CATCH_ANY, CMP_EQ, CMP_LT, FINALLY, STS_ERR, STS_OK, and TRY.
int cp_rsa_enc (unsigned char * out, int * out_len, unsigned char * in, int in_len, rsa_t pub)
Encrypts using the RSA cryptosystem.
Parameters
[out] out - the output buffer.
[out] out_len - the number of bytes written in the output buffer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] pub - the public key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 720 of file relic_cp_rsa.c.
References bn_add(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), bn_zero(), CATCH_ANY, FINALLY, pad_pkcs1(), RSA_ENC, RSA_ENC_FIN, RSA_PAD_LEN, STS_ERR, STS_OK, and TRY.
int cp_rsa_dec_basic (unsigned char * out, int * out_len, unsigned char * in, int in_len, rsa_t prv)
Decrypts using the basic RSA decryption method.
Parameters
[out] out - the output buffer.
[out] out_len - the number of bytes written in the output buffer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] prv - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 780 of file relic_cp_rsa.c.
References bn_cmp(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), CATCH_ANY, CMP_LT, FINALLY, pad_pkcs1(), RSA_DEC, RSA_PAD_LEN, STS_ERR, STS_OK, and TRY.
int cp_rsa_dec_quick (unsigned char * out, int * out_len, unsigned char * in, int in_len, rsa_t prv)
Decrypts using the fast RSA decryption with CRT optimization.
Parameters
[out] out - the output buffer.
[out] out_len - the number of bytes written in the output buffer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] prv - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 839 of file relic_cp_rsa.c.
References bn_add(), bn_cmp(), bn_copy(), bn_free, bn_mod, bn_mul, bn_mxp, BN_NEG, bn_new, bn_null, bn_read_bin(), bn_sign(), bn_size_bin(), bn_sub(), bn_write_bin(), CATCH_ANY, CMP_LT, FINALLY, pad_pkcs1(), RSA_DEC, RSA_PAD_LEN, STS_ERR, STS_OK, and TRY.
int cp_rsa_sig_basic (unsigned char * sig, int * sig_len, unsigned char * msg, int msg_len, int hash, rsa_t prv)
Signs using the basic RSA signature algorithm. The flag must be non-zero if the message being signed is already a hash value.
Parameters
[out] sig - the signature
[out] sig_len - the number of bytes written in the signature.
[in] msg - the message to sign.
[in] msg_len - the number of bytes to sign.
[in] hash - the flag to indicate the message format.
[in] prv - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 918 of file relic_cp_rsa.c.
References bn_add(), bn_bits(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), bn_zero(), CATCH_ANY, ERR_CAUGHT, FINALLY, MD_LEN, md_map, pad_pkcs1(), RSA_PAD_LEN, RSA_SIG, RSA_SIG_FIN, RSA_SIG_HASH, STS_ERR, STS_OK, THROW, and TRY.
int cp_rsa_sig_quick (unsigned char * sig, int * sig_len, unsigned char * msg, int msg_len, int hash, rsa_t prv)
Signs using the fast RSA signature algorithm with CRT optimization. The flag must be non-zero if the message being signed is already a hash value.
Parameters
[out] sig - the signature
[out] sig_len - the number of bytes written in the signature.
[in] msg - the message to sign.
[in] msg_len - the number of bytes to sign.
[in] hash - the flag to indicate the message format.
[in] prv - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 1001 of file relic_cp_rsa.c.
References bn_add(), bn_bits(), bn_copy(), bn_free, bn_mod, bn_mul, bn_mxp, BN_NEG, bn_new, bn_null, bn_read_bin(), bn_sign(), bn_size_bin(), bn_sub(), bn_write_bin(), bn_zero(), CATCH_ANY, ERR_CAUGHT, FINALLY, MD_LEN, md_map, pad_pkcs1(), RSA_PAD_LEN, RSA_SIG, RSA_SIG_FIN, RSA_SIG_HASH, STS_ERR, STS_OK, THROW, and TRY.
int cp_rsa_ver (unsigned char * sig, int sig_len, unsigned char * msg, int msg_len, int hash, rsa_t pub)
Verifies an RSA signature. The flag must be non-zero if the message being signed is already a hash value.
Parameters
[in] sig - the signature to verify.
[in] sig_len - the signature length in bytes.
[in] msg - the signed message.
[in] msg_len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] pub - the public key.
Returns
1 if the signature is valid, 0 otherwise.
Definition at line 1102 of file relic_cp_rsa.c.
References bn_bits(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), CATCH_ANY, CMP_EQ, FINALLY, MAX, md_map, pad_pkcs1(), RSA_PAD_LEN, RSA_VER, RSA_VER_HASH, STS_OK, TRY, and util_cmp_const().
Variable Documentation
const unsigned char shone_id[] static
Initial value:
=
        { 0x30, 0x21, 0x30, 0x09, 0x06, 0x05, 0x2b, 0x0e, 0x03, 0x02, 0x1a, 0x05, 0x00, 0x04, 0x14 }
ASN.1 identifier of the hash function SHA-1.
Definition at line 188 of file relic_cp_rsa.c.
Referenced by hash_id().
const unsigned char sh224_id[] static
Initial value:
=
        { 0x30, 0x2d, 0x30, 0x0d, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x04, 0x05, 0x00, 0x04, 0x1c }
ASN.1 identifier of the hash function SHA-224.
Definition at line 194 of file relic_cp_rsa.c.
Referenced by hash_id().
const unsigned char sh256_id[] static
Initial value:
=
        { 0x30, 0x31, 0x30, 0x0d, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x01, 0x05, 0x00, 0x04, 0x20 }
ASN.1 identifier of the hash function SHA-256.
Definition at line 200 of file relic_cp_rsa.c.
Referenced by hash_id().
const unsigned char sh384_id[] static
Initial value:
=
        { 0x30, 0x41, 0x30, 0x0d, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x02, 0x05, 0x00, 0x04, 0x30 }
ASN.1 identifier of the hash function SHA-384.
Definition at line 206 of file relic_cp_rsa.c.
Referenced by hash_id().
const unsigned char sh512_id[] static
Initial value:
=
        { 0x30, 0x51, 0x30, 0x0d, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x03, 0x05, 0x00, 0x04, 0x40 }
ASN.1 identifier of the hash function SHA-512.
Definition at line 212 of file relic_cp_rsa.c.
Referenced by hash_id().