RELIC: src/fp/relic_fp_rdc.c File Reference
relic_fp_rdc.c File Reference
Prime field arithmetic.
#include "relic_core.h"
#include "relic_bn_low.h"
#include "relic_fp_low.h"
Functions
void fp_rdc_basic (fp_t c, dv_t a)
void fp_rdc_monty_basic (fp_t c, dv_t a)
void fp_rdc_monty_comba (fp_t c, dv_t a)
void fp_rdc_quick (fp_t c, dv_t a)
Detailed Description
Implementation of the prime field modular reduction functions.
Version
Id:
relic_fp_rdc.c 1557 2013-08-30 06:31:37Z dfaranha
Definition in file relic_fp_rdc.c.
Function Documentation
void fp_rdc_basic (fp_t c, dv_t a)
Reduces a multiplication result modulo the prime field modulo using division-based reduction.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 42 of file relic_fp_rdc.c.
References bn_divn_low(), CATCH_ANY, dv_copy(), dv_free, dv_new, dv_null, ERR_CAUGHT, FINALLY, fp_copy(), FP_DIGS, fp_prime_get(), THROW, and TRY.
void fp_rdc_monty_basic (fp_t c, dv_t a)
Reduces a multiplication result modulo the prime field order using Shoolbook Montgomery reduction.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 77 of file relic_fp_rdc.c.
References bn_add1_low(), CMP_LT, fp_cmpn_low(), fp_copy(), FP_DIGS, fp_mula_low(), fp_prime_get(), fp_prime_get_rdc(), and fp_subn_low().
void fp_rdc_monty_comba (fp_t c, dv_t a)
Reduces a multiplication result modulo the prime field order using Comba Montgomery reduction.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 108 of file relic_fp_rdc.c.
References fp_rdcn_low().
void fp_rdc_quick (fp_t c, dv_t a)
Reduces a multiplication result modulo the prime field modulo using fast reduction.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 118 of file relic_fp_rdc.c.
References fp_prime_get(), and fp_rdcs_low().