RELIC: include/relic_arch.h File Reference
relic_arch.h File Reference
Architecture-dependent utilities.
#include "relic_types.h"
#include "relic_label.h"
Macros
#define STRING(STR) STR
#define FETCH(STR, ID, L) strncpy(STR, ID, L);
Functions
void arch_init (void)
void arch_clean (void)
ull_t arch_cycles (void)
Detailed Description
Interface of architecture-dependent functions.
Version
Id:
relic_arch.h 1513 2013-08-27 15:45:09Z dfaranha
Definition in file relic_arch.h.
Macro Definition Documentation
#define STRING (STR) STR
Chooses a proper way to store a string in the target architecture.
Parameters
[in] STR - the string to store.
Definition at line 58 of file relic_arch.h.
#define FETCH (STR, ID, L) strncpy(STR, ID, L);
Fetches a constant string to be used by the library.
Parameters
[out] STR - the resulting prepared parameter.
[in] ID - the parameter represented as a string.
[in] L - the length of the string.
Definition at line 71 of file relic_arch.h.
Function Documentation
void arch_init (void)
Performs architecture-dependent initialization.
Definition at line 44 of file relic_arch_arm.c.
Referenced by core_init().
void arch_clean (void)
Performs architecture-dependent finalization.
Definition at line 56 of file relic_arch_arm.c.
Referenced by core_clean().
ull_t arch_cycles (void)
Return the number of elapsed cycles.
Definition at line 60 of file relic_arch_arm.c.
Referenced by bench_after(), and bench_before().