RELIC: src/pp/relic_pp_map.c File Reference
relic_pp_map.c File Reference
Pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_mil_k2 (fp2_t r, ep_t t, ep_t p, ep_t q, bn_t a)
static void pp_mil_k12 (fp12_t r, ep2_t t, ep2_t q, ep_t p, bn_t a)
static void pp_mil_sps_k12 (fp12_t r, ep2_t t, ep2_t q, ep_t p, int *s, int len)
static void pp_mil_lit_k12 (fp12_t r, ep_t t, ep_t p, ep2_t q, bn_t a)
static void pp_fin_k12_oatep (fp12_t r, ep2_t t, ep2_t q, ep_t p)
void pp_map_init (void)
void pp_map_clean (void)
void pp_map_tatep_k2 (fp2_t r, ep_t p, ep_t q)
void pp_map_tatep_k12 (fp12_t r, ep_t p, ep2_t q)
void pp_map_weilp_k2 (fp2_t r, ep_t p, ep_t q)
void pp_map_weilp_k12 (fp12_t r, ep_t p, ep2_t q)
void pp_map_oatep_k12 (fp12_t r, ep_t p, ep2_t q)
Detailed Description
Implementation of the pairings over prime curves.
Version
Id:
relic_pp_map.c 1591 2013-09-03 08:20:25Z dfaranha
Definition in file relic_pp_map.c.
Function Documentation
static void pp_mil_k2 (fp2_t r, ep_t t, ep_t p, ep_t q, bn_t a) static
Compute the Miller loop for pairings of type G_2 x G_1 over the bits of a given parameter.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] p - the first point of the pairing, in G_1.
[in] q - the second point of the pairing, in G_1.
[in] a - the loop parameter.
Definition at line 50 of file relic_pp_map.c.
References bn_bits(), bn_test_bit(), CATCH_ANY, ep_copy(), ep_free, ep_neg, ep_new, ep_null, ERR_CAUGHT, FINALLY, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_zero(), fp_set_dig(), pp_add_k2, pp_dbl_k2, THROW, and TRY.
Referenced by pp_map_tatep_k2(), and pp_map_weilp_k2().
static void pp_mil_k12 (fp12_t r, ep2_t t, ep2_t q, ep_t p, bn_t a) static
Compute the Miller loop for pairings of type G_2 x G_1 over the bits of a given parameter.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the first point of the pairing, in G_2.
[in] p - the second point of the pairing, in G_1.
[in] a - the loop parameter.
Definition at line 97 of file relic_pp_map.c.
References bn_bits(), bn_test_bit(), CATCH_ANY, ep2_copy(), ep_free, ep_neg, ep_new, ep_null, ERR_CAUGHT, FINALLY, fp12_free, fp12_mul_dxs, fp12_new, fp12_null, fp12_sqr(), fp12_zero(), fp_set_dig(), pp_add_k12, pp_dbl_k12, THROW, and TRY.
Referenced by pp_map_weilp_k12().
static void pp_mil_sps_k12 (fp12_t r, ep2_t t, ep2_t q, ep_t p, int * s, int len) static
Compute the Miller loop for pairings of type G_2 x G_1 over the bits of a given parameter represented in sparse form.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the first point of the pairing, in G_2.
[in] p - the second point of the pairing, in G_1.
[in] s - the loop parameter in sparse form. ] len - the length of the loop parameter.
Definition at line 145 of file relic_pp_map.c.
References CATCH_ANY, ep2_copy(), ep2_free, ep2_neg, ep2_new, ep2_null, ep_free, ep_neg, ep_new, ep_null, ERR_CAUGHT, FINALLY, fp12_free, fp12_mul_dxs, fp12_new, fp12_null, fp12_sqr(), fp12_zero(), fp_set_dig(), pp_add_k12, pp_dbl_k12, THROW, and TRY.
Referenced by pp_map_oatep_k12().
static void pp_mil_lit_k12 (fp12_t r, ep_t t, ep_t p, ep2_t q, bn_t a) static
Compute the Miller loop for pairings of type G_1 x G_2 over the bits of a given parameter.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] p - the first point of the pairing, in G_1.
[in] q - the second point of the pairing, in G_2.
[in] a - the loop parameter.
Definition at line 201 of file relic_pp_map.c.
References bn_bits(), bn_test_bit(), CATCH_ANY, ep_copy(), ERR_CAUGHT, FINALLY, fp12_free, fp12_mul, fp12_new, fp12_null, fp12_sqr(), fp12_zero(), fp_set_dig(), pp_add_lit_k12(), pp_dbl_lit_k12(), THROW, and TRY.
Referenced by pp_map_tatep_k12(), and pp_map_weilp_k12().
static void pp_fin_k12_oatep (fp12_t r, ep2_t t, ep2_t q, ep_t p) static
Compute the final lines for optimal ate pairings.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the first point of the pairing, in G_2.
[in] p - the second point of the pairing, in G_1.
[in] a - the loop parameter.
Definition at line 242 of file relic_pp_map.c.
References CATCH_ANY, ep2_frb(), ep2_free, ep2_neg, ep2_new, ep2_null, ERR_CAUGHT, FINALLY, fp12_free, fp12_mul_dxs, fp12_new, fp12_null, fp12_zero(), fp_set_dig(), fp_zero(), pp_add_k12, THROW, and TRY.
Referenced by pp_map_oatep_k12().
void pp_map_init (void)
Initializes the pairing over prime fields.
Definition at line 283 of file relic_pp_map.c.
References ep2_curve_init().
Referenced by core_init().
void pp_map_clean (void)
Finalizes the pairing over prime fields.
Definition at line 287 of file relic_pp_map.c.
References ep2_curve_clean().
Referenced by core_clean().
void pp_map_tatep_k2 (fp2_t r, ep_t p, ep_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 293 of file relic_pp_map.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), CATCH_ANY, ep_curve_get_ord(), ep_free, ep_new, ep_null, ERR_CAUGHT, FINALLY, pp_exp_k2(), pp_mil_k2(), THROW, and TRY.
void pp_map_tatep_k12 (fp12_t r, ep_t p, ep2_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 323 of file relic_pp_map.c.
References bn_free, bn_new, bn_null, CATCH_ANY, ep_curve_get_ord(), ep_free, ep_new, ep_null, ERR_CAUGHT, FINALLY, pp_exp_k12(), pp_mil_lit_k12(), THROW, and TRY.
void pp_map_weilp_k2 (fp2_t r, ep_t p, ep_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 351 of file relic_pp_map.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), CATCH_ANY, ep2_free, ep_curve_get_ord(), ep_free, ep_new, ep_null, ERR_CAUGHT, FINALLY, fp2_free, fp2_inv(), fp2_mul, fp2_new, fp2_null, pp_mil_k2(), THROW, and TRY.
void pp_map_weilp_k12 (fp12_t r, ep_t p, ep2_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 390 of file relic_pp_map.c.
References bn_free, bn_new, bn_null, CATCH_ANY, ep2_free, ep2_new, ep2_null, ep_curve_get_ord(), ep_free, ep_new, ep_null, ERR_CAUGHT, FINALLY, fp12_free, fp12_inv(), fp12_inv_uni(), fp12_mul, fp12_new, fp12_null, pp_mil_k12(), pp_mil_lit_k12(), THROW, and TRY.
void pp_map_oatep_k12 (fp12_t r, ep_t p, ep2_t q)
Computes the optimal ate pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 436 of file relic_pp_map.c.
References B12_P638, bn_free, BN_NEG, bn_new, bn_null, BN_P158, BN_P254, BN_P256, BN_P638, bn_sign(), CATCH_ANY, ep2_free, ep2_neg, ep2_new, ep2_null, ep_param_get(), ERR_CAUGHT, FINALLY, fp12_inv_uni(), FP_BITS, fp_param_get_map(), fp_param_get_var(), pp_exp_k12(), pp_fin_k12_oatep(), pp_mil_sps_k12(), THROW, and TRY.