RELIC: src/fp/relic_fp_shift.c File Reference
relic_fp_shift.c File Reference
Prime field arithmetic.
#include "relic_core.h"
#include "relic_fp_low.h"
Functions
void fp_lsh (fp_t c, const fp_t a, int bits)
void fp_rsh (fp_t c, const fp_t a, int bits)
Detailed Description
Implementation of the prime field arithmetic shift functions.
Version
Id:
relic_fp_shift.c 1552 2013-08-30 04:11:47Z dfaranha
Definition in file relic_fp_shift.c.
Function Documentation
void fp_lsh (fp_t c, const fp_t a, int bits)
Shifts a prime field element number to the left. Computes c = a * 2^bits.
Parameters
[out] c - the result.
[in] a - the prime field element to shift.
[in] bits - the number of bits to shift.
Definition at line 39 of file relic_fp_shift.c.
References fp_copy(), FP_DIG_LOG, fp_lsh1_low(), fp_lshb_low(), fp_lshd_low(), and SPLIT.
void fp_rsh (fp_t c, const fp_t a, int bits)
Shifts a prime field element to the right. Computes c = floor(a / 2^bits).
Parameters
[out] c - the result.
[in] a - the prime field element to shift.
[in] bits - the number of bits to shift.
Definition at line 65 of file relic_fp_shift.c.
References fp_copy(), FP_DIG_LOG, fp_rsh1_low(), fp_rshb_low(), fp_rshd_low(), and SPLIT.