RELIC: src/pp/relic_pp_dbl.c File Reference
relic_pp_dbl.c File Reference
Pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_pp_low.h"
#include "relic_util.h"
Functions
void pp_dbl_k2_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
void pp_dbl_k12_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k2_projc_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
void pp_dbl_k12_projc_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k2_projc_lazyr (fp2_t l, ep_t r, ep_t p, ep_t q)
void pp_dbl_k12_projc_lazyr (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_lit_k12 (fp12_t l, ep_t r, ep_t p, ep2_t q)
Detailed Description
Implementation of the Miller doubling function.
Version
Id:
relic_pp_dbl.c 1524 2013-08-27 16:52:25Z dfaranha
Definition in file relic_pp_dbl.c.
Function Documentation
void pp_dbl_k2_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 43 of file relic_pp_dbl.c.
References CATCH_ANY, ep_copy(), ep_dbl_slp_basic(), ep_free, ep_new, ep_null, ERR_CAUGHT, FINALLY, fp2_zero(), fp_add, fp_copy(), fp_free, fp_mul, fp_new, fp_null, fp_sub, THROW, and TRY.
void pp_dbl_k12_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 69 of file relic_pp_dbl.c.
References CATCH_ANY, ep2_copy(), ep2_curve_is_twist(), ep2_dbl_slp_basic(), ep2_free, ep2_new, ep2_null, EP_MTYPE, ERR_CAUGHT, FINALLY, fp12_zero(), fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sub, fp_copy(), fp_mul, THROW, and TRY.
void pp_dbl_k2_projc_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 109 of file relic_pp_dbl.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, THROW, and TRY.
void pp_dbl_k12_projc_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 194 of file relic_pp_dbl.c.
References CATCH_ANY, ep2_curve_get_b(), ep2_curve_is_twist(), ep_curve_opt_b(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_add, fp_hlv, fp_mul, fp_sub, OPT_TWO, THROW, and TRY.
void pp_dbl_k2_projc_lazyr (fp2_t l, ep_t r, ep_t p, ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 352 of file relic_pp_dbl.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_add, fp_dbl, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, THROW, and TRY.
void pp_dbl_k12_projc_lazyr (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 436 of file relic_pp_dbl.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ep2_curve_get_b(), ep2_curve_is_twist(), ep_curve_opt_b(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_add, fp2_addd_low(), fp2_addn_low(), fp2_dbl, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_rdcn_low(), fp2_sqr, fp2_sqrn_low(), fp2_sub, fp2_subc_low(), fp_add, fp_hlv, fp_mul, fp_sub, OPT_TWO, THROW, and TRY.
void pp_dbl_lit_k12 (fp12_t l, ep_t r, ep_t p, ep2_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 609 of file relic_pp_dbl.c.
References CATCH_ANY, ep2_curve_is_twist(), ep_curve_get_b(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_add, fp2_dbl, fp_add, fp_dbl, fp_free, fp_mul, fp_neg, fp_new, fp_null, fp_sqr, fp_sub, fp_zero(), THROW, and TRY.
Referenced by pp_mil_lit_k12().