RELIC: src/relic_err.c File Reference
relic_err.c File Reference
Core functions.
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_err.h"
#include <execinfo.h>
Functions
void err_simple_msg (int error)
void err_full_msg (const char *function, const char *file, int line, int error)
void err_get_msg (err_t *e, char **msg)
int err_get_code (void)
Detailed Description
Implementation of error-handling routines.
Version
Id:
relic_err.c 1512 2013-08-27 15:42:01Z dfaranha
Definition in file relic_err.c.
Function Documentation
void err_simple_msg (int error)
Prints the error message with little information.
Parameters
[in] error - the error code.
Definition at line 51 of file relic_err.c.
References core_get(), and ERR_CAUGHT.
void err_full_msg (const char * function, const char * file, int line, int error)
Prints the error message with detailed information.
Parameters
[in] function - the function where the error occurred.
[in] file - the source file where the error occurred.
[in] line - the line in the file where the error occurred.
[in] error - the error code.
Definition at line 59 of file relic_err.c.
References core_get(), ERR_CAUGHT, and _ctx_t::reason.
void err_get_msg (err_t * e, char ** msg)
Prints the error message respective to an error code.
Parameters
[out] e - the error occurred.
[out] msg - the error message.
Definition at line 92 of file relic_err.c.
References core_get(), _sts_t::error, _ctx_t::last, and _ctx_t::reason.
int err_get_code (void)
Returns the code returned by the last function call and resets the current code.
Returns
ERR_OK if no errors occurred in the function, ERR_ERR otherwise.
Definition at line 101 of file relic_err.c.
References _ctx_t::code, core_get(), and STS_OK.