RELIC: src/epx/relic_ep2_norm.c File Reference
relic_ep2_norm.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep2_norm_imp (ep2_t r, ep2_t p)
void ep2_norm (ep2_t r, ep2_t p)
Detailed Description
Implementation of point normalization on prime elliptic curves over quadratic extensions.
Version
Id:
relic_ep2_norm.c 1589 2013-09-03 08:19:40Z dfaranha
Definition in file relic_ep2_norm.c.
Function Documentation
static void ep2_norm_imp (ep2_t r, ep2_t p) static
Normalizes a point represented in projective coordinates.
Parameters
r - the result.
p - the point to normalize.
Definition at line 47 of file relic_ep2_norm.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_inv(), fp2_mul, fp2_new, fp2_null, fp2_sqr, fp_set_dig(), fp_zero(), THROW, and TRY.
Referenced by ep2_norm().
void ep2_norm (ep2_t r, ep2_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 85 of file relic_ep2_norm.c.
References ep2_copy(), ep2_is_infty(), ep2_norm_imp(), and ep2_set_infty().
Referenced by ep2_is_valid(), ep2_mul(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_nafwi(), ep2_mul_fix_ordin(), ep2_mul_fix_yaowi(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_ordin(), ep2_mul_sim_basic(), ep2_mul_sim_joint(), ep2_mul_sim_ordin(), ep2_mul_sim_trick(), and ep2_tab().