#
# University of Luxembourg
# Laboratory of Algorithmics, Cryptology and Security (LACS)
#
# FigureOfMerit (FOM)
#
# Copyright (C) 2015 University of Luxembourg
#
# Written in 2015 by Daniel Dinu <dumitru-daniel.dinu@uni.lu>
#
# This file is part of FigureOfMerit.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


__author__ = 'daniel.dinu'


# Input
CSV_DELIMITER = ','
CSV_QUOTECHAR = '"'
CSV_LINETERMINATOR = '\n'


# Triathlon competitors
TRIATHLON_COMPETITORS_CSV_FILE = 'Input/CiphersInfo/Triathlon.csv'
TRIATHLON_COMPETITORS_CSV_HEADER_LINES = 1

TRIATHLON_COMPETITORS_FULL_NAME_COLUMN_INDEX = 0
TRIATHLON_COMPETITORS_SUBMISSION_DATE_COLUMN_INDEX = 1
TRIATHLON_COMPETITORS_B1_COUNT_COLUMN_INDEX = 2
TRIATHLON_COMPETITORS_B2_COUNT_COLUMN_INDEX = 3
TRIATHLON_COMPETITORS_B3_COUNT_COLUMN_INDEX = 4
TRIATHLON_COMPETITORS_B4_COUNT_COLUMN_INDEX = 5
TRIATHLON_COMPETITORS_B5_COUNT_COLUMN_INDEX = 6


# Implementations info
IMPLEMENTATIONS_INFO_CSV_FILE_PATH_FORMAT = 'Input/Info/{0}_info.csv'
IMPLEMENTATIONS_INFO_CSV_FILE_PREFIX = 'FELICS'
IMPLEMENTATIONS_INFO_CSV_HEADER_LINES = 1


IMPLEMENTATIONS_INFO_CIPHER_NAME_COLUMN_INDEX = 0
IMPLEMENTATIONS_INFO_BLOCK_SIZE_COLUMN_INDEX = 1
IMPLEMENTATIONS_INFO_KEY_SIZE_COLUMN_INDEX = 2
IMPLEMENTATIONS_INFO_IMPLEMENTATION_VERSION_COLUMN_INDEX = 3
IMPLEMENTATIONS_INFO_IMPLEMENTATION_DESCRIPTION_COLUMN_INDEX = 4
IMPLEMENTATIONS_INFO_IMPLEMENTERS_COLUMN_INDEX = 5

IMPLEMENTERS_INITIAL_SEPARATOR1 = ','
IMPLEMENTERS_INITIAL_SEPARATOR2 = ' and'
IMPLEMENTERS_SEPARATOR = ', '


# Scenario 1 statistics
SCENARIO1_STATISTICS_CSV_FILE = "Output/scenario1_statistics.csv"
SCENARIO1_STATISTICS_CSV_HEADER_LINES = 1

SCENARIO1_STATISTICS_FULL_NAME_COLUMN_INDEX = 0
SCENARIO1_STATISTICS_P1_POSITION_COLUMN_INDEX = 1
SCENARIO1_STATISTICS_P1_ENTRIES_COLUMN_INDEX = 2


# Scenario 2 statistics
SCENARIO2_STATISTICS_CSV_FILE = "Output/scenario2_statistics.csv"
SCENARIO2_STATISTICS_CSV_HEADER_LINES = 1

SCENARIO2_STATISTICS_FULL_NAME_COLUMN_INDEX = 0
SCENARIO2_STATISTICS_P2_POSITION_COLUMN_INDEX = 1
SCENARIO2_STATISTICS_P2_ENTRIES_COLUMN_INDEX = 2
SCENARIO2_STATISTICS_P3_ENTRIES_COLUMN_INDEX = 3
SCENARIO2_STATISTICS_P4_ENTRIES_COLUMN_INDEX = 4


# Weights
P1_WEIGHT = 10
P2_WEIGHT = 10
P3_WEIGHT = 20
P4_WEIGHT = 20

B1_WEIGHT = 100
B2_WEIGHT = 50
B3_WEIGHT = 10
B4_WEIGHT = 50
B5_WEIGHT = 10


# Output
TRIATHLON_RESULT_PLAYERS_MEDIAWIKI_FILE_PATH = 'Output/TriathlonResultsPlayers.mkw'
TRIATHLON_RESULT_IMPLEMENTATIONS_MEDIAWIKI_FILE_PATH = 'Output/TriathlonResultsImplementations.mkw'

TRIATHLON_RESULT_FILE_ACCESS_MODE = 'w'

TRIATHLON_PLAYERS_MEDIAWIKI_ROW_FORMAT = '|-\n! {}\n| {}\n'
TRIATHLON_IMPLEMENTATIONS_MEDIAWIKI_ROW_FORMAT = '|-\n! {}\n| {}\n| {}\n| {}\n'


# Statistics csv
IMPLEMENTATION_FULL_NAME_FORMAT = '{}_{}_{}_v{}'
