RELIC: include/relic_fbx.h File Reference
relic_fbx.h File Reference
Extensions of binary fields.
#include "relic_fb.h"
#include "relic_types.h"
Macros
#define fb2_null(A) fb_null(A[0]); fb_null(A[1]); \
#define fb2_new(A) fb_new(A[0]); fb_new(A[1]); \
#define fb2_free(A) fb_free(A[0]); fb_free(A[1]); \
#define fb2_copy(C, A) fb_copy(C[0], A[0]); fb_copy(C[1], A[1]); \
#define fb2_neg(C, A) fb_neg(C[0], A[0]); fb_neg(C[1], A[1]); \
#define fb2_zero(A) fb_zero(A[0]); fb_zero(A[1]); \
#define fb2_is_zero(A) (fb_is_zero(A[0]) && fb_is_zero(A[1])) \
#define fb2_rand(A) fb_rand(A[0]); fb_rand(A[1]); \
#define fb2_print(A) fb_print(A[0]); fb_print(A[1]); \
#define fb2_cmp(A, B)
#define fb2_add(C, A, B) fb_add(C[0], A[0], B[0]); fb_add(C[1], A[1], B[1]); \
#define fb2_sub(C, A, B) fb_sub(C[0], A[0], B[0]); fb_sub(C[1], A[1], B[1]); \
#define fb4_null(A) fb_null(A[0]); fb_null(A[1]); fb_null(A[2]); fb_null(A[3]); \
#define fb4_new(A) fb_new(A[0]); fb_new(A[1]); fb_new(A[2]); fb_new(A[3]); \
#define fb4_free(A) fb_free(A[0]); fb_free(A[1]); fb_free(A[2]); fb_free(A[3]); \
#define fb4_copy(C, A)
#define fb4_neg(C, A)
#define fb4_zero(A) fb_zero(A[0]); fb_zero(A[1]); fb_zero(A[2]); fb_zero(A[3]); \
#define fb4_set_dig(C, A) fb_set_dig(C[0], A); fb_zero(C[1]); fb_zero(C[2]); fb_zero(C[3]); \
#define fb4_is_zero(A)
#define fb4_rand(A) fb_rand(A[0]); fb_rand(A[1]); fb_rand(A[2]); fb_rand(A[3]); \
#define fb4_print(A) fb_print(A[0]); fb_print(A[1]); fb_print(A[2]); fb_print(A[3]); \
#define fb4_cmp(A, B)
#define fb4_cmp_dig(A, B)
#define fb4_add(C, A, B)
#define fb4_sub(C, A, B)
Typedefs
typedef fb_t fb2_t [2]
typedef fb_t fb4_t [4]
Functions
void fb2_mul (fb2_t c, fb2_t a, fb2_t b)
void fb2_mul_nor (fb2_t c, fb2_t a)
void fb2_sqr (fb2_t c, fb2_t a)
void fb2_slv (fb2_t c, fb2_t a)
void fb2_inv (fb2_t c, fb2_t a)
void fb4_mul (fb4_t c, fb4_t a, fb4_t b)
void fb4_mul_dxd (fb4_t c, fb4_t a, fb4_t b)
void fb4_mul_dxs (fb4_t c, fb4_t a, fb4_t b)
void fb4_mul_sxs (fb4_t c, fb4_t a, fb4_t b)
void fb4_sqr (fb4_t c, fb4_t a)
void fb4_inv (fb2_t c, fb2_t a)
void fb4_exp (fb4_t c, fb4_t a, bn_t b)
void fb4_frb (fb4_t c, fb4_t a)
Detailed Description
Interface of the module for extension field arithmetic over binary fields.
Version
$Id$
Definition in file relic_fbx.h.
Macro Definition Documentation
#define fb2_null (A) fb_null(A[0]); fb_null(A[1]); \
Initializes a quadratic extension binary field with a null value.
Parameters
[out] A - the quadratic extension element to initialize.
Definition at line 72 of file relic_fbx.h.
Referenced by etat_exp(), and fb4_inv().
#define fb2_new (A) fb_new(A[0]); fb_new(A[1]); \
Calls a function to allocate a quadratic extension binary field element.
Parameters
[out] A - the new quadratic extension field element.
Definition at line 80 of file relic_fbx.h.
Referenced by etat_exp(), and fb4_inv().
#define fb2_free (A) fb_free(A[0]); fb_free(A[1]); \
Calls a function to free a quadratic extension binary field element.
Parameters
[out] A - the quadratic extension field element to free.
Definition at line 88 of file relic_fbx.h.
Referenced by etat_exp(), and fb4_inv().
#define fb2_copy (C, A) fb_copy(C[0], A[0]); fb_copy(C[1], A[1]); \
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the quadratic extension field element to copy.
Definition at line 97 of file relic_fbx.h.
Referenced by etat_exp(), and fb4_inv().
#define fb2_neg (C, A) fb_neg(C[0], A[0]); fb_neg(C[1], A[1]); \
Negates a quadratic extension field element.
f
Parameters
[out] C - the result.
[out] A - the quadratic extension field element to negate.
Definition at line 106 of file relic_fbx.h.
#define fb2_zero (A) fb_zero(A[0]); fb_zero(A[1]); \
Assigns zero to a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to zero.
Definition at line 114 of file relic_fbx.h.
#define fb2_is_zero (A) (fb_is_zero(A[0]) && fb_is_zero(A[1])) \
Tests if a quadratic extension field element is zero or not.
Parameters
[in] A - the quadratic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 123 of file relic_fbx.h.
#define fb2_rand (A) fb_rand(A[0]); fb_rand(A[1]); \
Assigns a random value to a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to assign.
Definition at line 131 of file relic_fbx.h.
#define fb2_print (A) fb_print(A[0]); fb_print(A[1]); \
Prints a quadratic extension field element to standard output.
Parameters
[in] A - the quadratic extension field element to print.
Definition at line 139 of file relic_fbx.h.
#define fb2_cmp (A, B)
Value:
((fb_cmp(A[0], B[0]) == CMP_EQ) && (fb_cmp(A[1], B[1]) == CMP_EQ)   \
        ? CMP_EQ : CMP_NE)                                                  \
Returns the result of a comparison between two quadratic extension field elements
Parameters
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Returns
CMP_NE if a != b, CMP_EQ if a == b.
Definition at line 150 of file relic_fbx.h.
#define fb2_add (C, A, B) fb_add(C[0], A[0], B[0]); fb_add(C[1], A[1], B[1]); \
Adds two quadratic extension field elements. Computes c = a + b.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Definition at line 161 of file relic_fbx.h.
Referenced by etat_exp(), and fb4_inv().
#define fb2_sub (C, A, B) fb_sub(C[0], A[0], B[0]); fb_sub(C[1], A[1], B[1]); \
Subtracts a quadratic extension field element from another. Computes c = a - b.
Parameters
[out] C - the result.
[in] A - the quadratic extension binary field element.
[in] B - the quadratic extension binary field element.
Definition at line 172 of file relic_fbx.h.
#define fb4_null (A) fb_null(A[0]); fb_null(A[1]); fb_null(A[2]); fb_null(A[3]); \
Initializes a quadratic extension binary field with a null value.
Parameters
[out] A - the quartic extension element to initialize.
Definition at line 180 of file relic_fbx.h.
Referenced by etat_exp(), fb4_exp(), fb4_mul_dxd(), pb_map_etatn_imp(), and pb_map_etats_imp().
#define fb4_new (A) fb_new(A[0]); fb_new(A[1]); fb_new(A[2]); fb_new(A[3]); \
Calls a funtion to allocate a quartic extension binary field element.
Parameters
[out] A - the new quartic extension field element.
Definition at line 188 of file relic_fbx.h.
Referenced by etat_exp(), fb4_exp(), fb4_mul_dxd(), pb_map_etatn_imp(), and pb_map_etats_imp().
#define fb4_free (A) fb_free(A[0]); fb_free(A[1]); fb_free(A[2]); fb_free(A[3]); \
Calls a function to free a quartic extension binary field element.
Parameters
[out] A - the quartic extension field element to free.
Definition at line 196 of file relic_fbx.h.
Referenced by etat_exp(), fb4_exp(), fb4_mul_dxd(), pb_map_etatn_imp(), and pb_map_etats_imp().
#define fb4_copy (C, A)
Value:
fb_copy(C[0], A[0]); fb_copy(C[1], A[1]);                           \
        fb_copy(C[2], A[2]); fb_copy(C[3], A[3]);                           \
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the quartic extension field element to copy.
Definition at line 205 of file relic_fbx.h.
Referenced by fb4_exp(), and pb_map_etats_imp().
#define fb4_neg (C, A)
Value:
fb_neg(C[0], A[0]); fb_neg(C[1], A[1]);                             \
        fb_neg(C[2], A[2]); fb_neg(C[3], A[3]);                             \
Negates a quartic extension field element.
Parameters
[out] C - the result.
[out] A - the quartic extension field element to negate.
Definition at line 215 of file relic_fbx.h.
#define fb4_zero (A) fb_zero(A[0]); fb_zero(A[1]); fb_zero(A[2]); fb_zero(A[3]); \
Assigns zero to a quartic extension field element.
Parameters
[out] A - the quartic extension field element to zero.
Definition at line 224 of file relic_fbx.h.
Referenced by pb_map_etats_imp().
#define fb4_set_dig (C, A) fb_set_dig(C[0], A); fb_zero(C[1]); fb_zero(C[2]); fb_zero(C[3]); \
Assigns zero to a quartic extension field element.
Parameters
[out] C - the quartic extension field element to assign.
[in] A - the digit.
Definition at line 233 of file relic_fbx.h.
#define fb4_is_zero (A)
Value:
(fb_is_zero(A[0]) && fb_is_zero(A[1]) &&                            \
        fb_is_zero(A[2]) && fb_is_zero(A[3]))                               \
Tests if a quartic extension field element is zero or not.
Parameters
[in] A - the quartic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 242 of file relic_fbx.h.
#define fb4_rand (A) fb_rand(A[0]); fb_rand(A[1]); fb_rand(A[2]); fb_rand(A[3]); \
Assigns a random value to a quartic extension field element.
Parameters
[out] A - the binary field element to assign.
Definition at line 251 of file relic_fbx.h.
#define fb4_print (A) fb_print(A[0]); fb_print(A[1]); fb_print(A[2]); fb_print(A[3]); \
Prints a quartic extension field element to standard output.
Parameters
[in] A - the quartic extension field element to print.
Definition at line 259 of file relic_fbx.h.
#define fb4_cmp (A, B)
Value:
((fb_cmp(A[0], B[0]) == CMP_EQ) && (fb_cmp(A[1], B[1]) == CMP_EQ) &&\
        (fb_cmp(A[2], B[2]) == CMP_EQ) && (fb_cmp(A[3], B[3]) == CMP_EQ)    \
        ? CMP_EQ : CMP_NE)                                                  \
Returns the result of a comparison between two quartic extension field elements.
Parameters
[in] A - the first quartic extension field element.
[in] B - the second quartic extension field element.
Returns
CMP_NE if a != b, CMP_EQ if a == b.
Definition at line 270 of file relic_fbx.h.
#define fb4_cmp_dig (A, B)
Value:
((fb_cmp_dig(A[0], B) == CMP_EQ) && (fb_is_zero(A[1]) == CMP_EQ) && \
        (fb_is_zero(A[2]) == CMP_EQ) && (fb_is_zero(A[3]) == CMP_EQ)        \
        ? CMP_EQ : CMP_NE)                                                  \
Returns the result of a comparison between a quartic extension field and a digit.
Parameters
[in] A - the quartic extension field element.
[in] B - the digit.
Returns
CMP_NE if a != b, CMP_EQ if a == b.
Definition at line 283 of file relic_fbx.h.
#define fb4_add (C, A, B)
Value:
fb_add(C[0], A[0], B[0]); fb_add(C[1], A[1], B[1]);                 \
        fb_add(C[2], A[2], B[2]); fb_add(C[3], A[3], B[3]);                 \
Adds two quartic extension field elements. Computes c = a + b.
Parameters
[out] C - the result.
[in] A - the first binary field element to add.
[in] B - the second binary field element to add.
Definition at line 295 of file relic_fbx.h.
#define fb4_sub (C, A, B)
Value:
fb_sub(C[0], A[0], B[0]); fb_sub(C[1], A[1], B[1]);                 \
        fb_sub(C[2], A[2], B[2]); fb_sub(C[3], A[3], B[3]);                 \
Subtracts a quartic extension field element from another. Computes c = a - b.
Parameters
[out] C - the result.
[in] A - the first quartic extension field element.
[in] B - the second quartic extension field element.
Definition at line 307 of file relic_fbx.h.
Typedef Documentation
typedef fb_t fb2_t[2]
Represents a quadratic extension binary field element.
This extension field is constructed with the basis {1, s}, where s is a quadratic non-residue in the binary field.
Definition at line 52 of file relic_fbx.h.
typedef fb_t fb4_t[4]
Represents a quartic extension binary field element.
This extension field is constructed with the basis {1, s, t, st}, where s is a quadratic non-residue in the binary field and t is a quadratic non-residue in the quadratic extension field (s^2 = s + 1 and t^2 = t + 1).
Definition at line 61 of file relic_fbx.h.
Function Documentation
void fb2_mul (fb2_t c, fb2_t a, fb2_t b)
Multiples two quadratic extension field elements. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the quadratic extension binary field element.
[in] b - the quadratic extension binary field element.
Definition at line 40 of file relic_fb2_mul.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_free, fb_mul, fb_new, fb_null, FINALLY, THROW, and TRY.
Referenced by etat_exp(), and fb4_inv().
void fb2_mul_nor (fb2_t c, fb2_t a)
Multiples a quadratic extension field element by a quadratic non-residue. Computes c = a * s.
Parameters
[out] c - the result.
[in] a - the quadratic extension binary field element.
[in] b - the quadratic extension binary field element.
Definition at line 70 of file relic_fb2_mul.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_new, fb_null, FINALLY, THROW, and TRY.
void fb2_sqr (fb2_t c, fb2_t a)
Computes the square of a quadratic extension field element. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 39 of file relic_fbx_sqr.c.
References fb_add(), and fb_sqr.
Referenced by fb4_inv().
void fb2_slv (fb2_t c, fb2_t a)
Solves a quadratic equation for c, Tr(a) = 0. Computes c such that c^2 + c = a.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
Definition at line 39 of file relic_fbx_slv.c.
References fb_add(), fb_add_dig(), fb_slv, and fb_trc.
void fb2_inv (fb2_t c, fb2_t a)
Inverts a quadratic extension field element. Computes c = a^{-1}.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to invert.
Definition at line 39 of file relic_fbx_inv.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_sqr, FINALLY, THROW, and TRY.
Referenced by etat_exp(), and fb4_inv().
void fb4_mul (fb4_t c, fb4_t a, fb4_t b)
Multiples two quartic extension field elements. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 272 of file relic_fb4_mul.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_free, fb_mul, fb_new, fb_null, FINALLY, THROW, and TRY.
Referenced by etat_exp(), fb4_exp(), and pb_map_etats_imp().
void fb4_mul_dxd (fb4_t c, fb4_t a, fb4_t b)
Multiplies two quartic extension field elements represented in a polynomial basis instead of a tower of extensions.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 348 of file relic_fb4_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, fb4_free, fb4_new, fb4_null, fb_add(), fb_copy(), FB_DIGS, fb_free, fb_lsh1_low(), fb_lshb_low(), fb_mul, fb_mul_21(), fb_mul_41(), fb_mul_42(), fb_mul_420(), fb_mul_51(), fb_mul_beta(), fb_new, fb_null, fb_rdc1_low(), FINALLY, THROW, and TRY.
void fb4_mul_dxs (fb4_t c, fb4_t a, fb4_t b)
Multiplies two sparse quartic extension field elements.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 599 of file relic_fb4_mul.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_mul, fb_new, fb_null, FINALLY, THROW, and TRY.
Referenced by pb_map_etatn_imp(), and pb_map_etats_imp().
void fb4_mul_sxs (fb4_t c, fb4_t a, fb4_t b)
Multiplies two sparse quartic extension field elements.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 662 of file relic_fb4_mul.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_add_dig(), fb_free, fb_mul, fb_new, fb_null, FINALLY, THROW, and TRY.
Referenced by pb_map_etatn_imp(), and pb_map_etats_imp().
void fb4_sqr (fb4_t c, fb4_t a)
Computes the square of a quartic extension field element. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to square.
Definition at line 45 of file relic_fbx_sqr.c.
References fb_add(), and fb_sqr.
Referenced by etat_exp(), fb4_exp(), and pb_map_etatn_imp().
void fb4_inv (fb2_t c, fb2_t a)
Inverts a quartic extension field element. Computes c = a^{-1}.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to invert.
void fb4_exp (fb4_t c, fb4_t a, bn_t b)
Computes a power of a quartic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the quartic extension element to exponentiate.
[in] b - the exponent.
Definition at line 39 of file relic_fbx_exp.c.
References bn_bits(), bn_test_bit(), CATCH_ANY, ERR_CAUGHT, fb4_copy, fb4_free, fb4_mul(), fb4_new, fb4_null, fb4_sqr(), FINALLY, THROW, and TRY.
void fb4_frb (fb4_t c, fb4_t a)
Computes the q-th power Frobenius map of a quartic extension field element. Compute c = a^{2^m}.
Parameters
[out] c - the result.
[in] a - the quartic extension element to exponentiate.
Definition at line 39 of file relic_fbx_frb.c.
References fb_add(), FB_BITS, and fb_copy().
Referenced by etat_exp().