RELIC: src/fb/relic_fb_slv.c File Reference
relic_fb_slv.c File Reference
Binary field arithmetic.
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
#include "relic_util.h"
Functions
void fb_slv_basic (fb_t c, const fb_t a)
void fb_slv_quick (fb_t c, const fb_t a)
Detailed Description
Implementation of quadratic equation solution on binary fields.
Version
Id:
relic_fb_slv.c 1561 2013-09-02 00:01:53Z dfaranha
Definition in file relic_fb_slv.c.
Function Documentation
void fb_slv_basic (fb_t c, const fb_t a)
Solves a quadratic equation for a, Tr(a) = 0 by repeated squarings and additions.
Parameters
[out] c - the result.
[in] a - the binary field element to solve.
Definition at line 46 of file relic_fb_slv.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_add_dig(), FB_BITS, fb_copy(), fb_free, fb_new, fb_null, fb_sqr, fb_trc, FINALLY, THROW, and TRY.
void fb_slv_quick (fb_t c, const fb_t a)
Solves a quadratic equation for a, Tr(a) = 0 with precomputed half-traces.
Parameters
[out] c - the result.
[in] a - the binary field element to solve.
Definition at line 78 of file relic_fb_slv.c.
References fb_add_dig(), fb_slvn_low(), and fb_trc.