RELIC: src/eb/relic_eb_curve.c File Reference
relic_eb_curve.c File Reference
Elliptic curves over binary fields.
#include <string.h>
#include "relic_core.h"
#include "relic_eb.h"
#include "relic_conf.h"
Functions
static void compute_kbltz (void)
static void detect_opt (int *opt, fb_t a)
void eb_curve_init (void)
void eb_curve_clean (void)
dig_t * eb_curve_get_a ()
int eb_curve_opt_a ()
dig_t * eb_curve_get_b ()
int eb_curve_opt_b ()
dig_t * eb_curve_get_c ()
int eb_curve_opt_c ()
int eb_curve_is_kbltz ()
int eb_curve_is_super ()
void eb_curve_get_gen (eb_t g)
void eb_curve_get_ord (bn_t n)
void eb_curve_get_cof (bn_t h)
void eb_curve_get_vm (bn_t vm)
void eb_curve_get_s0 (bn_t s0)
void eb_curve_get_s1 (bn_t s1)
const eb_t * eb_curve_get_tab ()
void eb_curve_set_ordin (const fb_t a, const fb_t b, const eb_t g, const bn_t r, const bn_t h)
void eb_curve_set_kbltz (const fb_t a, const eb_t g, const bn_t r, const bn_t h)
void eb_curve_set_super (const fb_t a, const fb_t b, const fb_t c, const eb_t g, const bn_t r, const bn_t h)
Detailed Description
Implementation of the binary elliptic curve utilities.
Version
Id:
relic_eb_curve.c 1573 2013-09-02 07:17:18Z dfaranha
Definition in file relic_eb_curve.c.
Function Documentation
static void compute_kbltz (void) static
Precomputes additional parameters for Koblitz curves used by the w-TNAF multiplication algorithm.
Definition at line 48 of file relic_eb_curve.c.
References bn_add_dig(), bn_copy(), bn_dbl(), bn_free, bn_neg(), bn_new, bn_null, bn_set_dig(), bn_sub(), bn_sub_dig(), bn_zero(), CATCH_ANY, core_get(), _ctx_t::eb_opt_a, _ctx_t::eb_s0, _ctx_t::eb_s1, _ctx_t::eb_vm, ERR_CAUGHT, FB_BITS, FINALLY, OPT_ZERO, THROW, and TRY.
Referenced by eb_curve_set_kbltz(), and eb_curve_set_ordin().
static void detect_opt (int * opt, fb_t a) static
Detects an optimization based on the curve coefficients.
Parameters
opt - the resulting optimization.
a - the curve coefficient.
Definition at line 131 of file relic_eb_curve.c.
References CMP_EQ, fb_bits(), fb_cmp_dig(), FB_DIGIT, fb_is_zero(), OPT_DIGIT, OPT_NONE, OPT_ONE, and OPT_ZERO.
Referenced by eb_curve_set_kbltz(), eb_curve_set_ordin(), and eb_curve_set_super().
void eb_curve_init (void)
Initializes the binary elliptic curve arithmetic module.
Definition at line 151 of file relic_eb_curve.c.
References bn_init(), core_get(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_pre, _ctx_t::eb_ptr, _ctx_t::eb_r, _ctx_t::eb_s0, _ctx_t::eb_s1, EB_TABLE, _ctx_t::eb_vm, FB_DIGS, fb_new, fb_zero(), eb_st::x, eb_st::y, and eb_st::z.
Referenced by core_init().
void eb_curve_clean (void)
Finalizes the binary elliptic curve arithmetic module.
Definition at line 180 of file relic_eb_curve.c.
References bn_clean(), core_get(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_pre, _ctx_t::eb_r, _ctx_t::eb_s0, _ctx_t::eb_s1, EB_TABLE, _ctx_t::eb_vm, fb_free, eb_st::x, eb_st::y, and eb_st::z.
Referenced by core_clean().
dig_t* eb_curve_get_a (void)
Returns the a coefficient of the currently configured binary elliptic curve.
Returns
the a coefficient of the elliptic curve.
Definition at line 201 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_a.
Referenced by eb_add_basic_ordin(), eb_add_projc_ordin_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_hlv(), eb_mul_halve(), and eb_rhs().
int eb_curve_opt_a (void)
Returns a optimization identifier based on the coefficient a of the curve.
Returns
the optimization identifier.
Definition at line 205 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_opt_a.
Referenced by eb_add_basic_ordin(), eb_add_projc_ordin_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_hlv(), eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), eb_rhs(), and eb_tab().
dig_t* eb_curve_get_b (void)
Returns the b coefficient of the currently configured binary elliptic curve.
Returns
the b coefficient of the elliptic curve.
Definition at line 209 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_b.
Referenced by eb_mul_halve(), eb_mul_lodah(), eb_rhs(), etat_exp(), pb_map_etatn_imp(), and pb_map_etats_imp().
int eb_curve_opt_b (void)
Returns a optimization identifier based on the coefficient b of the curve.
Returns
the optimization identifier.
Definition at line 213 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_opt_b.
Referenced by eb_mul_lodah(), and eb_rhs().
dig_t* eb_curve_get_c (void)
Returns the c coefficient of the currently configured supersingular binary elliptic curve.
Returns
the c coefficient of the supersingular elliptic curve.
Definition at line 217 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_c.
Referenced by eb_add_basic_super(), eb_dbl_basic_super(), eb_is_valid(), eb_map(), eb_neg_basic(), eb_neg_projc(), eb_pck(), and eb_upk().
int eb_curve_opt_c (void)
Returns a optimization identifier based on the coefficient c of the curve.
Returns
the optimization identifier.
Definition at line 226 of file relic_eb_curve.c.
References core_get(), _ctx_t::eb_opt_c, and OPT_NONE.
Referenced by eb_add_basic_super(), eb_dbl_basic_super(), eb_map(), eb_neg_basic(), and eb_neg_projc().
int eb_curve_is_kbltz (void)
Tests if the configured binary elliptic curve is a Koblitz curve.
Returns
1 if the binary elliptic curve is a Koblitz curve, 0 otherwise.
Definition at line 235 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_is_kbltz.
Referenced by eb_mul_fix_lwnaf(), eb_mul_lwnaf(), eb_mul_pre_lwnaf(), eb_mul_rwnaf(), eb_mul_sim_gen(), eb_mul_sim_inter(), and eb_tab().
int eb_curve_is_super (void)
Tests if the configured binary elliptic curve is supersingular.
Returns
1 if the binary elliptic curve is supersingular, 0 otherwise.
Definition at line 239 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_is_super.
Referenced by eb_add_basic(), eb_add_projc(), eb_dbl_basic(), eb_dbl_projc(), eb_is_valid(), eb_map(), eb_mul_lodah(), eb_mul_rwnaf(), eb_neg_basic(), eb_neg_projc(), eb_norm(), eb_norm_sim(), eb_pck(), eb_rhs(), and eb_upk().
void eb_curve_get_gen (eb_t g)
Returns the generator of the group of points in the binary elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 243 of file relic_eb_curve.c.
References core_get(), and eb_copy().
Referenced by eb_mul_gen(), and eb_mul_sim_gen().
void eb_curve_get_ord (bn_t n)
Returns the order of the group of points in the binary elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 247 of file relic_eb_curve.c.
References bn_copy(), and core_get().
Referenced by eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_halve(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_pre_nafwi(), eb_mul_pre_yaowi(), eb_mul_sim_trick(), and eb_rand().
void eb_curve_get_cof (bn_t h)
Returns the cofactor of the binary elliptic curve.
Parameters
[out] n - the returned cofactor.
Definition at line 251 of file relic_eb_curve.c.
References bn_copy(), and core_get().
Referenced by eb_map(), and eb_mul_halve().
void eb_curve_get_vm (bn_t vm)
Returns the parameter Vm of a Koblitz curve.
Parameters
[out] vm - the returned parameter.
Definition at line 256 of file relic_eb_curve.c.
References bn_copy(), bn_zero(), and core_get().
Referenced by eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), and eb_tab().
void eb_curve_get_s0 (bn_t s0)
Returns the parameter S0 of a Koblitz curve.
Parameters
[out] s0 - the returned parameter.
Definition at line 264 of file relic_eb_curve.c.
References bn_copy(), bn_zero(), and core_get().
Referenced by eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), and eb_tab().
void eb_curve_get_s1 (bn_t s1)
Returns the parameter S1 of a Koblitz curve.
Parameters
[out] s1 - the returned parameter.
Definition at line 272 of file relic_eb_curve.c.
References bn_copy(), bn_zero(), and core_get().
Referenced by eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), and eb_tab().
const eb_t* eb_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 281 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_ptr.
Referenced by eb_curve_set_kbltz(), eb_curve_set_ordin(), eb_curve_set_super(), eb_mul_gen(), and eb_mul_sim_gen().
void eb_curve_set_ordin (const fb_t a, const fb_t b, const eb_t g, const bn_t n, const bn_t h)
Configures a new ordinary binary elliptic curve by its coefficients and generator.
Parameters
[in] a - the coefficient a of the curve.
[in] b - the coefficient b of the curve.
[in] g - the generator.
[in] n - the order of the generator.
[in] h - the cofactor.
Definition at line 299 of file relic_eb_curve.c.
References bn_copy(), CMP_EQ, compute_kbltz(), core_get(), detect_opt(), _ctx_t::eb_a, _ctx_t::eb_b, eb_curve_get_tab(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_is_kbltz, _ctx_t::eb_is_super, eb_mul_pre, eb_norm(), _ctx_t::eb_opt_a, _ctx_t::eb_opt_b, _ctx_t::eb_r, fb_cmp_dig(), and fb_copy().
Referenced by eb_param_set().
void eb_curve_set_kbltz (const fb_t a, const eb_t g, const bn_t n, const bn_t h)
Configures a new Koblitz binary elliptic curve by its coefficients and generator.
Parameters
[in] a - the coefficient a of the curve.
[in] g - the generator.
[in] n - the order of the generator.
[in] h - the cofactor.
Definition at line 332 of file relic_eb_curve.c.
References bn_copy(), compute_kbltz(), core_get(), detect_opt(), _ctx_t::eb_a, _ctx_t::eb_b, eb_curve_get_tab(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_is_kbltz, _ctx_t::eb_is_super, eb_mul_pre, eb_norm(), _ctx_t::eb_opt_a, _ctx_t::eb_opt_b, _ctx_t::eb_r, fb_copy(), and fb_set_dig().
Referenced by eb_param_set().
void eb_curve_set_super (const fb_t a, const fb_t b, const fb_t c, const eb_t g, const bn_t n, const bn_t h)
Configures a new supersingular binary elliptic curve by its coefficients and generator.
Parameters
[in] a - the coefficient a of the curve.
[in] b - the coefficient b of the curve.
[in] c - the coefficient c of the curve.
[in] g - the generator.
[in] n - the order of the generator.
[in] h - the cofactor.
Definition at line 359 of file relic_eb_curve.c.
References bn_copy(), core_get(), detect_opt(), _ctx_t::eb_a, _ctx_t::eb_b, _ctx_t::eb_c, eb_curve_get_tab(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_is_kbltz, _ctx_t::eb_is_super, eb_mul_pre, eb_norm(), _ctx_t::eb_opt_a, _ctx_t::eb_opt_b, _ctx_t::eb_opt_c, _ctx_t::eb_r, and fb_copy().
Referenced by eb_param_set().