RELIC: src/fb/relic_fb_rdc.c File Reference
relic_fb_rdc.c File Reference
Binary field arithmetic.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_bn_low.h"
#include "relic_dv.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
#include "relic_util.h"
Functions
void fb_rdc_basic (fb_t c, dv_t a)
void fb_rdc_quick (fb_t c, dv_t a)
Detailed Description
Implementation of the binary field modular reduction.
Version
Id:
relic_fb_rdc.c 1518 2013-08-27 15:50:52Z dfaranha
Definition in file relic_fb_rdc.c.
Function Documentation
void fb_rdc_basic (fb_t c, dv_t a)
Reduces a multiplication result modulo an irreducible polynomial using shift-and-add modular reduction.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 50 of file relic_fb_rdc.c.
References CATCH_ANY, dv_new, dv_null, ERR_CAUGHT, fb_addd_low(), FB_BITS, fb_bits(), fb_copy(), FB_DIG_LOG, FB_DIGS, fb_free, fb_lshb_low(), fb_poly_get(), fb_test_bit(), FINALLY, SPLIT, THROW, and TRY.
void fb_rdc_quick (fb_t c, dv_t a)
Reduces a multiplication result modulo a trinomial or pentanomial.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 100 of file relic_fb_rdc.c.
References fb_rdcn_low().