RELIC: src/md/relic_md_sha1.c File Reference
relic_md_sha1.c File Reference
Hash functions.
#include <string.h>
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_util.h"
#include "relic_md.h"
#include "sha.h"
Functions
void md_map_shone (unsigned char *hash, const unsigned char *msg, int len)
void md_map_shone_mid (unsigned char *msg, int len, unsigned char *state)
Detailed Description
Implementation of the SHA-1 hash function.
Version
Id:
relic_md_sha1.c 1566 2013-09-02 04:09:52Z dfaranha
Definition in file relic_md_sha1.c.
Function Documentation
void md_map_shone (unsigned char * hash, const unsigned char * msg, int len)
Computes the SHA-1 hash function.
Parameters
[out] hash - the digest.
[in] msg - the message to hash.
[in] len - the message length in bytes.
Definition at line 44 of file relic_md_sha1.c.
References ERR_NO_VALID, SHA1Input(), SHA1Reset(), SHA1Result(), shaSuccess, and THROW.
void md_map_shone_mid (unsigned char * msg, int len, unsigned char * state)
Returns the internal state of the hash function.
Parameters
[in] msg - the message to hash.
[in] len - the message length in bytes.
[out] state - the internal state.
Definition at line 58 of file relic_md_sha1.c.
References ERR_NO_VALID, SHA1Context::Intermediate_Hash, SHA1Input(), SHA1Reset(), shaSuccess, THROW, and util_conv_big().
Referenced by rand_bytes().