RELIC: include/relic_core.h File Reference
relic_core.h File Reference
Core functions.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "relic_err.h"
#include "relic_bn.h"
#include "relic_eb.h"
#include "relic_epx.h"
#include "relic_conf.h"
#include "relic_bench.h"
#include "relic_rand.h"
#include "relic_pool.h"
#include "relic_label.h"
Data Structures
struct _ctx_t
Macros
#define STS_OK 0
#define STS_ERR 1
#define CMP_LT -1
#define CMP_EQ 0
#define CMP_GT 1
#define CMP_NE 2
#define OPT_ZERO 0
#define OPT_ONE 1
#define OPT_TWO 2
#define OPT_DIGIT 3
#define OPT_MINUS3 4
#define OPT_NONE 5
#define MAX_TERMS 16
Typedefs
typedef struct _ctx_t ctx_t
Functions
int core_init (void)
int core_clean (void)
ctx_t * core_get (void)
void core_set (ctx_t *ctx)
Detailed Description
Interface of the library core functions.
Version
Id:
relic_core.h 1552 2013-08-30 04:11:47Z dfaranha
Definition in file relic_core.h.
Macro Definition Documentation
#define STS_OK 0
Indicates that the function executed correctly.
Definition at line 66 of file relic_core.h.
Referenced by core_clean(), core_init(), cp_rabin_dec(), cp_rabin_enc(), cp_rabin_gen(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), eb_param_set_any(), eb_param_set_any_kbltz(), eb_param_set_any_ordin(), eb_param_set_any_super(), ep_param_set_any(), ep_param_set_any_kbltz(), ep_param_set_any_ordin(), ep_param_set_any_pairf(), ep_param_set_any_super(), err_get_code(), fp_param_set_any(), fp_param_set_any_dense(), fp_param_set_any_pmers(), fp_param_set_any_tower(), and pad_pkcs1().
#define STS_ERR 1
Indicates that an error occurred during the function execution.
Definition at line 71 of file relic_core.h.
Referenced by core_init(), cp_rabin_dec(), cp_rabin_enc(), cp_rabin_gen(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), eb_param_set_any(), eb_param_set_any_kbltz(), eb_param_set_any_ordin(), eb_param_set_any_super(), ep_param_set_any(), ep_param_set_any_kbltz(), ep_param_set_any_ordin(), ep_param_set_any_pairf(), ep_param_set_any_super(), fp_param_set_any_dense(), fp_param_set_any_pmers(), and pad_pkcs1().
#define CMP_LT -1
Indicates that a comparison returned that the first argument was lesser than the second argument.
Definition at line 77 of file relic_core.h.
Referenced by bn_add(), bn_cmp(), bn_cmp_abs(), bn_cmp_dig(), bn_div_imp(), bn_factor(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_stein(), bn_is_prime_solov(), bn_lcm(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_sub(), cp_ecdsa_ver(), cp_ecss_ver(), cp_rabin_gen(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), fp_add_basic(), fp_add_dig(), fp_dbl_basic(), fp_inv_binar(), fp_inv_monty(), fp_rand(), and fp_rdc_monty_basic().
#define CMP_EQ 0
Indicates that a comparison returned that the first argument was equal to the second argument.
Definition at line 83 of file relic_core.h.
Referenced by bn_is_prime_basic(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_smb_jac(), bn_smb_leg(), cp_bbs_ver(), cp_bls_ver(), cp_rabin_dec(), cp_rabin_gen(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_ver(), detect_opt(), dv_cmp_const(), eb_cmp(), eb_curve_set_ordin(), eb_is_valid(), ep2_cmp(), ep2_is_valid(), ep_cmp(), ep_is_valid(), fp12_cmp(), fp12_cmp_dig(), fp12_test_cyc(), fp18_cmp(), fp18_cmp_dig(), fp18_test_cyc(), fp2_cmp(), fp2_cmp_dig(), fp3_cmp(), fp3_srt(), fp6_cmp(), fp_cmp_dig(), fp_inv_binar(), fp_inv_exgcd(), fp_srt(), and util_cmp_const().
#define CMP_GT 1
Indicates that a comparison returned that the first argument was greater than the second argument.
Definition at line 89 of file relic_core.h.
Referenced by bn_cmp(), bn_cmp_abs(), bn_cmp_dig(), bn_factor(), bn_gcd_ext_mid(), bn_gcd_lehme(), eb_mul_halve(), fb_cmp_dig(), fp_cmp_dig(), fp_inv_binar(), fp_inv_monty(), and tnaf_mod().
#define CMP_NE 2
Indicates that two incomparable elements are not equal.
Definition at line 94 of file relic_core.h.
Referenced by cp_ecdsa_ver(), cp_ecss_ver(), dv_cmp_const(), eb_cmp(), ep2_cmp(), ep_cmp(), fp12_cmp(), fp18_cmp(), fp2_cmp(), fp3_cmp(), fp6_cmp(), and util_cmp_const().
#define OPT_ZERO 0
Optimization identifer for the case where a coefficient is 0.
Definition at line 99 of file relic_core.h.
Referenced by compute_kbltz(), detect_opt(), eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_hlv(), eb_mul_fix_kbltz(), eb_mul_lodah(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), eb_neg_basic(), eb_neg_projc(), eb_rhs(), eb_tab(), ep2_dbl_basic_imp(), ep_dbl_basic_imp(), ep_dbl_projc_imp(), and ep_rhs().
#define OPT_ONE 1
Optimization identifer for the case where a coefficient is 1.
Definition at line 104 of file relic_core.h.
Referenced by detect_opt(), eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_hlv(), eb_map(), eb_mul_lodah(), eb_neg_basic(), eb_neg_projc(), eb_rhs(), ep2_dbl_basic_imp(), ep_dbl_basic_imp(), ep_dbl_projc_imp(), and ep_rhs().
#define OPT_TWO 2
Optimization identifer for the case where a coefficient is 1.
Definition at line 109 of file relic_core.h.
Referenced by detect_opt(), pp_dbl_k12_projc_basic(), and pp_dbl_k12_projc_lazyr().
#define OPT_DIGIT 3
Optimization identifer for the case where a coefficient is small.
Definition at line 114 of file relic_core.h.
Referenced by detect_opt(), eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_hlv(), eb_mul_lodah(), eb_neg_basic(), eb_neg_projc(), eb_rhs(), ep2_dbl_basic_imp(), ep_dbl_basic_imp(), ep_dbl_projc_imp(), and ep_rhs().
#define OPT_MINUS3 4
Optimization identifier for the case where a coefficient is -3.
Definition at line 119 of file relic_core.h.
Referenced by detect_opt(), and ep_dbl_projc_imp().
#define OPT_NONE 5
Optimization identifier for the case where the coefficient is random
Definition at line 124 of file relic_core.h.
Referenced by detect_opt(), and eb_curve_opt_c().
#define MAX_TERMS 16
Maximum number of terms to describe a sparse object.
Definition at line 129 of file relic_core.h.
Referenced by fb_poly_get_chain(), find_chain(), fp_param_get_sps(), fp_prime_get_sps(), fp_prime_set_pmers(), pp_exp_b12(), and pp_exp_bn().
Typedef Documentation
typedef struct _ctx_t ctx_t
Library context.
Function Documentation
int core_init (void)
Initializes the library.
Returns
STS_OK if no error occurs, STS_ERR otherwise.
Definition at line 66 of file relic_core.c.
References arch_init(), CATCH_ANY, _ctx_t::code, eb_curve_init(), ep_curve_init(), ERR_NO_BUFFER, ERR_NO_CONFIG, ERR_NO_CURVE, ERR_NO_FIELD, ERR_NO_FILE, ERR_NO_MEMORY, ERR_NO_PRECI, ERR_NO_READ, ERR_NO_VALID, fb_poly_init(), first_ctx, fp_prime_init(), _ctx_t::last, MSG_NO_BUFFER, MSG_NO_CONFIG, MSG_NO_CURVE, MSG_NO_FIELD, MSG_NO_FILE, MSG_NO_MEMORY, MSG_NO_PRECI, MSG_NO_READ, MSG_NO_VALID, pb_map_init(), pp_map_init(), rand_init(), _ctx_t::reason, STS_ERR, STS_OK, _ctx_t::trace, and TRY.
int core_clean (void)
Finalizes the library.
Returns
STS_OK if no error occurs, STS_ERR otherwise.
Definition at line 130 of file relic_core.c.
References arch_clean(), eb_curve_clean(), ep_curve_clean(), fb_poly_clean(), fp_prime_clean(), pb_map_clean(), pp_map_clean(), rand_clean(), and STS_OK.
ctx_t* core_get (void)
Returns a pointer to the current library context.
Returns
a pointer to the library context.
Definition at line 159 of file relic_core.c.
References core_ctx.
Referenced by bench_after(), bench_before(), bench_compute(), bench_print(), bench_reset(), bench_total(), compute_kbltz(), eb_curve_clean(), eb_curve_get_a(), eb_curve_get_b(), eb_curve_get_c(), eb_curve_get_cof(), eb_curve_get_gen(), eb_curve_get_ord(), eb_curve_get_s0(), eb_curve_get_s1(), eb_curve_get_tab(), eb_curve_get_vm(), eb_curve_init(), eb_curve_is_kbltz(), eb_curve_is_super(), eb_curve_opt_a(), eb_curve_opt_b(), eb_curve_opt_c(), eb_curve_set_kbltz(), eb_curve_set_ordin(), eb_curve_set_super(), eb_param_get(), eb_param_level(), eb_param_print(), eb_param_set(), ep2_curve_clean(), ep2_curve_get_a(), ep2_curve_get_b(), ep2_curve_get_gen(), ep2_curve_get_ord(), ep2_curve_get_tab(), ep2_curve_init(), ep2_curve_is_twist(), ep2_curve_set(), ep_curve_clean(), ep_curve_get_a(), ep_curve_get_b(), ep_curve_get_beta(), ep_curve_get_cof(), ep_curve_get_gen(), ep_curve_get_ord(), ep_curve_get_tab(), ep_curve_get_v1(), ep_curve_get_v2(), ep_curve_init(), ep_curve_is_kbltz(), ep_curve_is_super(), ep_curve_opt_a(), ep_curve_opt_b(), ep_curve_set_kbltz(), ep_curve_set_ordin(), ep_curve_set_super(), ep_param_get(), ep_param_set(), err_full_msg(), err_get_code(), err_get_msg(), err_simple_msg(), fb_param_get(), fb_param_set(), fb_poly_add(), fb_poly_get(), fb_poly_get_chain(), fb_poly_get_rdc(), fb_poly_get_slv(), fb_poly_get_srz(), fb_poly_get_trc(), fb_poly_init(), fb_poly_set(), fb_poly_set_dense(), fb_poly_set_penta(), fb_poly_set_trino(), fb_poly_tab_sqr(), fb_poly_tab_srz(), find_chain(), find_solve(), find_srz(), find_trace(), fp2_calc(), fp2_mul_frb(), fp3_calc(), fp3_mul_frb(), fp_param_get(), fp_param_set(), fp_prime_clean(), fp_prime_conv(), fp_prime_conv_dig(), fp_prime_get(), fp_prime_get_cnr(), fp_prime_get_conv(), fp_prime_get_mod8(), fp_prime_get_qnr(), fp_prime_get_rdc(), fp_prime_get_sps(), fp_prime_init(), fp_prime_set(), fp_prime_set_dense(), fp_prime_set_pmers(), pb_map_get_sqr(), pb_map_get_srt(), pb_map_get_tab(), pb_map_init(), rand_bytes(), rand_clean(), rand_init(), and rand_seed().
void core_set (ctx_t * ctx)
Switched the library context to a new context.
Parameters
[in] ctx - the new library context.
Definition at line 163 of file relic_core.c.