RELIC: src/fbx/relic_fb4_mul.c File Reference
relic_fb4_mul.c File Reference
Extensions of binary fields.
#include "relic_core.h"
#include "relic_fbx.h"
#include "relic_fb_low.h"
Functions
void fb_mul_beta (dig_t *c, dig_t *a)
void fb_mul_21 (dig_t *c, dig_t *a)
void fb_mul_420 (dig_t *c, dig_t *a)
void fb_mul_41 (dig_t *c, dig_t *a)
void fb_mul_42 (dig_t *c, dig_t *a)
void fb_mul_51 (dig_t *c, dig_t *a)
void fb4_mul (fb4_t c, fb4_t a, fb4_t b)
void fb4_mul_dxd (fb4_t c, fb4_t a, fb4_t b)
void fb4_mul_dxs (fb4_t c, fb4_t a, fb4_t b)
void fb4_mul_sxs (fb4_t c, fb4_t a, fb4_t b)
Detailed Description
Implementation of multiplication in quartic extensions of binary fields.
The implementations of fb4_mul() and fb4_mul_dxs() are based on:
Beuchat et al., A comparison between hardware accelerators for the modified Tate pairing over F_2^m and F_3^m, 2008.
The implementation of fb4_mul_dxd() is based on:
Shirase et al., Efficient computation of Eta pairing over binary field with Vandermonde matrix, 2008.
and optimal 4-way Toom-Cook from:
Bodrato, Towards optimal Toom-Cook multiplication for univariate and multivariate polynomials in characteristic 2 and 0, 2007.
Version
Id:
relic_fb4_mul.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_fb4_mul.c.
Function Documentation
void fb_mul_beta (dig_t * c, dig_t * a)
Definition at line 55 of file relic_fb4_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, FB_DIGIT, FB_DIGS, fb_lshb_low(), fb_lshd_low(), fb_rdc1_low(), FINALLY, THROW, and TRY.
Referenced by fb4_mul_dxd().
void fb_mul_21 (dig_t * c, dig_t * a)
Definition at line 112 of file relic_fb4_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, FB_DIGIT, FB_DIGS, fb_lshb_low(), fb_rdc1_low(), FINALLY, THROW, and TRY.
Referenced by fb4_mul_dxd().
void fb_mul_420 (dig_t * c, dig_t * a)
Definition at line 143 of file relic_fb4_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, fb_addn_low(), FB_DIGIT, FB_DIGS, fb_lshb_low(), fb_rdc1_low(), FINALLY, THROW, and TRY.
Referenced by fb4_mul_dxd().
void fb_mul_41 (dig_t * c, dig_t * a)
Definition at line 175 of file relic_fb4_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, FB_DIGIT, FB_DIGS, fb_lshb_low(), fb_rdc1_low(), FINALLY, THROW, and TRY.
Referenced by fb4_mul_dxd().
void fb_mul_42 (dig_t * c, dig_t * a)
Definition at line 206 of file relic_fb4_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, FB_DIGIT, FB_DIGS, fb_lshb_low(), fb_rdc1_low(), FINALLY, THROW, and TRY.
Referenced by fb4_mul_dxd().
void fb_mul_51 (dig_t * c, dig_t * a)
Definition at line 237 of file relic_fb4_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, FB_DIGIT, FB_DIGS, fb_lshb_low(), fb_rdc1_low(), FINALLY, THROW, and TRY.
Referenced by fb4_mul_dxd().
void fb4_mul (fb4_t c, fb4_t a, fb4_t b)
Multiples two quartic extension field elements. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 272 of file relic_fb4_mul.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_free, fb_mul, fb_new, fb_null, FINALLY, THROW, and TRY.
Referenced by etat_exp(), fb4_exp(), and pb_map_etats_imp().
void fb4_mul_dxd (fb4_t c, fb4_t a, fb4_t b)
Multiplies two quartic extension field elements represented in a polynomial basis instead of a tower of extensions.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 348 of file relic_fb4_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, fb4_free, fb4_new, fb4_null, fb_add(), fb_copy(), FB_DIGS, fb_free, fb_lsh1_low(), fb_lshb_low(), fb_mul, fb_mul_21(), fb_mul_41(), fb_mul_42(), fb_mul_420(), fb_mul_51(), fb_mul_beta(), fb_new, fb_null, fb_rdc1_low(), FINALLY, THROW, and TRY.
void fb4_mul_dxs (fb4_t c, fb4_t a, fb4_t b)
Multiplies two sparse quartic extension field elements.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 599 of file relic_fb4_mul.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_mul, fb_new, fb_null, FINALLY, THROW, and TRY.
Referenced by pb_map_etatn_imp(), and pb_map_etats_imp().
void fb4_mul_sxs (fb4_t c, fb4_t a, fb4_t b)
Multiplies two sparse quartic extension field elements.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 662 of file relic_fb4_mul.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_add_dig(), fb_free, fb_mul, fb_new, fb_null, FINALLY, THROW, and TRY.
Referenced by pb_map_etatn_imp(), and pb_map_etats_imp().