RELIC: src/fpx/relic_fpx_add.c File Reference
relic_fpx_add.c File Reference
Extensions of prime fields.
#include "relic_core.h"
#include "relic_pp_low.h"
Functions
void fp2_add_basic (fp2_t c, fp2_t a, fp2_t b)
void fp2_sub_basic (fp2_t c, fp2_t a, fp2_t b)
void fp2_dbl_basic (fp2_t c, fp2_t a)
void fp2_add_integ (fp2_t c, fp2_t a, fp2_t b)
void fp2_sub_integ (fp2_t c, fp2_t a, fp2_t b)
void fp2_dbl_integ (fp2_t c, fp2_t a)
void fp2_neg (fp2_t c, fp2_t a)
void fp3_add_basic (fp2_t c, fp2_t a, fp2_t b)
void fp3_sub_basic (fp2_t c, fp2_t a, fp2_t b)
void fp3_dbl_basic (fp2_t c, fp2_t a)
void fp3_neg (fp3_t c, fp3_t a)
void fp3_add_integ (fp2_t c, fp2_t a, fp2_t b)
void fp3_sub_integ (fp2_t c, fp2_t a, fp2_t b)
void fp3_dbl_integ (fp2_t c, fp2_t a)
void fp6_add (fp6_t c, fp6_t a, fp6_t b)
void fp6_sub (fp6_t c, fp6_t a, fp6_t b)
void fp6_dbl (fp6_t c, fp6_t a)
void fp6_neg (fp6_t c, fp6_t a)
void fp12_add (fp12_t c, fp12_t a, fp12_t b)
void fp12_sub (fp12_t c, fp12_t a, fp12_t b)
void fp12_neg (fp12_t c, fp12_t a)
void fp18_add (fp18_t c, fp18_t a, fp18_t b)
void fp18_sub (fp18_t c, fp18_t a, fp18_t b)
void fp18_neg (fp18_t c, fp18_t a)
Detailed Description
Implementation of addition in extensions defined over prime fields.
Version
Id:
relic_fpx_add.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_fpx_add.c.
Function Documentation
void fp2_add_basic (fp2_t c, fp2_t a, fp2_t b)
Adds two quadratic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 41 of file relic_fpx_add.c.
References fp_add.
void fp2_sub_basic (fp2_t c, fp2_t a, fp2_t b)
Subtracts a quadratic extension field element from another using basic arithmetic.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Definition at line 46 of file relic_fpx_add.c.
References fp_sub.
void fp2_dbl_basic (fp2_t c, fp2_t a)
Doubles a quadratic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to double.
Definition at line 51 of file relic_fpx_add.c.
References fp_dbl.
void fp2_add_integ (fp2_t c, fp2_t a, fp2_t b)
Adds two quadratic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 61 of file relic_fpx_add.c.
References fp2_addm_low().
void fp2_sub_integ (fp2_t c, fp2_t a, fp2_t b)
Subtracts a quadratic extension field element from another using integrated modular reduction.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Definition at line 65 of file relic_fpx_add.c.
References fp2_subm_low().
void fp2_dbl_integ (fp2_t c, fp2_t a)
Doubles a quadratic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to double.
Definition at line 69 of file relic_fpx_add.c.
References fp2_dblm_low().
void fp2_neg (fp2_t c, fp2_t a)
Negates a quadratic extension field element.
Parameters
[out] C - the result.
[out] A - the quadratic extension field element to negate.
Definition at line 75 of file relic_fpx_add.c.
References fp_neg.
Referenced by ep2_frb(), ep2_neg_basic(), ep2_neg_projc(), fp12_frb(), fp6_frb(), fp6_neg(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), and pp_add_lit_k12().
void fp3_add_basic (fp2_t c, fp2_t a, fp2_t b)
Definition at line 82 of file relic_fpx_add.c.
References fp_add.
void fp3_sub_basic (fp2_t c, fp2_t a, fp2_t b)
Definition at line 88 of file relic_fpx_add.c.
References fp_sub.
void fp3_dbl_basic (fp2_t c, fp2_t a)
Definition at line 94 of file relic_fpx_add.c.
References fp_dbl.
void fp3_neg (fp3_t c, fp3_t a)
Negates a cubic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the cubic extension field element to negate.
Definition at line 103 of file relic_fpx_add.c.
References fp_neg.
void fp3_add_integ (fp2_t c, fp2_t a, fp2_t b)
Definition at line 111 of file relic_fpx_add.c.
References fp3_addm_low().
void fp3_sub_integ (fp2_t c, fp2_t a, fp2_t b)
Definition at line 115 of file relic_fpx_add.c.
References fp3_subm_low().
void fp3_dbl_integ (fp2_t c, fp2_t a)
Definition at line 119 of file relic_fpx_add.c.
References fp3_dblm_low().
void fp6_add (fp6_t c, fp6_t a, fp6_t b)
Adds two sextic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first sextic extension field element.
[in] b - the second sextic extension field element.
Definition at line 125 of file relic_fpx_add.c.
References fp2_add.
Referenced by fp12_add(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_mul_lazyr(), fp12_sqr(), fp18_add(), fp18_inv(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp18_mul_lazyr(), fp18_sqr_basic(), fp18_sqr_cyc(), fp18_sqr_lazyr(), and fp18_sqr_pck().
void fp6_sub (fp6_t c, fp6_t a, fp6_t b)
Subtracts a sextic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 131 of file relic_fpx_add.c.
References fp2_sub.
Referenced by fp12_inv(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_sqr(), fp12_sub(), fp18_inv(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp18_sqr_basic(), fp18_sqr_cyc(), fp18_sqr_lazyr(), fp18_sqr_pck(), and fp18_sub().
void fp6_dbl (fp6_t c, fp6_t a)
Doubles a sextic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to double.
Definition at line 137 of file relic_fpx_add.c.
References fp2_dbl.
Referenced by fp12_sqr(), and fp18_sqr_basic().
void fp6_neg (fp6_t c, fp6_t a)
Negates a sextic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the sextic extension field element to negate.
Definition at line 144 of file relic_fpx_add.c.
References fp2_neg().
Referenced by fp12_inv(), fp12_inv_uni(), fp12_neg(), and fp18_neg().
void fp12_add (fp12_t c, fp12_t a, fp12_t b)
Adds two dodecic extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first dodecic extension field element.
[in] B - the second dodecic extension field element.
Definition at line 150 of file relic_fpx_add.c.
References fp6_add().
void fp12_sub (fp12_t c, fp12_t a, fp12_t b)
Subtracts a dodecic extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first dodecic extension field element.
[in] B - the second dodecic extension field element.
Definition at line 155 of file relic_fpx_add.c.
References fp6_sub().
void fp12_neg (fp12_t c, fp12_t a)
Negates a dodecic extension field element.
Parameters
[out] C - the result.
[out] A - the dodecic extension field element to negate.
Definition at line 160 of file relic_fpx_add.c.
References fp6_neg().
void fp18_add (fp18_t c, fp18_t a, fp18_t b)
Adds two octodecic extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first octodecic extension field element.
[in] B - the second octodecic extension field element.
Definition at line 165 of file relic_fpx_add.c.
References fp6_add().
void fp18_sub (fp18_t c, fp18_t a, fp18_t b)
Subtracts a octodecic extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first octodecic extension field element.
[in] B - the second octodecic extension field element.
Definition at line 171 of file relic_fpx_add.c.
References fp6_sub().
void fp18_neg (fp18_t c, fp18_t a)
Negates a octodecic extension field element.
Parameters
[out] C - the result.
[out] A - the octodecic extension field element to negate.
Definition at line 177 of file relic_fpx_add.c.
References fp6_neg().