RELIC: src/ep/relic_ep_param.c File Reference
relic_ep_param.c File Reference
Prime elliptic curves.
#include "relic_core.h"
#include "relic_epx.h"
Macros
#define ASSIGN(CURVE, FIELD)
#define ASSIGNK(CURVE, FIELD)
#define NIST_P256_A "FFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFC"
#define NIST_P256_B "5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B"
#define NIST_P256_X "6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296"
#define NIST_P256_Y "4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5"
#define NIST_P256_R "FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551"
#define NIST_P256_H "1"
#define SECG_K256_A "0"
#define SECG_K256_B "7"
#define SECG_K256_X "79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798"
#define SECG_K256_Y "483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8"
#define SECG_K256_R "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141"
#define SECG_K256_H "1"
#define SECG_K256_BETA "7AE96A2B657C07106E64479EAC3434E99CF0497512F58995C1396C28719501EE"
#define SECG_K256_LAMB "5363AD4CC05C30E0A5261C028812645A122E22EA20816678DF02967C1B23BD72"
#define BN_P256_A "0"
#define BN_P256_B "11"
#define BN_P256_X "B64000000000FF2F2200000085FD5480B0001F44B6B88BF142BC818F95E3E6AE"
#define BN_P256_Y "4"
#define BN_P256_R "B64000000000FF2F2200000085FD547FD8001F44B6B7F4B7C2BC818F7B6BEF99"
#define BN_P256_H "1"
#define BN_P256_BETA "B64000000000FF2E2F00000085FC555230001F445D656FB022BC77236CD54C89"
#define BN_P256_LAMB "B64000000000FF2D3C00000085FB562050001F44040FF68D82BC6CB6D9E8694E"
Functions
int ep_param_get ()
void ep_param_set (int param)
int ep_param_set_any ()
int ep_param_set_any_ordin ()
int ep_param_set_any_kbltz ()
int ep_param_set_any_super ()
int ep_param_set_any_pairf ()
void ep_param_print ()
int ep_param_level ()
int ep_param_embed ()
Detailed Description
Implementation of the prime elliptic curve utilities.
Version
Id:
relic_ep_param.c 1493 2013-06-02 19:23:13Z dfaranha
Definition in file relic_ep_param.c.
Macro Definition Documentation
#define NIST_P256_A "FFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFC"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 134 of file relic_ep_param.c.
#define NIST_P256_B "5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 135 of file relic_ep_param.c.
#define NIST_P256_X "6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 136 of file relic_ep_param.c.
#define NIST_P256_Y "4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 137 of file relic_ep_param.c.
#define NIST_P256_R "FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 138 of file relic_ep_param.c.
#define NIST_P256_H "1"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 139 of file relic_ep_param.c.
#define SECG_K256_A "0"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 148 of file relic_ep_param.c.
#define SECG_K256_B "7"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 149 of file relic_ep_param.c.
#define SECG_K256_X "79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 150 of file relic_ep_param.c.
#define SECG_K256_Y "483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 151 of file relic_ep_param.c.
#define SECG_K256_R "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 152 of file relic_ep_param.c.
#define SECG_K256_H "1"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 153 of file relic_ep_param.c.
#define SECG_K256_BETA "7AE96A2B657C07106E64479EAC3434E99CF0497512F58995C1396C28719501EE"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 154 of file relic_ep_param.c.
#define SECG_K256_LAMB "5363AD4CC05C30E0A5261C028812645A122E22EA20816678DF02967C1B23BD72"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 155 of file relic_ep_param.c.
#define BN_P256_A "0"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 224 of file relic_ep_param.c.
#define BN_P256_B "11"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 225 of file relic_ep_param.c.
#define BN_P256_X "B64000000000FF2F2200000085FD5480B0001F44B6B88BF142BC818F95E3E6AE"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 226 of file relic_ep_param.c.
#define BN_P256_Y "4"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 227 of file relic_ep_param.c.
#define BN_P256_R "B64000000000FF2F2200000085FD547FD8001F44B6B7F4B7C2BC818F7B6BEF99"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 228 of file relic_ep_param.c.
#define BN_P256_H "1"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 229 of file relic_ep_param.c.
#define BN_P256_BETA "B64000000000FF2E2F00000085FC555230001F445D656FB022BC77236CD54C89"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 230 of file relic_ep_param.c.
#define BN_P256_LAMB "B64000000000FF2D3C00000085FB562050001F44040FF68D82BC6CB6D9E8694E"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 231 of file relic_ep_param.c.
#define ASSIGN (CURVE, FIELD)
Value:
fp_param_set(FIELD);                                                    \
    FETCH(str, CURVE##_A, sizeof(CURVE##_A));                               \
    fp_read(a, str, strlen(str), 16);                                       \
    FETCH(str, CURVE##_B, sizeof(CURVE##_B));                               \
    fp_read(b, str, strlen(str), 16);                                       \
    FETCH(str, CURVE##_X, sizeof(CURVE##_X));                               \
    fp_read(g->x, str, strlen(str), 16);                                    \
    FETCH(str, CURVE##_Y, sizeof(CURVE##_Y));                               \
    fp_read(g->y, str, strlen(str), 16);                                    \
    FETCH(str, CURVE##_R, sizeof(CURVE##_R));                               \
    bn_read_str(r, str, strlen(str), 16);                                   \
    FETCH(str, CURVE##_H, sizeof(CURVE##_H));                               \
    bn_read_str(h, str, strlen(str), 16);                                   \
Assigns a set of ordinary elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
[in] FIELD - the finite field identifier.
Definition at line 319 of file relic_ep_param.c.
Referenced by ep_param_set().
#define ASSIGNK (CURVE, FIELD)
Value:
ASSIGN(CURVE, FIELD);                                                   \
    FETCH(str, CURVE##_BETA, sizeof(CURVE##_BETA));                         \
    fp_read(beta, str, strlen(str), 16);                                    \
    FETCH(str, CURVE##_LAMB, sizeof(CURVE##_LAMB));                         \
    bn_read_str(lamb, str, strlen(str), 16);                                \
Assigns a set of Koblitz elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
[in] FIELD - the finite field identifier.
Definition at line 340 of file relic_ep_param.c.
Referenced by ep_param_set().
Function Documentation
int ep_param_get (void)
Returns the parameter identifier of the currently configured prime elliptic curve.
Returns
the parameter identifier.
Definition at line 351 of file relic_ep_param.c.
References core_get(), and _ctx_t::ep_id.
Referenced by ep2_curve_set(), ep2_map(), ep_param_embed(), ep_param_level(), ep_param_print(), pp_exp_k12(), and pp_map_oatep_k12().
void ep_param_set (int param)
Configures a new prime elliptic curve by its parameter identifier.
Parameters
- the parameter identifier.
Definition at line 355 of file relic_ep_param.c.
References ASSIGN, ASSIGNK, B12_638, B12_P638, B24_477, B24_P477, BN_158, BN_254, BN_256, BN_638, bn_free, bn_new, bn_null, BN_P158, BN_P254, BN_P256, BN_P638, CATCH_ANY, core_get(), ep_curve_set_kbltz(), ep_curve_set_ordin(), ep_curve_set_super(), ep_free, _ctx_t::ep_id, ep_new, ep_null, ERR_CAUGHT, ERR_NO_VALID, FINALLY, FP_BYTES, fp_free, fp_new, fp_null, fp_set_dig(), fp_zero(), KSS_508, KSS_P508, NIST_192, NIST_224, NIST_256, NIST_384, NIST_521, NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, SECG_160, SECG_160D, SECG_192, SECG_224, SECG_256, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, SS_1536, SS_P1536, THROW, and TRY.
Referenced by ep_param_set_any_kbltz(), ep_param_set_any_ordin(), ep_param_set_any_pairf(), and ep_param_set_any_super().
int ep_param_set_any (void)
Configures some set of curve parameters for the current security level.
Definition at line 542 of file relic_ep_param.c.
References ep_param_set_any_kbltz(), ep_param_set_any_ordin(), ep_param_set_any_pairf(), STS_ERR, and STS_OK.
int ep_param_set_any_ordin (void)
Configures some set of ordinary curve parameters for the current security level.
Returns
STS_OK if there is a curve at this security level, STS_ERR otherwise.
Definition at line 558 of file relic_ep_param.c.
References ep_param_set(), NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, SECG_P160, STS_ERR, and STS_OK.
Referenced by ep_param_set_any().
int ep_param_set_any_kbltz (void)
Configures some set of Koblitz curve parameters for the current security level.
Returns
STS_OK if there is a curve at this security level, STS_ERR otherwise.
Definition at line 582 of file relic_ep_param.c.
References B24_P477, BN_P158, BN_P254, BN_P638, ep_param_set(), KSS_P508, SECG_K160, SECG_K192, SECG_K224, SECG_K256, STS_ERR, and STS_OK.
Referenced by ep_param_set_any().
int ep_param_set_any_super (void)
Configures some set of supersingular curve parameters for the current security level.
Returns
STS_OK if there is a curve at this security level, STS_ERR otherwise.
Definition at line 612 of file relic_ep_param.c.
References ep_param_set(), SS_P1536, STS_ERR, and STS_OK.
int ep_param_set_any_pairf (void)
Configures some set of pairing-friendly curve parameters for the current security level.
Returns
STS_OK if there is a curve at this security level, STS_ERR otherwise.
Definition at line 626 of file relic_ep_param.c.
References B12_P638, B24_P477, BN_P158, BN_P254, BN_P256, ep2_curve_set(), EP_DTYPE, EP_MTYPE, ep_param_set(), KSS_P508, SS_P1536, STS_ERR, and STS_OK.
Referenced by ep_param_set_any().
void ep_param_print (void)
Prints the current configured prime elliptic curve.
Definition at line 678 of file relic_ep_param.c.
References B12_P638, B24_P477, BN_P158, BN_P254, BN_P256, BN_P638, ep_param_get(), KSS_P508, NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, SS_P1536, and util_banner.
int ep_param_level (void)
Returns the current security level.
Definition at line 737 of file relic_ep_param.c.
References B12_P638, BN_P158, BN_P254, BN_P256, BN_P638, ep_param_get(), NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, and SS_P1536.
int ep_param_embed (void)
Returns the embedding degree of the currently configured elliptic curve.
Definition at line 768 of file relic_ep_param.c.
References B12_P638, BN_P158, BN_P254, BN_P256, BN_P638, ep_param_get(), and SS_P1536.