RELIC: include/relic_pb.h File Reference
relic_pb.h File Reference
Pairings over binary elliptic curves.
#include "relic_fb.h"
#include "relic_fbx.h"
#include "relic_eb.h"
#include "relic_types.h"
Macros
#define pb_map(R, P, Q) pb_map_etats(R, P, Q)
Functions
void pb_map_init ()
void pb_map_clean ()
const fb_t * pb_map_get_tab ()
const fb_t * pb_map_get_sqr ()
const fb_t * pb_map_get_srt ()
int pb_map_get_par (int core)
void pb_map_etats (fb4_t r, const eb_t p, const eb_t q)
void pb_map_etatn (fb4_t r, const eb_t p, const eb_t q)
Detailed Description
Interface of the module for computing bilinear pairings over binary elliptic curves.
Version
Id:
relic_pb.h 1585 2013-09-03 08:17:47Z dfaranha
Definition in file relic_pb.h.
Macro Definition Documentation
#define pb_map (R, P, Q) pb_map_etats(R, P, Q)
Computes the pairing of two binary elliptic curve points. Computes R = e(P, Q).
Parameters
[out] R - the result.
[in] P - the first elliptic curve point.
[in] Q - the second elliptic curve point.
Definition at line 58 of file relic_pb.h.
Function Documentation
void pb_map_init ()
Initializes the module for computing pairings over binary fields.
Definition at line 43 of file relic_pb_map.c.
References core_get(), CORES, FB_BITS, fb_itr_pre, FB_TABLE, _ctx_t::pb_exp, pb_map_get_sqr(), pb_map_get_srt(), pb_map_get_tab(), and _ctx_t::pb_ptr.
Referenced by core_init(), and fb_poly_set().
void pb_map_clean ()
Finalizes the module for computing pairings over binary fields.
Definition at line 72 of file relic_pb_map.c.
Referenced by core_clean().
const fb_t* pb_map_get_tab ()
Returns the table for computing the final exponentiation in the selected pairing.
Returns
The precomputed table.
Definition at line 76 of file relic_pb_map.c.
References core_get(), and _ctx_t::pb_ptr.
Referenced by etat_exp(), and pb_map_init().
const fb_t* pb_map_get_sqr ()
Returns the table for computing the repeated squarings needed for parallel execution.
Returns
The precomputed table.
const fb_t* pb_map_get_srt ()
Returns the table for computing the repeated square-roots needed for parallel execution.
Returns
The precomputed table.
int pb_map_get_par (int core)
Returns the parallel partition of the pairing algorithm for a given core.
Parameters
[in] core - the core identifier.
Returns
The chunk size.
Definition at line 112 of file relic_pb_map.c.
References CORES, FB_BITS, and MIN.
Referenced by pb_map_etats_imp().
void pb_map_etats (fb4_t r, const eb_t p, const eb_t q)
Computes the etat pairing of two binary elliptic curve points without using square roots.
Parameters
[out] r - the result.
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Definition at line 619 of file relic_pb_etat1.c.
References etat_exp(), and pb_map_etats_imp().
void pb_map_etatn (fb4_t r, const eb_t p, const eb_t q)
Computes the etat pairing of two binary elliptic curve points using square roots.
Parameters
[out] r - the result.
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Definition at line 628 of file relic_pb_etat1.c.
References etat_exp(), and pb_map_etatn_imp().