RELIC: src/fpx/relic_fp18_mul.c File Reference
relic_fp18_mul.c File Reference
Extensions of prime fields.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_pp_low.h"
Functions
void fp18_mul_basic (fp18_t c, fp18_t a, fp18_t b)
static void fp6_mul_dxs_basic (fp6_t c, fp6_t a, fp6_t b)
static void fp6_mul_dxs_unr (dv6_t c, fp6_t a, fp6_t b)
static void fp6_mul0_basic (fp6_t c, fp6_t a, fp6_t b)
static void fp6_mul1_basic (fp6_t c, fp6_t a, fp6_t b)
void fp18_mul_dxs_basic (fp18_t c, fp18_t a, fp18_t b)
void fp18_mul_lazyr (fp18_t c, fp18_t a, fp18_t b)
void fp18_mul_dxs_lazyr (fp18_t c, fp18_t a, fp18_t b)
Detailed Description
Implementation of multiplication in a octodecic extension of a prime field.
Version
Id:
relic_fp18_mul.c 1590 2013-09-03 08:20:00Z dfaranha
Definition in file relic_fp18_mul.c.
Function Documentation
void fp18_mul_basic (fp18_t c, fp18_t a, fp18_t b)
Multiples two octodecic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the octodecic extension field element.
[in] b - the octodecic extension field element.
Definition at line 42 of file relic_fp18_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_add(), fp6_copy(), fp6_free, fp6_mul, fp6_mul_art(), fp6_new, fp6_null, fp6_sub(), THROW, and TRY.
static void fp6_mul_dxs_basic (fp6_t c, fp6_t a, fp6_t b) static
Definition at line 105 of file relic_fp18_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_add, fp3_free, fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_sub, fp_copy(), THROW, and TRY.
Referenced by fp18_mul_dxs_basic().
static void fp6_mul_dxs_unr (dv6_t c, fp6_t a, fp6_t b) static
Definition at line 154 of file relic_fp18_mul.c.
References CATCH_ANY, dv_copy(), dv_zero(), ERR_CAUGHT, FINALLY, fp3_add, fp3_free, fp3_muln_low(), fp3_new, fp3_null, fp_copy(), FP_DIGS, fp_prime_get_cnr(), fp_subc_low(), THROW, and TRY.
Referenced by fp18_mul_dxs_lazyr().
static void fp6_mul0_basic (fp6_t c, fp6_t a, fp6_t b) static
Definition at line 213 of file relic_fp18_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_add, fp2_copy(), fp2_free, fp2_mul, fp2_mul_art(), fp2_mul_nor, fp2_new, fp2_null, fp2_sub, fp_add, fp_copy(), fp_mul, THROW, and TRY.
Referenced by fp18_mul_dxs_basic(), and fp18_mul_dxs_lazyr().
static void fp6_mul1_basic (fp6_t c, fp6_t a, fp6_t b) static
Definition at line 286 of file relic_fp18_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_add, fp2_copy(), fp2_free, fp2_mul, fp2_mul_art(), fp2_mul_nor, fp2_new, fp2_null, fp2_sub, fp_add, fp_copy(), fp_mul, fp_zero(), THROW, and TRY.
Referenced by fp18_mul_dxs_basic(), and fp18_mul_dxs_lazyr().
void fp18_mul_dxs_basic (fp18_t c, fp18_t a, fp18_t b)
Multiples a dense octodecic extension field element by a sparse element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dense octodecic extension field element.
[in] b - the sparse octodecic extension field element.
Definition at line 361 of file relic_fp18_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_add(), fp6_copy(), fp6_free, fp6_mul, fp6_mul0_basic(), fp6_mul1_basic(), fp6_mul_art(), fp6_mul_dxs_basic(), fp6_new, fp6_null, fp6_sub(), THROW, and TRY.
void fp18_mul_lazyr (fp18_t c, fp18_t a, fp18_t b)
Multiples two octodecic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octodecic extension field element.
[in] b - the octodecic extension field element.
Definition at line 466 of file relic_fp18_mul.c.
References CATCH_ANY, dv6_free, dv6_new, dv6_null, dv_copy(), ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp6_add(), fp6_free, fp6_mul_unr(), fp6_new, fp6_null, FP_DIGS, THROW, and TRY.
void fp18_mul_dxs_lazyr (fp18_t c, fp18_t a, fp18_t b)
Multiples a dense octodecic extension field element by a sparse element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dense octodecic extension field element.
[in] b - the sparse octodecic extension field element.
Definition at line 551 of file relic_fp18_mul.c.
References CATCH_ANY, dv6_free, dv6_new, dv6_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp6_add(), fp6_copy(), fp6_free, fp6_mul, fp6_mul0_basic(), fp6_mul1_basic(), fp6_mul_art(), fp6_mul_dxs_unr(), fp6_mul_unr(), fp6_new, fp6_null, fp6_sub(), THROW, and TRY.