RELIC: src/pb/relic_pb_map.c File Reference
relic_pb_map.c File Reference
Pairings over binary elliptic curves.
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_bench.h"
#include "relic_pb.h"
#include "relic_util.h"
Functions
void pb_map_init ()
void pb_map_clean ()
const fb_t * pb_map_get_tab ()
const fb_t * pb_map_get_sqr (int core)
const fb_t * pb_map_get_srt (int core)
int pb_map_get_par (int core)
Detailed Description
Implementation of the core functions for computing pairings over binary fields.
Version
Id:
relic_pb_map.c 1576 2013-09-03 05:41:43Z dfaranha
Definition in file relic_pb_map.c.
Function Documentation
void pb_map_init ()
Initializes the module for computing pairings over binary fields.
Definition at line 43 of file relic_pb_map.c.
References core_get(), CORES, FB_BITS, fb_itr_pre, FB_TABLE, _ctx_t::pb_exp, pb_map_get_sqr(), pb_map_get_srt(), pb_map_get_tab(), and _ctx_t::pb_ptr.
Referenced by core_init(), and fb_poly_set().
void pb_map_clean ()
Finalizes the module for computing pairings over binary fields.
Definition at line 72 of file relic_pb_map.c.
Referenced by core_clean().
const fb_t* pb_map_get_tab ()
Returns the table for computing the final exponentiation in the selected pairing.
Returns
The precomputed table.
Definition at line 76 of file relic_pb_map.c.
References core_get(), and _ctx_t::pb_ptr.
Referenced by etat_exp(), and pb_map_init().
const fb_t* pb_map_get_sqr (int core)
Definition at line 84 of file relic_pb_map.c.
References core_get().
Referenced by pb_map_etats_imp(), and pb_map_init().
const fb_t* pb_map_get_srt (int core)
Definition at line 98 of file relic_pb_map.c.
References core_get().
Referenced by pb_map_etats_imp(), and pb_map_init().
int pb_map_get_par (int core)
Returns the parallel partition of the pairing algorithm for a given core.
Parameters
[in] core - the core identifier.
Returns
The chunk size.
Definition at line 112 of file relic_pb_map.c.
References CORES, FB_BITS, and MIN.
Referenced by pb_map_etats_imp().