RELIC: src/cp/relic_cp_ecdsa.c File Reference
relic_cp_ecdsa.c File Reference
Cryptographic protocols.
#include "relic.h"
#include "relic_test.h"
Functions
void cp_ecdsa_gen (bn_t d, ec_t q)
void cp_ecdsa_sig (bn_t r, bn_t s, unsigned char *msg, int len, int hash, bn_t d)
int cp_ecdsa_ver (bn_t r, bn_t s, unsigned char *msg, int len, int hash, ec_t q)
Detailed Description
Implementation of the ECDSA protocol.
Version
Id:
relic_cp_ecdsa.c 1504 2013-06-26 20:33:59Z conradoplg
Definition in file relic_cp_ecdsa.c.
Function Documentation
void cp_ecdsa_gen (bn_t d, ec_t q)
Generates an ECDSA key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Definition at line 39 of file relic_cp_ecdsa.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ec_curve_get_ord, ec_mul_gen, ERR_CAUGHT, FINALLY, THROW, and TRY.
void cp_ecdsa_sig (bn_t r, bn_t s, unsigned char * msg, int len, int hash, bn_t d)
Signs a message using ECDSA.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] d - the private key.
Definition at line 64 of file relic_cp_ecdsa.c.
References bn_add(), bn_bits(), bn_free, bn_gcd_ext, bn_is_zero(), bn_mod, bn_mul, BN_NEG, bn_new, bn_null, BN_POS, bn_rand(), bn_read_bin(), bn_rsh(), bn_sign(), CATCH_ANY, CEIL, ec_curve_get_ord, ec_free, ec_get_x, ec_mul_gen, ec_new, ec_null, ERR_CAUGHT, FINALLY, MD_LEN, md_map, THROW, and TRY.
int cp_ecdsa_ver (bn_t r, bn_t s, unsigned char * msg, int len, int hash, ec_t q)
Verifies a message signed with ECDSA using the basic method.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] q - the public key.
Definition at line 133 of file relic_cp_ecdsa.c.
References bn_add(), bn_bits(), bn_cmp(), bn_free, bn_gcd_ext, bn_is_zero(), bn_mod, bn_mul, BN_NEG, bn_new, bn_null, BN_POS, bn_read_bin(), bn_rsh(), bn_sign(), CATCH_ANY, CEIL, CMP_LT, CMP_NE, dv_cmp_const(), ec_curve_get_ord, ec_free, ec_get_x, ec_is_infty, ec_mul_sim_gen, ec_new, ec_null, ERR_CAUGHT, FINALLY, MD_LEN, md_map, MIN, THROW, and TRY.