RELIC: src/md/relic_md_sha224.c File Reference
relic_md_sha224.c File Reference
Hash functions.
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_md.h"
#include "sha.h"
Functions
void md_map_sh224 (unsigned char *hash, const unsigned char *msg, int len)
Detailed Description
Implementation of the SHA-224 hash function.
Version
Id:
relic_md_sha224.c 1566 2013-09-02 04:09:52Z dfaranha
Definition in file relic_md_sha224.c.
Function Documentation
void md_map_sh224 (unsigned char * hash, const unsigned char * msg, int len)
Computes the SHA-224 hash function.
Parameters
[out] hash - the digest.
[in] msg - the message to hash.
[in] len - the message length in bytes.
Definition at line 41 of file relic_md_sha224.c.
References ERR_NO_VALID, SHA224Input(), SHA224Reset(), SHA224Result(), shaSuccess, and THROW.