#!/bin/bash

#
# University of Luxembourg
# Laboratory of Algorithmics, Cryptology and Security (LACS)
#
# FELICS - Fair Evaluation of Lightweight Cryptographic Systems
#
# Copyright (C) 2015 University of Luxembourg
#
# Written in 2015 by Daniel Dinu <dumitru-daniel.dinu@uni.lu>
#
# This file is part of FELICS.
#
# FELICS is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# FELICS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#

#
# Constants
#


FALSE=0
TRUE=1

SCRIPT_MODE_0=0
SCRIPT_MODE_1=1

SCRIPT_MODES=($SCRIPT_MODE_0 $SCRIPT_MODE_1)


SCRIPT_SCENARIO_0=0
SCRIPT_SCENARIO_1=1

SCRIPT_SCENARIOS=($SCRIPT_SCENARIO_0 $SCRIPT_SCENARIO_1)


SCRIPT_ARCHITECTURE_PC=PC
SCRIPT_ARCHITECTURE_AVR=AVR
SCRIPT_ARCHITECTURE_MSP=MSP
SCRIPT_ARCHITECTURE_ARM=ARM

SCRIPT_ARCHITECTURES=($SCRIPT_ARCHITECTURE_PC $SCRIPT_ARCHITECTURE_AVR $SCRIPT_ARCHITECTURE_MSP $SCRIPT_ARCHITECTURE_ARM)

SCRIPT_ARCHITECTURES=($SCRIPT_ARCHITECTURE_PC $SCRIPT_ARCHITECTURE_AVR $SCRIPT_ARCHITECTURE_MSP $SCRIPT_ARCHITECTURE_ARM)

SCRIPT_COMPILER_OPTION_OPTIMIZE_3="-O3"
SCRIPT_COMPILER_OPTION_OPTIMIZE_2="-O2"
SCRIPT_COMPILER_OPTION_OPTIMIZE_1="-O1"
SCRIPT_COMPILER_OPTION_OPTIMIZE_S="-Os"

SCRIPT_COMPILER_OPTIONS=("$SCRIPT_COMPILER_OPTION_OPTIMIZE_3" "$SCRIPT_COMPILER_OPTION_OPTIMIZE_2" "$SCRIPT_COMPILER_OPTION_OPTIMIZE_1" "$SCRIPT_COMPILER_OPTION_OPTIMIZE_S")

DEFAULT_SCRIPT_TARGET=.
DEFAULT_SCRIPT_OUTPUT=/dev/tty

CIPHER_FILE=cipher
SCENARIO1_FILE=scenario1

ALL_FILES=*
ELF_FILE_EXTENSION=.elf
OBJECT_FILE_EXTENSION=.o

SCRIPT_VERBOSE_DISABLED=0
SCRIPT_VERBOSE_ENABLED=1

SCRIPT_BUILD_DISABLED=0
SCRIPT_BUILD_ENABLED=1

SCRIPT_INCREMENTAL_STRATEGY_DISABLED=0
SCRIPT_INCREMENTAL_STRATEGY_ENABLED=1


IMPLEMENTATION_INFO_FILE=./../source/implementation.info

SECTION_SEPARATOR=:

CODE_SECTION_S=SetupCode
CODE_SECTION_E=EncryptCode

CODE_SECTIONS=($CODE_SECTION_S $CODE_SECTION_E)

CONSTANTS_SECTION_S=SetupConstants
CONSTANTS_SECTION_E=EncryptConstants

CONSTANTS_SECTIONS=($CONSTANTS_SECTION_S $CONSTANTS_SECTION_E)

IMPLEMENTATION_TYPE=Implementation
IMPLEMENTATION_ASM=ASM
IMPLEMENTATION_C=C
IMPLEMENTATION_C_ASM=C+ASM

EXAMPLE_CIPHER_NAME=CipherName

DIRECTORY_NAME_SEPARATOR=_

FILE_NAME_SEPARATOR=_

SCENARIO_NAME_PART=_scenario
COMPILER_OPTIONS_NAME_PART=_co_

SCRIPT_FORMAT_0=0
SCRIPT_FORMAT_1=1
SCRIPT_FORMAT_2=2
SCRIPT_FORMAT_3=3
SCRIPT_FORMAT_4=4
SCRIPT_FORMAT_5=5

SCRIPT_FORMATS=($SCRIPT_FORMAT_0 $SCRIPT_FORMAT_1 $SCRIPT_FORMAT_2 $SCRIPT_FORMAT_3 $SCRIPT_FORMAT_4 $SCRIPT_FORMAT_5)

SCRIPT_VERBOSITY_0=0
SCRIPT_VERBOSITY_1=1
SCRIPT_VERBOSITY_2=2

SCRIPT_VERBOSITIES=($SCRIPT_VERBOSITY_0 $SCRIPT_VERBOSITY_1 $SCRIPT_VERBOSITY_2)

KEEP_GENERATED_FILES=1

MAKE_CLEAN_TARGET=clean


SCRIPT_OUTPUT_PATH=./../results/

INFO_OUTPUT_FILE_NAME=info

SCRIPT_RAW_OUTPUT_EXTENSION=.out
SCRIPT_MEDIAWIKI_OUTPUT_EXTENSION=.mwk
SCRIPT_XML_OUTPUT_EXTENSION=.xml
SCRIPT_LATEX_OUTPUT_EXTENSION=.tex
SCRIPT_CSV_OUTPUT_EXTENSION=.csv

CIPHERS_PATH=./../source/ciphers/

CSV_FIELD_DELIMITER=,
CSV_TEXT_DELIMITER=\"
CSV_EQUAL_DELIMITER==
