RELIC: include/relic_eb.h File Reference
relic_eb.h File Reference
Elliptic curves over binary fields.
#include "relic_fb.h"
#include "relic_bn.h"
#include "relic_conf.h"
#include "relic_types.h"
#include "relic_label.h"
Data Structures
struct eb_st
Macros
#define EB_TABLE_BASIC (FB_BITS)
#define EB_TABLE_YAOWI (FB_BITS / EB_DEPTH + 1)
#define EB_TABLE_NAFWI (FB_BITS / EB_DEPTH + 1)
#define EB_TABLE_COMBS (1 << EB_DEPTH)
#define EB_TABLE_COMBD (1 << (EB_DEPTH + 1))
#define EB_TABLE_LWNAF (1 << (EB_DEPTH - 2))
#define EB_TABLE EB_TABLE_COMBS
#define EB_TABLE_MAX MAX(EB_TABLE_BASIC, EB_TABLE_COMBD)
#define eb_null(A) /* empty */
#define eb_new(A) /* empty */
#define eb_free(A) /* empty */
#define eb_neg(R, P) eb_neg_projc(R, P)
#define eb_add(R, P, Q) eb_add_projc(R, P, Q);
#define eb_sub(R, P, Q) eb_sub_projc(R, P, Q)
#define eb_dbl(R, P) eb_dbl_projc(R, P);
#define eb_frb(R, P) eb_frb_projc(R, P)
#define eb_mul(R, P, K) eb_mul_lwnaf(R, P, K)
#define eb_mul_pre(T, P) eb_mul_pre_combs(T, P)
#define eb_mul_fix(R, T, K) eb_mul_fix_combs(R, T, K)
#define eb_mul_sim(R, P, K, Q, M) eb_mul_sim_inter(R, P, K, Q, M)
Typedefs
typedef eb_st eb_t [1]
Enumerations
enum {
NIST_B163 = 1, NIST_K163, NIST_B233, NIST_K233,
EBACS_B251, HALVE_B257, SECG_K239, NIST_B283,
NIST_K283, NIST_B409, NIST_K409, NIST_B571,
NIST_K571, ETAT_P271, ETAT_T271, ETAT_S353,
ETAT_S1223
}
Functions
void eb_curve_init (void)
void eb_curve_clean (void)
dig_t * eb_curve_get_a (void)
dig_t * eb_curve_get_b (void)
dig_t * eb_curve_get_c (void)
int eb_curve_opt_a (void)
int eb_curve_opt_b (void)
int eb_curve_opt_c (void)
int eb_curve_is_kbltz (void)
int eb_curve_is_super (void)
void eb_curve_get_gen (eb_t g)
const eb_t * eb_curve_get_tab (void)
void eb_curve_get_ord (bn_t n)
void eb_curve_get_cof (bn_t h)
void eb_curve_get_vm (bn_t vm)
void eb_curve_get_s0 (bn_t s0)
void eb_curve_get_s1 (bn_t s1)
void eb_curve_set_ordin (const fb_t a, const fb_t b, const eb_t g, const bn_t n, const bn_t h)
void eb_curve_set_kbltz (const fb_t a, const eb_t g, const bn_t n, const bn_t h)
void eb_curve_set_super (const fb_t a, const fb_t b, const fb_t c, const eb_t g, const bn_t n, const bn_t h)
void eb_param_set (int param)
int eb_param_set_any (void)
int eb_param_set_any_ordin (void)
int eb_param_set_any_kbltz (void)
int eb_param_set_any_super (void)
int eb_param_get (void)
void eb_param_print (void)
int eb_param_level (void)
int eb_is_infty (const eb_t p)
void eb_set_infty (eb_t p)
void eb_copy (eb_t r, const eb_t p)
int eb_cmp (const eb_t p, const eb_t q)
void eb_rand (eb_t p)
void eb_rhs (fb_t rhs, const eb_t p)
int eb_is_valid (const eb_t p)
void eb_tab (eb_t *t, const eb_t p, int w)
void eb_print (const eb_t p)
void eb_neg_basic (eb_t r, const eb_t p)
void eb_neg_projc (eb_t r, const eb_t p)
void eb_add_basic (eb_t r, const eb_t p, const eb_t q)
void eb_add_projc (eb_t r, const eb_t p, const eb_t q)
void eb_sub_basic (eb_t r, const eb_t p, const eb_t q)
void eb_sub_projc (eb_t r, const eb_t p, const eb_t q)
void eb_dbl_basic (eb_t r, const eb_t p)
void eb_dbl_projc (eb_t r, const eb_t p)
void eb_hlv (eb_t r, const eb_t p)
void eb_frb_basic (eb_t r, const eb_t p)
void eb_frb_projc (eb_t r, const eb_t p)
void eb_mul_basic (eb_t r, const eb_t p, const bn_t k)
void eb_mul_lodah (eb_t r, const eb_t p, const bn_t k)
void eb_mul_lwnaf (eb_t r, const eb_t p, const bn_t k)
void eb_mul_rwnaf (eb_t r, const eb_t p, const bn_t k)
void eb_mul_halve (eb_t r, const eb_t p, const bn_t k)
void eb_mul_gen (eb_t r, const bn_t k)
void eb_mul_dig (eb_t r, const eb_t p, const dig_t k)
void eb_mul_pre_basic (eb_t *t, const eb_t p)
void eb_mul_pre_yaowi (eb_t *t, const eb_t p)
void eb_mul_pre_nafwi (eb_t *t, const eb_t p)
void eb_mul_pre_combs (eb_t *t, const eb_t p)
void eb_mul_pre_combd (eb_t *t, const eb_t p)
void eb_mul_pre_lwnaf (eb_t *t, const eb_t p)
void eb_mul_fix_basic (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_fix_yaowi (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_fix_nafwi (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_fix_combs (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_fix_combd (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_fix_lwnaf (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_sim_basic (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_trick (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_inter (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_joint (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_gen (eb_t r, const bn_t k, const eb_t q, const bn_t m)
void eb_norm (eb_t r, const eb_t p)
void eb_norm_sim (eb_t *r, const eb_t *t, int n)
void eb_map (eb_t p, const unsigned char *msg, int len)
void eb_pck (eb_t r, const eb_t p)
int eb_upk (eb_t r, const eb_t p)
Detailed Description
Interface of the module for arithmetic on binary elliptic curves.
Version
Id:
relic_eb.h 1572 2013-09-02 07:11:29Z dfaranha
Definition in file relic_eb.h.
Macro Definition Documentation
#define EB_TABLE_BASIC (FB_BITS)
Size of a precomputation table using the binary method.
Definition at line 92 of file relic_eb.h.
#define EB_TABLE_YAOWI (FB_BITS / EB_DEPTH + 1)
Size of a precomputation table using Yao's windowing method.
Definition at line 97 of file relic_eb.h.
#define EB_TABLE_NAFWI (FB_BITS / EB_DEPTH + 1)
Size of a precomputation table using the NAF windowing method.
Definition at line 102 of file relic_eb.h.
#define EB_TABLE_COMBS (1 << EB_DEPTH)
Size of a precomputation table using the single-table comb method.
Definition at line 107 of file relic_eb.h.
Referenced by eb_mul_pre_combs().
#define EB_TABLE_COMBD (1 << (EB_DEPTH + 1))
Size of a precomputation table using the double-table comb method.
Definition at line 112 of file relic_eb.h.
#define EB_TABLE_LWNAF (1 << (EB_DEPTH - 2))
Size of a precomputation table using the w-(T)NAF method.
Definition at line 117 of file relic_eb.h.
#define EB_TABLE EB_TABLE_COMBS
Size of a precomputation table using the chosen algorithm.
Definition at line 129 of file relic_eb.h.
Referenced by eb_curve_clean(), and eb_curve_init().
#define EB_TABLE_MAX MAX(EB_TABLE_BASIC, EB_TABLE_COMBD)
Maximum size of a precomputation table.
Definition at line 142 of file relic_eb.h.
#define eb_null (A) /* empty */
Initializes a point on a binary elliptic curve with a null value.
Parameters
[out] A - the point to initialize.
Definition at line 191 of file relic_eb.h.
Referenced by eb_is_valid(), eb_mul_basic(), eb_mul_dig(), eb_mul_fix_nafwi(), eb_mul_fix_yaowi(), eb_mul_frb(), eb_mul_gen(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_rnaf_imp(), eb_mul_sim_basic(), eb_mul_sim_gen(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_ordin(), eb_mul_sim_trick(), eb_param_set(), eb_sub_basic(), and eb_sub_projc().
#define eb_new (A) /* empty */
Calls a function to allocate a point on a binary elliptic curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 223 of file relic_eb.h.
Referenced by eb_is_valid(), eb_mul_basic(), eb_mul_dig(), eb_mul_fix_nafwi(), eb_mul_fix_yaowi(), eb_mul_frb(), eb_mul_gen(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_basic(), eb_mul_sim_gen(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_ordin(), eb_mul_sim_trick(), eb_param_set(), eb_sub_basic(), and eb_sub_projc().
#define eb_free (A) /* empty */
Calls a function to clean and free a point on a binary elliptic curve.
Parameters
[out] A - the point to clean and free.
Definition at line 253 of file relic_eb.h.
Referenced by eb_is_valid(), eb_mul_basic(), eb_mul_dig(), eb_mul_fix_nafwi(), eb_mul_fix_yaowi(), eb_mul_frb(), eb_mul_gen(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_basic(), eb_mul_sim_gen(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_ordin(), eb_mul_sim_trick(), eb_param_set(), eb_sub_basic(), and eb_sub_projc().
#define eb_neg (R, P) eb_neg_projc(R, P)
Negates a binary elliptic curve point. Computes R = -P.
Parameters
[out] R - the result.
[in] P - the point to negate.
Definition at line 270 of file relic_eb.h.
Referenced by eb_mul_frb(), eb_mul_rtnaf_imp(), and eb_tab().
#define eb_add (R, P, Q) eb_add_projc(R, P, Q);
Adds two binary elliptic curve points. Computes R = P + Q.
Parameters
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add.
Definition at line 283 of file relic_eb.h.
Referenced by eb_mul_basic(), eb_mul_dig(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_nafwi(), eb_mul_fix_ordin(), eb_mul_fix_yaowi(), eb_mul_frb(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_basic(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_ordin(), eb_mul_sim_trick(), and eb_tab().
#define eb_sub (R, P, Q) eb_sub_projc(R, P, Q)
Subtracts a binary elliptic curve point from another. Computes R = P - Q.
Parameters
[out] R - the result.
[in] P - the first point.
[in] Q - the second point.
Definition at line 296 of file relic_eb.h.
Referenced by eb_mul_fix_kbltz(), eb_mul_fix_nafwi(), eb_mul_fix_ordin(), eb_mul_frb(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_ordin(), and eb_tab().
#define eb_dbl (R, P) eb_dbl_projc(R, P);
Doubles a binary elliptic curve point. Computes R = 2P.
Parameters
[out] R - the result.
[in] P - the point to double.
Definition at line 308 of file relic_eb.h.
Referenced by eb_mul_basic(), eb_mul_dig(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_ordin(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_pre_nafwi(), eb_mul_pre_yaowi(), eb_mul_rnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_ordin(), eb_mul_sim_trick(), and eb_tab().
#define eb_frb (R, P) eb_frb_projc(R, P)
Computes the Frobenius map of a binary elliptic curve point on a Koblitz curve. Computes R = t(P).
Parameters
[out] R - the result.
[in] P - the point.
Definition at line 321 of file relic_eb.h.
Referenced by eb_mul_fix_kbltz(), eb_mul_frb(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), and eb_tab().
#define eb_mul (R, P, K) eb_mul_lwnaf(R, P, K)
Multiplies a binary elliptic curve point by an integer. Computes R = kP.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer.
Definition at line 338 of file relic_eb.h.
Referenced by eb_map(), eb_mul_gen(), and eb_mul_sim_basic().
#define eb_mul_pre (T, P) eb_mul_pre_combs(T, P)
Builds a precomputation table for multiplying a fixed binary elliptic point point.
Parameters
[out] T - the precomputation table.
[in] P - the point to multiply.
Definition at line 357 of file relic_eb.h.
Referenced by eb_curve_set_kbltz(), eb_curve_set_ordin(), and eb_curve_set_super().
#define eb_mul_fix (R, T, K) eb_mul_fix_combs(R, T, K)
Multiplies a fixed binary elliptic point using a precomputation table. Computes R = kP.
Parameters
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer.
Definition at line 379 of file relic_eb.h.
Referenced by eb_mul_gen().
#define eb_mul_sim (R, P, K, Q, M) eb_mul_sim_inter(R, P, K, Q, M)
Multiplies and adds two binary elliptic curve points simultaneously. Computes R = kP + mQ.
Parameters
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer,
Definition at line 401 of file relic_eb.h.
Referenced by eb_mul_sim_gen().
Typedef Documentation
typedef eb_st eb_t[1]
Pointer to an elliptic curve point.
Definition at line 176 of file relic_eb.h.
Enumeration Type Documentation
anonymous enum
Binary elliptic curve identifiers.
Enumerator
NIST_B163
NIST B-163 binary curve.
NIST_K163
NIST K-163 Koblitz curve.
NIST_B233
NIST B-133 binary curve.
NIST_K233
NIST K-233 Koblitz curve.
EBACS_B251
Curve over 2^{251} used in eBATs.
HALVE_B257
Curve over 2^{257} good for halving.
SECG_K239
SECG K-239 binary curve.
NIST_B283
NIST B-283 binary curve.
NIST_K283
NIST K-283 Koblitz curve.
NIST_B409
NIST B-409 binary curve.
NIST_K409
NIST K-409 Koblitz curve.
NIST_B571
NIST B-571 binary curve.
NIST_K571
NIST K-571 Koblitz curve.
ETAT_P271
MIRACL low-security pairing-friendly curve.
ETAT_T271
MIRACL low-security pairing-friendly curve.
ETAT_S353
Pairing-friendly curve with 80-bit security.
ETAT_S1223
MIRACL high-security pairing-friendly curve.
Definition at line 52 of file relic_eb.h.
Function Documentation
void eb_curve_init (void)
Initializes the binary elliptic curve arithmetic module.
Definition at line 151 of file relic_eb_curve.c.
References bn_init(), core_get(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_pre, _ctx_t::eb_ptr, _ctx_t::eb_r, _ctx_t::eb_s0, _ctx_t::eb_s1, EB_TABLE, _ctx_t::eb_vm, FB_DIGS, fb_new, fb_zero(), eb_st::x, eb_st::y, and eb_st::z.
Referenced by core_init().
void eb_curve_clean (void)
Finalizes the binary elliptic curve arithmetic module.
Definition at line 180 of file relic_eb_curve.c.
References bn_clean(), core_get(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_pre, _ctx_t::eb_r, _ctx_t::eb_s0, _ctx_t::eb_s1, EB_TABLE, _ctx_t::eb_vm, fb_free, eb_st::x, eb_st::y, and eb_st::z.
Referenced by core_clean().
dig_t* eb_curve_get_a (void)
Returns the a coefficient of the currently configured binary elliptic curve.
Returns
the a coefficient of the elliptic curve.
Definition at line 201 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_a.
Referenced by eb_add_basic_ordin(), eb_add_projc_ordin_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_hlv(), eb_mul_halve(), and eb_rhs().
dig_t* eb_curve_get_b (void)
Returns the b coefficient of the currently configured binary elliptic curve.
Returns
the b coefficient of the elliptic curve.
Definition at line 209 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_b.
Referenced by eb_mul_halve(), eb_mul_lodah(), eb_rhs(), etat_exp(), pb_map_etatn_imp(), and pb_map_etats_imp().
dig_t* eb_curve_get_c (void)
Returns the c coefficient of the currently configured supersingular binary elliptic curve.
Returns
the c coefficient of the supersingular elliptic curve.
Definition at line 217 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_c.
Referenced by eb_add_basic_super(), eb_dbl_basic_super(), eb_is_valid(), eb_map(), eb_neg_basic(), eb_neg_projc(), eb_pck(), and eb_upk().
int eb_curve_opt_a (void)
Returns a optimization identifier based on the coefficient a of the curve.
Returns
the optimization identifier.
Definition at line 205 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_opt_a.
Referenced by eb_add_basic_ordin(), eb_add_projc_ordin_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_hlv(), eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), eb_rhs(), and eb_tab().
int eb_curve_opt_b (void)
Returns a optimization identifier based on the coefficient b of the curve.
Returns
the optimization identifier.
Definition at line 213 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_opt_b.
Referenced by eb_mul_lodah(), and eb_rhs().
int eb_curve_opt_c (void)
Returns a optimization identifier based on the coefficient c of the curve.
Returns
the optimization identifier.
Definition at line 226 of file relic_eb_curve.c.
References core_get(), _ctx_t::eb_opt_c, and OPT_NONE.
Referenced by eb_add_basic_super(), eb_dbl_basic_super(), eb_map(), eb_neg_basic(), and eb_neg_projc().
int eb_curve_is_kbltz (void)
Tests if the configured binary elliptic curve is a Koblitz curve.
Returns
1 if the binary elliptic curve is a Koblitz curve, 0 otherwise.
Definition at line 235 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_is_kbltz.
Referenced by eb_mul_fix_lwnaf(), eb_mul_lwnaf(), eb_mul_pre_lwnaf(), eb_mul_rwnaf(), eb_mul_sim_gen(), eb_mul_sim_inter(), and eb_tab().
int eb_curve_is_super (void)
Tests if the configured binary elliptic curve is supersingular.
Returns
1 if the binary elliptic curve is supersingular, 0 otherwise.
Definition at line 239 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_is_super.
Referenced by eb_add_basic(), eb_add_projc(), eb_dbl_basic(), eb_dbl_projc(), eb_is_valid(), eb_map(), eb_mul_lodah(), eb_mul_rwnaf(), eb_neg_basic(), eb_neg_projc(), eb_norm(), eb_norm_sim(), eb_pck(), eb_rhs(), and eb_upk().
void eb_curve_get_gen (eb_t g)
Returns the generator of the group of points in the binary elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 243 of file relic_eb_curve.c.
References core_get(), and eb_copy().
Referenced by eb_mul_gen(), and eb_mul_sim_gen().
const eb_t* eb_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 281 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_ptr.
Referenced by eb_curve_set_kbltz(), eb_curve_set_ordin(), eb_curve_set_super(), eb_mul_gen(), and eb_mul_sim_gen().
void eb_curve_get_ord (bn_t n)
Returns the order of the group of points in the binary elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 247 of file relic_eb_curve.c.
References bn_copy(), and core_get().
Referenced by eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_halve(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_pre_nafwi(), eb_mul_pre_yaowi(), eb_mul_sim_trick(), and eb_rand().
void eb_curve_get_cof (bn_t h)
Returns the cofactor of the binary elliptic curve.
Parameters
[out] n - the returned cofactor.
Definition at line 251 of file relic_eb_curve.c.
References bn_copy(), and core_get().
Referenced by eb_map(), and eb_mul_halve().
void eb_curve_get_vm (bn_t vm)
Returns the parameter Vm of a Koblitz curve.
Parameters
[out] vm - the returned parameter.
Definition at line 256 of file relic_eb_curve.c.
References bn_copy(), bn_zero(), and core_get().
Referenced by eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), and eb_tab().
void eb_curve_get_s0 (bn_t s0)
Returns the parameter S0 of a Koblitz curve.
Parameters
[out] s0 - the returned parameter.
Definition at line 264 of file relic_eb_curve.c.
References bn_copy(), bn_zero(), and core_get().
Referenced by eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), and eb_tab().
void eb_curve_get_s1 (bn_t s1)
Returns the parameter S1 of a Koblitz curve.
Parameters
[out] s1 - the returned parameter.
Definition at line 272 of file relic_eb_curve.c.
References bn_copy(), bn_zero(), and core_get().
Referenced by eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), and eb_tab().
void eb_curve_set_ordin (const fb_t a, const fb_t b, const eb_t g, const bn_t n, const bn_t h)
Configures a new ordinary binary elliptic curve by its coefficients and generator.
Parameters
[in] a - the coefficient a of the curve.
[in] b - the coefficient b of the curve.
[in] g - the generator.
[in] n - the order of the generator.
[in] h - the cofactor.
Definition at line 299 of file relic_eb_curve.c.
References bn_copy(), CMP_EQ, compute_kbltz(), core_get(), detect_opt(), _ctx_t::eb_a, _ctx_t::eb_b, eb_curve_get_tab(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_is_kbltz, _ctx_t::eb_is_super, eb_mul_pre, eb_norm(), _ctx_t::eb_opt_a, _ctx_t::eb_opt_b, _ctx_t::eb_r, fb_cmp_dig(), and fb_copy().
Referenced by eb_param_set().
void eb_curve_set_kbltz (const fb_t a, const eb_t g, const bn_t n, const bn_t h)
Configures a new Koblitz binary elliptic curve by its coefficients and generator.
Parameters
[in] a - the coefficient a of the curve.
[in] g - the generator.
[in] n - the order of the generator.
[in] h - the cofactor.
Definition at line 332 of file relic_eb_curve.c.
References bn_copy(), compute_kbltz(), core_get(), detect_opt(), _ctx_t::eb_a, _ctx_t::eb_b, eb_curve_get_tab(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_is_kbltz, _ctx_t::eb_is_super, eb_mul_pre, eb_norm(), _ctx_t::eb_opt_a, _ctx_t::eb_opt_b, _ctx_t::eb_r, fb_copy(), and fb_set_dig().
Referenced by eb_param_set().
void eb_curve_set_super (const fb_t a, const fb_t b, const fb_t c, const eb_t g, const bn_t n, const bn_t h)
Configures a new supersingular binary elliptic curve by its coefficients and generator.
Parameters
[in] a - the coefficient a of the curve.
[in] b - the coefficient b of the curve.
[in] c - the coefficient c of the curve.
[in] g - the generator.
[in] n - the order of the generator.
[in] h - the cofactor.
Definition at line 359 of file relic_eb_curve.c.
References bn_copy(), core_get(), detect_opt(), _ctx_t::eb_a, _ctx_t::eb_b, _ctx_t::eb_c, eb_curve_get_tab(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_is_kbltz, _ctx_t::eb_is_super, eb_mul_pre, eb_norm(), _ctx_t::eb_opt_a, _ctx_t::eb_opt_b, _ctx_t::eb_opt_c, _ctx_t::eb_r, and fb_copy().
Referenced by eb_param_set().
void eb_param_set (int param)
Configures a new binary elliptic curve by its parameter identifier.
Parameters
[in] param - the parameters identifier.
Definition at line 336 of file relic_eb_param.c.
References ASSIGN, ASSIGNS, bn_free, bn_new, bn_null, CATCH_ANY, core_get(), eb_curve_set_kbltz(), eb_curve_set_ordin(), eb_curve_set_super(), eb_free, _ctx_t::eb_id, eb_new, eb_null, EBACS_B251, ERR_CAUGHT, ERR_NO_VALID, ETAT_P271, ETAT_S1223, ETAT_S353, ETAT_T271, FB_BYTES, fb_free, fb_new, fb_null, fb_set_bit(), fb_zero(), FINALLY, HALVE_B257, NIST_163, NIST_233, NIST_283, NIST_409, NIST_571, NIST_B163, NIST_B233, NIST_B283, NIST_B409, NIST_B571, NIST_K163, NIST_K233, NIST_K283, NIST_K409, NIST_K571, PENTA_251, PENTA_271, SECG_239, SECG_K239, THROW, TRINO_1223, TRINO_257, TRINO_271, TRINO_353, and TRY.
Referenced by eb_param_set_any_kbltz(), eb_param_set_any_ordin(), and eb_param_set_any_super().
int eb_param_set_any (void)
Configures some set of curve parameters for the current security level.
Definition at line 519 of file relic_eb_param.c.
References eb_param_set_any_kbltz(), eb_param_set_any_ordin(), eb_param_set_any_super(), STS_ERR, and STS_OK.
int eb_param_set_any_ordin (void)
Configures some set of ordinary curve parameters for the current security level.
Returns
STS_OK if there is a curve at this security level, STS_ERR otherwise.
Definition at line 535 of file relic_eb_param.c.
References eb_param_set(), EBACS_B251, HALVE_B257, NIST_B163, NIST_B233, NIST_B283, NIST_B409, NIST_B571, STS_ERR, and STS_OK.
Referenced by eb_param_set_any().
int eb_param_set_any_kbltz (void)
Configures some set of Koblitz curve parameters for the current security level.
Returns
STS_OK if there is a curve at this security level, STS_ERR otherwise.
Definition at line 561 of file relic_eb_param.c.
References eb_param_set(), NIST_K163, NIST_K233, NIST_K283, NIST_K409, NIST_K571, SECG_K239, STS_ERR, and STS_OK.
Referenced by eb_param_set_any().
int eb_param_set_any_super (void)
Configures some set of supersingular curve parameters for the current security level.
Returns
STS_OK if there is a curve at this security level, STS_ERR otherwise.
Definition at line 585 of file relic_eb_param.c.
References eb_param_set(), ETAT_P271, ETAT_S1223, ETAT_S353, ETAT_T271, STS_ERR, and STS_OK.
Referenced by eb_param_set_any().
int eb_param_get (void)
Returns the parameter identifier of the currently configured binary elliptic curve.
Returns
the parameter identifier.
Definition at line 332 of file relic_eb_param.c.
References core_get(), and _ctx_t::eb_id.
void eb_param_print (void)
Prints the current configured binary elliptic curve.
Definition at line 607 of file relic_eb_param.c.
References core_get(), EBACS_B251, ETAT_P271, ETAT_S1223, ETAT_S353, ETAT_T271, HALVE_B257, NIST_B163, NIST_B233, NIST_B283, NIST_B409, NIST_B571, NIST_K163, NIST_K233, NIST_K283, NIST_K409, NIST_K571, SECG_K239, and util_banner.
int eb_param_level (void)
Returns the current security level.
Definition at line 663 of file relic_eb_param.c.
References core_get(), EBACS_B251, ETAT_P271, ETAT_S1223, ETAT_S353, ETAT_T271, HALVE_B257, NIST_B163, NIST_B233, NIST_B283, NIST_B409, NIST_B571, NIST_K163, NIST_K233, NIST_K283, NIST_K409, NIST_K571, and SECG_K239.
int eb_is_infty (const eb_t p)
Tests if a point on a binary elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 78 of file relic_eb_util.c.
References fb_is_zero().
Referenced by eb_add_basic(), eb_add_projc(), eb_dbl_basic(), eb_dbl_projc(), eb_frb_basic(), eb_frb_projc(), eb_is_valid(), eb_neg_basic(), eb_neg_projc(), eb_norm(), and eb_norm_sim().
void eb_set_infty (eb_t p)
Assigns a binary elliptic curve point to a point at the infinity.
Parameters
[out] p - the point to assign.
Definition at line 82 of file relic_eb_util.c.
References fb_zero().
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin(), eb_add_projc_ordin_mix(), eb_add_projc_super(), eb_add_projc_super_mix(), eb_dbl_basic(), eb_dbl_projc(), eb_frb_basic(), eb_frb_projc(), eb_mul_basic(), eb_mul_dig(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_kbltz(), eb_mul_fix_nafwi(), eb_mul_fix_ordin(), eb_mul_fix_yaowi(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_lodah(), eb_mul_ltnaf_imp(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_ordin(), eb_mul_sim_trick(), eb_neg_basic(), eb_neg_projc(), eb_norm(), eb_sub_basic(), eb_sub_projc(), and eb_tab().
void eb_copy (eb_t r, const eb_t p)
Copies the second argument to the first argument.
Parameters
[out] r - the result.
[in] p - the binary elliptic curve point to copy.
Definition at line 89 of file relic_eb_util.c.
References fb_copy().
Referenced by eb_add_basic(), eb_add_projc(), eb_curve_get_gen(), eb_mul_basic(), eb_mul_dig(), eb_mul_fix_combs(), eb_mul_frb(), eb_mul_halve(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_pre_nafwi(), eb_mul_pre_yaowi(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_norm(), and eb_tab().
int eb_cmp (const eb_t p, const eb_t q)
Compares two binary elliptic curve points.
Parameters
[in] p - the first binary elliptic curve point.
[in] q - the second binary elliptic curve point.
Returns
CMP_EQ if p == q and CMP_NE if p != q.
Definition at line 96 of file relic_eb_util.c.
References CMP_EQ, CMP_NE, and fb_cmp().
void eb_rand (eb_t p)
Assigns a random value to a binary elliptic curve point.
Parameters
[out] p - the binary elliptic curve point to assign.
Definition at line 112 of file relic_eb_util.c.
References bn_bits(), bn_free, bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, eb_curve_get_ord(), eb_mul_gen(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_rhs (fb_t rhs, const eb_t p)
Computes the right-hand side of the elliptic curve equation at a certain elliptic curve point.
Parameters
[out] rhs - the result.
[in] p - the point.
Definition at line 136 of file relic_eb_util.c.
References CATCH_ANY, eb_curve_get_a(), eb_curve_get_b(), eb_curve_is_super(), eb_curve_opt_a(), eb_curve_opt_b(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_free, fb_mul, fb_mul_dig(), fb_new, fb_null, fb_sqr, FINALLY, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by eb_is_valid(), eb_map(), and eb_upk().
int eb_is_valid (const eb_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 212 of file relic_eb_util.c.
References CATCH_ANY, CMP_EQ, eb_curve_get_c(), eb_curve_is_super(), eb_free, eb_is_infty(), eb_new, eb_norm(), eb_null, eb_rhs(), ERR_CAUGHT, fb_add(), fb_cmp(), fb_free, fb_mul, fb_new, fb_null, fb_sqr, FINALLY, THROW, and TRY.
void eb_tab (eb_t * t, const eb_t p, int w)
Builds a precomputation table for multiplying a random binary elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 246 of file relic_eb_util.c.
References bn_add(), bn_add_dig(), bn_copy(), bn_hlv(), bn_is_zero(), bn_neg(), BN_NEG, bn_new, bn_set_dig(), bn_sign(), bn_sub(), bn_sub_dig(), eb_add, eb_copy(), eb_curve_get_s0(), eb_curve_get_s1(), eb_curve_get_vm(), eb_curve_is_kbltz(), eb_curve_opt_a(), eb_dbl, eb_frb, eb_mul_frb(), eb_neg, eb_norm(), eb_norm_sim(), eb_set_infty(), eb_sub, fb_set_dig(), MASK, and OPT_ZERO.
Referenced by eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), eb_mul_pre_lwnaf(), eb_mul_sim_kbltz(), and eb_mul_sim_ordin().
void eb_print (const eb_t p)
Prints a binary elliptic curve point.
Parameters
[in] p - the binary elliptic curve point to print.
Definition at line 1025 of file relic_eb_util.c.
References fb_print().
void eb_neg_basic (eb_t r, const eb_t p)
Negates a binary elliptic curve point represented by affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 43 of file relic_eb_neg.c.
References eb_curve_get_c(), eb_curve_is_super(), eb_curve_opt_c(), eb_is_infty(), eb_set_infty(), fb_add(), fb_add_dig(), fb_copy(), OPT_DIGIT, OPT_ONE, and OPT_ZERO.
Referenced by eb_sub_basic().
void eb_neg_projc (eb_t r, const eb_t p)
Negates a binary elliptic curve point represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 84 of file relic_eb_neg.c.
References CATCH_ANY, eb_curve_get_c(), eb_curve_is_super(), eb_curve_opt_c(), eb_is_infty(), eb_set_infty(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_free, fb_mul, fb_new, fb_null, FINALLY, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by eb_sub_projc().
void eb_add_basic (eb_t r, const eb_t p, const eb_t q)
Adds two binary elliptic curve points represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 730 of file relic_eb_add.c.
References eb_add_basic_ordin(), eb_add_basic_super(), eb_copy(), eb_curve_is_super(), and eb_is_infty().
Referenced by eb_sub_basic().
void eb_add_projc (eb_t r, const eb_t p, const eb_t q)
Adds two binary elliptic curve points represented in projective coordinates. Computes R = P + Q.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 782 of file relic_eb_add.c.
References eb_add_projc_ordin(), eb_add_projc_super(), eb_copy(), eb_curve_is_super(), and eb_is_infty().
Referenced by eb_sub_projc().
void eb_sub_basic (eb_t r, const eb_t p, const eb_t q)
Subtracts a binary elliptic curve point from another, both points represented by affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 752 of file relic_eb_add.c.
References CATCH_ANY, eb_add_basic(), eb_free, eb_neg_basic(), eb_new, eb_null, eb_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_sub_projc (eb_t r, const eb_t p, const eb_t q)
Subtracts a binary elliptic curve point from another, both points represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 804 of file relic_eb_add.c.
References CATCH_ANY, eb_add_projc(), eb_free, eb_neg_projc(), eb_new, eb_null, eb_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_dbl_basic (eb_t r, const eb_t p)
Doubles a binary elliptic curve point represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 335 of file relic_eb_dbl.c.
References eb_curve_is_super(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_is_infty(), and eb_set_infty().
Referenced by eb_add_basic_ordin(), and eb_add_basic_super().
void eb_dbl_projc (eb_t r, const eb_t p)
Doubles a binary elliptic curve point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 356 of file relic_eb_dbl.c.
References eb_curve_is_super(), eb_dbl_projc_ordin(), eb_dbl_projc_super(), eb_is_infty(), and eb_set_infty().
Referenced by eb_add_projc_ordin(), eb_add_projc_ordin_mix(), eb_add_projc_super(), and eb_add_projc_super_mix().
void eb_hlv (eb_t r, const eb_t p)
Halves a point represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to halve.
Definition at line 41 of file relic_eb_hlv.c.
References CATCH_ANY, eb_curve_get_a(), eb_curve_opt_a(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_free, fb_mul, fb_new, fb_null, fb_set_dig(), fb_slv, fb_srt, fb_trc, FINALLY, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by eb_mul_halve().
void eb_frb_basic (eb_t r, const eb_t p)
Computes the Frobenius map of a binary elliptic curve point represented by affine coordinates.
Parameters
[out] r - the result.
[in] p - the point.
Definition at line 45 of file relic_eb_frb.c.
References eb_is_infty(), eb_set_infty(), fb_set_bit(), fb_sqr, and fb_zero().
void eb_frb_projc (eb_t r, const eb_t p)
Computes the Frobenius map of a binary elliptic curve point represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the point.
Definition at line 63 of file relic_eb_frb.c.
References eb_is_infty(), eb_set_infty(), fb_set_dig(), and fb_sqr.
void eb_mul_basic (eb_t r, const eb_t p, const bn_t k)
Multiplies a binary elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 637 of file relic_eb_mul.c.
References bn_bits(), bn_is_zero(), bn_test_bit(), CATCH_ANY, eb_add, eb_copy(), eb_dbl, eb_free, eb_new, eb_norm(), eb_null, eb_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_lodah (eb_t r, const eb_t p, const bn_t k)
Multiplies a binary elliptic point by an integer using the constant-time Lpez-Dahab point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 677 of file relic_eb_mul.c.
References bn_bits(), bn_test_bit(), CATCH_ANY, dv_free, dv_new, dv_null, dv_zero(), eb_curve_get_b(), eb_curve_is_super(), eb_curve_opt_b(), eb_set_infty(), ERR_CAUGHT, ERR_NO_VALID, fb_add(), fb_add_dig(), fb_addd_low(), fb_addn_low(), fb_copy(), FB_DIGS, fb_inv, fb_is_zero(), fb_mul, fb_mul1_low(), fb_muln_low(), fb_rdcn_low(), fb_set_bit(), fb_sqr, fb_sqrl_low(), fb_zero(), FINALLY, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
void eb_mul_lwnaf (eb_t r, const eb_t p, const bn_t k)
Multiplies a binary elliptic point by an integer using the left-to-right w-NAF method. If the binary curve is a Koblitz curve, w-TNAF is used.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 874 of file relic_eb_mul.c.
References eb_curve_is_kbltz(), eb_mul_lnaf_imp(), and eb_mul_ltnaf_imp().
void eb_mul_rwnaf (eb_t r, const eb_t p, const bn_t k)
Multiplies a binary elliptic point by an integer using the right-to-left w-NAF method. If the binary curve is a Koblitz curve, w-TNAF is used.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 891 of file relic_eb_mul.c.
References eb_curve_is_kbltz(), eb_curve_is_super(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), ERR_NO_CONFIG, and THROW.
void eb_mul_halve (eb_t r, const eb_t p, const bn_t k)
Multiplies a binary elliptic point by an integer using the halving method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 921 of file relic_eb_mul.c.
References bn_bits(), bn_cmp_dig(), bn_free, bn_lsh(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), bn_rec_naf(), CATCH_ANY, CMP_GT, eb_add, eb_copy(), eb_curve_get_a(), eb_curve_get_b(), eb_curve_get_cof(), eb_curve_get_ord(), eb_dbl, eb_free, eb_hlv(), eb_new, eb_norm(), eb_null, eb_set_infty(), eb_sub, EB_WIDTH, ERR_CAUGHT, fb_add(), FB_BITS, fb_copy(), fb_free, fb_mul, fb_new, fb_null, fb_set_dig(), fb_slv, fb_srt, fb_trc, fb_zero(), FINALLY, THROW, and TRY.
void eb_mul_gen (eb_t r, const bn_t k)
Multiplies the generator of a binary elliptic curve by an integer.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 1096 of file relic_eb_mul.c.
References CATCH_ANY, eb_curve_get_gen(), eb_curve_get_tab(), eb_free, eb_mul, eb_mul_fix, eb_new, eb_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by eb_rand().
void eb_mul_dig (eb_t r, const eb_t p, const dig_t k)
Multiplies a binary elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 1118 of file relic_eb_mul.c.
References CATCH_ANY, eb_add, eb_copy(), eb_dbl, eb_free, eb_new, eb_norm(), eb_null, eb_set_infty(), ERR_CAUGHT, FINALLY, THROW, TRY, and util_bits_dig().
Referenced by eb_map(), and eb_mul_rnaf_imp().
void eb_mul_pre_basic (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 155 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, eb_copy(), eb_curve_get_ord(), eb_dbl, eb_norm_sim(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_pre_yaowi (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 199 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, eb_copy(), eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm_sim(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_pre_nafwi (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 271 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, eb_copy(), eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm_sim(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_pre_combs (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 363 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, eb_add, eb_copy(), eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm(), eb_norm_sim(), eb_set_infty(), EB_TABLE_COMBS, ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_pre_combd (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 458 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, eb_add, eb_copy(), eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm_sim(), eb_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_pre_lwnaf (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 560 of file relic_eb_mul_fix.c.
References eb_curve_is_kbltz(), EB_DEPTH, and eb_tab().
void eb_mul_fix_basic (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 180 of file relic_eb_mul_fix.c.
References bn_bits(), bn_test_bit(), eb_add, eb_norm(), and eb_set_infty().
void eb_mul_fix_yaowi (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 228 of file relic_eb_mul_fix.c.
References bn_is_zero(), bn_rec_win(), CATCH_ANY, CEIL, eb_add, EB_DEPTH, eb_free, eb_new, eb_norm(), eb_null, eb_set_infty(), EP_DEPTH, ERR_CAUGHT, FB_BITS, FINALLY, THROW, and TRY.
void eb_mul_fix_nafwi (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 302 of file relic_eb_mul_fix.c.
References bn_rec_naf(), CATCH_ANY, eb_add, EB_DEPTH, eb_free, eb_new, eb_norm(), eb_null, eb_set_infty(), eb_sub, ERR_CAUGHT, FB_BITS, FINALLY, THROW, and TRY.
void eb_mul_fix_combs (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 402 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_test_bit(), CATCH_ANY, eb_add, eb_copy(), eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_fix_combd (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 503 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_test_bit(), CATCH_ANY, eb_add, eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm(), eb_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_fix_lwnaf (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 573 of file relic_eb_mul_fix.c.
References eb_curve_is_kbltz(), eb_mul_fix_kbltz(), and eb_mul_fix_ordin().
void eb_mul_sim_basic (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 288 of file relic_eb_mul_sim.c.
References CATCH_ANY, eb_add, eb_free, eb_mul, eb_new, eb_norm(), eb_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_sim_trick (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 313 of file relic_eb_mul_sim.c.
References bn_free, bn_new, bn_null, bn_rec_win(), CATCH_ANY, CEIL, eb_add, eb_curve_get_ord(), eb_dbl, eb_free, eb_new, eb_norm(), eb_norm_sim(), eb_null, eb_set_infty(), EB_WIDTH, ERR_CAUGHT, FB_BITS, FINALLY, MAX, THROW, and TRY.
void eb_mul_sim_inter (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 401 of file relic_eb_mul_sim.c.
References eb_curve_is_kbltz(), eb_mul_sim_kbltz(), and eb_mul_sim_ordin().
void eb_mul_sim_joint (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 419 of file relic_eb_mul_sim.c.
References bn_bits(), bn_rec_jsf(), CATCH_ANY, eb_add, eb_copy(), eb_dbl, eb_free, eb_new, eb_norm(), eb_norm_sim(), eb_null, eb_set_infty(), eb_sub, ERR_CAUGHT, FB_BITS, FINALLY, MAX, THROW, and TRY.
void eb_mul_sim_gen (eb_t r, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds the generator and a binary elliptic curve point simultaneously. Computes R = kG + mQ.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
Definition at line 484 of file relic_eb_mul_sim.c.
References CATCH_ANY, eb_curve_get_gen(), eb_curve_get_tab(), eb_curve_is_kbltz(), eb_free, eb_mul_sim, eb_mul_sim_kbltz(), eb_mul_sim_ordin(), eb_new, eb_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_norm (eb_t r, const eb_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 114 of file relic_eb_norm.c.
References eb_copy(), eb_curve_is_super(), eb_is_infty(), eb_norm_halve(), eb_norm_ordin(), eb_norm_super(), and eb_set_infty().
Referenced by eb_curve_set_kbltz(), eb_curve_set_ordin(), eb_curve_set_super(), eb_is_valid(), eb_mul_basic(), eb_mul_dig(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_nafwi(), eb_mul_fix_ordin(), eb_mul_fix_yaowi(), eb_mul_frb(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), eb_mul_pre_combs(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_basic(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_ordin(), eb_mul_sim_trick(), eb_norm_sim(), and eb_tab().
void eb_norm_sim (eb_t * r, const eb_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 147 of file relic_eb_norm.c.
References CATCH_ANY, eb_curve_is_super(), eb_is_infty(), eb_norm(), eb_norm_ordin(), eb_norm_super(), ERR_CAUGHT, fb_copy(), fb_free, fb_inv_sim(), fb_new, fb_null, fb_set_dig(), FINALLY, THROW, and TRY.
Referenced by eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_pre_nafwi(), eb_mul_pre_yaowi(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_trick(), and eb_tab().
void eb_map (eb_t p, const unsigned char * msg, int len)
Maps a byte array to a point in a binary elliptic curve.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 42 of file relic_eb_map.c.
References bn_add_dig(), bn_bits(), BN_DIGIT, bn_free, bn_mod_2b(), bn_new, bn_null, bn_read_bin(), CATCH_ANY, dv_copy(), eb_curve_get_c(), eb_curve_get_cof(), eb_curve_is_super(), eb_curve_opt_c(), eb_mul, eb_mul_dig(), eb_rhs(), ERR_CAUGHT, FB_BITS, FB_BYTES, FB_DIGS, fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_set_dig(), fb_slv, fb_sqr, fb_trc, FINALLY, MD_LEN, md_map, MIN, OPT_ONE, THROW, and TRY.
void eb_pck (eb_t r, const eb_t p)
Compresses a point.
Parameters
[out] r - the result.
[in] p - the point to compress.
Definition at line 41 of file relic_eb_pck.c.
References eb_curve_get_c(), eb_curve_is_super(), fb_copy(), fb_get_bit(), fb_inv, fb_mul, and fb_set_dig().
int eb_upk (eb_t r, const eb_t p)
Decompresses a point.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful
Definition at line 67 of file relic_eb_pck.c.
References CATCH_ANY, eb_curve_get_c(), eb_curve_is_super(), eb_rhs(), ERR_CAUGHT, fb_add_dig(), fb_copy(), fb_free, fb_get_bit(), fb_inv, fb_mul, fb_new, fb_null, fb_set_dig(), fb_slv, fb_sqr, fb_trc, FINALLY, THROW, and TRY.