RELIC: include/low/relic_fp_low.h File Reference
relic_fp_low.h File Reference
Prime field arithmetic.
Functions
dig_t fp_add1_low (dig_t *c, const dig_t *a, dig_t digit)
dig_t fp_addn_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_addm_low (dig_t *c, const dig_t *a, const dig_t *b)
dig_t fp_addd_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_addc_low (dig_t *c, const dig_t *a, const dig_t *b)
dig_t fp_sub1_low (dig_t *c, const dig_t *a, dig_t digit)
dig_t fp_subn_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_subm_low (dig_t *c, const dig_t *a, const dig_t *b)
dig_t fp_subd_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_subc_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_negm_low (dig_t *c, const dig_t *a)
dig_t fp_dbln_low (dig_t *c, const dig_t *a)
void fp_dblm_low (dig_t *c, const dig_t *a)
void fp_hlvm_low (dig_t *c, const dig_t *a)
void fp_hlvd_low (dig_t *c, const dig_t *a)
int fp_cmp1_low (dig_t a, dig_t b)
int fp_cmpn_low (const dig_t *a, const dig_t *b)
dig_t fp_lsh1_low (dig_t *c, const dig_t *a)
dig_t fp_lshb_low (dig_t *c, const dig_t *a, int bits)
void fp_lshd_low (dig_t *c, const dig_t *a, int digits)
dig_t fp_rsh1_low (dig_t *c, const dig_t *a)
dig_t fp_rshb_low (dig_t *c, const dig_t *a, int bits)
void fp_rshd_low (dig_t *c, const dig_t *a, int digits)
dig_t fp_mula_low (dig_t *c, const dig_t *a, dig_t digit)
dig_t fp_mul1_low (dig_t *c, const dig_t *a, dig_t digit)
void fp_muln_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_mulm_low (dig_t *c, const dig_t *a, const dig_t *b)
void fp_sqrn_low (dig_t *c, const dig_t *a)
void fp_sqrm_low (dig_t *c, const dig_t *a)
void fp_rdcs_low (dig_t *c, const dig_t *a, const dig_t *m)
void fp_rdcn_low (dig_t *c, dig_t *a)
void fp_invn_low (dig_t *c, const dig_t *a)
Detailed Description
Interface of the low-level prime field arithmetic module.
Version
Id:
relic_fp_low.h 1535 2013-08-28 04:01:10Z dfaranha
Definition in file relic_fp_low.h.
Function Documentation
dig_t fp_add1_low (dig_t * c, const dig_t * a, dig_t digit)
Adds a digit vector and a digit. Computes c = a + digit.
Parameters
[out] c - the result.
[in] a - the digit vector to add.
[in] digit - the digit to add.
Returns
the carry of the last digit addition.
Referenced by fp_add_dig().
dig_t fp_addn_low (dig_t * c, const dig_t * a, const dig_t * b)
Adds to digit vectors of the same size. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Returns
the carry of the last digit addition.
Referenced by fp_add_basic(), fp_hlv_basic(), fp_sub_basic(), and fp_sub_dig().
void fp_addm_low (dig_t * c, const dig_t * a, const dig_t * b)
Adds to digit vectors of the same size with integrated modular reduction. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Referenced by fp_add_integ().
dig_t fp_addd_low (dig_t * c, const dig_t * a, const dig_t * b)
Adds to double-length digit vectors. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Returns
the carry of the last digit addition.
Referenced by fp3_mul_basic(), and fp3_sqr_basic().
void fp_addc_low (dig_t * c, const dig_t * a, const dig_t * b)
Adds to double-length digit vectors and reduces modulo p * R. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Referenced by fp2_mul_basic(), fp3_mul_basic(), and fp3_sqr_basic().
dig_t fp_sub1_low (dig_t * c, const dig_t * a, dig_t digit)
Subtracts a digit from a digit vector. Computes c = a - digit.
Parameters
[out] c - the result.
[in] a - the digit vector.
[in] digit - the digit to subtract.
Returns
the carry of the last digit subtraction.
Referenced by fp_sub_dig().
dig_t fp_subn_low (dig_t * c, const dig_t * a, const dig_t * b)
Subtracts a digit vector from another digit vector. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the digit vector.
[in] b - the digit vector to subtract.
Returns
the carry of the last digit subtraction.
Referenced by fp_add_basic(), fp_add_dig(), fp_dbl_basic(), fp_inv_monty(), fp_neg_basic(), fp_rand(), fp_rdc_monty_basic(), and fp_sub_basic().
void fp_subm_low (dig_t * c, const dig_t * a, const dig_t * b)
Subtracts to digit vectors of the same size with integrated modular reduction. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Referenced by fp_sub_integ().
dig_t fp_subd_low (dig_t * c, const dig_t * a, const dig_t * b)
Subtracts a double-length digit vector from another digit vector. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Returns
the carry of the last digit subtraction.
void fp_subc_low (dig_t * c, const dig_t * a, const dig_t * b)
Subtracts a double-length digit vector from another digit vector. Computes c = a - b. This version of the function should handle possible carries by adding p * R.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Referenced by fp2_mul_basic(), fp3_mul_basic(), fp3_sqr_basic(), and fp6_mul_dxs_unr().
void fp_negm_low (dig_t * c, const dig_t * a)
Negates a digit vector. Computes c = -a.
Parameters
[out] c - the result.
[out] a - the prime field element to negate.
Referenced by fp_neg_integ().
dig_t fp_dbln_low (dig_t * c, const dig_t * a)
Doubles a digit vector. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the digit vector.
Returns
the carry of the last digit doubling.
void fp_dblm_low (dig_t * c, const dig_t * a)
Doubles a digit vector with integrated modular reduction. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
Referenced by fp_dbl_integ().
void fp_hlvm_low (dig_t * c, const dig_t * a)
Halves a digit vector with integrated modular reduction. Computes c = a/2.
Parameters
[out] c - the result.
[in] a - the digit vector to halve.
Referenced by fp_hlv_integ().
void fp_hlvd_low (dig_t * c, const dig_t * a)
Halves a double-precision digit vector. Computes c = a/2.
Parameters
[out] c - the result.
[in] a - the digit vector to halve.
Referenced by fp18_sqr_lazyr(), fp3_sqr_basic(), and fp6_sqr_unr().
int fp_cmp1_low (dig_t a, dig_t b)
Compares two digits.
Parameters
[in] a - the first digit to compare.
[in] b - the second digit to compare.
Returns
CMP_LT if a < b, CMP_EQ if a == b and CMP_GT if a > b.
Referenced by fp_cmp_dig().
int fp_cmpn_low (const dig_t * a, const dig_t * b)
Compares two digit vectors of the same size.
Parameters
[in] a - the first digit vector to compare.
[in] b - the second digit vector to compare.
Returns
CMP_LT if a < b, CMP_EQ if a == b and CMP_GT if a > b.
Referenced by fp_add_basic(), fp_add_dig(), fp_cmp(), fp_dbl_basic(), fp_inv_monty(), fp_rand(), and fp_rdc_monty_basic().
dig_t fp_lsh1_low (dig_t * c, const dig_t * a)
Shifts a digit vector to the left by 1 bits. Computes c = a << 1.
Parameters
[out] c - the result.
[in] a - the digit vector to shift.
Returns
the carry of the last digit shift.
Referenced by fp_dbl_basic(), and fp_lsh().
dig_t fp_lshb_low (dig_t * c, const dig_t * a, int bits)
Shifts a digit vector to the left by an amount smaller than a digit. Computes c = a << bits.
Parameters
[out] c - the result.
[in] a - the digit vector to shift.
[in] bits - the shift amount.
Returns
the carry of the last digit shift.
Referenced by fp_lsh().
void fp_lshd_low (dig_t * c, const dig_t * a, int digits)
Shifts a digit vector to the left by some digits. Computes c = a << (digits * DIGIT).
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] digits - the shift ammount.
Referenced by fp_lsh().
dig_t fp_rsh1_low (dig_t * c, const dig_t * a)
Shifts a digit vector to the right by 1 bit. Computes c = a >> 1.
Parameters
[out] c - the result.
[in] a - the digit vector to shift.
Returns
the carry of the last digit shift.
Referenced by fp_hlv_basic(), fp_inv_binar(), fp_inv_monty(), and fp_rsh().
dig_t fp_rshb_low (dig_t * c, const dig_t * a, int bits)
Shifts a digit vector to the right by an amount smaller than a digit. Computes c = a >> bits.
Parameters
[out] c - the result.
[in] a - the digit vector to shift.
[in] bits - the shift amount.
Returns
the carry of the last digit shift.
Referenced by fp_rsh().
void fp_rshd_low (dig_t * c, const dig_t * a, int digits)
Shifts a digit vector to the right by some digits. Computes c = a >> (digits * DIGIT).
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] digits - the shift amount.
Referenced by fp_rsh().
dig_t fp_mula_low (dig_t * c, const dig_t * a, dig_t digit)
Multiplies a digit vector by a digit and adds this result to another digit vector. Computes c = c + a * digit.
Parameters
[out] c - the result.
[in] a - the digit vector to multiply.
[in] digit - the digit to multiply.
Returns
the carry of the addition.
Referenced by fp_mul_basic(), and fp_rdc_monty_basic().
dig_t fp_mul1_low (dig_t * c, const dig_t * a, dig_t digit)
Multiplies a digit vector by a digit and stores this result in another digit vector. Computes c = a * digit.
Parameters
[out] c - the result.
[in] a - the digit vector to multiply.
[in] digit - the digit to multiply.
Returns
the most significant digit.
Referenced by fp_prime_conv_dig().
void fp_muln_low (dig_t * c, const dig_t * a, const dig_t * b)
Multiplies two digit vectors of the same size. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the first digit vector to multiply.
[in] b - the second digit vector to multiply.
Referenced by fp12_mul_dxs_lazyr(), fp2_mul_basic(), fp3_mul_basic(), fp3_sqr_basic(), and fp_mul_comba().
void fp_mulm_low (dig_t * c, const dig_t * a, const dig_t * b)
Multiplies two digit vectors of the same size with embedded modular reduction. Computes c = (a * b) mod p.
Parameters
[out] c - the result.
[in] a - the first digit vector to multiply.
[in] b - the second digit vector to multiply.
Referenced by fp_mul_integ().
void fp_sqrn_low (dig_t * c, const dig_t * a)
Squares a digit vector. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the digit vector to square.
Referenced by fp3_sqr_basic(), and fp_sqr_comba().
void fp_sqrm_low (dig_t * c, const dig_t * a)
Squares a digit vector with embedded modular reduction.
Parameters
[out] c - the result.
[in] a - the digit vector to square.
Referenced by fp_sqr_integ().
void fp_rdcs_low (dig_t * c, const dig_t * a, const dig_t * m)
Reduces a digit vector modulo m represented in special form. Computes c = a mod m.
Parameters
[out] c - the result.
[in] a - the digit vector to reduce.
[in] m - the modulus.
Referenced by fp_rdc_quick().
void fp_rdcn_low (dig_t * c, dig_t * a)
Reduces a digit vector modulo the configured prime p. Computes c = a mod p.
Parameters
[out] c - the result.
[in] a - the digit vector to reduce.
Referenced by fp_rdc_monty_comba().
void fp_invn_low (dig_t * c, const dig_t * a)
Inverts a digit vector modulo the configured prime.
Parameters
[out] c - the result.
[in] a - the digit vector to invert.
Referenced by fp_inv_lower().