RELIC: src/cp/relic_cp_ecmqv.c File Reference
relic_cp_ecmqv.c File Reference
Cryptographic protocols.
#include "relic.h"
#include "relic_test.h"
#include "relic_bench.h"
Functions
void cp_ecmqv_gen (bn_t d, ec_t q)
void cp_ecmqv_key (unsigned char *key, int key_len, bn_t d1, bn_t d2, ec_t q2u, ec_t q1v, ec_t q2v)
Detailed Description
Implementation of the ECMQV protocol.
Version
Id:
relic_cp_ecmqv.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_cp_ecmqv.c.
Function Documentation
void cp_ecmqv_gen (bn_t d, ec_t q)
Generate an ECMQV key pair.
Should also be used to generate the ephemeral key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Definition at line 40 of file relic_cp_ecmqv.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ec_curve_get_ord, ec_mul_gen, ERR_CAUGHT, FINALLY, THROW, and TRY.
void cp_ecmqv_key (unsigned char * key, int key_len, bn_t d1, bn_t d2, ec_t q2u, ec_t q1v, ec_t q2v)
Derives a shared secret using ECMQV.
Parameters
[out] key - the shared key.
int] key_len - the intended shared key length in bytes.
[in] d1 - the private key.
[in] d2 - the ephemeral private key.
[in] q2u - the ephemeral public key.
[in] q1v - the point received from the other party.
[in] q2v - the ephemeral point received from the other party.
Definition at line 65 of file relic_cp_ecmqv.c.
References bn_add(), bn_bits(), bn_free, bn_mod, bn_mod_2b(), bn_mul, bn_new, bn_null, bn_set_bit(), bn_size_bin(), bn_write_bin(), CATCH_ANY, EC_BYTES, ec_curve_get_ord, ec_free, ec_get_x, ec_mul_sim, ec_new, ec_null, ERR_CAUGHT, FINALLY, md_kdf2(), THROW, and TRY.