RELIC: include/relic_fb.h File Reference
relic_fb.h File Reference
Binary field arithmetic.
#include "relic_bn.h"
#include "relic_dv.h"
#include "relic_conf.h"
#include "relic_types.h"
#include "relic_label.h"
Macros
#define FB_BITS ((int)FB_POLYN)
#define FB_DIGIT ((int)DIGIT)
#define FB_DIG_LOG ((int)DIGIT_LOG)
#define FB_DIGS ((int)((FB_BITS)/(FB_DIGIT) + (FB_BITS % FB_DIGIT > 0)))
#define FB_BYTES ((int)((FB_BITS)/8 + (FB_BITS % 8 > 0)))
#define FB_TABLE_BASIC (1)
#define FB_TABLE_QUICK ((FB_DIGIT / 4) * FB_DIGS * 16)
#define FB_TABLE FB_TABLE_QUICK
#define FB_TABLE_MAX FB_TABLE_QUICK
#define fb_null(A) /* empty */
#define fb_new(A) /* empty */
#define fb_free(A) /* empty */
#define fb_mul(C, A, B) fb_mul_lodah(C, A, B)
#define fb_sqr(C, A) fb_sqr_table(C, A)
#define fb_srt(C, A) fb_srt_quick(C, A)
#define fb_rdc(C, A) fb_rdc_quick(C, A)
#define fb_trc(A) fb_trc_quick(A)
#define fb_slv(C, A) fb_slv_quick(C, A)
#define fb_inv(C, A) fb_inv_exgcd(C, A)
#define fb_exp(C, A, B) fb_exp_slide(C, A, B)
#define fb_itr_pre(T, B) fb_itr_pre_quick(T, B)
#define fb_itr(C, A,...) CAT(fb_itr, OPT(__VA_ARGS__))(C, A, __VA_ARGS__)
#define fb_itr_imp(C, A, B, T) fb_itr_quick(C, A, T)
Typedefs
typedef align dig_t fb_t [FB_DIGS+PADDING(FB_BYTES)/(FB_DIGIT/8)]
typedef align dig_t fb_st [FB_DIGS+PADDING(FB_BYTES)/(FB_DIGIT/8)]
Enumerations
enum {
PENTA_64 = 1, TRINO_113, TRINO_127, PENTA_128,
PENTA_131, NIST_163, SQRT_163, TRINO_193,
NIST_233, SQRT_233, SECG_239, SQRT_239,
SQRT_251, PENTA_251, TRINO_257, TRINO_271,
PENTA_271, NIST_283, SQRT_283, TRINO_353,
TRINO_367, NIST_409, TRINO_439, NIST_571,
SQRT_571, TRINO_1223
}
Functions
void fb_poly_init (void)
void fb_poly_clean (void)
dig_t * fb_poly_get (void)
void fb_poly_set_dense (const fb_t f)
void fb_poly_set_trino (int a)
void fb_poly_set_penta (int a, int b, int c)
dig_t * fb_poly_get_srz (void)
const dig_t * fb_poly_tab_srz (int i)
const fb_t * fb_poly_tab_sqr (int i)
const int * fb_poly_get_chain (int *len)
void fb_poly_get_rdc (int *a, int *b, int *c)
void fb_poly_get_trc (int *a, int *b, int *c)
const dig_t * fb_poly_get_slv (void)
void fb_param_set (int param)
void fb_param_set_any (void)
void fb_param_print (void)
void fb_poly_add (fb_t c, const fb_t a)
void fb_poly_sub (fb_t c, const fb_t a)
void fb_copy (fb_t c, const fb_t a)
void fb_neg (fb_t c, const fb_t a)
void fb_zero (fb_t a)
int fb_is_zero (const fb_t a)
int fb_test_bit (const fb_t a, int bit)
int fb_get_bit (const fb_t a, int bit)
void fb_set_bit (fb_t a, int bit, int value)
void fb_set_dig (fb_t c, dig_t a)
int fb_bits (const fb_t a)
void fb_rand (fb_t a)
void fb_print (const fb_t a)
void fb_size (int *size, const fb_t a, int radix)
void fb_read (fb_t a, const char *str, int len, int radix)
void fb_write (char *str, int len, const fb_t a, int radix)
int fb_cmp (const fb_t a, const fb_t b)
int fb_cmp_dig (const fb_t a, dig_t b)
void fb_add (fb_t c, const fb_t a, const fb_t b)
void fb_add_dig (fb_t c, const fb_t a, dig_t b)
void fb_sub (fb_t c, const fb_t a, const fb_t b)
void fb_sub_dig (fb_t c, const fb_t a, dig_t b)
void fb_mul_basic (fb_t c, const fb_t a, const fb_t b)
void fb_mul_integ (fb_t c, const fb_t a, const fb_t b)
void fb_mul_lcomb (fb_t c, const fb_t a, const fb_t b)
void fb_mul_rcomb (fb_t c, const fb_t a, const fb_t b)
void fb_mul_lodah (fb_t c, const fb_t a, const fb_t b)
void fb_mul_dig (fb_t c, const fb_t a, dig_t b)
void fb_mul_karat (fb_t c, const fb_t a, const fb_t b)
void fb_sqr_basic (fb_t c, const fb_t a)
void fb_sqr_integ (fb_t c, const fb_t a)
void fb_sqr_table (fb_t c, const fb_t a)
void fb_lsh (fb_t c, const fb_t a, int bits)
void fb_rsh (fb_t c, const fb_t a, int bits)
void fb_rdc_basic (fb_t c, dv_t a)
void fb_rdc_quick (fb_t c, dv_t a)
void fb_srt_basic (fb_t c, const fb_t a)
void fb_srt_quick (fb_t c, const fb_t a)
dig_t fb_trc_basic (const fb_t a)
dig_t fb_trc_quick (const fb_t a)
void fb_inv_basic (fb_t c, const fb_t a)
void fb_inv_binar (fb_t c, const fb_t a)
void fb_inv_exgcd (fb_t c, const fb_t a)
void fb_inv_almos (fb_t c, const fb_t a)
void fb_inv_itoht (fb_t c, const fb_t a)
void fb_inv_bruch (fb_t c, const fb_t a)
void fb_inv_lower (fb_t c, const fb_t a)
void fb_inv_sim (fb_t *c, const fb_t *a, int n)
void fb_exp_2b (fb_t c, const fb_t a, int b)
void fb_exp_basic (fb_t c, const fb_t a, const bn_t b)
void fb_exp_slide (fb_t c, const fb_t a, const bn_t b)
void fb_exp_monty (fb_t c, const fb_t a, const bn_t b)
void fb_slv_basic (fb_t c, const fb_t a)
void fb_slv_quick (fb_t c, const fb_t a)
void fb_itr_basic (fb_t c, const fb_t a, int b)
void fb_itr_pre_quick (fb_t *t, int b)
void fb_itr_quick (fb_t c, const fb_t a, const fb_t *t)
Detailed Description
Interface of module for binary field arithmetic.
Version
Id:
relic_fb.h 1572 2013-09-02 07:11:29Z dfaranha
Definition in file relic_fb.h.
Macro Definition Documentation
#define FB_BITS ((int)FB_POLYN)
Precision in bits of a binary field element.
Definition at line 52 of file relic_fb.h.
Referenced by compute_kbltz(), conf_print(), eb_map(), eb_mul_fix_kbltz(), eb_mul_fix_nafwi(), eb_mul_fix_ordin(), eb_mul_fix_yaowi(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_ordin(), eb_mul_sim_trick(), etat_exp(), fb4_frb(), fb_exp_slide(), fb_inv_almos(), fb_inv_basic(), fb_inv_binar(), fb_inv_bruch(), fb_inv_exgcd(), fb_inv_itoht(), fb_mul_basic(), fb_param_print(), fb_poly_set_penta(), fb_poly_set_trino(), fb_rand(), fb_rdc_basic(), fb_slv_basic(), fb_srt_basic(), fb_trc_basic(), find_chain(), find_solve(), find_srz(), find_trace(), pb_map_etatn_imp(), pb_map_etats_imp(), pb_map_get_par(), and pb_map_init().
#define FB_DIGIT ((int)DIGIT)
Size in bits of a digit.
Definition at line 57 of file relic_fb.h.
Referenced by detect_opt(), fb_exp_monty(), fb_inv_almos(), fb_inv_binar(), fb_inv_bruch(), fb_itr_pre_quick(), fb_mul_21(), fb_mul_41(), fb_mul_42(), fb_mul_420(), fb_mul_51(), fb_mul_beta(), fb_mul_rcomb(), and fb_print().
#define FB_DIG_LOG ((int)DIGIT_LOG)
Logarithm of the digit size in base 2.
Definition at line 62 of file relic_fb.h.
Referenced by fb_bits(), fb_get_bit(), fb_inv_exgcd(), fb_lsh(), fb_poly_set_penta(), fb_poly_set_trino(), fb_rand(), fb_rdc_basic(), fb_rsh(), fb_set_bit(), and fb_test_bit().
#define FB_DIGS ((int)((FB_BITS)/(FB_DIGIT) + (FB_BITS % FB_DIGIT > 0)))
Size in digits of a block sufficient to store a binary field element.
Definition at line 67 of file relic_fb.h.
Referenced by conf_print(), eb_curve_init(), eb_map(), eb_mul_lodah(), fb4_mul_dxd(), fb_bits(), fb_cmp_dig(), fb_copy(), fb_inv_almos(), fb_inv_binar(), fb_inv_bruch(), fb_inv_exgcd(), fb_is_zero(), fb_itr_pre_quick(), fb_mul_21(), fb_mul_41(), fb_mul_42(), fb_mul_420(), fb_mul_51(), fb_mul_basic(), fb_mul_beta(), fb_mul_karat(), fb_mul_lcomb(), fb_mul_rcomb(), fb_neg(), fb_poly_add(), fb_print(), fb_rand(), fb_rdc_basic(), and fb_zero().
#define FB_BYTES ((int)((FB_BITS)/8 + (FB_BITS % 8 > 0)))
Size in bytes of a block sufficient to store a binary field element.
Definition at line 72 of file relic_fb.h.
Referenced by cp_sokaka_key(), eb_map(), and eb_param_set().
#define FB_TABLE_BASIC (1)
Size of a precomputation table for repeated squaring/square-root using the trivial approach.
Definition at line 136 of file relic_fb.h.
#define FB_TABLE_QUICK ((FB_DIGIT / 4) * FB_DIGS * 16)
Size of a precomputation table for repeated squaring/square-root using the faster approach.
Definition at line 142 of file relic_fb.h.
#define FB_TABLE FB_TABLE_QUICK
Size of a precomputation table for repeated squaring/square-root using the chosen algorithm.
Definition at line 151 of file relic_fb.h.
Referenced by find_chain(), and pb_map_init().
#define FB_TABLE_MAX FB_TABLE_QUICK
Maximum size of a precomputation table.
Definition at line 160 of file relic_fb.h.
#define fb_null (A) /* empty */
Initializes a binary field element with a null value.
Parameters
[out] A - the binary field element to initialize.
Definition at line 191 of file relic_fb.h.
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin(), eb_add_projc_ordin_mix(), eb_add_projc_super(), eb_add_projc_super_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_hlv(), eb_is_valid(), eb_map(), eb_mul_halve(), eb_neg_projc(), eb_norm_sim(), eb_param_set(), eb_rhs(), eb_upk(), fb2_inv(), fb2_mul(), fb2_mul_nor(), fb4_mul(), fb4_mul_dxd(), fb4_mul_dxs(), fb4_mul_sxs(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_basic(), fb_inv_bruch(), fb_inv_exgcd(), fb_inv_itoht(), fb_inv_sim(), fb_itr_pre_quick(), fb_mul_basic(), fb_poly_set_penta(), fb_poly_set_trino(), fb_size(), fb_slv_basic(), fb_trc_basic(), fb_write(), find_solve(), find_trace(), pb_map_etatn_imp(), and pb_map_etats_imp().
#define fb_new (A) /* empty */
Calls a function to allocate a binary field element.
Parameters
[out] A - the new binary field element.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 207 of file relic_fb.h.
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin(), eb_add_projc_ordin_mix(), eb_add_projc_super(), eb_add_projc_super_mix(), eb_curve_init(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_hlv(), eb_is_valid(), eb_map(), eb_mul_halve(), eb_neg_projc(), eb_norm_sim(), eb_param_set(), eb_rhs(), eb_upk(), fb2_inv(), fb2_mul(), fb2_mul_nor(), fb4_mul(), fb4_mul_dxd(), fb4_mul_dxs(), fb4_mul_sxs(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_basic(), fb_inv_bruch(), fb_inv_itoht(), fb_inv_sim(), fb_itr_pre_quick(), fb_mul_basic(), fb_poly_set_penta(), fb_poly_set_trino(), fb_size(), fb_slv_basic(), fb_trc_basic(), fb_write(), find_solve(), find_trace(), pb_map_etatn_imp(), and pb_map_etats_imp().
#define fb_free (A) /* empty */
Calls a function to free a binary field element.
Parameters
[out] A - the binary field element to clean and free.
Definition at line 225 of file relic_fb.h.
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin(), eb_add_projc_ordin_mix(), eb_add_projc_super(), eb_add_projc_super_mix(), eb_curve_clean(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_hlv(), eb_is_valid(), eb_map(), eb_mul_halve(), eb_neg_projc(), eb_norm_sim(), eb_param_set(), eb_rhs(), eb_upk(), fb2_inv(), fb2_mul(), fb2_mul_nor(), fb4_mul(), fb4_mul_dxd(), fb4_mul_dxs(), fb4_mul_sxs(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_basic(), fb_inv_bruch(), fb_inv_itoht(), fb_inv_sim(), fb_itr_pre_quick(), fb_mul_basic(), fb_poly_set_penta(), fb_poly_set_trino(), fb_rdc_basic(), fb_size(), fb_slv_basic(), fb_trc_basic(), fb_write(), find_solve(), find_trace(), pb_map_etatn_imp(), and pb_map_etats_imp().
#define fb_mul (C, A, B) fb_mul_lodah(C, A, B)
Multiples two binary field elements. Computes c = a * b.
Parameters
[out] C - the result.
[in] A - the first binary field element to multiply.
[in] B - the second binary field element to multiply.
Definition at line 248 of file relic_fb.h.
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin(), eb_add_projc_ordin_mix(), eb_add_projc_super(), eb_add_projc_super_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_hlv(), eb_is_valid(), eb_map(), eb_mul_halve(), eb_mul_lodah(), eb_neg_projc(), eb_norm_halve(), eb_norm_ordin(), eb_norm_super(), eb_pck(), eb_rhs(), eb_upk(), fb2_inv(), fb2_mul(), fb4_mul(), fb4_mul_dxd(), fb4_mul_dxs(), fb4_mul_sxs(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_basic(), fb_inv_itoht(), fb_inv_sim(), pb_map_etatn_imp(), and pb_map_etats_imp().
#define fb_sqr (C, A) fb_sqr_table(C, A)
Squares a binary field element. Computes c = a * a.
Parameters
[out] C - the result.
[in] A - the binary field element to square.
Definition at line 260 of file relic_fb.h.
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin(), eb_add_projc_ordin_mix(), eb_add_projc_super(), eb_add_projc_super_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_dbl_projc_super(), eb_frb_basic(), eb_frb_projc(), eb_is_valid(), eb_map(), eb_mul_lodah(), eb_mul_rtnaf_imp(), eb_norm_ordin(), eb_rhs(), eb_upk(), etat_exp(), fb2_inv(), fb2_sqr(), fb4_sqr(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_basic(), fb_inv_itoht(), fb_itr_basic(), fb_itr_pre_quick(), fb_slv_basic(), fb_srt_basic(), fb_trc_basic(), find_solve(), find_srz(), find_trace(), pb_map_etatn_imp(), and pb_map_etats_imp().
#define fb_srt (C, A) fb_srt_quick(C, A)
Extracts the square root of a binary field element. Computes c = a^(1/2).
Parameters
[out] C - the result.
[in] A - the binary field element.
Definition at line 274 of file relic_fb.h.
Referenced by eb_hlv(), eb_mul_halve(), fb_itr_basic(), fb_itr_pre_quick(), and pb_map_etats_imp().
#define fb_rdc (C, A) fb_rdc_quick(C, A)
Reduces a multiplication result modulo a binary irreducible polynomial. Computes c = a mod f(z).
Parameters
[out] C - the result.
[in] A - the multiplication result to reduce.
Definition at line 287 of file relic_fb.h.
Referenced by fb_mul_basic(), fb_mul_karat(), fb_mul_lcomb(), fb_mul_lodah(), fb_mul_rcomb(), fb_sqr_basic(), and fb_sqr_table().
#define fb_trc (A) fb_trc_quick(A)
Compute the trace of a binary field element. Computes c = Tr(a).
Parameters
[in] A - the binary field element.
Returns
the trace of the binary field element.
Definition at line 299 of file relic_fb.h.
Referenced by eb_hlv(), eb_map(), eb_mul_halve(), eb_upk(), fb2_slv(), fb_slv_basic(), and fb_slv_quick().
#define fb_slv (C, A) fb_slv_quick(C, A)
Solves a quadratic equation for c, Tr(a) = 0. Computes c such that c^2 + c = a.
Parameters
[out] C - the result.
[in] A - the binary field element.
Definition at line 312 of file relic_fb.h.
Referenced by eb_hlv(), eb_map(), eb_mul_halve(), eb_upk(), and fb2_slv().
#define fb_inv (C, A) fb_inv_exgcd(C, A)
Inverts a binary field element. Computes c = a^{-1}.
Parameters
[out] C - the result.
[in] A - the binary field element to invert.
Definition at line 328 of file relic_fb.h.
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_map(), eb_mul_lodah(), eb_norm_ordin(), eb_norm_super(), eb_pck(), eb_upk(), fb2_inv(), and fb_inv_sim().
#define fb_exp (C, A, B) fb_exp_slide(C, A, B)
Exponentiates a binary field element. Computes c = a^b.
Parameters
[out] C - the result.
[in] A - the basis.
[in] B - the exponent.
Definition at line 345 of file relic_fb.h.
#define fb_itr_pre (T, B) fb_itr_pre_quick(T, B)
Precomputed the table for repeated squaring/square-root.
Parameters
[out] T - the table.
[in] B - the exponent.
Definition at line 359 of file relic_fb.h.
Referenced by find_chain(), and pb_map_init().
#define fb_itr (C, A, ...) CAT(fb_itr, OPT(__VA_ARGS__))(C, A, __VA_ARGS__)
Computes the repeated Frobenius (squaring) or inverse Frobenius (square-root) of a binary field element. If the number of arguments is 3, then simple consecutive squaring/square-root is used. If the number of arguments if 4, then a table-based method is used and the fourth argument is a pointer fo the precomputed table. The variant with 4 arguments should be used when several 2^k/2^-k powers are computed with the same k. Computes c = a^(2^b), where b can be positive or negative.
Parameters
[out] C - the result.
[in] A - the binary field element to exponentiate.
[in] B - the exponent.
[in] ... - the modulus and an optional argument.
Definition at line 376 of file relic_fb.h.
Referenced by etat_exp(), fb_inv_itoht(), and pb_map_etats_imp().
#define fb_itr_imp (C, A, B, T) fb_itr_quick(C, A, T)
Reduces a multiple precision integer modulo another integer. This macro should not be called directly. Use bn_mod() with 4 arguments instead.
Parameters
[out] C - the result.
[in] A - the binary field element to exponentiate.
[in] B - the exponent.
[in] T - the precomputed table for the exponent.
Definition at line 390 of file relic_fb.h.
Typedef Documentation
typedef align dig_t fb_t[FB_DIGS+PADDING(FB_BYTES)/(FB_DIGIT/8)]
Represents a binary field element.
Definition at line 171 of file relic_fb.h.
typedef align dig_t fb_st[FB_DIGS+PADDING(FB_BYTES)/(FB_DIGIT/8)]
Represents a binary field element with automatic memory allocation.
Definition at line 179 of file relic_fb.h.
Enumeration Type Documentation
anonymous enum
Finite field identifiers.
Enumerator
PENTA_64
Toy pentanomial.
TRINO_113
Hankerson's trinomial for GLS curves.
TRINO_127
Hankerson's trinomial for GLS curves.
PENTA_128
GCM pentanomial
PENTA_131
Pentanomial for ECC2K-130 challenge.
NIST_163
NIST 163-bit fast reduction polynomial.
SQRT_163
Square-root friendly 163-bit polynomial.
TRINO_193
Example with 193 bits for Itoh-Tsuji.
NIST_233
NIST 233-bit fast reduction polynomial.
SQRT_233
Square-root friendly 233-bit polynomial.
SECG_239
SECG 239-bit fast reduction polynomial.
SQRT_239
Square-root friendly 239-bit polynomial.
SQRT_251
Square-root friendly 251-bit polynomial.
PENTA_251
eBATS curve_2_251 pentanomial.
TRINO_257
Hankerson's trinomial for halving curve.
TRINO_271
Scott's 271-bit pairing-friendly trinomial.
PENTA_271
Scott's 271-bit pairing-friendly pentanomial.
NIST_283
NIST 283-bit fast reduction polynomial.
SQRT_283
Square-root friendly 283-bit polynomial.
TRINO_353
Scott's 271-bit pairing-friendly trinomial.
TRINO_367
Detrey's trinomial for genus 2 curves.
NIST_409
NIST 409-bit fast reduction polynomial.
TRINO_439
Hankerson's trinomial for genus 2 curves.
NIST_571
NIST 571-bit fast reduction polynomial.
SQRT_571
Square-root friendly 571-bit polynomial.
TRINO_1223
Scott's 1223-bit pairing-friendly trinomial.
Definition at line 77 of file relic_fb.h.
Function Documentation
void fb_poly_init (void)
Initializes the binary field arithmetic layer.
Definition at line 322 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, _ctx_t::fb_poly, and fb_zero().
Referenced by core_init().
void fb_poly_clean (void)
Finalizes the binary field arithmetic layer.
Definition at line 330 of file relic_fb_poly.c.
Referenced by core_clean().
dig_t* fb_poly_get (void)
Returns the irreducible polynomial f(z) configured for the binary field.
Returns
the irreducible polynomial.
Definition at line 333 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_poly.
Referenced by fb_inv_almos(), fb_inv_binar(), fb_inv_bruch(), fb_inv_exgcd(), and fb_rdc_basic().
void fb_poly_set_dense (const fb_t f)
Configures the irreducible polynomial of the binary field as a dense polynomial.
Parameters
[in] f - the new irreducible polynomial.
Definition at line 369 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, and fb_poly_set().
void fb_poly_set_trino (int a)
Configures a trinomial as the irreducible polynomial by its non-zero coefficients. The other coefficients are FB_BITS and 0.
Parameters
[in] a - the second coefficient.
Definition at line 376 of file relic_fb_poly.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FB_BITS, FB_DIG_LOG, fb_free, _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, fb_new, fb_null, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, fb_poly_set(), fb_set_bit(), fb_zero(), FINALLY, THROW, and TRY.
Referenced by fb_param_set().
void fb_poly_set_penta (int a, int b, int c)
Configures a pentanomial as the binary field modulo by its non-zero coefficients. The other coefficients are FB_BITS and 0.
Parameters
[in] a - the second coefficient.
[in] b - the third coefficient.
[in] c - the fourth coefficient.
Definition at line 404 of file relic_fb_poly.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FB_BITS, FB_DIG_LOG, fb_free, _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, fb_new, fb_null, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, fb_poly_set(), fb_set_bit(), fb_zero(), FINALLY, THROW, and TRY.
Referenced by fb_param_set().
dig_t* fb_poly_get_srz (void)
Returns the square root of z.
Returns
the square root of z.
Definition at line 437 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_srz.
const dig_t* fb_poly_tab_srz (int i)
Returns sqrt(z) * (i represented as a polynomial).
Returns
the precomputed result.
Definition at line 459 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_tab_srz.
const fb_t* fb_poly_tab_sqr (int i)
Returns a table for accelerating repeated squarings.
Parameters
the number of the table.
Returns
the precomputed result.
Definition at line 445 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_tab_ptr.
Referenced by fb_inv_itoht(), and find_chain().
const int* fb_poly_get_chain (int * len)
Returns an addition chain for (FB_BITS - 1).
Parameters
[out] len - the number of elements in the addition chain.
Returns
a pointer to the addition chain.
Definition at line 499 of file relic_fb_poly.c.
References _ctx_t::chain, _ctx_t::chain_len, core_get(), and MAX_TERMS.
Referenced by fb_inv_itoht().
void fb_poly_get_rdc (int * a, int * b, int * c)
Returns the non-zero coefficients of the configured trinomial or pentanomial. If b is -1, the irreducible polynomial configured is a trinomial. The other coefficients are FB_BITS and 0.
Parameters
[out] a - the second coefficient.
[out] b - the third coefficient.
[out] c - the fourth coefficient.
Definition at line 484 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_pa, _ctx_t::fb_pb, and _ctx_t::fb_pc.
Referenced by fb_param_print().
void fb_poly_get_trc (int * a, int * b, int * c)
Returns the non-zero bits used to compute the trace function. The -1 coefficient is the last coefficient.
Parameters
[out] a - the first coefficient.
[out] b - the second coefficient.
[out] c - the third coefficient.
Definition at line 473 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_ta, _ctx_t::fb_tb, and _ctx_t::fb_tc.
const dig_t* fb_poly_get_slv (void)
Returns the table of precomputed half-traces.
Returns
the table of half-traces.
Definition at line 491 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_half.
void fb_param_set (int param)
Assigns a standard irreducible polynomial as modulo of the binary field.
Parameters
[in] param - the standardized polynomial identifier.
Definition at line 50 of file relic_fb_param.c.
References core_get(), ERR_NO_VALID, _ctx_t::fb_id, fb_poly_set_penta(), fb_poly_set_trino(), NIST_163, NIST_233, NIST_283, NIST_409, NIST_571, PENTA_128, PENTA_131, PENTA_251, PENTA_271, PENTA_64, SECG_239, SQRT_163, SQRT_233, SQRT_239, SQRT_251, SQRT_283, SQRT_571, THROW, TRINO_113, TRINO_1223, TRINO_127, TRINO_193, TRINO_257, TRINO_271, TRINO_353, TRINO_367, and TRINO_439.
Referenced by fb_param_set_any().
void fb_param_set_any (void)
Configures some finite field parameters for the current security level.
Definition at line 141 of file relic_fb_param.c.
References ERR_NO_FIELD, fb_param_set(), NIST_163, NIST_233, NIST_283, NIST_409, NIST_571, PENTA_128, PENTA_131, PENTA_251, PENTA_271, PENTA_64, SECG_239, SQRT_163, SQRT_233, SQRT_239, SQRT_251, SQRT_283, SQRT_571, THROW, TRINO_113, TRINO_1223, TRINO_127, TRINO_193, TRINO_257, TRINO_271, TRINO_353, TRINO_367, and TRINO_439.
void fb_param_print (void)
Prints the currently configured irreducible polynomial.
Definition at line 231 of file relic_fb_param.c.
References FB_BITS, fb_poly_get_rdc(), util_banner, and util_print.
void fb_poly_add (fb_t c, const fb_t a)
Adds a binary field element and the irreducible polynomial. Computes c = a + f(z).
Parameters
[out] c - the destination.
[in] a - the binary field element.
Definition at line 337 of file relic_fb_poly.c.
References core_get(), fb_add(), fb_copy(), FB_DIGS, _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, and _ctx_t::fb_poly.
Referenced by fb_inv_almos(), fb_inv_binar(), fb_mul_basic(), and fb_poly_sub().
void fb_poly_sub (fb_t c, const fb_t a)
Subtracts the irreducible polynomial from a binary field element. Computes c = a - f(z).
Parameters
[out] c - the destination.
[in] a - the binary field element.
Definition at line 365 of file relic_fb_poly.c.
References fb_poly_add().
void fb_copy (fb_t c, const fb_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the binary field element to copy.
Definition at line 80 of file relic_fb_util.c.
References FB_DIGS.
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin_mix(), eb_add_projc_super_mix(), eb_copy(), eb_curve_set_kbltz(), eb_curve_set_ordin(), eb_curve_set_super(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_dbl_projc_super(), eb_hlv(), eb_mul_halve(), eb_mul_lodah(), eb_neg_basic(), eb_neg_projc(), eb_norm_halve(), eb_norm_ordin(), eb_norm_sim(), eb_norm_super(), eb_pck(), eb_rhs(), eb_upk(), etat_exp(), fb2_mul_nor(), fb4_frb(), fb4_inv(), fb4_mul_dxd(), fb4_mul_dxs(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_almos(), fb_inv_basic(), fb_inv_binar(), fb_inv_bruch(), fb_inv_exgcd(), fb_inv_itoht(), fb_inv_sim(), fb_itr_basic(), fb_itr_pre_quick(), fb_lsh(), fb_mul_basic(), fb_mul_rcomb(), fb_poly_add(), fb_poly_set(), fb_rdc_basic(), fb_rsh(), fb_size(), fb_slv_basic(), fb_srt_basic(), fb_trc_basic(), fb_write(), find_solve(), find_trace(), pb_map_etatn_imp(), and pb_map_etats_imp().
void fb_neg (fb_t c, const fb_t a)
Negates a binary field element.
Parameters
[out] c - the result.
[out] a - the binary field element to negate.
Definition at line 86 of file relic_fb_util.c.
References FB_DIGS.
void fb_zero (fb_t a)
Assigns zero to a binary field element.
Parameters
[out] a - the binary field element to assign.
Definition at line 92 of file relic_fb_util.c.
References FB_DIGS.
Referenced by eb_curve_init(), eb_frb_basic(), eb_mul_halve(), eb_mul_lodah(), eb_param_set(), eb_set_infty(), fb_inv_bruch(), fb_itr_pre_quick(), fb_mul_basic(), fb_poly_init(), fb_poly_set_penta(), fb_poly_set_trino(), fb_read(), fb_set_dig(), find_solve(), find_trace(), pb_map_etatn_imp(), and pb_map_etats_imp().
int fb_is_zero (const fb_t a)
Tests if a binary field element is zero or not.
Parameters
[in] a - the binary field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 100 of file relic_fb_util.c.
References FB_DIGS.
Referenced by detect_opt(), eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin(), eb_add_projc_ordin_mix(), eb_add_projc_super(), eb_add_projc_super_mix(), eb_is_infty(), eb_mul_lodah(), fb_size(), fb_write(), and find_trace().
int fb_test_bit (const fb_t a, int bit)
Tests if the bit in a given position is non-zero on a binary field element.
Parameters
[in] a - the binary field element to test.
[in] bit - the bit position.
Returns
0 is the bit is zero, not zero otherwise.
Definition at line 111 of file relic_fb_util.c.
References FB_DIG_LOG, and SPLIT.
Referenced by fb_mul_basic(), and fb_rdc_basic().
int fb_get_bit (const fb_t a, int bit)
Reads the bit stored in the given position on a binary field element.
Parameters
[in] a - the binary field element.
[in] bit - the bit position.
Returns
the bit value.
Definition at line 121 of file relic_fb_util.c.
References FB_DIG_LOG, and SPLIT.
Referenced by eb_pck(), and eb_upk().
void fb_set_bit (fb_t a, int bit, int value)
Stores a bit in a given position on a binary field element.
Parameters
[out] a - the binary field element.
[in] bit - the bit position.
[in] value - the bit value.
Definition at line 132 of file relic_fb_util.c.
References FB_DIG_LOG, and SPLIT.
Referenced by eb_frb_basic(), eb_mul_lodah(), eb_mul_sim_kbltz(), eb_param_set(), fb_poly_set_penta(), fb_poly_set_trino(), find_solve(), find_trace(), pb_map_etatn_imp(), and pb_map_etats_imp().
void fb_set_dig (fb_t c, dig_t a)
Assigns a small positive polynomial to a binary field element.
The degree of the polynomial must be smaller than FB_DIGIT.
Parameters
[out] c - the result.
[in] a - the small polynomial to assign.
Definition at line 161 of file relic_fb_util.c.
References fb_zero().
Referenced by eb_curve_set_kbltz(), eb_frb_projc(), eb_hlv(), eb_map(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_norm_ordin(), eb_norm_sim(), eb_norm_super(), eb_pck(), eb_tab(), eb_upk(), fb_exp_monty(), fb_exp_slide(), fb_inv_almos(), fb_inv_basic(), fb_inv_bruch(), fb_itr_pre_quick(), and find_srz().
int fb_bits (const fb_t a)
Returns the number of bits of a binary field element.
Parameters
[in] a - the binary field element.
Returns
the number of bits.
Definition at line 147 of file relic_fb_util.c.
References FB_DIG_LOG, FB_DIGS, and util_bits_dig().
Referenced by detect_opt(), fb_inv_exgcd(), fb_mul_basic(), fb_rdc_basic(), and fb_size().
void fb_rand (fb_t a)
Assigns a random value to a binary field element.
Parameters
[out] a - the binary field element to assign.
Definition at line 166 of file relic_fb_util.c.
References FB_BITS, FB_DIG_LOG, FB_DIGS, MASK, rand_bytes(), and SPLIT.
void fb_print (const fb_t a)
Prints a binary field element to standard output.
Parameters
[in] a - the binary field element to print.
Definition at line 178 of file relic_fb_util.c.
References FB_DIGIT, FB_DIGS, and util_print.
Referenced by eb_print().
void fb_size (int * size, const fb_t a, int radix)
Returns the number of digits in radix necessary to store a binary field element. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[out] size - the result.
[in] a - the binary field element.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Definition at line 193 of file relic_fb_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, fb_bits(), fb_copy(), fb_free, fb_is_zero(), fb_new, fb_null, fb_rsh(), FINALLY, log_radix(), THROW, TRY, and valid_radix().
Referenced by fb_write().
void fb_read (fb_t a, const char * str, int len, int radix)
Reads a binary field element from a string in a given radix. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[out] a - the result.
[in] str - the string.
[in] len - the size of the string.
[in] radix - the radix.
Exceptions
ERR_NO_BUFFER - if the string if too long.
ERR_NO_VALID - if the radix is invalid.
Definition at line 238 of file relic_fb_util.c.
References ERR_NO_BUFFER, ERR_NO_VALID, fb_add_dig(), fb_lshb_low(), fb_zero(), log_radix(), THROW, TOUPPER, util_conv_char(), and valid_radix().
void fb_write (char * str, int len, const fb_t a, int radix)
Writes a binary field element to a string in a given radix. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[out] str - the string.
[in] len - the buffer capacity.
[in] a - the binary field element to write.
[in] radix - the radix.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
ERR_NO_VALID - if the radix is invalid.
Definition at line 272 of file relic_fb_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_VALID, fb_copy(), fb_free, fb_is_zero(), fb_new, fb_null, fb_rshb_low(), fb_size(), FINALLY, log_radix(), THROW, TRY, util_conv_char(), and valid_radix().
int fb_cmp (const fb_t a, const fb_t b)
Returns the result of a comparison between two binary field elements.
Parameters
[in] a - the first binary field element.
[in] b - the second binary field element.
Returns
CMP_LT if a < b, CMP_EQ if a == b and CMP_GT if a > b.
Definition at line 50 of file relic_fb_cmp.c.
References fb_cmpn_low().
Referenced by eb_cmp(), and eb_is_valid().
int fb_cmp_dig (const fb_t a, dig_t b)
Returns the result of a comparison between a binary field element and a small binary field element.
Parameters
[in] a - the binary field element.
[in] b - the small binary field element.
Returns
CMP_LT if a < b, CMP_EQ if a == b and CMP_GT if a > b.
Definition at line 40 of file relic_fb_cmp.c.
References CMP_GT, fb_cmp1_low(), and FB_DIGS.
Referenced by detect_opt(), and eb_curve_set_ordin().
void fb_add (fb_t c, const fb_t a, const fb_t b)
Adds two binary field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first binary field element to add.
[in] b - the second binary field element to add.
Definition at line 44 of file relic_fb_add.c.
References fb_addn_low().
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin(), eb_add_projc_ordin_mix(), eb_add_projc_super(), eb_add_projc_super_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_dbl_projc_super(), eb_hlv(), eb_is_valid(), eb_mul_halve(), eb_mul_lodah(), eb_neg_basic(), eb_neg_projc(), eb_norm_halve(), eb_rhs(), etat_exp(), fb2_inv(), fb2_mul(), fb2_mul_nor(), fb2_slv(), fb2_sqr(), fb4_frb(), fb4_inv(), fb4_mul(), fb4_mul_dxd(), fb4_mul_dxs(), fb4_mul_sxs(), fb4_sqr(), fb_inv_binar(), fb_inv_bruch(), fb_mul_basic(), fb_poly_add(), fb_slv_basic(), fb_trc_basic(), find_solve(), find_trace(), pb_map_etatn_imp(), and pb_map_etats_imp().
void fb_add_dig (fb_t c, const fb_t a, dig_t b)
Adds a binary field element and a small binary field element. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the binary field element to add.
[in] b - the small binary field element to add.
Definition at line 48 of file relic_fb_add.c.
References fb_add1_low().
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_super(), eb_hlv(), eb_mul_lodah(), eb_neg_basic(), eb_neg_projc(), eb_rhs(), eb_upk(), fb2_slv(), fb4_mul_sxs(), fb_read(), fb_slv_basic(), fb_slv_quick(), pb_map_etatn_imp(), and pb_map_etats_imp().
void fb_sub (fb_t c, const fb_t a, const fb_t b)
Subtracts a binary field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the binary field element.
[in] b - the binary field element to subtract.
Definition at line 52 of file relic_fb_add.c.
References fb_addn_low().
void fb_sub_dig (fb_t c, const fb_t a, dig_t b)
Subtracts a small binary field element from a binary field element. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the binary field element.
[in] b - the small binary field element to subtract.
Definition at line 56 of file relic_fb_add.c.
References fb_add1_low().
void fb_mul_basic (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Shift-and-add multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 265 of file relic_fb_mul.c.
References CATCH_ANY, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fb_add(), FB_BITS, fb_bits(), fb_copy(), FB_DIGS, fb_free, fb_lsh1_low(), fb_new, fb_null, fb_poly_add(), fb_rdc, fb_test_bit(), fb_zero(), FINALLY, THROW, and TRY.
void fb_mul_integ (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using multiplication integrated with modular reduction.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 313 of file relic_fb_mul.c.
References fb_mulm_low().
void fb_mul_lcomb (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Left-to-right comb multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 321 of file relic_fb_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fb_addd_low(), FB_DIGS, fb_lsh1_low(), fb_rdc, FINALLY, THROW, and TRY.
void fb_mul_rcomb (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Right-to-left comb multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 360 of file relic_fb_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fb_addd_low(), fb_copy(), FB_DIGIT, FB_DIGS, fb_lsh1_low(), fb_rdc, FINALLY, THROW, and TRY.
void fb_mul_lodah (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Lpez-Dahab multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 402 of file relic_fb_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, fb_muln_low(), fb_rdc, FINALLY, THROW, and TRY.
void fb_mul_dig (fb_t c, const fb_t a, dig_t b)
Multiplies a binary field element by a small binary field element.
Parameters
[out] c - the result.
[in] a - the binary field element.
[in] b - the small binary field element to multiply.
Definition at line 448 of file relic_fb_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, fb_mul1_low(), fb_rdc1_low(), FINALLY, THROW, and TRY.
Referenced by eb_add_projc_ordin_mix(), eb_dbl_projc_ordin(), eb_rhs(), and find_srz().
void fb_mul_karat (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element.
[in] b - the second binary field element.
Definition at line 425 of file relic_fb_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, FB_DIGS, FB_KARAT, fb_mul_karat_imp(), fb_rdc, FINALLY, THROW, and TRY.
void fb_sqr_basic (fb_t c, const fb_t a)
Squares a binary field element using bit-manipulation squaring.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 47 of file relic_fb_sqr.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, fb_rdc, fb_sqrn_low(), FINALLY, THROW, and TRY.
void fb_sqr_integ (fb_t c, const fb_t a)
Squares a binary field element with integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 91 of file relic_fb_sqr.c.
References fb_sqrm_low().
void fb_sqr_table (fb_t c, const fb_t a)
Squares a binary field element using table-based squaring.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 69 of file relic_fb_sqr.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, fb_rdc, fb_sqrl_low(), FINALLY, THROW, and TRY.
void fb_lsh (fb_t c, const fb_t a, int bits)
Shifts a binary field element to the left. Computes c = a * z^bits mod f(z).
Parameters
[out] c - the result.
[in] a - the binary field element to shift.
[in] bits - the number of bits to shift.
Definition at line 41 of file relic_fb_shift.c.
References fb_copy(), FB_DIG_LOG, fb_lsh1_low(), fb_lshb_low(), fb_lshd_low(), and SPLIT.
Referenced by fb_inv_bruch(), and fb_itr_pre_quick().
void fb_rsh (fb_t c, const fb_t a, int bits)
Shifts a binary field element to the right. Computes c = a / (z^bits).
Parameters
[out] c - the result.
[in] a - the binary field element to shift.
[in] bits - the number of bits to shift.
Definition at line 66 of file relic_fb_shift.c.
References fb_copy(), FB_DIG_LOG, fb_rsh1_low(), fb_rshb_low(), fb_rshd_low(), and SPLIT.
Referenced by fb_inv_bruch(), fb_size(), and find_solve().
void fb_rdc_basic (fb_t c, dv_t a)
Reduces a multiplication result modulo an irreducible polynomial using shift-and-add modular reduction.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 50 of file relic_fb_rdc.c.
References CATCH_ANY, dv_new, dv_null, ERR_CAUGHT, fb_addd_low(), FB_BITS, fb_bits(), fb_copy(), FB_DIG_LOG, FB_DIGS, fb_free, fb_lshb_low(), fb_poly_get(), fb_test_bit(), FINALLY, SPLIT, THROW, and TRY.
void fb_rdc_quick (fb_t c, dv_t a)
Reduces a multiplication result modulo a trinomial or pentanomial.
Parameters
[out] c - the result.
[in] a - the multiplication result to reduce.
Definition at line 100 of file relic_fb_rdc.c.
References fb_rdcn_low().
void fb_srt_basic (fb_t c, const fb_t a)
Extracts the square root of a binary field element using repeated squaring. Computes c = a^{1/2}.
Parameters
[out] c - the result.
[in] a - the binary field element to take a square root.
Definition at line 46 of file relic_fb_srt.c.
References FB_BITS, fb_copy(), and fb_sqr.
void fb_srt_quick (fb_t c, const fb_t a)
Extracts the square root of a binary field element using a fast square root extraction algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to take a square root.
Definition at line 60 of file relic_fb_srt.c.
References fb_srtn_low().
dig_t fb_trc_basic (const fb_t a)
Computes the trace of a binary field element using repeated squaring. Returns Tr(a).
Parameters
[in] a - the binary field element.
Returns
the trace of the binary field element.
Definition at line 40 of file relic_fb_trc.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), FB_BITS, fb_copy(), fb_free, fb_new, fb_null, fb_sqr, FINALLY, THROW, and TRY.
dig_t fb_trc_quick (const fb_t a)
Computes the trace of a binary field element using a fast trace computation algorithm. Returns Tr(a).
Parameters
[in] a - the binary field element.
Returns
the trace of the binary field element.
Definition at line 71 of file relic_fb_trc.c.
References fb_trcn_low().
void fb_inv_basic (fb_t c, const fb_t a)
Inverts a binary field element using Fermat's Little Theorem.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Definition at line 45 of file relic_fb_inv.c.
References CATCH_ANY, ERR_CAUGHT, FB_BITS, fb_copy(), fb_free, fb_mul, fb_new, fb_null, fb_set_dig(), fb_sqr, FINALLY, THROW, and TRY.
void fb_inv_binar (fb_t c, const fb_t a)
Inverts a binary field element using the binary method.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Definition at line 107 of file relic_fb_inv.c.
References bn_rsh1_low(), CATCH_ANY, dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fb_add(), fb_addd_low(), FB_BITS, fb_copy(), FB_DIGIT, FB_DIGS, fb_poly_add(), fb_poly_get(), FINALLY, THROW, and TRY.
void fb_inv_exgcd (fb_t c, const fb_t a)
Inverts a binary field element using the Extended Euclidean algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Definition at line 208 of file relic_fb_inv.c.
References CATCH_ANY, dv_free, dv_new, dv_zero(), ERR_CAUGHT, fb_addd_low(), FB_BITS, fb_bits(), fb_copy(), FB_DIG_LOG, FB_DIGS, fb_lsha_low(), fb_null, fb_poly_get(), FINALLY, SPLIT, THROW, TRY, and util_bits_dig().
void fb_inv_almos (fb_t c, const fb_t a)
Inverts a binary field element using the Almost Inverse algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Definition at line 320 of file relic_fb_inv.c.
References bn_rsh1_low(), CATCH_ANY, dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fb_addd_low(), fb_addn_low(), FB_BITS, fb_copy(), FB_DIGIT, FB_DIGS, fb_poly_add(), fb_poly_get(), fb_set_dig(), FINALLY, THROW, and TRY.
void fb_inv_itoht (fb_t c, const fb_t a)
Inverts a binary field element using Itoh-Tsuji inversion.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Definition at line 412 of file relic_fb_inv.c.
References CATCH_ANY, ERR_CAUGHT, FB_BITS, fb_copy(), fb_free, fb_itr, fb_mul, fb_new, fb_null, fb_poly_get_chain(), fb_poly_tab_sqr(), fb_sqr, FINALLY, THROW, and TRY.
void fb_inv_bruch (fb_t c, const fb_t a)
Inverts a binary field element using the hardware-friendly Brunner-Curiger-Hofstetter algorithm.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Definition at line 471 of file relic_fb_inv.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), FB_BITS, fb_copy(), FB_DIGIT, FB_DIGS, fb_free, fb_lsh(), fb_new, fb_null, fb_poly_get(), fb_rsh(), fb_set_dig(), fb_zero(), FINALLY, THROW, and TRY.
void fb_inv_lower (fb_t c, const fb_t a)
Inverts a binary field element using a direct call to the lower layer.
Parameters
[out] c - the result.
[in] a - the binary field element to invert.
Definition at line 538 of file relic_fb_inv.c.
References fb_invn_low().
void fb_inv_sim (fb_t * c, const fb_t * a, int n)
Inverts multiple binary field elements.
Parameters
[out] c - the result.
[in] a - the binary field elements to invert.
[in] n - the number of elements.
Definition at line 543 of file relic_fb_inv.c.
References CATCH_ANY, ERR_CAUGHT, fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, FINALLY, THROW, and TRY.
Referenced by eb_norm_sim().
void fb_exp_2b (fb_t c, const fb_t a, int b)
Exponentiates a binary field element through consecutive squaring. Computes c = a^(2^b).
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
void fb_exp_basic (fb_t c, const fb_t a, const bn_t b)
Exponentiates a binary field element using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 46 of file relic_fb_exp.c.
References bn_bits(), bn_test_bit(), CATCH_ANY, ERR_CAUGHT, fb_copy(), fb_free, fb_mul, fb_new, fb_null, fb_sqr, FINALLY, THROW, and TRY.
void fb_exp_slide (fb_t c, const fb_t a, const bn_t b)
Exponentiates a binary field element using the sliding window method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 80 of file relic_fb_exp.c.
References bn_rec_slw(), CATCH_ANY, ERR_CAUGHT, FB_BITS, fb_copy(), fb_free, fb_mul, fb_new, fb_null, fb_set_dig(), fb_sqr, FB_WIDTH, FINALLY, THROW, TRY, and util_bits_dig().
void fb_exp_monty (fb_t c, const fb_t a, const bn_t b)
Exponentiates a binary field element using the constant-time Montgomery powering ladder method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 137 of file relic_fb_exp.c.
References CATCH_ANY, ERR_CAUGHT, fb_copy(), FB_DIGIT, fb_free, fb_mul, fb_new, fb_null, fb_set_dig(), fb_sqr, FINALLY, THROW, and TRY.
void fb_slv_basic (fb_t c, const fb_t a)
Solves a quadratic equation for a, Tr(a) = 0 by repeated squarings and additions.
Parameters
[out] c - the result.
[in] a - the binary field element to solve.
Definition at line 46 of file relic_fb_slv.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_add_dig(), FB_BITS, fb_copy(), fb_free, fb_new, fb_null, fb_sqr, fb_trc, FINALLY, THROW, and TRY.
void fb_slv_quick (fb_t c, const fb_t a)
Solves a quadratic equation for a, Tr(a) = 0 with precomputed half-traces.
Parameters
[out] c - the result.
[in] a - the binary field element to solve.
Definition at line 78 of file relic_fb_slv.c.
References fb_add_dig(), fb_slvn_low(), and fb_trc.
void fb_itr_basic (fb_t c, const fb_t a, int b)
Computes the iterated squaring/square-root of a binary field element by consecutive squaring/square-root. Computes c = a^(2^b).
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 46 of file relic_fb_itr.c.
References fb_copy(), fb_sqr, and fb_srt.
void fb_itr_pre_quick (fb_t * t, int b)
Precomputes a table for iterated squaring/square-root of a binary field element.
Parameters
[out] t - the precomputed table.
[in] b - the exponent.
Definition at line 59 of file relic_fb_itr.c.
References CATCH_ANY, ERR_CAUGHT, fb_copy(), FB_DIGIT, FB_DIGS, fb_free, fb_lsh(), fb_new, fb_null, fb_set_dig(), fb_sqr, fb_srt, fb_zero(), FINALLY, THROW, and TRY.
void fb_itr_quick (fb_t c, const fb_t a, const fb_t * t)
Computes the iterated squaring/square-root of a binary field element by a table based method. Computes c = a^(2^b).
Parameters
[out] c - the result.
[in] a - the basis.
[in] t - the precomputed table.
Definition at line 97 of file relic_fb_itr.c.
References fb_itrn_low().