RELIC: src/md/sha1.c File Reference
sha1.c File Reference
#include "sha.h"
Macros
#define SHA1_ROTL(bits, word) (((word) << (bits)) | ((word) >> (32-(bits))))
#define SHA1AddLength(context, length)
Functions
static void SHA1Finalize (SHA1Context *context, uint8_t Pad_Byte)
static void SHA1PadMessage (SHA1Context *, uint8_t Pad_Byte)
static void SHA1ProcessMessageBlock (SHA1Context *)
int SHA1Reset (SHA1Context *context)
int SHA1Input (SHA1Context *context, const uint8_t *message_array, unsigned length)
int SHA1FinalBits (SHA1Context *context, const uint8_t message_bits, unsigned int length)
int SHA1Result (SHA1Context *context, uint8_t Message_Digest[SHA1HashSize])
Macro Definition Documentation
#define SHA1_ROTL (bits, word) (((word) << (bits)) | ((word) >> (32-(bits))))
Definition at line 43 of file sha1.c.
Referenced by SHA1ProcessMessageBlock().
#define SHA1AddLength (context, length)
Value:
(addTemp = (context)->Length_Low,                      \
     (context)->Corrupted =                                \
        (((context)->Length_Low += (length)) < addTemp) && \
        (++(context)->Length_High == 0) ? 1 : 0)
Definition at line 49 of file sha1.c.
Referenced by SHA1FinalBits(), and SHA1Input().
Function Documentation
static void SHA1Finalize (SHA1Context * context, uint8_t Pad_Byte) static
Definition at line 262 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Length_High, SHA1Context::Length_Low, SHA1Context::Message_Block, SHA1_Message_Block_Size, and SHA1PadMessage().
Referenced by SHA1FinalBits(), and SHA1Result().
static void SHA1PadMessage (SHA1Context * context, uint8_t Pad_Byte) static
Definition at line 298 of file sha1.c.
References SHA1Context::Length_High, SHA1Context::Length_Low, SHA1Context::Message_Block, SHA1Context::Message_Block_Index, SHA1_Message_Block_Size, and SHA1ProcessMessageBlock().
Referenced by SHA1Finalize().
static void SHA1ProcessMessageBlock (SHA1Context * context) static
Definition at line 351 of file sha1.c.
References SHA1Context::Intermediate_Hash, SHA1Context::Message_Block, SHA1Context::Message_Block_Index, SHA1_ROTL, SHA_Ch, SHA_Maj, and SHA_Parity.
Referenced by SHA1Input(), and SHA1PadMessage().
int SHA1Reset (SHA1Context * context)
Definition at line 75 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, SHA1Context::Intermediate_Hash, SHA1Context::Length_High, SHA1Context::Length_Low, SHA1Context::Message_Block_Index, shaNull, and shaSuccess.
Referenced by md_map_shone(), and md_map_shone_mid().
int SHA1Input (SHA1Context * context, const uint8_t * message_array, unsigned length)
Definition at line 116 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, SHA1Context::Message_Block, SHA1Context::Message_Block_Index, SHA1_Message_Block_Size, SHA1AddLength, SHA1ProcessMessageBlock(), shaNull, shaStateError, and shaSuccess.
int SHA1FinalBits (SHA1Context * context, const uint8_t message_bits, unsigned int length)
Definition at line 166 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, SHA1AddLength, SHA1Finalize(), shaNull, shaStateError, and shaSuccess.
int SHA1Result (SHA1Context * context, uint8_t Message_Digest[SHA1HashSize])
Definition at line 223 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, SHA1Context::Intermediate_Hash, SHA1Finalize(), SHA1HashSize, shaNull, and shaSuccess.
Referenced by md_map_shone().