RELIC: src/bn/relic_bn_mxp.c File Reference
relic_bn_mxp.c File Reference
Multiple precision integer arithmetic.
#include "relic_core.h"
Macros
#define TABLE_SIZE 64
Functions
void bn_mxp_basic (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_slide (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_monty (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_dig (bn_t c, const bn_t a, dig_t b, const bn_t m)
Detailed Description
Implementation of the multiple precision exponentiation functions.
Version
Id:
relic_bn_mxp.c 1544 2013-08-29 02:27:27Z dfaranha
Definition in file relic_bn_mxp.c.
Macro Definition Documentation
#define TABLE_SIZE 64
Size of precomputation table.
Definition at line 41 of file relic_bn_mxp.c.
Referenced by bn_mxp_slide().
Function Documentation
void bn_mxp_basic (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a modulus using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 49 of file relic_bn_mxp.c.
References bn_bits(), bn_copy(), bn_free, bn_is_zero(), bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sqr, bn_test_bit(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_mxp_slide (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a modulus using the sliding window method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 108 of file relic_bn_mxp.c.
References BN_BITS, bn_bits(), bn_copy(), bn_free, bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_rec_slw(), bn_set_dig(), bn_sqr, bn_trim(), CATCH_ANY, ERR_CAUGHT, FINALLY, TABLE_SIZE, THROW, TRY, and util_bits_dig().
void bn_mxp_monty (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a modulus using a constant-time Montgomery powering ladder method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 204 of file relic_bn_mxp.c.
References bn_copy(), BN_DIGIT, bn_free, bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sqr, CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_mxp_dig (bn_t c, const bn_t a, dig_t b, const bn_t m)
Exponentiates a multiple precision integer by a small power modulo a modulus using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 274 of file relic_bn_mxp.c.
References bn_copy(), bn_free, bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sqr, CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, TRY, and util_bits_dig().