RELIC: src/eb/relic_eb_mul_fix.c File Reference
relic_eb_mul_fix.c File Reference
Elliptic curves over binary fields.
#include "string.h"
#include "relic_core.h"
#include "relic_eb.h"
Functions
static void eb_mul_fix_kbltz (eb_t r, const eb_t *t, const bn_t k)
static void eb_mul_fix_ordin (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_pre_basic (eb_t *t, const eb_t p)
void eb_mul_fix_basic (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_pre_yaowi (eb_t *t, const eb_t p)
void eb_mul_fix_yaowi (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_pre_nafwi (eb_t *t, const eb_t p)
void eb_mul_fix_nafwi (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_pre_combs (eb_t *t, const eb_t p)
void eb_mul_fix_combs (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_pre_combd (eb_t *t, const eb_t p)
void eb_mul_fix_combd (eb_t r, const eb_t *t, const bn_t k)
void eb_mul_pre_lwnaf (eb_t *t, const eb_t p)
void eb_mul_fix_lwnaf (eb_t r, const eb_t *t, const bn_t k)
Detailed Description
Implementation of fixed point multiplication on binary elliptic curves.
Version
Id:
relic_eb_mul_fix.c 1566 2013-09-02 04:09:52Z dfaranha
Definition in file relic_eb_mul_fix.c.
Function Documentation
static void eb_mul_fix_kbltz (eb_t r, const eb_t * t, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-TNAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] t - the precomputed table.
[in] k - the integer.
Definition at line 54 of file relic_eb_mul_fix.c.
References bn_free, bn_new, bn_null, bn_rec_tnaf(), CATCH_ANY, eb_add, eb_curve_get_s0(), eb_curve_get_s1(), eb_curve_get_vm(), eb_curve_opt_a(), EB_DEPTH, eb_frb, eb_norm(), eb_set_infty(), eb_sub, ERR_CAUGHT, FB_BITS, FINALLY, OPT_ZERO, THROW, and TRY.
Referenced by eb_mul_fix_lwnaf().
static void eb_mul_fix_ordin (eb_t r, const eb_t * t, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] t - the precomputed table.
[in] k - the integer.
Definition at line 121 of file relic_eb_mul_fix.c.
References bn_rec_naf(), eb_add, eb_dbl, EB_DEPTH, eb_norm(), eb_set_infty(), eb_sub, and FB_BITS.
Referenced by eb_mul_fix_lwnaf().
void eb_mul_pre_basic (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 155 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, eb_copy(), eb_curve_get_ord(), eb_dbl, eb_norm_sim(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_fix_basic (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 180 of file relic_eb_mul_fix.c.
References bn_bits(), bn_test_bit(), eb_add, eb_norm(), and eb_set_infty().
void eb_mul_pre_yaowi (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 199 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, eb_copy(), eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm_sim(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_fix_yaowi (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 228 of file relic_eb_mul_fix.c.
References bn_is_zero(), bn_rec_win(), CATCH_ANY, CEIL, eb_add, EB_DEPTH, eb_free, eb_new, eb_norm(), eb_null, eb_set_infty(), EP_DEPTH, ERR_CAUGHT, FB_BITS, FINALLY, THROW, and TRY.
void eb_mul_pre_nafwi (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 271 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, eb_copy(), eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm_sim(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_fix_nafwi (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 302 of file relic_eb_mul_fix.c.
References bn_rec_naf(), CATCH_ANY, eb_add, EB_DEPTH, eb_free, eb_new, eb_norm(), eb_null, eb_set_infty(), eb_sub, ERR_CAUGHT, FB_BITS, FINALLY, THROW, and TRY.
void eb_mul_pre_combs (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 363 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, eb_add, eb_copy(), eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm(), eb_norm_sim(), eb_set_infty(), EB_TABLE_COMBS, ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_fix_combs (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 402 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_test_bit(), CATCH_ANY, eb_add, eb_copy(), eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_pre_combd (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 458 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, eb_add, eb_copy(), eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm_sim(), eb_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_fix_combd (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 503 of file relic_eb_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_test_bit(), CATCH_ANY, eb_add, eb_curve_get_ord(), eb_dbl, EB_DEPTH, eb_norm(), eb_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_pre_lwnaf (eb_t * t, const eb_t p)
Builds a precomputation table for multiplying a fixed binary elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 560 of file relic_eb_mul_fix.c.
References eb_curve_is_kbltz(), EB_DEPTH, and eb_tab().
void eb_mul_fix_lwnaf (eb_t r, const eb_t * t, const bn_t k)
Multiplies a fixed binary elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 573 of file relic_eb_mul_fix.c.
References eb_curve_is_kbltz(), eb_mul_fix_kbltz(), and eb_mul_fix_ordin().