RELIC: src/fb/relic_fb_trc.c File Reference
relic_fb_trc.c File Reference
Binary field arithmetic.
#include "relic_core.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
Functions
dig_t fb_trc_basic (const fb_t a)
dig_t fb_trc_quick (const fb_t a)
Detailed Description
Implementation of binary field trace function.
Version
Id:
relic_fb_trc.c 1561 2013-09-02 00:01:53Z dfaranha
Definition in file relic_fb_trc.c.
Function Documentation
dig_t fb_trc_basic (const fb_t a)
Computes the trace of a binary field element using repeated squaring. Returns Tr(a).
Parameters
[in] a - the binary field element.
Returns
the trace of the binary field element.
Definition at line 40 of file relic_fb_trc.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), FB_BITS, fb_copy(), fb_free, fb_new, fb_null, fb_sqr, FINALLY, THROW, and TRY.
dig_t fb_trc_quick (const fb_t a)
Computes the trace of a binary field element using a fast trace computation algorithm. Returns Tr(a).
Parameters
[in] a - the binary field element.
Returns
the trace of the binary field element.
Definition at line 71 of file relic_fb_trc.c.
References fb_trcn_low().