RELIC: src/relic_bench.c File Reference
relic_bench.c File Reference
Core functions.
#include <stdio.h>
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
Functions
void bench_reset ()
void bench_before ()
void bench_after ()
void bench_compute (int benches)
void bench_print ()
ull_t bench_total ()
Detailed Description
Implementation of useful benchmark routines.
Version
Id:
relic_bench.c 1530 2013-08-27 18:05:47Z dfaranha
Definition in file relic_bench.c.
Function Documentation
void bench_reset (void)
Resets the benchmark data.
Parameters
[in] label - the benchmark label.
Definition at line 118 of file relic_bench.c.
References core_get(), and _ctx_t::total.
void bench_before (void)
Measures the time before a benchmark is executed.
Definition at line 124 of file relic_bench.c.
References arch_cycles(), _ctx_t::before, CLOCK, and core_get().
void bench_after (void)
Measures the time after a benchmark was started and adds it to the total.
Definition at line 138 of file relic_bench.c.
References _ctx_t::after, arch_cycles(), _ctx_t::before, CLOCK, core_get(), and _ctx_t::total.
void bench_compute (int benches)
Computes the mean elapsed time between the start and the end of a benchmark.
Parameters
benches - the number of executed benchmarks.
Definition at line 169 of file relic_bench.c.
References core_get(), and _ctx_t::total.
void bench_print (void)
Prints the last benchmark.
Definition at line 182 of file relic_bench.c.
References core_get(), _ctx_t::total, and util_print.
ull_t bench_total (void)
Returns the result of the last benchmark.
Returns
the last benchmark.
Definition at line 199 of file relic_bench.c.
References core_get(), and _ctx_t::total.