RELIC: include/low/relic_fb_low.h File Reference
relic_fb_low.h File Reference
Binary field arithmetic.
#include "relic_types.h"
Functions
void fb_add1_low (dig_t *c, const dig_t *a, dig_t digit)
void fb_addn_low (dig_t *c, const dig_t *a, const dig_t *b)
void fb_addd_low (dig_t *c, const dig_t *a, const dig_t *b, int size)
int fb_cmp1_low (dig_t a, dig_t b)
int fb_cmpn_low (const dig_t *a, const dig_t *b)
dig_t fb_lsh1_low (dig_t *c, const dig_t *a)
dig_t fb_lshb_low (dig_t *c, const dig_t *a, int bits)
void fb_lshd_low (dig_t *c, const dig_t *a, int digits)
dig_t fb_rsh1_low (dig_t *c, const dig_t *a)
dig_t fb_rshb_low (dig_t *c, const dig_t *a, int bits)
void fb_rshd_low (dig_t *c, const dig_t *a, int digits)
dig_t fb_lsha_low (dig_t *c, const dig_t *a, int bits, int size)
void fb_mul1_low (dig_t *c, const dig_t *a, dig_t digit)
void fb_muln_low (dig_t *c, const dig_t *a, const dig_t *b)
void fb_muld_low (dig_t *c, const dig_t *a, const dig_t *b, int size)
void fb_mulm_low (dig_t *c, const dig_t *a, const dig_t *b)
void fb_sqrn_low (dig_t *c, const dig_t *a)
void fb_sqrl_low (dig_t *c, const dig_t *a)
void fb_sqrm_low (dig_t *c, const dig_t *a)
void fb_itrn_low (dig_t *c, const dig_t *a, dig_t *t)
void fb_srtn_low (dig_t *c, const dig_t *a)
void fb_slvn_low (dig_t *c, const dig_t *a)
dig_t fb_trcn_low (const dig_t *a)
void fb_rdcn_low (dig_t *c, dig_t *a)
void fb_rdc1_low (dig_t *c, dig_t *a)
void fb_invn_low (dig_t *c, const dig_t *a)
Detailed Description
Interface of the low-level binary field arithmetic module.
All functions assume a configured polynomial basis f(z) and that the destination has enough capacity to store the result of the computation.
Version
Id:
relic_fb_low.h 1535 2013-08-28 04:01:10Z dfaranha
Definition in file relic_fb_low.h.
Function Documentation
void fb_add1_low (dig_t * c, const dig_t * a, dig_t digit)
Adds a digit vector and a digit. Computes c = a + digit.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] digit - the digit to add.
Referenced by fb_add_dig(), and fb_sub_dig().
void fb_addn_low (dig_t * c, const dig_t * a, const dig_t * b)
Adds two digit vectors of the same size. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
Referenced by eb_mul_lodah(), fb_add(), fb_inv_almos(), fb_mul_420(), and fb_sub().
void fb_addd_low (dig_t * c, const dig_t * a, const dig_t * b, int size)
Adds two digit vectors of the same size, with this size different than the standard precision and specified in the last parameter. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first digit vector to add.
[in] b - the second digit vector to add.
[in] size - the number of digits to add.
Referenced by eb_mul_lodah(), fb_inv_almos(), fb_inv_binar(), fb_inv_exgcd(), fb_mul_karat_imp(), fb_mul_lcomb(), fb_mul_rcomb(), and fb_rdc_basic().
int fb_cmp1_low (dig_t a, dig_t b)
Compares two digits.
Parameters
[in] a - the first digit to compare.
[in] b - the second digit to compare.
Returns
CMP_LT if a < b, CMP_EQ if a == b and CMP_GT if a > b.
Referenced by fb_cmp_dig().
int fb_cmpn_low (const dig_t * a, const dig_t * b)
Compares two digit vectors of the same size.
Parameters
[in] a - the first digit vector to compare.
[in] b - the second digit vector to compare.
Returns
CMP_LT if a < b, CMP_EQ if a == b and CMP_GT if a > b.
Referenced by fb_cmp().
dig_t fb_lsh1_low (dig_t * c, const dig_t * a)
Shifts a digit vector to the left by 1 bit. Computes c = a * z.
Parameters
[out] c - the result
[in] a - the digit vector to shift.
Returns
the carry of the last digit shift.
Referenced by fb4_mul_dxd(), fb_lsh(), fb_mul_basic(), fb_mul_lcomb(), and fb_mul_rcomb().
dig_t fb_lshb_low (dig_t * c, const dig_t * a, int bits)
Shifts a digit vector to the left by an amount smaller than a digit. The shift amount must be bigger than 0 and smaller than FB_DIGIT. Computes c = a * z^bits.
Parameters
[out] c - the result
[in] a - the digit vector to shift.
[in] bits - the shift ammount.
Returns
the carry of the last digit shift.
Referenced by fb4_mul_dxd(), fb_lsh(), fb_mul_21(), fb_mul_41(), fb_mul_42(), fb_mul_420(), fb_mul_51(), fb_mul_beta(), fb_rdc_basic(), and fb_read().
void fb_lshd_low (dig_t * c, const dig_t * a, int digits)
Shifts a digit vector to the left by some digits. Computes c = a * z^(digits * DIGIT).
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] digits - the shift amount.
Referenced by fb_lsh(), and fb_mul_beta().
dig_t fb_rsh1_low (dig_t * c, const dig_t * a)
Shifts a digit vector to the right by 1 bit. Computes c = a / z.
Parameters
[out] c - the result
[in] a - the digit vector to shift.
Returns
the carry of the last digit shift.
Referenced by fb_rsh().
dig_t fb_rshb_low (dig_t * c, const dig_t * a, int bits)
Shifts a digit vector to the right by an amount smaller than a digit. The shift amount must be bigger than 0 and smaller than FB_DIGIT. Computes c = a / (z^bits).
Parameters
[out] c - the result
[in] a - the digit vector to shift.
[in] bits - the shift amount.
Returns
the carry of the last digit shift.
Referenced by fb_rsh(), and fb_write().
void fb_rshd_low (dig_t * c, const dig_t * a, int digits)
Shifts a digit vector to the right by some digits. Computes c = a / z^(digits * DIGIT).
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] digits - the shift amount.
Referenced by fb_rsh().
dig_t fb_lsha_low (dig_t * c, const dig_t * a, int bits, int size)
Adds a left-shifted digit vector to another digit vector. The shift amount must be shorter than the digit size. Computes c = c + (a * z^bits).
Parameters
[out] c - the result.
[in] a - the first digit vector to shift and add.
[in] size - the number of digits to add.
[in] bits - the shift amount.
Returns
the carry of the last shift.
Referenced by fb_inv_exgcd().
void fb_mul1_low (dig_t * c, const dig_t * a, dig_t digit)
Multiplies a digit vector by a digit.
Parameters
[out] c - the result.
[in] a - the digit vector to multiply.
[in] digit - the digit to multiply.
Referenced by eb_mul_lodah(), and fb_mul_dig().
void fb_muln_low (dig_t * c, const dig_t * a, const dig_t * b)
Multiplies two digit vectors of the same size.
Parameters
[out] c - the result.
[in] a - the first digit vector to multiply.
[in] b - the second digit vector to multiply.
Referenced by eb_mul_lodah(), and fb_mul_lodah().
void fb_muld_low (dig_t * c, const dig_t * a, const dig_t * b, int size)
Multiplies two digit vectors of the same size but smaller than the standard precision.
Parameters
[out] c - the result.
[in] a - the first digit vector to multiply.
[in] b - the second digit vector to multiply.
[in] size - the size of the digit vectors.
Referenced by fb_mul_karat_imp().
void fb_mulm_low (dig_t * c, const dig_t * a, const dig_t * b)
Multiplies two digit vectors of the same size with embedded modular reduction.
Parameters
[out] c - the result.
[in] a - the first digit vector to multiply.
[in] b - the second digit vector to multiply.
Referenced by fb_mul_integ().
void fb_sqrn_low (dig_t * c, const dig_t * a)
Squares a digit vector using bit manipulation.
Parameters
[out] c - the result.
[in] a - the digit vector to square.
Referenced by fb_sqr_basic().
void fb_sqrl_low (dig_t * c, const dig_t * a)
Squares a digit vector using a lookup table.
Parameters
[out] c - the result.
[in] a - the digit vector to square.
Referenced by eb_mul_lodah(), and fb_sqr_table().
void fb_sqrm_low (dig_t * c, const dig_t * a)
Squares a digit vector with embedded modular reduction.
Parameters
[out] c - the result.
[in] a - the digit vector to square.
Referenced by fb_sqr_integ().
void fb_itrn_low (dig_t * c, const dig_t * a, dig_t * t)
Exponentiates consecutively a digit vector to a fixed power 2^k/2^-k given a precomputed table.
Parameters
[out] c - the result.
[in] a - the digit vector to square.
[in] t - the
Referenced by fb_itr_quick().
void fb_srtn_low (dig_t * c, const dig_t * a)
Extracts the square root of a digit vector.
Parameters
[out] c - the result.
[in] a - the digit vector to extract the square root.
Referenced by fb_srt_quick().
void fb_slvn_low (dig_t * c, const dig_t * a)
Solves a quadratic equation for c^2 + c = a.
Parameters
[out] c - the result.
[in] a - the digit vector.
Referenced by fb_slv_quick().
dig_t fb_trcn_low (const dig_t * a)
Computes the trace of a digit vector.
Parameters
[in] a - the digit vector.
Returns
the trace of the argument.
Referenced by fb_trc_quick().
void fb_rdcn_low (dig_t * c, dig_t * a)
Reduces a digit vector modulo the configured irreducible polynomial.
Parameters
[out] c - the result.
[in] a - the digit vector to reduce.
Referenced by eb_mul_lodah(), and fb_rdc_quick().
void fb_rdc1_low (dig_t * c, dig_t * a)
Reduces the most significant bits of a digit vector modulo the configured irreducible polynomial. The maximum number of bits to be reduced is equal to the size of the digit.
Parameters
[out] c - the result.
[in] a - the digit vector to reduce.
Referenced by fb4_mul_dxd(), fb_mul_21(), fb_mul_41(), fb_mul_42(), fb_mul_420(), fb_mul_51(), fb_mul_beta(), and fb_mul_dig().
void fb_invn_low (dig_t * c, const dig_t * a)
Inverts a digit vector modulo the configured irreducible polynomial.
Parameters
[out] c - the result.
[in] a - the digit vector to invert.
Referenced by fb_inv_lower().