RELIC: src/fbx/relic_fbx_frb.c File Reference
relic_fbx_frb.c File Reference
Extensions of binary fields.
#include "relic_core.h"
#include "relic_fbx.h"
Functions
void fb4_frb (fb4_t c, fb4_t a)
Detailed Description
Implementation of frobenius action in binary fields extensions.
Version
Id:
relic_fbx_frb.c 1489 2013-06-02 18:33:31Z dfaranha
Definition in file relic_fbx_frb.c.
Function Documentation
void fb4_frb (fb4_t c, fb4_t a)
Computes the q-th power Frobenius map of a quartic extension field element. Compute c = a^{2^m}.
Parameters
[out] c - the result.
[in] a - the quartic extension element to exponentiate.
Definition at line 39 of file relic_fbx_frb.c.
References fb_add(), FB_BITS, and fb_copy().
Referenced by etat_exp().