RELIC: src/cp/relic_cp_ecss.c File Reference
relic_cp_ecss.c File Reference
Cryptographic protocols.
#include "relic.h"
#include "relic_test.h"
Functions
void cp_ecss_gen (bn_t d, ec_t q)
void cp_ecss_sig (bn_t e, bn_t s, unsigned char *msg, int len, bn_t d)
int cp_ecss_ver (bn_t e, bn_t s, unsigned char *msg, int len, ec_t q)
Detailed Description
Implementation of the Schnorr protocol.
Version
Id:
relic_cp_ecss.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_cp_ecss.c.
Function Documentation
void cp_ecss_gen (bn_t d, ec_t q)
Generates an Elliptic Curve Schnorr Signature key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Definition at line 39 of file relic_cp_ecss.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ec_curve_get_ord, ec_mul_gen, ERR_CAUGHT, FINALLY, THROW, and TRY.
void cp_ecss_sig (bn_t e, bn_t s, unsigned char * msg, int len, bn_t d)
Signs a message using the Elliptic Curve Schnorr Signature.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] d - the private key.
Definition at line 64 of file relic_cp_ecss.c.
References bn_add(), bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_mul, bn_new, bn_null, BN_POS, bn_rand(), bn_read_bin(), bn_rsh(), bn_sub(), bn_write_bin(), CATCH_ANY, CEIL, EC_BYTES, ec_curve_get_ord, ec_free, ec_get_x, ec_mul_gen, ec_new, ec_null, ERR_CAUGHT, FINALLY, MD_LEN, md_map, THROW, and TRY.
int cp_ecss_ver (bn_t e, bn_t s, unsigned char * msg, int len, ec_t q)
Verifies a message signed with the Elliptic Curve Schnorr Signature using the basic method.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] q - the public key.
Definition at line 127 of file relic_cp_ecss.c.
References bn_bits(), bn_cmp(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_read_bin(), bn_rsh(), bn_sign(), bn_write_bin(), CATCH_ANY, CEIL, CMP_LT, CMP_NE, dv_cmp_const(), EC_BYTES, ec_curve_get_ord, ec_free, ec_get_x, ec_mul_sim_gen, ec_new, ec_null, ERR_CAUGHT, FINALLY, MD_LEN, md_map, MIN, THROW, and TRY.