RELIC: src/fbx/relic_fbx_sqr.c File Reference
relic_fbx_sqr.c File Reference
Extensions of binary fields.
#include "relic_core.h"
#include "relic_fbx.h"
Functions
void fb2_sqr (fb2_t c, fb2_t a)
void fb4_sqr (fb4_t c, fb4_t a)
Detailed Description
Implementation of squaring in binary fields extensions.
Version
Id:
relic_fbx_sqr.c 1489 2013-06-02 18:33:31Z dfaranha
Definition in file relic_fbx_sqr.c.
Function Documentation
void fb2_sqr (fb2_t c, fb2_t a)
Computes the square of a quadratic extension field element. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the binary field element to square.
Definition at line 39 of file relic_fbx_sqr.c.
References fb_add(), and fb_sqr.
Referenced by fb4_inv().
void fb4_sqr (fb4_t c, fb4_t a)
Computes the square of a quartic extension field element. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to square.
Definition at line 45 of file relic_fbx_sqr.c.
References fb_add(), and fb_sqr.
Referenced by etat_exp(), fb4_exp(), and pb_map_etatn_imp().