RELIC: src/relic_core.c File Reference
relic_core.c File Reference
Core functions.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "relic_core.h"
#include "relic_rand.h"
#include "relic_types.h"
#include "relic_err.h"
#include "relic_arch.h"
#include "relic_fp.h"
#include "relic_fb.h"
#include "relic_ep.h"
#include "relic_eb.h"
#include "relic_cp.h"
#include "relic_pp.h"
Functions
int core_init (void)
int core_clean (void)
ctx_t * core_get ()
void core_set (ctx_t *ctx)
Variables
ctx_t first_ctx
ctx_t * core_ctx = NULL
Detailed Description
Implementation of the library basic functions.
Version
Id:
relic_core.c 1522 2013-08-27 15:55:54Z dfaranha
Definition in file relic_core.c.
Function Documentation
int core_init (void)
Initializes the library.
Returns
STS_OK if no error occurs, STS_ERR otherwise.
Definition at line 66 of file relic_core.c.
References arch_init(), CATCH_ANY, _ctx_t::code, eb_curve_init(), ep_curve_init(), ERR_NO_BUFFER, ERR_NO_CONFIG, ERR_NO_CURVE, ERR_NO_FIELD, ERR_NO_FILE, ERR_NO_MEMORY, ERR_NO_PRECI, ERR_NO_READ, ERR_NO_VALID, fb_poly_init(), first_ctx, fp_prime_init(), _ctx_t::last, MSG_NO_BUFFER, MSG_NO_CONFIG, MSG_NO_CURVE, MSG_NO_FIELD, MSG_NO_FILE, MSG_NO_MEMORY, MSG_NO_PRECI, MSG_NO_READ, MSG_NO_VALID, pb_map_init(), pp_map_init(), rand_init(), _ctx_t::reason, STS_ERR, STS_OK, _ctx_t::trace, and TRY.
int core_clean (void)
Finalizes the library.
Returns
STS_OK if no error occurs, STS_ERR otherwise.
Definition at line 130 of file relic_core.c.
References arch_clean(), eb_curve_clean(), ep_curve_clean(), fb_poly_clean(), fp_prime_clean(), pb_map_clean(), pp_map_clean(), rand_clean(), and STS_OK.
ctx_t* core_get (void)
Returns a pointer to the current library context.
Returns
a pointer to the library context.
Definition at line 159 of file relic_core.c.
References core_ctx.
Referenced by bench_after(), bench_before(), bench_compute(), bench_print(), bench_reset(), bench_total(), compute_kbltz(), eb_curve_clean(), eb_curve_get_a(), eb_curve_get_b(), eb_curve_get_c(), eb_curve_get_cof(), eb_curve_get_gen(), eb_curve_get_ord(), eb_curve_get_s0(), eb_curve_get_s1(), eb_curve_get_tab(), eb_curve_get_vm(), eb_curve_init(), eb_curve_is_kbltz(), eb_curve_is_super(), eb_curve_opt_a(), eb_curve_opt_b(), eb_curve_opt_c(), eb_curve_set_kbltz(), eb_curve_set_ordin(), eb_curve_set_super(), eb_param_get(), eb_param_level(), eb_param_print(), eb_param_set(), ep2_curve_clean(), ep2_curve_get_a(), ep2_curve_get_b(), ep2_curve_get_gen(), ep2_curve_get_ord(), ep2_curve_get_tab(), ep2_curve_init(), ep2_curve_is_twist(), ep2_curve_set(), ep_curve_clean(), ep_curve_get_a(), ep_curve_get_b(), ep_curve_get_beta(), ep_curve_get_cof(), ep_curve_get_gen(), ep_curve_get_ord(), ep_curve_get_tab(), ep_curve_get_v1(), ep_curve_get_v2(), ep_curve_init(), ep_curve_is_kbltz(), ep_curve_is_super(), ep_curve_opt_a(), ep_curve_opt_b(), ep_curve_set_kbltz(), ep_curve_set_ordin(), ep_curve_set_super(), ep_param_get(), ep_param_set(), err_full_msg(), err_get_code(), err_get_msg(), err_simple_msg(), fb_param_get(), fb_param_set(), fb_poly_add(), fb_poly_get(), fb_poly_get_chain(), fb_poly_get_rdc(), fb_poly_get_slv(), fb_poly_get_srz(), fb_poly_get_trc(), fb_poly_init(), fb_poly_set(), fb_poly_set_dense(), fb_poly_set_penta(), fb_poly_set_trino(), fb_poly_tab_sqr(), fb_poly_tab_srz(), find_chain(), find_solve(), find_srz(), find_trace(), fp2_calc(), fp2_mul_frb(), fp3_calc(), fp3_mul_frb(), fp_param_get(), fp_param_set(), fp_prime_clean(), fp_prime_conv(), fp_prime_conv_dig(), fp_prime_get(), fp_prime_get_cnr(), fp_prime_get_conv(), fp_prime_get_mod8(), fp_prime_get_qnr(), fp_prime_get_rdc(), fp_prime_get_sps(), fp_prime_init(), fp_prime_set(), fp_prime_set_dense(), fp_prime_set_pmers(), pb_map_get_sqr(), pb_map_get_srt(), pb_map_get_tab(), pb_map_init(), rand_bytes(), rand_clean(), rand_init(), and rand_seed().
void core_set (ctx_t * ctx)
Switched the library context to a new context.
Parameters
[in] ctx - the new library context.
Definition at line 163 of file relic_core.c.
Variable Documentation
ctx_t first_ctx
Default library context.
Definition at line 55 of file relic_core.c.
Referenced by core_init().
ctx_t* core_ctx = NULL
Active library context.
Definition at line 60 of file relic_core.c.
Referenced by core_get(), trace_enter(), and trace_exit().