RELIC: src/fb/relic_fb_poly.c File Reference
relic_fb_poly.c File Reference
Binary field arithmetic.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_dv.h"
#include "relic_fb.h"
#include "relic_pb.h"
#include "relic_fb_low.h"
Functions
static void find_trace ()
static void find_solve ()
static void find_srz ()
static void find_chain ()
static void fb_poly_set (const fb_t f)
void fb_poly_init (void)
void fb_poly_clean (void)
dig_t * fb_poly_get (void)
void fb_poly_add (fb_t c, const fb_t a)
void fb_poly_sub (fb_t c, const fb_t a)
void fb_poly_set_dense (const fb_t f)
void fb_poly_set_trino (int a)
void fb_poly_set_penta (int a, int b, int c)
dig_t * fb_poly_get_srz (void)
const fb_t * fb_poly_tab_sqr (int i)
const dig_t * fb_poly_tab_srz (int i)
void fb_poly_get_trc (int *a, int *b, int *c)
void fb_poly_get_rdc (int *a, int *b, int *c)
const dig_t * fb_poly_get_slv ()
const int * fb_poly_get_chain (int *len)
Detailed Description
Implementation of the binary field modulus manipulation.
Version
Id:
relic_fb_poly.c 1572 2013-09-02 07:11:29Z dfaranha
Definition in file relic_fb_poly.c.
Function Documentation
static void find_trace () static
Find non-zero bits for fast trace computation.
Exceptions
ERR_NO_MEMORY if there is no available memory.
ERR_NO_VALID if the polynomial is invalid.
Definition at line 55 of file relic_fb_poly.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, ERR_NO_VALID, fb_add(), FB_BITS, fb_copy(), fb_free, fb_is_zero(), fb_new, fb_null, fb_set_bit(), fb_sqr, _ctx_t::fb_ta, _ctx_t::fb_tb, _ctx_t::fb_tc, fb_zero(), FINALLY, THROW, and TRY.
Referenced by fb_poly_set().
static void find_solve () static
Precomputes half-traces for z^i with odd i.
Exceptions
ERR_NO_MEMORY if there is no available memory.
Definition at line 117 of file relic_fb_poly.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, fb_add(), FB_BITS, fb_copy(), fb_free, _ctx_t::fb_half, fb_new, fb_null, fb_rsh(), fb_set_bit(), fb_sqr, fb_zero(), FINALLY, THROW, and TRY.
Referenced by fb_poly_set().
static void find_srz () static
Precomputes the square root of z.
Definition at line 161 of file relic_fb_poly.c.
References core_get(), FB_BITS, fb_mul_dig(), fb_set_dig(), fb_sqr, _ctx_t::fb_srz, and _ctx_t::fb_tab_srz.
Referenced by fb_poly_set().
static void find_chain () static
Finds an addition chain for (FB_BITS - 1).
Definition at line 184 of file relic_fb_poly.c.
References _ctx_t::chain, _ctx_t::chain_len, core_get(), FB_BITS, fb_itr_pre, fb_poly_tab_sqr(), _ctx_t::fb_tab_ptr, _ctx_t::fb_tab_sqr, FB_TABLE, and MAX_TERMS.
Referenced by fb_poly_set().
static void fb_poly_set (const fb_t f) static
Configures the irreducible polynomial of the binary field.
Parameters
[in] f - the new irreducible polynomial.
Definition at line 297 of file relic_fb_poly.c.
References core_get(), fb_copy(), find_chain(), find_solve(), find_srz(), find_trace(), and pb_map_init().
Referenced by fb_poly_set_dense(), fb_poly_set_penta(), and fb_poly_set_trino().
void fb_poly_init (void)
Initializes the binary field arithmetic layer.
Definition at line 322 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, _ctx_t::fb_poly, and fb_zero().
Referenced by core_init().
void fb_poly_clean (void)
Finalizes the binary field arithmetic layer.
Definition at line 330 of file relic_fb_poly.c.
Referenced by core_clean().
dig_t* fb_poly_get (void)
Returns the irreducible polynomial f(z) configured for the binary field.
Returns
the irreducible polynomial.
Definition at line 333 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_poly.
Referenced by fb_inv_almos(), fb_inv_binar(), fb_inv_bruch(), fb_inv_exgcd(), and fb_rdc_basic().
void fb_poly_add (fb_t c, const fb_t a)
Adds a binary field element and the irreducible polynomial. Computes c = a + f(z).
Parameters
[out] c - the destination.
[in] a - the binary field element.
Definition at line 337 of file relic_fb_poly.c.
References core_get(), fb_add(), fb_copy(), FB_DIGS, _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, and _ctx_t::fb_poly.
Referenced by fb_inv_almos(), fb_inv_binar(), fb_mul_basic(), and fb_poly_sub().
void fb_poly_sub (fb_t c, const fb_t a)
Subtracts the irreducible polynomial from a binary field element. Computes c = a - f(z).
Parameters
[out] c - the destination.
[in] a - the binary field element.
Definition at line 365 of file relic_fb_poly.c.
References fb_poly_add().
void fb_poly_set_dense (const fb_t f)
Configures the irreducible polynomial of the binary field as a dense polynomial.
Parameters
[in] f - the new irreducible polynomial.
Definition at line 369 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, and fb_poly_set().
void fb_poly_set_trino (int a)
Configures a trinomial as the irreducible polynomial by its non-zero coefficients. The other coefficients are FB_BITS and 0.
Parameters
[in] a - the second coefficient.
Definition at line 376 of file relic_fb_poly.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FB_BITS, FB_DIG_LOG, fb_free, _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, fb_new, fb_null, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, fb_poly_set(), fb_set_bit(), fb_zero(), FINALLY, THROW, and TRY.
Referenced by fb_param_set().
void fb_poly_set_penta (int a, int b, int c)
Configures a pentanomial as the binary field modulo by its non-zero coefficients. The other coefficients are FB_BITS and 0.
Parameters
[in] a - the second coefficient.
[in] b - the third coefficient.
[in] c - the fourth coefficient.
Definition at line 404 of file relic_fb_poly.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FB_BITS, FB_DIG_LOG, fb_free, _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, fb_new, fb_null, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, fb_poly_set(), fb_set_bit(), fb_zero(), FINALLY, THROW, and TRY.
Referenced by fb_param_set().
dig_t* fb_poly_get_srz (void)
Returns the square root of z.
Returns
the square root of z.
Definition at line 437 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_srz.
const fb_t* fb_poly_tab_sqr (int i)
Returns a table for accelerating repeated squarings.
Parameters
the number of the table.
Returns
the precomputed result.
Definition at line 445 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_tab_ptr.
Referenced by fb_inv_itoht(), and find_chain().
const dig_t* fb_poly_tab_srz (int i)
Returns sqrt(z) * (i represented as a polynomial).
Returns
the precomputed result.
Definition at line 459 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_tab_srz.
void fb_poly_get_trc (int * a, int * b, int * c)
Returns the non-zero bits used to compute the trace function. The -1 coefficient is the last coefficient.
Parameters
[out] a - the first coefficient.
[out] b - the second coefficient.
[out] c - the third coefficient.
Definition at line 473 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_ta, _ctx_t::fb_tb, and _ctx_t::fb_tc.
void fb_poly_get_rdc (int * a, int * b, int * c)
Returns the non-zero coefficients of the configured trinomial or pentanomial. If b is -1, the irreducible polynomial configured is a trinomial. The other coefficients are FB_BITS and 0.
Parameters
[out] a - the second coefficient.
[out] b - the third coefficient.
[out] c - the fourth coefficient.
Definition at line 484 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_pa, _ctx_t::fb_pb, and _ctx_t::fb_pc.
Referenced by fb_param_print().
const dig_t* fb_poly_get_slv (void)
Returns the table of precomputed half-traces.
Returns
the table of half-traces.
Definition at line 491 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_half.
const int* fb_poly_get_chain (int * len)
Returns an addition chain for (FB_BITS - 1).
Parameters
[out] len - the number of elements in the addition chain.
Returns
a pointer to the addition chain.
Definition at line 499 of file relic_fb_poly.c.
References _ctx_t::chain, _ctx_t::chain_len, core_get(), and MAX_TERMS.
Referenced by fb_inv_itoht().