RELIC: src/eb/relic_eb_add.c File Reference
relic_eb_add.c File Reference
Elliptic curves over binary fields.
#include "string.h"
#include "relic_core.h"
#include "relic_eb.h"
Functions
static void eb_add_basic_ordin (eb_t r, const eb_t p, const eb_t q)
static void eb_add_basic_super (eb_t r, const eb_t p, const eb_t q)
static void eb_add_projc_ordin_mix (eb_t r, const eb_t p, const eb_t q)
static void eb_add_projc_ordin (eb_t r, const eb_t p, const eb_t q)
static void eb_add_projc_super_mix (eb_t r, const eb_t p, const eb_t q)
static void eb_add_projc_super (eb_t r, const eb_t p, const eb_t q)
void eb_add_basic (eb_t r, const eb_t p, const eb_t q)
void eb_sub_basic (eb_t r, const eb_t p, const eb_t q)
void eb_add_projc (eb_t r, const eb_t p, const eb_t q)
void eb_sub_projc (eb_t r, const eb_t p, const eb_t q)
Detailed Description
Implementation of point addition on binary elliptic curves.
Version
Id:
relic_eb_add.c 1573 2013-09-02 07:17:18Z dfaranha
Definition in file relic_eb_add.c.
Function Documentation
static void eb_add_basic_ordin (eb_t r, const eb_t p, const eb_t q) static
Adds two points represented in affine coordinates on an ordinary binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 53 of file relic_eb_add.c.
References CATCH_ANY, eb_curve_get_a(), eb_curve_opt_a(), eb_dbl_basic(), eb_set_infty(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_free, fb_inv, fb_is_zero(), fb_mul, fb_new, fb_null, fb_sqr, FINALLY, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by eb_add_basic().
static void eb_add_basic_super (eb_t r, const eb_t p, const eb_t q) static
Adds two points represented in affine coordinates on a supersingular binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 138 of file relic_eb_add.c.
References CATCH_ANY, eb_curve_get_c(), eb_curve_opt_c(), eb_dbl_basic(), eb_set_infty(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_free, fb_inv, fb_is_zero(), fb_mul, fb_new, fb_null, fb_sqr, FINALLY, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by eb_add_basic().
static void eb_add_projc_ordin_mix (eb_t r, const eb_t p, const eb_t q) static
Adds a point represented in affine coordinates to a point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the affine point.
[in] q - the projective point.
Definition at line 228 of file relic_eb_add.c.
References CATCH_ANY, eb_curve_get_a(), eb_curve_opt_a(), eb_dbl_projc(), eb_set_infty(), ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_is_zero(), fb_mul, fb_mul_dig(), fb_new, fb_null, fb_sqr, FINALLY, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by eb_add_projc_ordin().
static void eb_add_projc_ordin (eb_t r, const eb_t p, const eb_t q) static
Adds two points represented in projective coordinates on an ordinary binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 364 of file relic_eb_add.c.
References CATCH_ANY, eb_add_projc_ordin_mix(), eb_dbl_projc(), eb_set_infty(), ERR_CAUGHT, fb_add(), fb_free, fb_is_zero(), fb_mul, fb_new, fb_null, fb_sqr, FINALLY, THROW, and TRY.
Referenced by eb_add_projc().
static void eb_add_projc_super_mix (eb_t r, const eb_t p, const eb_t q) static
Adds two points represented in projective coordinates on a supersingular binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 497 of file relic_eb_add.c.
References CATCH_ANY, eb_dbl_projc(), eb_set_infty(), ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_is_zero(), fb_mul, fb_new, fb_null, fb_sqr, FINALLY, THROW, and TRY.
Referenced by eb_add_projc_super().
static void eb_add_projc_super (eb_t r, const eb_t p, const eb_t q) static
Adds two points represented in projective coordinates on a supersingular binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 614 of file relic_eb_add.c.
References CATCH_ANY, eb_add_projc_super_mix(), eb_dbl_projc(), eb_set_infty(), ERR_CAUGHT, fb_add(), fb_free, fb_is_zero(), fb_mul, fb_new, fb_null, fb_sqr, FINALLY, THROW, and TRY.
Referenced by eb_add_projc().
void eb_add_basic (eb_t r, const eb_t p, const eb_t q)
Adds two binary elliptic curve points represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 730 of file relic_eb_add.c.
References eb_add_basic_ordin(), eb_add_basic_super(), eb_copy(), eb_curve_is_super(), and eb_is_infty().
Referenced by eb_sub_basic().
void eb_sub_basic (eb_t r, const eb_t p, const eb_t q)
Subtracts a binary elliptic curve point from another, both points represented by affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 752 of file relic_eb_add.c.
References CATCH_ANY, eb_add_basic(), eb_free, eb_neg_basic(), eb_new, eb_null, eb_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_add_projc (eb_t r, const eb_t p, const eb_t q)
Adds two binary elliptic curve points represented in projective coordinates. Computes R = P + Q.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 782 of file relic_eb_add.c.
References eb_add_projc_ordin(), eb_add_projc_super(), eb_copy(), eb_curve_is_super(), and eb_is_infty().
Referenced by eb_sub_projc().
void eb_sub_projc (eb_t r, const eb_t p, const eb_t q)
Subtracts a binary elliptic curve point from another, both points represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 804 of file relic_eb_add.c.
References CATCH_ANY, eb_add_projc(), eb_free, eb_neg_projc(), eb_new, eb_null, eb_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.