RELIC: include/relic_rand.h File Reference
relic_rand.h File Reference
Pseudo-random number generator.
#include "relic_rand.h"
Macros
#define RAND_SIZE 64
Functions
void rand_init (void)
void rand_clean (void)
void rand_seed (unsigned char *buf, int size)
void rand_bytes (unsigned char *buf, int size)
Detailed Description
Interface of the module for pseudo-random number generation.
Version
Id:
relic_rand.h 1523 2013-08-27 16:12:11Z dfaranha
Definition in file relic_rand.h.
Macro Definition Documentation
#define RAND_SIZE 64
Size of the PRNG internal state in bytes.
Definition at line 48 of file relic_rand.h.
Referenced by rand_bytes(), and rand_init().
Function Documentation
void rand_init (void)
Initializes the pseudo-random number generator.
Definition at line 88 of file relic_rand.c.
References core_get(), ERR_NO_FILE, ERR_NO_READ, RAND_PATH, rand_seed(), RAND_SIZE, SEED_SIZE, and THROW.
Referenced by core_init().
void rand_clean (void)
Finishes the pseudo-random number generator.
Definition at line 149 of file relic_rand.c.
References core_get().
Referenced by core_clean().
void rand_seed (unsigned char * buf, int size)
Sets the initial state of the pseudo-random number generator.
Parameters
[in] buf - the buffer that represents the initial state.
[in] size - the number of bytes.
Definition at line 153 of file relic_rand.c.
References core_get(), ERR_NO_VALID, MIN, _ctx_t::rand, SEED_SIZE, and THROW.
Referenced by rand_init().
void rand_bytes (unsigned char * buf, int size)
Writes size pseudo-random bytes in the passed buffer.
Parameters
[out] buf - the buffer to write.
[in] size - the number of bytes to write.
Exceptions
ERR_NO_READ - it the pseudo-random number generator can't generate the specified number of bytes.
Definition at line 170 of file relic_rand.c.
References core_get(), MD_LEN_SHONE, md_map_shone_mid(), _ctx_t::rand, RAND_SIZE, and SEED_SIZE.
Referenced by bn_rand(), fb_rand(), fp_rand(), and pad_pkcs1().