RELIC: src/cp/relic_cp_rabin.c File Reference
relic_cp_rabin.c File Reference
Cryptographic protocols.
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_rand.h"
#include "relic_bn.h"
#include "relic_util.h"
#include "relic_cp.h"
#include "relic_md.h"
Macros
#define RABIN_PAD_LEN 8
#define RABIN_PAD (0xFF)
Functions
int cp_rabin_gen (rabin_t pub, rabin_t prv, int bits)
int cp_rabin_enc (unsigned char *out, int *out_len, unsigned char *in, int in_len, rabin_t pub)
int cp_rabin_dec (unsigned char *out, int *out_len, unsigned char *in, int in_len, rabin_t prv)
Detailed Description
Implementation of the Rabin cryptosystem.
Version
Id:
relic_cp_rabin.c 1527 2013-08-27 16:58:36Z dfaranha
Definition in file relic_cp_rabin.c.
Macro Definition Documentation
#define RABIN_PAD_LEN 8
Length in bytes of added redundancy.
Definition at line 49 of file relic_cp_rabin.c.
Referenced by cp_rabin_dec(), and cp_rabin_enc().
#define RABIN_PAD (0xFF)
Byte used as padding unit in signatures.
Definition at line 54 of file relic_cp_rabin.c.
Referenced by cp_rabin_dec(), and cp_rabin_enc().
Function Documentation
int cp_rabin_gen (rabin_t pub, rabin_t prv, int bits)
Generates a new key pair for the Rabin cryptosystem.
Parameters
[out] pub - the public key.
[out] prv - the private key,
[in] bits - the key length in bits.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 60 of file relic_cp_rabin.c.
References bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_gen_prime, bn_mod_2b(), bn_mul, bn_new, bn_null, CATCH_ANY, CMP_EQ, CMP_LT, FINALLY, STS_ERR, STS_OK, and TRY.
int cp_rabin_enc (unsigned char * out, int * out_len, unsigned char * in, int in_len, rabin_t pub)
Encrypts using the Rabin cryptosystem.
Parameters
[out] out - the output buffer.
[out] out_len - the number of bytes written in the output buffer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] pub - the public key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 105 of file relic_cp_rabin.c.
References bn_add(), bn_add_dig(), bn_free, bn_lsh(), bn_mod, bn_mod_2b(), bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_sqr, bn_write_bin(), bn_zero(), CATCH_ANY, FINALLY, RABIN_PAD, RABIN_PAD_LEN, STS_ERR, STS_OK, and TRY.
int cp_rabin_dec (unsigned char * out, int * out_len, unsigned char * in, int in_len, rabin_t prv)
Decrypts using the Rabin cryptosystem.
Parameters
[out] out - the output buffer.
[out] out_len - the number of bytes written in the output buffer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] prv - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 156 of file relic_cp_rabin.c.
References bn_add(), bn_add_dig(), bn_cmp(), bn_free, bn_is_zero(), bn_mod, bn_mod_2b(), bn_mul, bn_mxp, BN_NEG, bn_new, bn_null, bn_read_bin(), bn_rsh(), bn_sign(), bn_size_bin(), bn_sub(), bn_write_bin(), CATCH_ANY, CMP_EQ, FINALLY, RABIN_PAD, RABIN_PAD_LEN, STS_ERR, STS_OK, and TRY.