RELIC: src/eb/relic_eb_mul_sim.c File Reference
relic_eb_mul_sim.c File Reference
Elliptic curves over binary fields.
#include "string.h"
#include "relic_core.h"
#include "relic_eb.h"
#include "relic_util.h"
Functions
static void eb_mul_sim_kbltz (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m, const eb_t *t)
static void eb_mul_sim_ordin (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m, const eb_t *t)
void eb_mul_sim_basic (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_trick (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_inter (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_joint (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
void eb_mul_sim_gen (eb_t r, const bn_t k, const eb_t q, const bn_t m)
Detailed Description
Implementation of simultaneous point multiplication on binary elliptic curves.
Version
Id:
relic_eb_mul_sim.c 1566 2013-09-02 04:09:52Z dfaranha
Definition in file relic_eb_mul_sim.c.
Function Documentation
static void eb_mul_sim_kbltz (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m, const eb_t * t) static
Multiplies and adds two binary elliptic curve points simultaneously, optionally choosing the first point as the generator depending on an optional table of precomputed points.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
[in] t - the pointer to a precomputed table.
Definition at line 59 of file relic_eb_mul_sim.c.
References bn_free, bn_new, bn_null, bn_rec_tnaf(), CATCH_ANY, eb_add, eb_curve_get_s0(), eb_curve_get_s1(), eb_curve_get_vm(), eb_curve_opt_a(), EB_DEPTH, eb_frb, eb_free, eb_new, eb_norm(), eb_null, eb_set_infty(), eb_sub, eb_tab(), EB_WIDTH, ERR_CAUGHT, FB_BITS, fb_set_bit(), FINALLY, MAX, OPT_ZERO, THROW, and TRY.
Referenced by eb_mul_sim_gen(), and eb_mul_sim_inter().
static void eb_mul_sim_ordin (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m, const eb_t * t) static
Multiplies and adds two binary elliptic curve points simultaneously, optionally choosing the first point as the generator depending on an optional table of precomputed points.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
[in] t - the pointer to a precomputed table.
Definition at line 190 of file relic_eb_mul_sim.c.
References bn_rec_naf(), CATCH_ANY, eb_add, eb_dbl, EB_DEPTH, eb_free, eb_new, eb_norm(), eb_null, eb_set_infty(), eb_sub, eb_tab(), EB_WIDTH, ERR_CAUGHT, FB_BITS, FINALLY, MAX, THROW, and TRY.
Referenced by eb_mul_sim_gen(), and eb_mul_sim_inter().
void eb_mul_sim_basic (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 288 of file relic_eb_mul_sim.c.
References CATCH_ANY, eb_add, eb_free, eb_mul, eb_new, eb_norm(), eb_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
void eb_mul_sim_trick (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 313 of file relic_eb_mul_sim.c.
References bn_free, bn_new, bn_null, bn_rec_win(), CATCH_ANY, CEIL, eb_add, eb_curve_get_ord(), eb_dbl, eb_free, eb_new, eb_norm(), eb_norm_sim(), eb_null, eb_set_infty(), EB_WIDTH, ERR_CAUGHT, FB_BITS, FINALLY, MAX, THROW, and TRY.
void eb_mul_sim_inter (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 401 of file relic_eb_mul_sim.c.
References eb_curve_is_kbltz(), eb_mul_sim_kbltz(), and eb_mul_sim_ordin().
void eb_mul_sim_joint (eb_t r, const eb_t p, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds two binary elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 419 of file relic_eb_mul_sim.c.
References bn_bits(), bn_rec_jsf(), CATCH_ANY, eb_add, eb_copy(), eb_dbl, eb_free, eb_new, eb_norm(), eb_norm_sim(), eb_null, eb_set_infty(), eb_sub, ERR_CAUGHT, FB_BITS, FINALLY, MAX, THROW, and TRY.
void eb_mul_sim_gen (eb_t r, const bn_t k, const eb_t q, const bn_t m)
Multiplies and adds the generator and a binary elliptic curve point simultaneously. Computes R = kG + mQ.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
Definition at line 484 of file relic_eb_mul_sim.c.
References CATCH_ANY, eb_curve_get_gen(), eb_curve_get_tab(), eb_curve_is_kbltz(), eb_free, eb_mul_sim, eb_mul_sim_kbltz(), eb_mul_sim_ordin(), eb_new, eb_null, ERR_CAUGHT, FINALLY, THROW, and TRY.