RELIC: src/fpx/relic_fp2_mul.c File Reference
relic_fp2_mul.c File Reference
Extensions of prime fields.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_pp_low.h"
Functions
void fp2_mul_frb (fp2_t c, fp2_t a, int i, int j)
void fp2_mul_basic (fp2_t c, fp2_t a, fp2_t b)
void fp2_mul_nor_basic (fp2_t c, fp2_t a)
void fp2_mul_integ (fp2_t c, fp2_t a, fp2_t b)
void fp2_mul_nor_integ (fp2_t c, fp2_t a)
void fp2_mul_art (fp2_t c, fp2_t a)
Detailed Description
Implementation of multiplication in a quadratic extension of a prime field.
Version
Id:
relic_fp2_mul.c 1491 2013-06-02 19:18:37Z dfaranha
Definition in file relic_fp2_mul.c.
Function Documentation
void fp2_mul_frb (fp2_t c, fp2_t a, int i, int j)
Multiplies a quadratic extension field element by a power of the constant needed to compute a power of the Frobenius map.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
Definition at line 40 of file relic_fp2_mul.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp2_free, fp2_mul, fp2_new, fp2_null, _ctx_t::fp2_p, _ctx_t::fp2_p2, _ctx_t::fp2_p3, fp_copy(), fp_mul, THROW, and TRY.
Referenced by ep2_frb(), fp12_frb(), and fp6_frb().
void fp2_mul_basic (fp2_t c, fp2_t a, fp2_t b)
Multiples two quadratic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 81 of file relic_fp2_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, FINALLY, fp_add, fp_addc_low(), fp_muln_low(), fp_prime_get_qnr(), fp_rdc, fp_subc_low(), THROW, and TRY.
void fp2_mul_nor_basic (fp2_t c, fp2_t a)
Multiplies a quadratic extension field element by a quadratic/cubic non-residue.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 141 of file relic_fp2_mul.c.
References bn_free, bn_new, bn_null, CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp2_add, fp2_dbl, fp2_free, fp2_mul_art(), fp2_new, fp2_null, fp_add, fp_neg, fp_prime_get_mod8(), THROW, and TRY.
void fp2_mul_integ (fp2_t c, fp2_t a, fp2_t b)
Multiples two quadratic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 195 of file relic_fp2_mul.c.
References fp2_mulm_low().
void fp2_mul_nor_integ (fp2_t c, fp2_t a)
Multiplies a quadratic extension field element by a quadratic/cubic non-residue using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 199 of file relic_fp2_mul.c.
References fp2_norm_low().
void fp2_mul_art (fp2_t c, fp2_t a)
Multiplies a quadratic extension field element by the adjoined square root. Computes c = a * u.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 205 of file relic_fp2_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_copy(), fp_free, fp_neg, fp_new, fp_null, fp_prime_get_qnr(), fp_sub, THROW, and TRY.
Referenced by ep2_dbl_basic_imp(), ep2_frb(), fp2_mul_nor_basic(), fp6_mul0_basic(), and fp6_mul1_basic().