RELIC: src/fp/relic_fp_prime.c File Reference
relic_fp_prime.c File Reference
Prime field arithmetic.
#include "relic_core.h"
#include "relic_bn_low.h"
#include "relic_fp_low.h"
Functions
static void fp_prime_set (const bn_t p)
static void fp2_calc ()
static void fp3_calc ()
void fp_prime_init ()
void fp_prime_clean ()
const dig_t * fp_prime_get (void)
const dig_t * fp_prime_get_rdc (void)
const int * fp_prime_get_sps (int *len)
const dig_t * fp_prime_get_conv (void)
dig_t fp_prime_get_mod8 ()
int fp_prime_get_qnr ()
int fp_prime_get_cnr ()
void fp_prime_set_dense (const bn_t p)
void fp_prime_set_pmers (const int *f, int len)
void fp_prime_calc ()
void fp_prime_conv (fp_t c, const bn_t a)
void fp_prime_conv_dig (fp_t c, dig_t a)
void fp_prime_back (bn_t c, const fp_t a)
Detailed Description
Implementation of the prime field prime manipulation functions.
Version
Id:
relic_fp_prime.c 1552 2013-08-30 04:11:47Z dfaranha
Definition in file relic_fp_prime.c.
Function Documentation
static void fp_prime_set (const bn_t p) static
Assigns the prime field modulus.
Parameters
[in] p - the new prime field modulus.
Definition at line 45 of file relic_fp_prime.c.
References bn_copy(), BN_DIGIT, bn_divn_low(), bn_free, bn_lsh(), bn_mod, bn_mod_dig(), bn_mod_pre_monty(), bn_new, bn_null, bn_set_dig(), bn_trim(), CATCH_ANY, _ctx_t::cnr, _ctx_t::conv, core_get(), bn_st::dp, dv_copy(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, ERR_NO_VALID, FINALLY, FP_DIGS, fp_prime_calc(), _ctx_t::mod8, _ctx_t::one, _ctx_t::prime, _ctx_t::qnr, THROW, TRY, _ctx_t::u, and bn_st::used.
Referenced by fp_prime_set_dense(), and fp_prime_set_pmers().
static void fp2_calc () static
Computes the constantes required for evaluating Frobenius maps.
Definition at line 121 of file relic_fp_prime.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_sub_dig(), CATCH_ANY, core_get(), dv_copy(), ERR_CAUGHT, FINALLY, fp2_copy(), fp2_exp(), fp2_frb(), fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, _ctx_t::fp2_p, _ctx_t::fp2_p2, _ctx_t::fp2_p3, fp2_sqr, fp2_zero(), fp_copy(), FP_DIGS, fp_mul, fp_prime_get(), fp_set_dig(), fp_sqr, THROW, and TRY.
Referenced by fp_prime_calc().
static void fp3_calc () static
Computes the constants required for evaluating Frobenius maps.
Definition at line 190 of file relic_fp_prime.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_sub_dig(), CATCH_ANY, core_get(), dv_copy(), ERR_CAUGHT, FINALLY, _ctx_t::fp3_base, fp3_exp(), fp3_free, fp3_mul, fp3_new, fp3_null, _ctx_t::fp3_p, _ctx_t::fp3_p2, _ctx_t::fp3_p3, _ctx_t::fp3_p4, _ctx_t::fp3_p5, fp3_sqr, fp3_zero(), fp_copy(), FP_DIGS, fp_exp, fp_mul, fp_neg, fp_prime_get(), fp_prime_get_cnr(), fp_set_dig(), fp_sqr, fp_sub, THROW, and TRY.
Referenced by fp_prime_calc().
void fp_prime_init (void)
Initializes the prime field arithmetic layer.
Definition at line 296 of file relic_fp_prime.c.
References bn_init(), _ctx_t::conv, core_get(), FP_DIGS, _ctx_t::fp_id, _ctx_t::one, _ctx_t::prime, _ctx_t::sps, and _ctx_t::sps_len.
Referenced by core_init().
void fp_prime_clean (void)
Finalizes the prime field arithmetic layer.
Definition at line 307 of file relic_fp_prime.c.
References bn_clean(), _ctx_t::conv, core_get(), _ctx_t::fp_id, _ctx_t::one, _ctx_t::prime, _ctx_t::sps, and _ctx_t::sps_len.
Referenced by core_clean().
const dig_t* fp_prime_get (void)
Returns the order of the prime field.
Returns
the order of the prime field.
Definition at line 318 of file relic_fp_prime.c.
References core_get(), bn_st::dp, and _ctx_t::prime.
Referenced by fp2_calc(), fp3_calc(), fp3_srt(), fp_add_basic(), fp_add_dig(), fp_dbl_basic(), fp_hlv_basic(), fp_inv_basic(), fp_inv_binar(), fp_inv_exgcd(), fp_inv_monty(), fp_neg_basic(), fp_param_print(), fp_print(), fp_rand(), fp_rdc_basic(), fp_rdc_monty_basic(), fp_rdc_quick(), fp_srt(), fp_sub_basic(), fp_sub_dig(), and pp_exp_k2().
const dig_t* fp_prime_get_rdc (void)
Returns the additional value used for modular reduction.
Returns
the additional value used for modular reduction.
Definition at line 322 of file relic_fp_prime.c.
References core_get(), and _ctx_t::u.
Referenced by fp_rdc_monty_basic().
const int* fp_prime_get_sps (int * len)
Returns the prime stored in special form. The most significant bit is FP_BITS.
Parameters
[out] len - the number of returned bits, can be NULL.
Returns
the prime represented by it non-zero bits.
Definition at line 326 of file relic_fp_prime.c.
References core_get(), MAX_TERMS, _ctx_t::sps, and _ctx_t::sps_len.
const dig_t* fp_prime_get_conv (void)
Returns the additional value used for conversion from multiple precision integer to prime field element.
Returns
the additional value used for importing integers.
Definition at line 341 of file relic_fp_prime.c.
References _ctx_t::conv, core_get(), and bn_st::dp.
Referenced by fp_inv_monty().
dig_t fp_prime_get_mod8 (void)
Returns the result of prime order mod 8.
Returns
the result of prime order mod 8.
Definition at line 349 of file relic_fp_prime.c.
References core_get(), and _ctx_t::mod8.
Referenced by fp2_mul_nor_basic(), fp_param_set_any_tower(), and fp_srt().
int fp_prime_get_qnr (void)
Returns a non-quadratic residue in the prime field.
Returns
the non-quadratic residue.
Definition at line 353 of file relic_fp_prime.c.
References core_get(), and _ctx_t::qnr.
Referenced by fp2_inv(), fp2_mul_art(), fp2_mul_basic(), fp2_sqr_basic(), fp2_srt(), and fp_prime_calc().
int fp_prime_get_cnr (void)
Returns a non-cubic residue in the prime field.
Returns
the non-cubic residue.
Definition at line 357 of file relic_fp_prime.c.
References _ctx_t::cnr, and core_get().
Referenced by fp3_calc(), fp3_inv(), fp3_mul_basic(), fp3_sqr_basic(), fp6_mul_dxs_unr(), and fp_prime_calc().
void fp_prime_set_dense (const bn_t p)
Assigns the prime field modulus to a non-sparse prime.
Parameters
[in] p - the new prime field modulus.
Definition at line 361 of file relic_fp_prime.c.
References core_get(), ERR_NO_CONFIG, fp_prime_set(), _ctx_t::sps_len, and THROW.
Referenced by fp_param_set(), and fp_param_set_any_dense().
void fp_prime_set_pmers (const int * spars, int len)
Assigns the prime field modulus to a special form sparse prime.
Parameters
[in] spars - the list of powers of 2 describing the prime.
[in] len - the number of powers.
Definition at line 370 of file relic_fp_prime.c.
References bn_add(), bn_add_dig(), bn_free, bn_new, bn_null, bn_set_2b(), bn_sub(), bn_sub_dig(), CATCH_ANY, core_get(), ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_prime_set(), MAX_TERMS, _ctx_t::sps, _ctx_t::sps_len, THROW, and TRY.
Referenced by fp_param_set().
void fp_prime_calc (void)
Computes the constants needed for evaluating Frobenius maps in higher extension fields.
Definition at line 416 of file relic_fp_prime.c.
References fp2_calc(), fp3_calc(), fp_prime_get_cnr(), and fp_prime_get_qnr().
Referenced by ep2_curve_set(), and fp_prime_set().
void fp_prime_conv (fp_t c, const bn_t a)
Imports a multiple precision integer as a prime field element, doing the necessary conversion.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to import.
Definition at line 427 of file relic_fp_prime.c.
References bn_free, bn_is_zero(), bn_lsh(), bn_mod, bn_new, bn_null, CATCH_ANY, core_get(), dv_copy(), ERR_CAUGHT, ERR_NO_PRECI, FINALLY, FP_DIGIT, FP_DIGS, fp_zero(), THROW, and TRY.
Referenced by ep2_map(), ep_map(), fp_inv_binar(), fp_inv_exgcd(), and fp_read().
void fp_prime_conv_dig (fp_t c, dig_t a)
Imports a single digit as a prime field element, doing the necessary conversion.
Parameters
[out] c - the result.
[in] a - the digit to import.
Definition at line 469 of file relic_fp_prime.c.
References bn_null, CATCH_ANY, _ctx_t::conv, core_get(), bn_st::dp, dv_copy(), dv_free, dv_new, dv_zero(), ERR_CAUGHT, FINALLY, FP_DIGS, fp_mul1_low(), fp_rdc, fp_zero(), _ctx_t::one, THROW, and TRY.
Referenced by detect_opt(), fp_cmp_dig(), fp_mul_dig(), fp_read(), and fp_set_dig().
void fp_prime_back (bn_t c, const fp_t a)
Exports a prime field element as a multiple precision integer, doing the necessary conversion.
Parameters
[out] c - the result.
[in] a - the prime field element to export.
Definition at line 500 of file relic_fp_prime.c.
References bn_grow(), BN_POS, bn_trim(), CATCH_ANY, dv_copy(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, FINALLY, FP_DIGS, fp_rdc, THROW, and TRY.
Referenced by cp_sokaka_key(), fp_inv_binar(), fp_inv_exgcd(), fp_print(), fp_size(), and fp_write().