RELIC: include/low/relic_pp_low.h File Reference
relic_pp_low.h File Reference
Prime field arithmetic.
#include "relic_pp.h"
Functions
void fp2_addn_low (fp2_t c, fp2_t a, fp2_t b)
void fp2_addm_low (fp2_t c, fp2_t a, fp2_t b)
void fp2_addd_low (dv2_t c, dv2_t a, dv2_t b)
void fp2_addc_low (dv2_t c, dv2_t a, dv2_t b)
void fp2_subn_low (fp2_t c, fp2_t a, fp2_t b)
void fp2_subm_low (fp2_t c, fp2_t a, fp2_t b)
void fp2_subd_low (dv2_t c, dv2_t a, dv2_t b)
void fp2_subc_low (dv2_t c, dv2_t a, dv2_t b)
void fp2_dbln_low (fp2_t c, fp2_t a)
void fp2_dblm_low (fp2_t c, fp2_t a)
void fp2_norm_low (fp2_t c, fp2_t a)
void fp2_nord_low (dv2_t c, dv2_t a)
void fp2_muln_low (dv2_t c, fp2_t a, fp2_t b)
void fp2_mulc_low (dv2_t c, fp2_t a, fp2_t b)
void fp2_mulm_low (fp2_t c, fp2_t a, fp2_t b)
void fp2_sqrn_low (dv2_t c, fp2_t a)
void fp2_sqrm_low (fp2_t c, fp2_t a)
void fp2_rdcn_low (fp2_t c, dv2_t a)
void fp3_addn_low (fp3_t c, fp3_t a, fp3_t b)
void fp3_addm_low (fp3_t c, fp3_t a, fp3_t b)
void fp3_subn_low (fp3_t c, fp3_t a, fp3_t b)
void fp3_subm_low (fp3_t c, fp3_t a, fp3_t b)
void fp3_subc_low (dv3_t c, dv3_t a, dv3_t b)
void fp3_dbln_low (fp3_t c, fp3_t a)
void fp3_dblm_low (fp3_t c, fp3_t a)
void fp3_muln_low (dv3_t c, fp3_t a, fp3_t b)
void fp3_mulm_low (fp3_t c, fp3_t a, fp3_t b)
void fp3_sqrn_low (dv2_t c, fp3_t a)
void fp3_sqrm_low (fp3_t c, fp3_t a)
void fp3_rdcn_low (fp3_t c, dv3_t a)
Detailed Description
Interface of the low-level prime field arithmetic module.
Version
Id:
relic_pp_low.h 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_pp_low.h.
Function Documentation
void fp2_addn_low (fp2_t c, fp2_t a, fp2_t b)
Adds two quadratic extension field elements of the same size. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), and pp_dbl_k12_projc_lazyr().
void fp2_addm_low (fp2_t c, fp2_t a, fp2_t b)
Adds two quadratic extension field elements of the same size with integrated modular reduction. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp2_add_integ(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), and fp6_sqr_unr().
void fp2_addd_low (dv2_t c, dv2_t a, dv2_t b)
Adds two double-precision quadratic extension field elements of the same size. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp12_sqr_cyc_lazyr(), fp6_mul_dxs_unr_lazyr(), fp6_sqr_unr(), and pp_dbl_k12_projc_lazyr().
void fp2_addc_low (dv2_t c, dv2_t a, dv2_t b)
Adds two double-precision quadratic extension field elements of the same size and corrects the result by conditionally adding 2^(FP_DIGS * WORD) * p. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp12_mul_dxs_lazyr(), fp12_mul_lazyr(), fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp18_mul_dxs_lazyr(), fp18_mul_lazyr(), fp18_sqr_lazyr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), and fp6_sqr_unr().
void fp2_subn_low (fp2_t c, fp2_t a, fp2_t b)
Subtracts a quadratic extension field element from another of the same size. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element.
[in] b - the field element to subtract.
void fp2_subm_low (fp2_t c, fp2_t a, fp2_t b)
Subtracts a quadratic extension field element from another of the same size with integrated modular reduction. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element.
[in] b - the field element to subtract.
Referenced by fp2_sub_integ(), and fp6_sqr_unr().
void fp2_subd_low (dv2_t c, dv2_t a, dv2_t b)
Subtracts a double-precision quadratic extension field element from another of the same size. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
void fp2_subc_low (dv2_t c, dv2_t a, dv2_t b)
Subtracts a double-precision quadratic extension field element from another of the same size and corrects the result by conditionally adding 2^(FP_DIGS * WORD) * p. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp12_mul_dxs_lazyr(), fp12_mul_lazyr(), fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp18_mul_dxs_lazyr(), fp18_mul_lazyr(), fp18_sqr_lazyr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_unr(), pp_add_k12_projc_lazyr(), and pp_dbl_k12_projc_lazyr().
void fp2_dbln_low (fp2_t c, fp2_t a)
Doubles a quadratic extension field element. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
void fp2_dblm_low (fp2_t c, fp2_t a)
Doubles a quadratic extension field element with integrated modular reduction. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the field element to double.
Referenced by fp2_dbl_integ(), and fp6_sqr_unr().
void fp2_norm_low (fp2_t c, fp2_t a)
Multiplies a quadratic extension field element by the quadratic/cubic non-residue. Computes c = a * E.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Referenced by fp2_mul_nor_integ().
void fp2_nord_low (dv2_t c, dv2_t a)
Multiplies a double-precision quadratic extension field element by the quadratic/cubic non-residue. Computes c = a * E.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Referenced by fp12_mul_dxs_lazyr(), fp12_mul_lazyr(), fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp18_mul_dxs_lazyr(), fp18_mul_lazyr(), fp18_sqr_lazyr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), and fp6_sqr_unr().
void fp2_muln_low (dv2_t c, fp2_t a, fp2_t b)
Multiplies two quadratic extension field elements of the same size. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
[in] b - the second field element to multiply.
Referenced by fp12_mul_dxs_lazyr(), fp6_mul_dxs_unr_lazyr(), fp6_mul_unr(), fp6_sqr_unr(), and pp_add_k12_projc_lazyr().
void fp2_mulc_low (dv2_t c, fp2_t a, fp2_t b)
Multiplies two quadratic extension elements of the same size and corrects the result by adding (2^(FP_DIGS * WORD) * p)/4. This function should only be used when the FP_SPACE optimization is detected. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
[in] b - the second field element to multiply.
Referenced by fp6_mul_dxs_unr_lazyr(), fp6_sqr_unr(), and pp_add_k12_projc_lazyr().
void fp2_mulm_low (fp2_t c, fp2_t a, fp2_t b)
Multiplies two quadratic extension field elements of the same size with embedded modular reduction. Computes c = (a * b) mod p.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
[in] b - the second field element to multiply.
Referenced by fp2_mul_integ().
void fp2_sqrn_low (dv2_t c, fp2_t a)
Squares a quadratic extension element. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the field element to square.
Referenced by fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp6_sqr_unr(), and pp_dbl_k12_projc_lazyr().
void fp2_sqrm_low (fp2_t c, fp2_t a)
Squares a quadratic extension field element with integrated modular reduction. Computes c = (a * a) mod p.
Parameters
[out] c - the result.
[in] a - the field element to square.
Referenced by fp2_sqr_integ().
void fp2_rdcn_low (fp2_t c, dv2_t a)
Reduces a quadratic extension element modulo the configured prime p. Computes c = a mod p.
Parameters
[out] c - the result.
[in] a - the digit vector to reduce.
Referenced by fp12_mul_dxs_lazyr(), fp12_mul_lazyr(), fp12_sqr_cyc_lazyr(), fp12_sqr_pck_lazyr(), fp18_mul_dxs_lazyr(), fp18_mul_lazyr(), fp18_sqr_lazyr(), fp2_rdc_integ(), fp6_mul_lazyr(), fp6_sqr_lazyr(), pp_add_k12_projc_lazyr(), and pp_dbl_k12_projc_lazyr().
void fp3_addn_low (fp3_t c, fp3_t a, fp3_t b)
Adds two cubic extension field elements of the same size. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
void fp3_addm_low (fp3_t c, fp3_t a, fp3_t b)
Adds two cubic extension field elements of the same size with integrated modular reduction. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
Referenced by fp3_add_integ().
void fp3_subn_low (fp3_t c, fp3_t a, fp3_t b)
Subtracts a cubic extension field element from another of the same size. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element.
[in] b - the field element to subtract.
void fp3_subm_low (fp3_t c, fp3_t a, fp3_t b)
Subtracts a cubic extension field element from another of the same size with integrated modular reduction. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element.
[in] b - the field element to subtract.
Referenced by fp3_sub_integ().
void fp3_subc_low (dv3_t c, dv3_t a, dv3_t b)
Subtracts a double-precision cubic extension field element from another of the same size and corrects the result by conditionally adding 2^(FP_DIGS * WORD) * p. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the first field element to add.
[in] b - the second field element to add.
void fp3_dbln_low (fp3_t c, fp3_t a)
Doubles a cubic extension field element. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
void fp3_dblm_low (fp3_t c, fp3_t a)
Doubles a cubic extension field element with integrated modular reduction. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the field element to double.
Referenced by fp3_dbl_integ().
void fp3_muln_low (dv3_t c, fp3_t a, fp3_t b)
Multiplies two cubic extension field elements of the same size. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
[in] b - the second field element to multiply.
Referenced by fp6_mul_dxs_unr().
void fp3_mulm_low (fp3_t c, fp3_t a, fp3_t b)
Multiplies two cubic extension field elements of the same size with embedded modular reduction. Computes c = (a * b) mod p.
Parameters
[out] c - the result.
[in] a - the first field element to multiply.
[in] b - the second field element to multiply.
Referenced by fp3_mul_integ().
void fp3_sqrn_low (dv2_t c, fp3_t a)
Squares a cubic extension element. Computes c = a * a.
Parameters
[out] c - the result.
[in] a - the field element to square.
void fp3_sqrm_low (fp3_t c, fp3_t a)
Squares a cubic extension field element with integrated modular reduction. Computes c = (a * a) mod p.
Parameters
[out] c - the result.
[in] a - the field element to square.
Referenced by fp3_sqr_integ().
void fp3_rdcn_low (fp3_t c, dv3_t a)
Reduces a cubic extension element modulo the configured prime p. Computes c = a mod p.
Parameters
[out] c - the result.
[in] a - the digit vector to reduce.
Referenced by fp3_rdc_integ().