RELIC: src/fb/relic_fb_mul.c File Reference
relic_fb_mul.c File Reference
Binary field arithmetic.
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
#include "relic_bn_low.h"
#include "relic_util.h"
Functions
static void fb_mul_karat_imp (dv_t c, const fb_t a, const fb_t b, int size, int level)
void fb_mul_basic (fb_t c, const fb_t a, const fb_t b)
void fb_mul_integ (fb_t c, const fb_t a, const fb_t b)
void fb_mul_lcomb (fb_t c, const fb_t a, const fb_t b)
void fb_mul_rcomb (fb_t c, const fb_t a, const fb_t b)
void fb_mul_lodah (fb_t c, const fb_t a, const fb_t b)
void fb_mul_karat (fb_t c, const fb_t a, const fb_t b)
void fb_mul_dig (fb_t c, const fb_t a, dig_t b)
Detailed Description
Implementation of the binary field multiplication functions.
Version
Id:
relic_fb_mul.c 1561 2013-09-02 00:01:53Z dfaranha
Definition in file relic_fb_mul.c.
Function Documentation
static void fb_mul_karat_imp (dv_t c, const fb_t a, const fb_t b, int size, int level) static
Multiplies two binary field elements using recursive Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element.
[in] b - the second binary field element.
[in] size - the number of digits to multiply.
[in] level - the number of Karatsuba steps to apply.
Definition at line 166 of file relic_fb_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, fb_addd_low(), fb_muld_low(), FINALLY, THROW, and TRY.
Referenced by fb_mul_karat().
void fb_mul_basic (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Shift-and-add multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 265 of file relic_fb_mul.c.
References CATCH_ANY, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fb_add(), FB_BITS, fb_bits(), fb_copy(), FB_DIGS, fb_free, fb_lsh1_low(), fb_new, fb_null, fb_poly_add(), fb_rdc, fb_test_bit(), fb_zero(), FINALLY, THROW, and TRY.
void fb_mul_integ (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using multiplication integrated with modular reduction.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 313 of file relic_fb_mul.c.
References fb_mulm_low().
void fb_mul_lcomb (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Left-to-right comb multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 321 of file relic_fb_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fb_addd_low(), FB_DIGS, fb_lsh1_low(), fb_rdc, FINALLY, THROW, and TRY.
void fb_mul_rcomb (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Right-to-left comb multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 360 of file relic_fb_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fb_addd_low(), fb_copy(), FB_DIGIT, FB_DIGS, fb_lsh1_low(), fb_rdc, FINALLY, THROW, and TRY.
void fb_mul_lodah (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using López-Dahab multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element to multiply.
[in] b - the second binary field element to multiply.
Definition at line 402 of file relic_fb_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, fb_muln_low(), fb_rdc, FINALLY, THROW, and TRY.
void fb_mul_karat (fb_t c, const fb_t a, const fb_t b)
Multiples two binary field elements using Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first binary field element.
[in] b - the second binary field element.
Definition at line 425 of file relic_fb_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, FB_DIGS, FB_KARAT, fb_mul_karat_imp(), fb_rdc, FINALLY, THROW, and TRY.
void fb_mul_dig (fb_t c, const fb_t a, dig_t b)
Multiplies a binary field element by a small binary field element.
Parameters
[out] c - the result.
[in] a - the binary field element.
[in] b - the small binary field element to multiply.
Definition at line 448 of file relic_fb_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, fb_mul1_low(), fb_rdc1_low(), FINALLY, THROW, and TRY.
Referenced by eb_add_projc_ordin_mix(), eb_dbl_projc_ordin(), eb_rhs(), and find_srz().