package com.galois.hacrypto.test;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Scanner;

import com.galois.hacrypto.req.Req;

/**
 * Runs all tests listed in a specified file, reading .req files from and
 * generating the corresponding .rsp files for those tests at a specified
 * directory root.
 * 
 * @author dmz
 */
public class RunJavaHarness {
	/**
	 * map from algorithm names to autogenerated input file names
	 */
	private Map<String, List<String>> testFiles = new HashMap<String, List<String>>();
	
	/**
	 * A File object representing the input directory. 
	 */
	private final File inputDir;
	
	/**
	 * A File object representing the output directory.
	 */
	private final File outputDir;
	
	/**
	 * A File object representing the test spec directory.
	 */
	private final File testDir;

	/**
	 * @param testDirName
	 *            The directory that holds the test definitions such as tests,
	 *            C_tests, and KAT files
	 * @param inputDirName
	 *            The directory that contains all the request files.
	 * @param outputDirName 
	 *            The directory that contains all the response files.
	 */
	public RunJavaHarness(String testDirName, String inputDirName, String outputDirName) {
		inputDir = new File(inputDirName);
		outputDir = new File(outputDirName);
		testDir = new File(testDirName);
	}
	
	/**
	 * Runs all the tests that are present in the harness_tests file that also have
	 * corresponding test definitions and request files, generating the appropriate
	 * response files.
	 */
	public void run() {
		File rspdir = new File(outputDir.getPath() + File.separator + "rsp");
		rspdir.mkdirs();
		File testFile = new File(testDir.getAbsolutePath() + File.separator + "harness_tests");
		Scanner testReader = null;
		try {
			testReader = new Scanner(testFile);
		} catch (FileNotFoundException e) {
			System.err.println("File " + testFile.getAbsolutePath()
					+ " not found");
			e.printStackTrace();
		}
		while (testReader.hasNext()) {
			readTestLine(testReader.nextLine());
		}
	}

	private void createFile(String fileName) {
		Req r;
		fileName = fileName.replace('/', File.separatorChar);
		File testSpec = new File(testDir.getAbsolutePath() + File.separator + fileName);
		if (!testSpec.exists()) {
			// no matching test spec, print an output line and return
			System.err.println("No test spec found for " + fileName + ", skipping test.");
			return;
		}
		String dir = fileName.substring(0,
				fileName.lastIndexOf(File.separatorChar));
		File req = new File(inputDir.getPath() + File.separator + "req" + File.separator
				+ fileName + ".req");
		if (!req.exists()) {
			// no matching tests, print an output line and exit
			System.err.println("No request file " + fileName + " found, skipping test.");
			return;
		}
		File rspDir = new File(outputDir.getPath() + File.separator + "rsp"
				+ File.separator + fileName.substring(0, fileName.indexOf("/")));
		rspDir.mkdirs();
		File rsp = new File(outputDir.getPath() + File.separator + "rsp" + File.separator 
				+ fileName + ".rsp");
		try {
			r = new Req(req.getAbsolutePath(), testSpec.getAbsolutePath());
			Entry<String, String> reqrsp = r.createReqRsp();
			Util.writeStringToOutDir(fileName + ".rsp", outputDir.getPath()
					+ File.separator + "rsp", reqrsp.getValue());
		} catch (Exception e) {
			e.printStackTrace();
			System.err.println("Skipping test.");
		}
	}

	/**
	 * Handles a line of a harnesses file.
	 * 
	 * @param line An entire line of a harnesses file.
	 */
	private void readTestLine(String line) {
		Scanner lineReader = new Scanner(line);
		while (lineReader.hasNext()) {
			final String s = lineReader.next();
			System.err.println("Running test " + s);
			createFile(s);
		}
		lineReader.close();
	}
	
	public static void main(String args[]) {
		String testSpecDir = "test_defs";
		String inputDir = "output";
		String outputDir = "outputH";
		
		if (args.length >= 3) {
			// assume the first argument is the test spec directory
			// the second is the input directory
			// the third is the output directory (usually the same as the second)

			testSpecDir = args[0];
			inputDir = args[1];
			outputDir = args[2];
		} 
		
		System.err.println("Starting run at " + new Date());
		long startTime = System.currentTimeMillis();
		final RunJavaHarness rt = new RunJavaHarness(testSpecDir, inputDir, outputDir);
		rt.run();
		long finishTime = System.currentTimeMillis();
		System.err.println("Run ended at " + new Date());
		long msec = finishTime - startTime;
		long seconds = msec / 1000;
		msec = msec % 1000;
		long minutes = seconds / 60;
		seconds = seconds % 60;
		System.err.printf("Elapsed time: %d:%02d.%03d", minutes, seconds, msec);
	}
}
