RELIC: src/pb/relic_pb_etat1.c File Reference
relic_pb_etat1.c File Reference
Pairings over binary elliptic curves.
#include <math.h>
#include "relic_core.h"
#include "relic_pb.h"
#include "relic_util.h"
Functions
static void etat_exp (fb4_t r, fb4_t a)
static void pb_map_etats_imp (fb4_t r, const eb_t p, const eb_t q)
static void pb_map_etatn_imp (fb4_t r, const eb_t p, const eb_t q)
void pb_map_etats (fb4_t r, const eb_t p, const eb_t q)
void pb_map_etatn (fb4_t r, const eb_t p, const eb_t q)
Detailed Description
Implementation of the eta_t bilinear pairing over genus 1 supersingular curves.
Version
Id:
relic_pb_etat1.c 1561 2013-09-02 00:01:53Z dfaranha
Definition in file relic_pb_etat1.c.
Function Documentation
static void etat_exp (fb4_t r, fb4_t a) static
Computes the final exponentiation of the eta_t pairing.
This function maps a random coset element to a fixed coset representative.
Parameters
[out] r - the result.
[in] a - the random coset element.
Definition at line 55 of file relic_pb_etat1.c.
References CATCH_ANY, eb_curve_get_b(), ERR_CAUGHT, fb2_add, fb2_copy, fb2_free, fb2_inv(), fb2_mul(), fb2_new, fb2_null, fb4_frb(), fb4_free, fb4_mul(), fb4_new, fb4_null, fb4_sqr(), fb_add(), FB_BITS, fb_copy(), fb_itr, fb_sqr, FINALLY, pb_map_get_tab(), THROW, and TRY.
Referenced by pb_map_etatn(), and pb_map_etats().
static void pb_map_etats_imp (fb4_t r, const eb_t p, const eb_t q) static
Definition at line 159 of file relic_pb_etat1.c.
References CATCH_ANY, CORES, eb_curve_get_b(), ERR_CAUGHT, fb4_copy, fb4_free, fb4_mul(), fb4_mul_dxs(), fb4_mul_sxs(), fb4_new, fb4_null, fb4_zero, fb_add(), fb_add_dig(), FB_BITS, fb_copy(), fb_free, fb_itr, fb_mul, fb_new, fb_null, fb_set_bit(), fb_sqr, fb_srt, fb_zero(), FINALLY, pb_map_get_par(), pb_map_get_sqr(), pb_map_get_srt(), THROW, and TRY.
Referenced by pb_map_etats().
static void pb_map_etatn_imp (fb4_t r, const eb_t p, const eb_t q) static
Definition at line 491 of file relic_pb_etat1.c.
References CATCH_ANY, eb_curve_get_b(), ERR_CAUGHT, fb4_free, fb4_mul_dxs(), fb4_mul_sxs(), fb4_new, fb4_null, fb4_sqr(), fb_add(), fb_add_dig(), FB_BITS, fb_copy(), fb_free, fb_mul, fb_new, fb_null, fb_set_bit(), fb_sqr, fb_zero(), FINALLY, THROW, and TRY.
Referenced by pb_map_etatn().
void pb_map_etats (fb4_t r, const eb_t p, const eb_t q)
Computes the etat pairing of two binary elliptic curve points without using square roots.
Parameters
[out] r - the result.
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Definition at line 619 of file relic_pb_etat1.c.
References etat_exp(), and pb_map_etats_imp().
void pb_map_etatn (fb4_t r, const eb_t p, const eb_t q)
Computes the etat pairing of two binary elliptic curve points using square roots.
Parameters
[out] r - the result.
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Definition at line 628 of file relic_pb_etat1.c.
References etat_exp(), and pb_map_etatn_imp().