RELIC: src/fb/relic_fb_add.c File Reference
relic_fb_add.c File Reference
Binary field arithmetic.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "relic_core.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
Functions
void fb_add (fb_t c, const fb_t a, const fb_t b)
void fb_add_dig (fb_t c, const fb_t a, dig_t b)
void fb_sub (fb_t c, const fb_t a, const fb_t b)
void fb_sub_dig (fb_t c, const fb_t a, dig_t b)
Detailed Description
Implementation of binary field addition and subtraction functions.
Version
Id:
relic_fb_add.c 1561 2013-09-02 00:01:53Z dfaranha
Definition in file relic_fb_add.c.
Function Documentation
void fb_add (fb_t c, const fb_t a, const fb_t b)
Adds two binary field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first binary field element to add.
[in] b - the second binary field element to add.
Definition at line 44 of file relic_fb_add.c.
References fb_addn_low().
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_add_projc_ordin(), eb_add_projc_ordin_mix(), eb_add_projc_super(), eb_add_projc_super_mix(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_ordin(), eb_dbl_projc_super(), eb_hlv(), eb_is_valid(), eb_mul_halve(), eb_mul_lodah(), eb_neg_basic(), eb_neg_projc(), eb_norm_halve(), eb_rhs(), etat_exp(), fb2_inv(), fb2_mul(), fb2_mul_nor(), fb2_slv(), fb2_sqr(), fb4_frb(), fb4_inv(), fb4_mul(), fb4_mul_dxd(), fb4_mul_dxs(), fb4_mul_sxs(), fb4_sqr(), fb_inv_binar(), fb_inv_bruch(), fb_mul_basic(), fb_poly_add(), fb_slv_basic(), fb_trc_basic(), find_solve(), find_trace(), pb_map_etatn_imp(), and pb_map_etats_imp().
void fb_add_dig (fb_t c, const fb_t a, dig_t b)
Adds a binary field element and a small binary field element. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the binary field element to add.
[in] b - the small binary field element to add.
Definition at line 48 of file relic_fb_add.c.
References fb_add1_low().
Referenced by eb_add_basic_ordin(), eb_add_basic_super(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_dbl_projc_super(), eb_hlv(), eb_mul_lodah(), eb_neg_basic(), eb_neg_projc(), eb_rhs(), eb_upk(), fb2_slv(), fb4_mul_sxs(), fb_read(), fb_slv_basic(), fb_slv_quick(), pb_map_etatn_imp(), and pb_map_etats_imp().
void fb_sub (fb_t c, const fb_t a, const fb_t b)
Subtracts a binary field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the binary field element.
[in] b - the binary field element to subtract.
Definition at line 52 of file relic_fb_add.c.
References fb_addn_low().
void fb_sub_dig (fb_t c, const fb_t a, dig_t b)
Subtracts a small binary field element from a binary field element. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the binary field element.
[in] b - the small binary field element to subtract.
Definition at line 56 of file relic_fb_add.c.
References fb_add1_low().