RELIC: include/relic_cp.h File Reference
relic_cp.h File Reference
Multiple precision integer arithmetic.
#include "relic_conf.h"
#include "relic_types.h"
#include "relic_bn.h"
#include "relic_ec.h"
#include "relic_pc.h"
Data Structures
struct _rsa_t
struct _rabin_t
struct _sokaka
Macros
#define CP_TEXT 0
#define CP_HASH 1
#define CP_EMPTY 0
#define CP_PKCS1 1
#define CP_PKCS2 2
#define rsa_null(A) /* empty */
#define rsa_new(A)
#define rsa_free(A) /* empty */
#define rabin_null(A) /* empty */
#define rabin_new(A)
#define rabin_free(A) /* empty */
#define sokaka_null(A) /* empty */
#define sokaka_new(A) /* empty */
#define sokaka_free(A) /* empty */
#define cp_rsa_gen(PB, PV, B) cp_rsa_gen_quick(PB, PV, B)
#define cp_rsa_dec(O, OL, I, IL, K) cp_rsa_dec_quick(O, OL, I, IL, K)
#define cp_rsa_sig(O, OL, I, IL, H, K) cp_rsa_sig_quick(O, OL, I, IL, H, K)
Typedefs
typedef struct _rsa_t rsa_st
typedef rsa_st rsa_t [1]
typedef struct _rabin_t rabin_st
typedef rabin_st rabin_t [1]
typedef struct _sokaka sokaka_st
typedef sokaka_st sokaka_t [1]
Functions
int cp_rsa_gen_basic (rsa_t pub, rsa_t prv, int bits)
int cp_rsa_gen_quick (rsa_t pub, rsa_t prv, int bits)
int cp_rsa_enc (unsigned char *out, int *out_len, unsigned char *in, int in_len, rsa_t pub)
int cp_rsa_dec_basic (unsigned char *out, int *out_len, unsigned char *in, int in_len, rsa_t prv)
int cp_rsa_dec_quick (unsigned char *out, int *out_len, unsigned char *in, int in_len, rsa_t prv)
int cp_rsa_sig_basic (unsigned char *sig, int *sig_len, unsigned char *msg, int msg_len, int hash, rsa_t prv)
int cp_rsa_sig_quick (unsigned char *sig, int *sig_len, unsigned char *msg, int msg_len, int hash, rsa_t prv)
int cp_rsa_ver (unsigned char *sig, int sig_len, unsigned char *msg, int msg_len, int hash, rsa_t pub)
int cp_rabin_gen (rabin_t pub, rabin_t prv, int bits)
int cp_rabin_enc (unsigned char *out, int *out_len, unsigned char *in, int in_len, rabin_t pub)
int cp_rabin_dec (unsigned char *out, int *out_len, unsigned char *in, int in_len, rabin_t prv)
void cp_ecdh_gen (bn_t d, ec_t q)
void cp_ecdh_key (unsigned char *key, int key_len, bn_t d, ec_t q)
void cp_ecmqv_gen (bn_t d, ec_t q)
void cp_ecmqv_key (unsigned char *key, int key_len, bn_t d1, bn_t d2, ec_t q2u, ec_t q1v, ec_t q2v)
void cp_ecdsa_gen (bn_t d, ec_t q)
void cp_ecdsa_sig (bn_t r, bn_t s, unsigned char *msg, int len, int hash, bn_t d)
int cp_ecdsa_ver (bn_t r, bn_t s, unsigned char *msg, int len, int hash, ec_t q)
void cp_ecss_gen (bn_t d, ec_t q)
void cp_ecss_sig (bn_t e, bn_t s, unsigned char *msg, int len, bn_t d)
int cp_ecss_ver (bn_t e, bn_t s, unsigned char *msg, int len, ec_t q)
void cp_sokaka_gen (bn_t master)
void cp_sokaka_gen_prv (sokaka_t k, char *id, int len, bn_t master)
void cp_sokaka_key (unsigned char *key, unsigned int key_len, char *id1, int len1, sokaka_t k, char *id2, int len2)
void cp_bls_gen (bn_t d, g2_t q)
void cp_bls_sig (g1_t s, unsigned char *msg, int len, bn_t d)
int cp_bls_ver (g1_t s, unsigned char *msg, int len, g2_t q)
void cp_bbs_gen (bn_t d, g2_t q, gt_t z)
void cp_bbs_sig (g1_t s, unsigned char *msg, int len, int hash, bn_t d)
int cp_bbs_ver (g1_t s, unsigned char *msg, int len, int hash, g2_t q, gt_t z)
Detailed Description
Interface of cryptographic protocols.
Version
Id:
relic_cp.h 1505 2013-06-26 20:34:20Z conradoplg
Definition in file relic_cp.h.
Macro Definition Documentation
#define CP_TEXT 0
Flag used to indicate that the message being signed is plaintext.
Definition at line 52 of file relic_cp.h.
#define CP_HASH 1
Flag used to indicate that the message being signed is a hash value.
Definition at line 57 of file relic_cp.h.
#define CP_EMPTY 0
Flag used to indicate that no padding should be used.
Definition at line 62 of file relic_cp.h.
#define CP_PKCS1 1
Flag used to indicate that PKCS#1 v1.5 padding should be used.
Definition at line 67 of file relic_cp.h.
#define CP_PKCS2 2
Flag used to indicate that PKCS#1 v2.5 padding should be used.
Definition at line 72 of file relic_cp.h.
#define rsa_null (A) /* empty */
Initializes an RSA key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 163 of file relic_cp.h.
#define rsa_new (A)
Value:
bn_new((A)->e);                                                         \
    bn_new((A)->n);                                                         \
    bn_new((A)->d);                                                         \
    bn_new((A)->dp);                                                        \
    bn_new((A)->dq);                                                        \
    bn_new((A)->p);                                                         \
    bn_new((A)->q);                                                         \
    bn_new((A)->qi);                                                        \
Calls a function to allocate and initialize an RSA key pair.
Parameters
[out] A - the new key pair.
Definition at line 220 of file relic_cp.h.
#define rsa_free (A) /* empty */
Calls a function to clean and free an RSA key pair.
Parameters
[out] A - the key pair to clean and free.
Definition at line 279 of file relic_cp.h.
#define rabin_null (A) /* empty */
Initializes a Rabin key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 301 of file relic_cp.h.
#define rabin_new (A)
Value:
bn_new((A)->n);                                                         \
    bn_new((A)->dp);                                                        \
    bn_new((A)->dq);                                                        \
    bn_new((A)->p);                                                         \
    bn_new((A)->q);                                                         \
Calls a function to allocate and initialize a Rabin key pair.
Parameters
[out] A - the new key pair.
Definition at line 336 of file relic_cp.h.
#define rabin_free (A) /* empty */
Calls a function to clean and free a Rabin key pair.
Parameters
[out] A - the key pair to clean and free.
Definition at line 383 of file relic_cp.h.
#define sokaka_null (A) /* empty */
Initializes a SOKAKA key pair with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 402 of file relic_cp.h.
#define sokaka_new (A) /* empty */
Calls a function to allocate and initialize a SOKAKA key pair.
Parameters
[out] A - the new key pair.
Definition at line 431 of file relic_cp.h.
#define sokaka_free (A) /* empty */
Calls a function to clean and free a SOKAKA key pair.
Parameters
[out] A - the key pair to clean and free.
Definition at line 464 of file relic_cp.h.
#define cp_rsa_gen (PB, PV, B) cp_rsa_gen_quick(PB, PV, B)
Generates a new RSA key pair.
Parameters
[out] PB - the public key.
[out] PV - the private key.
[in] B - the key length in bits.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 485 of file relic_cp.h.
#define cp_rsa_dec (O, OL, I, IL, K) cp_rsa_dec_quick(O, OL, I, IL, K)
Decrypts using RSA.
Parameters
[out] O - the output buffer.
[out] OL - the number of bytes written in the output buffer.
[in] I - the input buffer.
[in] IL - the number of bytes to encrypt.
[in] K - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 501 of file relic_cp.h.
#define cp_rsa_sig (O, OL, I, IL, H, K) cp_rsa_sig_quick(O, OL, I, IL, H, K)
Signs a message using the RSA cryptosystem.
Parameters
[out] O - the output buffer.
[out] OL - the number of bytes written in the output buffer.
[in] I - the input buffer.
[in] IL - the number of bytes to sign.
[in] H - the flag to indicate the message format.
[in] K - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 518 of file relic_cp.h.
Typedef Documentation
typedef struct _rsa_t rsa_st
Represents an RSA key pair.
typedef rsa_st rsa_t[1]
Pointer to an RSA key pair.
Definition at line 104 of file relic_cp.h.
typedef struct _rabin_t rabin_st
Represents a Rabin key pair.
typedef rabin_st rabin_t[1]
Pointer to a Rabin key pair.
Definition at line 129 of file relic_cp.h.
typedef struct _sokaka sokaka_st
Represents a SOK key pair.
typedef sokaka_st sokaka_t[1]
Pointer to SOK key pair.
Definition at line 148 of file relic_cp.h.
Function Documentation
int cp_rsa_gen_basic (rsa_t pub, rsa_t prv, int bits)
Generates a new key pair for basic RSA algorithm.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] bits - the key length in bits.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 588 of file relic_cp_rsa.c.
References bn_add(), bn_add_dig(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_gen_prime, bn_mul, BN_NEG, bn_new, bn_null, bn_set_2b(), bn_sign(), bn_sub_dig(), CATCH_ANY, CMP_EQ, CMP_LT, FINALLY, STS_ERR, STS_OK, and TRY.
int cp_rsa_gen_quick (rsa_t pub, rsa_t prv, int bits)
Generates a new key RSA pair for fast operations with the CRT optimization.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] bits - the key length in bits.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 647 of file relic_cp_rsa.c.
References bn_add(), bn_add_dig(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_gen_prime, bn_mod, bn_mul, BN_NEG, bn_new, bn_null, bn_set_2b(), bn_sign(), bn_sub_dig(), CATCH_ANY, CMP_EQ, CMP_LT, FINALLY, STS_ERR, STS_OK, and TRY.
int cp_rsa_enc (unsigned char * out, int * out_len, unsigned char * in, int in_len, rsa_t pub)
Encrypts using the RSA cryptosystem.
Parameters
[out] out - the output buffer.
[out] out_len - the number of bytes written in the output buffer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] pub - the public key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 720 of file relic_cp_rsa.c.
References bn_add(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), bn_zero(), CATCH_ANY, FINALLY, pad_pkcs1(), RSA_ENC, RSA_ENC_FIN, RSA_PAD_LEN, STS_ERR, STS_OK, and TRY.
int cp_rsa_dec_basic (unsigned char * out, int * out_len, unsigned char * in, int in_len, rsa_t prv)
Decrypts using the basic RSA decryption method.
Parameters
[out] out - the output buffer.
[out] out_len - the number of bytes written in the output buffer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] prv - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 780 of file relic_cp_rsa.c.
References bn_cmp(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), CATCH_ANY, CMP_LT, FINALLY, pad_pkcs1(), RSA_DEC, RSA_PAD_LEN, STS_ERR, STS_OK, and TRY.
int cp_rsa_dec_quick (unsigned char * out, int * out_len, unsigned char * in, int in_len, rsa_t prv)
Decrypts using the fast RSA decryption with CRT optimization.
Parameters
[out] out - the output buffer.
[out] out_len - the number of bytes written in the output buffer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] prv - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 839 of file relic_cp_rsa.c.
References bn_add(), bn_cmp(), bn_copy(), bn_free, bn_mod, bn_mul, bn_mxp, BN_NEG, bn_new, bn_null, bn_read_bin(), bn_sign(), bn_size_bin(), bn_sub(), bn_write_bin(), CATCH_ANY, CMP_LT, FINALLY, pad_pkcs1(), RSA_DEC, RSA_PAD_LEN, STS_ERR, STS_OK, and TRY.
int cp_rsa_sig_basic (unsigned char * sig, int * sig_len, unsigned char * msg, int msg_len, int hash, rsa_t prv)
Signs using the basic RSA signature algorithm. The flag must be non-zero if the message being signed is already a hash value.
Parameters
[out] sig - the signature
[out] sig_len - the number of bytes written in the signature.
[in] msg - the message to sign.
[in] msg_len - the number of bytes to sign.
[in] hash - the flag to indicate the message format.
[in] prv - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 918 of file relic_cp_rsa.c.
References bn_add(), bn_bits(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), bn_zero(), CATCH_ANY, ERR_CAUGHT, FINALLY, MD_LEN, md_map, pad_pkcs1(), RSA_PAD_LEN, RSA_SIG, RSA_SIG_FIN, RSA_SIG_HASH, STS_ERR, STS_OK, THROW, and TRY.
int cp_rsa_sig_quick (unsigned char * sig, int * sig_len, unsigned char * msg, int msg_len, int hash, rsa_t prv)
Signs using the fast RSA signature algorithm with CRT optimization. The flag must be non-zero if the message being signed is already a hash value.
Parameters
[out] sig - the signature
[out] sig_len - the number of bytes written in the signature.
[in] msg - the message to sign.
[in] msg_len - the number of bytes to sign.
[in] hash - the flag to indicate the message format.
[in] prv - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 1001 of file relic_cp_rsa.c.
References bn_add(), bn_bits(), bn_copy(), bn_free, bn_mod, bn_mul, bn_mxp, BN_NEG, bn_new, bn_null, bn_read_bin(), bn_sign(), bn_size_bin(), bn_sub(), bn_write_bin(), bn_zero(), CATCH_ANY, ERR_CAUGHT, FINALLY, MD_LEN, md_map, pad_pkcs1(), RSA_PAD_LEN, RSA_SIG, RSA_SIG_FIN, RSA_SIG_HASH, STS_ERR, STS_OK, THROW, and TRY.
int cp_rsa_ver (unsigned char * sig, int sig_len, unsigned char * msg, int msg_len, int hash, rsa_t pub)
Verifies an RSA signature. The flag must be non-zero if the message being signed is already a hash value.
Parameters
[in] sig - the signature to verify.
[in] sig_len - the signature length in bytes.
[in] msg - the signed message.
[in] msg_len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] pub - the public key.
Returns
1 if the signature is valid, 0 otherwise.
Definition at line 1102 of file relic_cp_rsa.c.
References bn_bits(), bn_free, bn_mxp, bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), CATCH_ANY, CMP_EQ, FINALLY, MAX, md_map, pad_pkcs1(), RSA_PAD_LEN, RSA_VER, RSA_VER_HASH, STS_OK, TRY, and util_cmp_const().
int cp_rabin_gen (rabin_t pub, rabin_t prv, int bits)
Generates a new key pair for the Rabin cryptosystem.
Parameters
[out] pub - the public key.
[out] prv - the private key,
[in] bits - the key length in bits.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 60 of file relic_cp_rabin.c.
References bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_gen_prime, bn_mod_2b(), bn_mul, bn_new, bn_null, CATCH_ANY, CMP_EQ, CMP_LT, FINALLY, STS_ERR, STS_OK, and TRY.
int cp_rabin_enc (unsigned char * out, int * out_len, unsigned char * in, int in_len, rabin_t pub)
Encrypts using the Rabin cryptosystem.
Parameters
[out] out - the output buffer.
[out] out_len - the number of bytes written in the output buffer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] pub - the public key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 105 of file relic_cp_rabin.c.
References bn_add(), bn_add_dig(), bn_free, bn_lsh(), bn_mod, bn_mod_2b(), bn_new, bn_null, bn_read_bin(), bn_size_bin(), bn_sqr, bn_write_bin(), bn_zero(), CATCH_ANY, FINALLY, RABIN_PAD, RABIN_PAD_LEN, STS_ERR, STS_OK, and TRY.
int cp_rabin_dec (unsigned char * out, int * out_len, unsigned char * in, int in_len, rabin_t prv)
Decrypts using the Rabin cryptosystem.
Parameters
[out] out - the output buffer.
[out] out_len - the number of bytes written in the output buffer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] prv - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 156 of file relic_cp_rabin.c.
References bn_add(), bn_add_dig(), bn_cmp(), bn_free, bn_is_zero(), bn_mod, bn_mod_2b(), bn_mul, bn_mxp, BN_NEG, bn_new, bn_null, bn_read_bin(), bn_rsh(), bn_sign(), bn_size_bin(), bn_sub(), bn_write_bin(), CATCH_ANY, CMP_EQ, FINALLY, RABIN_PAD, RABIN_PAD_LEN, STS_ERR, STS_OK, and TRY.
void cp_ecdh_gen (bn_t d, ec_t q)
Generates an ECDH key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Definition at line 40 of file relic_cp_ecdh.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ec_curve_get_ord, ec_mul_gen, ERR_CAUGHT, FINALLY, THROW, and TRY.
void cp_ecdh_key (unsigned char * key, int key_len, bn_t d, ec_t q)
Derives a shared secret using ECDH.
Parameters
[out] key - the shared key.
int] key_len - the intended shared key length in bytes.
[in] d - the private key.
[in] q - the point received from the other party.
Definition at line 65 of file relic_cp_ecdh.c.
References bn_new, bn_null, bn_size_bin(), bn_write_bin(), CATCH_ANY, EC_BYTES, ec_free, ec_get_x, ec_mul, ec_new, ec_null, ERR_CAUGHT, FINALLY, md_kdf2(), THROW, and TRY.
void cp_ecmqv_gen (bn_t d, ec_t q)
Generate an ECMQV key pair.
Should also be used to generate the ephemeral key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Definition at line 40 of file relic_cp_ecmqv.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ec_curve_get_ord, ec_mul_gen, ERR_CAUGHT, FINALLY, THROW, and TRY.
void cp_ecmqv_key (unsigned char * key, int key_len, bn_t d1, bn_t d2, ec_t q2u, ec_t q1v, ec_t q2v)
Derives a shared secret using ECMQV.
Parameters
[out] key - the shared key.
int] key_len - the intended shared key length in bytes.
[in] d1 - the private key.
[in] d2 - the ephemeral private key.
[in] q2u - the ephemeral public key.
[in] q1v - the point received from the other party.
[in] q2v - the ephemeral point received from the other party.
Definition at line 65 of file relic_cp_ecmqv.c.
References bn_add(), bn_bits(), bn_free, bn_mod, bn_mod_2b(), bn_mul, bn_new, bn_null, bn_set_bit(), bn_size_bin(), bn_write_bin(), CATCH_ANY, EC_BYTES, ec_curve_get_ord, ec_free, ec_get_x, ec_mul_sim, ec_new, ec_null, ERR_CAUGHT, FINALLY, md_kdf2(), THROW, and TRY.
void cp_ecdsa_gen (bn_t d, ec_t q)
Generates an ECDSA key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Definition at line 39 of file relic_cp_ecdsa.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ec_curve_get_ord, ec_mul_gen, ERR_CAUGHT, FINALLY, THROW, and TRY.
void cp_ecdsa_sig (bn_t r, bn_t s, unsigned char * msg, int len, int hash, bn_t d)
Signs a message using ECDSA.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] d - the private key.
Definition at line 64 of file relic_cp_ecdsa.c.
References bn_add(), bn_bits(), bn_free, bn_gcd_ext, bn_is_zero(), bn_mod, bn_mul, BN_NEG, bn_new, bn_null, BN_POS, bn_rand(), bn_read_bin(), bn_rsh(), bn_sign(), CATCH_ANY, CEIL, ec_curve_get_ord, ec_free, ec_get_x, ec_mul_gen, ec_new, ec_null, ERR_CAUGHT, FINALLY, MD_LEN, md_map, THROW, and TRY.
int cp_ecdsa_ver (bn_t r, bn_t s, unsigned char * msg, int len, int hash, ec_t q)
Verifies a message signed with ECDSA using the basic method.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] q - the public key.
Definition at line 133 of file relic_cp_ecdsa.c.
References bn_add(), bn_bits(), bn_cmp(), bn_free, bn_gcd_ext, bn_is_zero(), bn_mod, bn_mul, BN_NEG, bn_new, bn_null, BN_POS, bn_read_bin(), bn_rsh(), bn_sign(), CATCH_ANY, CEIL, CMP_LT, CMP_NE, dv_cmp_const(), ec_curve_get_ord, ec_free, ec_get_x, ec_is_infty, ec_mul_sim_gen, ec_new, ec_null, ERR_CAUGHT, FINALLY, MD_LEN, md_map, MIN, THROW, and TRY.
void cp_ecss_gen (bn_t d, ec_t q)
Generates an Elliptic Curve Schnorr Signature key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Definition at line 39 of file relic_cp_ecss.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ec_curve_get_ord, ec_mul_gen, ERR_CAUGHT, FINALLY, THROW, and TRY.
void cp_ecss_sig (bn_t e, bn_t s, unsigned char * msg, int len, bn_t d)
Signs a message using the Elliptic Curve Schnorr Signature.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] d - the private key.
Definition at line 64 of file relic_cp_ecss.c.
References bn_add(), bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_mul, bn_new, bn_null, BN_POS, bn_rand(), bn_read_bin(), bn_rsh(), bn_sub(), bn_write_bin(), CATCH_ANY, CEIL, EC_BYTES, ec_curve_get_ord, ec_free, ec_get_x, ec_mul_gen, ec_new, ec_null, ERR_CAUGHT, FINALLY, MD_LEN, md_map, THROW, and TRY.
int cp_ecss_ver (bn_t e, bn_t s, unsigned char * msg, int len, ec_t q)
Verifies a message signed with the Elliptic Curve Schnorr Signature using the basic method.
Parameters
[out] r - the first component of the signature.
[out] s - the second component of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] q - the public key.
Definition at line 127 of file relic_cp_ecss.c.
References bn_bits(), bn_cmp(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_read_bin(), bn_rsh(), bn_sign(), bn_write_bin(), CATCH_ANY, CEIL, CMP_LT, CMP_NE, dv_cmp_const(), EC_BYTES, ec_curve_get_ord, ec_free, ec_get_x, ec_mul_sim_gen, ec_new, ec_null, ERR_CAUGHT, FINALLY, MD_LEN, md_map, MIN, THROW, and TRY.
void cp_sokaka_gen (bn_t master)
Generates a master key for the SOK identity-based non-interactive authenticated key agreement protocol.
Parameters
[out] master - the master key.
Definition at line 47 of file relic_cp_sokaka.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_get_ord, THROW, and TRY.
void cp_sokaka_gen_prv (sokaka_t k, char * id, int len, bn_t master)
Generates a private key for the SOK protocol.
Parameters
[out] k - the private key.
[in] id - the identity.
[in] len - the length of identity in bytes.
[in] master - the master key.
Definition at line 70 of file relic_cp_sokaka.c.
References g1_map, g1_mul, g2_map, g2_mul, and pc_map_is_type1.
void cp_sokaka_key (unsigned char * key, unsigned int key_len, char * id1, int len1, sokaka_t k, char * id2, int len2)
Computes a shared key between two entities.
Parameters
[out] key - the shared key.
int] key_len - the intended shared key length in bytes.
[in] id1 - the first identity.
[in] len1 - the length of the first identity in bytes.
[in] k - the private key of the first identity.
[in] id2 - the second identity.
[in] len2 - the length of the second identity in bytes.
Definition at line 82 of file relic_cp_sokaka.c.
References bn_free, bn_new, bn_null, bn_size_bin(), bn_write_bin(), CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FB_BYTES, FINALLY, FP_BYTES, fp_prime_back(), g1_free, g1_map, g1_new, g1_null, g2_free, g2_map, g2_new, g2_null, gt_free, gt_new, gt_null, md_kdf1(), pc_map, pc_map_is_type1, THROW, and TRY.
void cp_bls_gen (bn_t d, g2_t q)
Generates a BLS key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Definition at line 40 of file relic_cp_bls.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ERR_CAUGHT, FINALLY, g2_get_ord, g2_mul_gen, pc_param_level, THROW, and TRY.
void cp_bls_sig (g1_t s, unsigned char * msg, int len, bn_t d)
Signs a message using BLS.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] d - the private key.
Definition at line 65 of file relic_cp_bls.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, g1_free, g1_map, g1_mul, g1_new, g1_null, THROW, and TRY.
int cp_bls_ver (g1_t s, unsigned char * msg, int len, g2_t q)
Verifies a message signed with BLS using the basic method.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] q - the public key.
Returns
a boolean value indicating the verification result.
Definition at line 83 of file relic_cp_bls.c.
References CATCH_ANY, CMP_EQ, ERR_CAUGHT, FINALLY, g1_map, g1_new, g1_null, g2_get_gen, g2_new, g2_null, gt_cmp, gt_free, gt_new, gt_null, pc_map, THROW, and TRY.
void cp_bbs_gen (bn_t d, g2_t q, gt_t z)
Generates a Boneh-Boyen key pair.
Parameters
[out] d - the private key.
[in] q - the first component of the public key.
[in] q - the second component of the public key.
Definition at line 40 of file relic_cp_bbs.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_get_gen, g1_new, g1_null, g2_get_gen, g2_get_ord, g2_mul_gen, g2_norm, pc_map, pc_param_level, THROW, and TRY.
void cp_bbs_sig (g1_t s, unsigned char * msg, int len, int hash, bn_t d)
Signs a message using Boneh-Boyen Short Signature.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] d - the private key.
Definition at line 76 of file relic_cp_bbs.c.
References bn_add(), bn_free, bn_gcd_ext, bn_mod, BN_NEG, bn_new, bn_null, bn_read_bin(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_get_ord, g1_mul_gen, MD_LEN, md_map, THROW, and TRY.
int cp_bbs_ver (g1_t s, unsigned char * msg, int len, int hash, g2_t q, gt_t z)
Verifies a message signed with BLS using the basic method.
Parameters
[in] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] q - the public key.
Returns
a boolean value indicating the verification result.
Definition at line 119 of file relic_cp_bbs.c.
References bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), CATCH_ANY, CMP_EQ, ERR_CAUGHT, FINALLY, g2_add, g2_free, g2_get_ord, g2_mul_gen, g2_new, g2_norm, g2_null, gt_cmp, gt_free, gt_new, gt_null, MD_LEN, md_map, pc_map, THROW, and TRY.