RELIC: src/cp/relic_cp_ecdh.c File Reference
relic_cp_ecdh.c File Reference
Cryptographic protocols.
#include "relic.h"
#include "relic_test.h"
#include "relic_bench.h"
Functions
void cp_ecdh_gen (bn_t d, ec_t q)
void cp_ecdh_key (unsigned char *key, int key_len, bn_t d, ec_t q)
Detailed Description
Implementation of the ECDSA protocol.
Version
Id:
relic_cp_ecdh.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_cp_ecdh.c.
Function Documentation
void cp_ecdh_gen (bn_t d, ec_t q)
Generates an ECDH key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Definition at line 40 of file relic_cp_ecdh.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ec_curve_get_ord, ec_mul_gen, ERR_CAUGHT, FINALLY, THROW, and TRY.
void cp_ecdh_key (unsigned char * key, int key_len, bn_t d, ec_t q)
Derives a shared secret using ECDH.
Parameters
[out] key - the shared key.
int] key_len - the intended shared key length in bytes.
[in] d - the private key.
[in] q - the point received from the other party.
Definition at line 65 of file relic_cp_ecdh.c.
References bn_new, bn_null, bn_size_bin(), bn_write_bin(), CATCH_ANY, EC_BYTES, ec_free, ec_get_x, ec_mul, ec_new, ec_null, ERR_CAUGHT, FINALLY, md_kdf2(), THROW, and TRY.