/*
 * Test data strategy for hacrypto.BCSHA_256.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2014-06-30 15:35 -0700.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package hacrypto;

import java.util.LinkedList;
import java.util.List;

import org.jmlspecs.jmlunitng.iterator.InstantiationIterator;
import org.jmlspecs.jmlunitng.iterator.IteratorAdapter;
import org.jmlspecs.jmlunitng.iterator.NonNullMultiIterator;
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for hacrypto.BCSHA_256. Provides
 * instances of hacrypto.BCSHA_256 for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2014-06-30 15:35 -0700
 */
public /*@ nullable_by_default */ class BCSHA_256_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of BCSHA_256.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add hacrypto.BCSHA_256 values or generators here */ });
  }

  /**
   * @return default instances of BCSHA_256, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<hacrypto.BCSHA_256> defaultValues() {
    final List<RepeatedAccessIterator<hacrypto.BCSHA_256>> iters = 
      new LinkedList<RepeatedAccessIterator<hacrypto.BCSHA_256>>();

    // an instantiation iterator for the default constructor
    // (if there isn't one, it will fail silently)
    iters.add(new InstantiationIterator<hacrypto.BCSHA_256>
      (hacrypto.BCSHA_256.class, 
       new Class<?>[0], 
       new ObjectArrayIterator<Object[]>(new Object[][]{{}})));

    return new NonNullMultiIterator<hacrypto.BCSHA_256>(iters);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public BCSHA_256_InstanceStrategy() {
    super(hacrypto.BCSHA_256.class);
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
