/*
 * Test data strategy for package hacrypto.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2014-06-30 15:35 -0700.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 package hacrypto;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ByteStrategy;

/**
 * Test data strategy for package hacrypto. Provides
 * package-scope test values for type byte.
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2014-06-30 15:35 -0700
 */
public /*@ nullable_by_default */ class PackageStrategy_byte 
  extends ByteStrategy {
  /**
   * @return package-scope values for type byte.
   */
  public RepeatedAccessIterator<?> packageValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add package-scope byte values or generators here */ });
  }
}
