RELIC: src/fbx/relic_fbx_inv.c File Reference
relic_fbx_inv.c File Reference
Extensions of binary fields.
#include "relic_core.h"
#include "relic_fbx.h"
Functions
void fb2_inv (fb2_t c, fb2_t a)
void fb4_inv (fb4_t c, fb4_t a)
Detailed Description
Implementation of inversion in binary fields extensions.
Version
Id:
relic_fbx_inv.c 1489 2013-06-02 18:33:31Z dfaranha
Definition in file relic_fbx_inv.c.
Function Documentation
void fb2_inv (fb2_t c, fb2_t a)
Inverts a quadratic extension field element. Computes c = a^{-1}.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to invert.
Definition at line 39 of file relic_fbx_inv.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_sqr, FINALLY, THROW, and TRY.
Referenced by etat_exp(), and fb4_inv().
void fb4_inv (fb4_t c, fb4_t a)
Definition at line 70 of file relic_fbx_inv.c.
References CATCH_ANY, ERR_CAUGHT, fb2_add, fb2_copy, fb2_free, fb2_inv(), fb2_mul(), fb2_new, fb2_null, fb2_sqr(), fb_add(), fb_copy(), FINALLY, THROW, and TRY.