RELIC: src/epx/relic_ep2_mul_sim.c File Reference
relic_ep2_mul_sim.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep2_mul_sim_ordin (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l, int gen)
void ep2_mul_sim_basic (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
void ep2_mul_sim_trick (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
void ep2_mul_sim_inter (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
void ep2_mul_sim_joint (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
void ep2_mul_sim_gen (ep2_t r, bn_t k, ep2_t q, bn_t l)
Detailed Description
Implementation of simultaneous point multiplication on a prime elliptic curve over a quadratic extension.
Version
Id:
relic_ep2_mul_sim.c 1550 2013-08-29 23:03:21Z dfaranha
Definition in file relic_ep2_mul_sim.c.
Function Documentation
static void ep2_mul_sim_ordin (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l, int gen) static
Definition at line 41 of file relic_ep2_mul_sim.c.
References bn_rec_naf(), ep2_add, ep2_curve_get_tab(), ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub, ep2_tab(), EP_DEPTH, EP_WIDTH, FP_BITS, and MAX.
Referenced by ep2_mul_sim_gen(), and ep2_mul_sim_inter().
void ep2_mul_sim_basic (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] l - the second integer,
Definition at line 128 of file relic_ep2_mul_sim.c.
References CATCH_ANY, ep2_add, ep2_free, ep2_mul(), ep2_new, ep2_norm(), ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_sim_trick (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] l - the second integer,
Definition at line 152 of file relic_ep2_mul_sim.c.
References bn_free, bn_new, bn_null, bn_rec_win(), CATCH_ANY, CEIL, ep2_add, ep2_curve_get_ord(), ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), EP_WIDTH, ERR_CAUGHT, FINALLY, FP_BITS, MAX, THROW, and TRY.
void ep2_mul_sim_inter (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] l - the second integer,
Definition at line 237 of file relic_ep2_mul_sim.c.
References ep2_mul_sim_ordin().
void ep2_mul_sim_joint (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] l - the second integer,
Definition at line 255 of file relic_ep2_mul_sim.c.
References bn_bits(), bn_rec_jsf(), CATCH_ANY, ep2_add, ep2_copy(), ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub, ERR_CAUGHT, FINALLY, FP_BITS, MAX, THROW, and TRY.
void ep2_mul_sim_gen (ep2_t r, bn_t k, ep2_t q, bn_t l)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = kG + lQ.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] l - the second integer,
Definition at line 317 of file relic_ep2_mul_sim.c.
References CATCH_ANY, ep2_curve_get_gen(), ep2_free, ep2_mul_sim, ep2_mul_sim_ordin(), ep2_new, ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.