RELIC: src/epx/relic_ep2_util.c File Reference
relic_ep2_util.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
int ep2_is_infty (ep2_t p)
void ep2_set_infty (ep2_t p)
void ep2_copy (ep2_t r, ep2_t p)
int ep2_cmp (ep2_t p, ep2_t q)
void ep2_rand (ep2_t p)
void ep2_rhs (fp2_t rhs, ep2_t p)
void ep2_tab (ep2_t *t, ep2_t p, int w)
int ep2_is_valid (ep2_t p)
void ep2_print (ep2_t p)
Detailed Description
Implementation of utilities for prime elliptic curves over quadratic extensions.
Version
Id:
relic_ep2_util.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_ep2_util.c.
Function Documentation
int ep2_is_infty (ep2_t p)
Tests if a point on a elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep2_util.c.
References fp2_is_zero().
Referenced by ep2_add_basic(), ep2_add_projc(), ep2_add_slp_basic(), ep2_dbl_basic(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_is_valid(), ep2_neg_basic(), ep2_neg_projc(), ep2_norm(), and pp_norm_k12().
void ep2_set_infty (ep2_t p)
Assigns a elliptic curve point to a point at the infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep2_util.c.
References fp2_zero().
Referenced by ep2_add_basic_imp(), ep2_add_projc_imp(), ep2_add_projc_mix(), ep2_curve_init(), ep2_dbl_basic(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_mul(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_nafwi(), ep2_mul_fix_ordin(), ep2_mul_fix_yaowi(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_sim_joint(), ep2_mul_sim_ordin(), ep2_mul_sim_trick(), ep2_neg_basic(), ep2_neg_projc(), ep2_norm(), ep2_sub_basic(), ep2_sub_projc(), and pp_norm_k12().
void ep2_copy (ep2_t r, ep2_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 49 of file relic_ep2_util.c.
References fp2_copy().
Referenced by ep2_add_basic(), ep2_add_projc(), ep2_add_slp_basic(), ep2_curve_get_gen(), ep2_curve_set(), ep2_mul(), ep2_mul_dig(), ep2_mul_fix_combs(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_nafwi(), ep2_mul_pre_ordin(), ep2_mul_pre_yaowi(), ep2_mul_sim_joint(), ep2_norm(), ep2_tab(), pp_add_k12_basic(), pp_dbl_k12_basic(), pp_mil_k12(), pp_mil_sps_k12(), and pp_norm_k12().
int ep2_cmp (ep2_t p, ep2_t q)
Compares two elliptic curve points.
Parameters
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Returns
CMP_EQ if p == q and CMP_NE if p != q.
Definition at line 56 of file relic_ep2_util.c.
References CMP_EQ, CMP_NE, and fp2_cmp().
void ep2_rand (ep2_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 72 of file relic_ep2_util.c.
References bn_bits(), bn_free, bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ep2_curve_get_gen(), ep2_curve_get_ord(), ep2_free, ep2_mul(), ep2_new, ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_rhs (fp2_t rhs, ep2_t p)
Computes the right-hand side of the elliptic curve equation at a certain elliptic curve point.
Parameters
[out] rhs - the result.
[in] p - the point.
Definition at line 103 of file relic_ep2_util.c.
References CATCH_ANY, ep2_curve_get_a(), ep2_curve_get_b(), ERR_CAUGHT, FINALLY, fp2_add, fp2_copy(), fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, THROW, and TRY.
Referenced by ep2_is_valid(), and ep2_map().
void ep2_tab (ep2_t * t, ep2_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 136 of file relic_ep2_util.c.
References ep2_add, ep2_copy(), ep2_dbl, ep2_norm(), and EP_WIDTH.
Referenced by ep2_mul_sim_ordin().
int ep2_is_valid (ep2_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 155 of file relic_ep2_util.c.
References CATCH_ANY, CMP_EQ, ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep2_rhs(), ERR_CAUGHT, FINALLY, fp2_cmp(), fp2_sqr, THROW, and TRY.
void ep2_print (ep2_t p)
Prints a elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 178 of file relic_ep2_util.c.
References fp2_print().