/*
 * Test data strategy for hacrypto.BCSHA_256.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2014-06-30 15:35 -0700.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package hacrypto.BCSHA_256_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import hacrypto.PackageStrategy_byte;
/**
 * Test data strategy for hacrypto.BCSHA_256. Provides
 * class-scope test values for type byte.
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2014-06-30 15:35 -0700
 */
public /*@ nullable_by_default */ class ClassStrategy_byte 
  extends PackageStrategy_byte {
  /**
   * @return class-scope values for type byte.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add class-scope byte values or generators here */ });
  }
}
