/*
 * Test data strategy for hacrypto.BCSHA_256.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2014-06-30 15:35 -0700.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package hacrypto.BCSHA_256_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import hacrypto.PackageStrategy_byte1DArray;
/**
 * Test data strategy for hacrypto.BCSHA_256. Provides
 * class-scope test values for type byte[].
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2014-06-30 15:35 -0700
 */
public /*@ nullable_by_default */ class ClassStrategy_byte1DArray 
  extends PackageStrategy_byte1DArray {
  /**
   * @return class-scope values for type byte[].
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add class-scope byte[] values or generators here */ });
  }

  /**
   * The maximum length of generated arrays can be controlled here for
   * parameters of type byte[]
   * in this class by changing the parameter to <code>setMaxLength</code>.
   * In addition, the data generators used can be changed by adding 
   * additional data class lines, or by removing some of the automatically 
   * generated ones. Note that lower-level strategies can override any 
   * behavior specified here by calling the same control methods in 
   * their own constructors.
   *
   * @see NonPrimitiveStrategy#addDataClass(Class<?>)
   * @see NonPrimitiveStrategy#clearDataClasses()
   * @see ArrayStrategy#setMaxLength(int)
   */
  public ClassStrategy_byte1DArray() {
    super();
    // uncomment to control the maximum array length, 1 by default
    // setMaxLength(1); 
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
