RELIC: src/eb/relic_eb_param.c File Reference
relic_eb_param.c File Reference
Elliptic curves over binary fields.
#include <string.h>
#include "relic_core.h"
#include "relic_eb.h"
#include "relic_util.h"
#include "relic_conf.h"
#include "relic_arch.h"
Macros
#define ASSIGN(CURVE, FIELD)
#define ASSIGNS(CURVE, FIELD)
#define NIST_B283_A "1"
#define NIST_B283_B "027B680AC8B8596DA5A4AF8A19A0303FCA97FD7645309FA2A581485AF6263E313B79A2F5"
#define NIST_B283_X "05F939258DB7DD90E1934F8C70B0DFEC2EED25B8557EAC9C80E2E198F8CDBECD86B12053"
#define NIST_B283_Y "03676854FE24141CB98FE6D4B20D02B4516FF702350EDDB0826779C813F0DF45BE8112F4"
#define NIST_B283_R "03FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEF90399660FC938A90165B042A7CEFADB307"
#define NIST_B283_H "2"
#define NIST_K283_A "0"
#define NIST_K283_B "1"
#define NIST_K283_X "0503213F78CA44883F1A3B8162F188E553CD265F23C1567A16876913B0C2AC2458492836"
#define NIST_K283_Y "01CCDA380F1C9E318D90F95D07E5426FE87E45C0E8184698E45962364E34116177DD2259"
#define NIST_K283_R "01FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE9AE2ED07577265DFF7F94451E061E163C61"
#define NIST_K283_H "4"
Functions
int eb_param_get ()
void eb_param_set (int param)
int eb_param_set_any ()
int eb_param_set_any_ordin ()
int eb_param_set_any_kbltz ()
int eb_param_set_any_super ()
void eb_param_print ()
int eb_param_level ()
Detailed Description
Implementation of the binary elliptic curve utilities.
Version
Id:
relic_eb_param.c 1520 2013-08-27 15:52:42Z dfaranha
Definition in file relic_eb_param.c.
Macro Definition Documentation
#define NIST_B283_A "1"
Parameters for the NIST B-283 binary elliptic curve.
Definition at line 147 of file relic_eb_param.c.
#define NIST_B283_B "027B680AC8B8596DA5A4AF8A19A0303FCA97FD7645309FA2A581485AF6263E313B79A2F5"
Parameters for the NIST B-283 binary elliptic curve.
Definition at line 148 of file relic_eb_param.c.
#define NIST_B283_X "05F939258DB7DD90E1934F8C70B0DFEC2EED25B8557EAC9C80E2E198F8CDBECD86B12053"
Parameters for the NIST B-283 binary elliptic curve.
Definition at line 149 of file relic_eb_param.c.
#define NIST_B283_Y "03676854FE24141CB98FE6D4B20D02B4516FF702350EDDB0826779C813F0DF45BE8112F4"
Parameters for the NIST B-283 binary elliptic curve.
Definition at line 150 of file relic_eb_param.c.
#define NIST_B283_R "03FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEF90399660FC938A90165B042A7CEFADB307"
Parameters for the NIST B-283 binary elliptic curve.
Definition at line 151 of file relic_eb_param.c.
#define NIST_B283_H "2"
Parameters for the NIST B-283 binary elliptic curve.
Definition at line 152 of file relic_eb_param.c.
#define NIST_K283_A "0"
Parameters for the NIST K-283 binary elliptic curve.
Definition at line 161 of file relic_eb_param.c.
#define NIST_K283_B "1"
Parameters for the NIST K-283 binary elliptic curve.
Definition at line 162 of file relic_eb_param.c.
#define NIST_K283_X "0503213F78CA44883F1A3B8162F188E553CD265F23C1567A16876913B0C2AC2458492836"
Parameters for the NIST K-283 binary elliptic curve.
Definition at line 163 of file relic_eb_param.c.
#define NIST_K283_Y "01CCDA380F1C9E318D90F95D07E5426FE87E45C0E8184698E45962364E34116177DD2259"
Parameters for the NIST K-283 binary elliptic curve.
Definition at line 164 of file relic_eb_param.c.
#define NIST_K283_R "01FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE9AE2ED07577265DFF7F94451E061E163C61"
Parameters for the NIST K-283 binary elliptic curve.
Definition at line 165 of file relic_eb_param.c.
#define NIST_K283_H "4"
Parameters for the NIST K-283 binary elliptic curve.
Definition at line 166 of file relic_eb_param.c.
#define ASSIGN (CURVE, FIELD)
Value:
fb_param_set(FIELD);                                                    \
    FETCH(str, CURVE##_A, sizeof(CURVE##_A));                               \
    fb_read(a, str, strlen(str), 16);                                       \
    FETCH(str, CURVE##_B, sizeof(CURVE##_B));                               \
    fb_read(b, str, strlen(str), 16);                                       \
    FETCH(str, CURVE##_X, sizeof(CURVE##_X));                               \
    fb_read(g->x, str, strlen(str), 16);                                    \
    FETCH(str, CURVE##_Y, sizeof(CURVE##_Y));                               \
    fb_read(g->y, str, strlen(str), 16);                                    \
    FETCH(str, CURVE##_R, sizeof(CURVE##_R));                               \
    bn_read_str(r, str, strlen(str), 16);                                   \
    FETCH(str, CURVE##_H, sizeof(CURVE##_H));                               \
    bn_read_str(h, str, strlen(str), 16);                                   \
Assigns a set of ordinary elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
[in] FIELD - the finite field identifier.
Definition at line 302 of file relic_eb_param.c.
Referenced by eb_param_set().
#define ASSIGNS (CURVE, FIELD)
Value:
ASSIGN(CURVE, FIELD);                                                   \
    FETCH(str, CURVE##_C, sizeof(CURVE##_C));                               \
    fb_read(c, str, strlen(str), 16);                                       \
Assigns a set of supersingular elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
[in] FIELD - the finite field identifier.
Definition at line 323 of file relic_eb_param.c.
Referenced by eb_param_set().
Function Documentation
int eb_param_get (void)
Returns the parameter identifier of the currently configured binary elliptic curve.
Returns
the parameter identifier.
Definition at line 332 of file relic_eb_param.c.
References core_get(), and _ctx_t::eb_id.
void eb_param_set (int param)
Configures a new binary elliptic curve by its parameter identifier.
Parameters
[in] param - the parameters identifier.
Definition at line 336 of file relic_eb_param.c.
References ASSIGN, ASSIGNS, bn_free, bn_new, bn_null, CATCH_ANY, core_get(), eb_curve_set_kbltz(), eb_curve_set_ordin(), eb_curve_set_super(), eb_free, _ctx_t::eb_id, eb_new, eb_null, EBACS_B251, ERR_CAUGHT, ERR_NO_VALID, ETAT_P271, ETAT_S1223, ETAT_S353, ETAT_T271, FB_BYTES, fb_free, fb_new, fb_null, fb_set_bit(), fb_zero(), FINALLY, HALVE_B257, NIST_163, NIST_233, NIST_283, NIST_409, NIST_571, NIST_B163, NIST_B233, NIST_B283, NIST_B409, NIST_B571, NIST_K163, NIST_K233, NIST_K283, NIST_K409, NIST_K571, PENTA_251, PENTA_271, SECG_239, SECG_K239, THROW, TRINO_1223, TRINO_257, TRINO_271, TRINO_353, and TRY.
Referenced by eb_param_set_any_kbltz(), eb_param_set_any_ordin(), and eb_param_set_any_super().
int eb_param_set_any (void)
Configures some set of curve parameters for the current security level.
Definition at line 519 of file relic_eb_param.c.
References eb_param_set_any_kbltz(), eb_param_set_any_ordin(), eb_param_set_any_super(), STS_ERR, and STS_OK.
int eb_param_set_any_ordin (void)
Configures some set of ordinary curve parameters for the current security level.
Returns
STS_OK if there is a curve at this security level, STS_ERR otherwise.
Definition at line 535 of file relic_eb_param.c.
References eb_param_set(), EBACS_B251, HALVE_B257, NIST_B163, NIST_B233, NIST_B283, NIST_B409, NIST_B571, STS_ERR, and STS_OK.
Referenced by eb_param_set_any().
int eb_param_set_any_kbltz (void)
Configures some set of Koblitz curve parameters for the current security level.
Returns
STS_OK if there is a curve at this security level, STS_ERR otherwise.
Definition at line 561 of file relic_eb_param.c.
References eb_param_set(), NIST_K163, NIST_K233, NIST_K283, NIST_K409, NIST_K571, SECG_K239, STS_ERR, and STS_OK.
Referenced by eb_param_set_any().
int eb_param_set_any_super (void)
Configures some set of supersingular curve parameters for the current security level.
Returns
STS_OK if there is a curve at this security level, STS_ERR otherwise.
Definition at line 585 of file relic_eb_param.c.
References eb_param_set(), ETAT_P271, ETAT_S1223, ETAT_S353, ETAT_T271, STS_ERR, and STS_OK.
Referenced by eb_param_set_any().
void eb_param_print (void)
Prints the current configured binary elliptic curve.
Definition at line 607 of file relic_eb_param.c.
References core_get(), EBACS_B251, ETAT_P271, ETAT_S1223, ETAT_S353, ETAT_T271, HALVE_B257, NIST_B163, NIST_B233, NIST_B283, NIST_B409, NIST_B571, NIST_K163, NIST_K233, NIST_K283, NIST_K409, NIST_K571, SECG_K239, and util_banner.
int eb_param_level (void)
Returns the current security level.
Definition at line 663 of file relic_eb_param.c.
References core_get(), EBACS_B251, ETAT_P271, ETAT_S1223, ETAT_S353, ETAT_T271, HALVE_B257, NIST_B163, NIST_B233, NIST_B283, NIST_B409, NIST_B571, NIST_K163, NIST_K233, NIST_K283, NIST_K409, NIST_K571, and SECG_K239.