/*
 * crypto_rng/try-notest.c version 20180223
 * D. J. Bernstein
 * Public domain.
 * Auto-generated by trygen-notest.py; do not edit.
 */

#include "crypto_rng.h"
#include "try.h"

const char *primitiveimplementation = crypto_rng_implementation;

#define TUNE_BYTES 1536
#ifdef SMALL
#define MAXTEST_BYTES 128
#else
#define MAXTEST_BYTES 4096
#endif
#ifdef SMALL
#define LOOPS 64
#else
#define LOOPS 512
#endif

static unsigned char *k;
static unsigned char *r;
static unsigned char *n;
static unsigned char *k2;
static unsigned char *r2;
static unsigned char *n2;
#define klen crypto_rng_KEYBYTES
#define rlen crypto_rng_OUTPUTBYTES
#define nlen crypto_rng_KEYBYTES

void preallocate(void)
{
}

void allocate(void)
{
  unsigned long long alloclen = 0;
  if (alloclen < TUNE_BYTES) alloclen = TUNE_BYTES;
  if (alloclen < MAXTEST_BYTES) alloclen = MAXTEST_BYTES;
  if (alloclen < crypto_rng_KEYBYTES) alloclen = crypto_rng_KEYBYTES;
  if (alloclen < crypto_rng_OUTPUTBYTES) alloclen = crypto_rng_OUTPUTBYTES;
  if (alloclen < crypto_rng_KEYBYTES) alloclen = crypto_rng_KEYBYTES;
  k = alignedcalloc(alloclen);
  r = alignedcalloc(alloclen);
  n = alignedcalloc(alloclen);
  k2 = alignedcalloc(alloclen);
  r2 = alignedcalloc(alloclen);
  n2 = alignedcalloc(alloclen);
}

void predoit(void)
{
}

void doit(void)
{
  crypto_rng(r,n,k);
}
