RELIC: include/relic_epx.h File Reference
relic_epx.h File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_fpx.h"
#include "relic_ep.h"
#include "relic_types.h"
Data Structures
struct ep2_st
struct ep3_st
Macros
#define ep2_null(A) /* empty */
#define ep2_new(A) /* empty */
#define ep2_free(A) /* empty */
#define ep2_neg(R, P) ep2_neg_projc(R, P)
#define ep2_add(R, P, Q) ep2_add_projc(R, P, Q);
#define ep2_sub(R, P, Q) ep2_sub_projc(R, P, Q)
#define ep2_dbl(R, P) ep2_dbl_projc(R, P);
#define ep2_mul_pre(T, P) ep2_mul_pre_combs(T, P)
#define ep2_mul_fix(R, T, K) ep2_mul_fix_combs(R, T, K)
#define ep2_mul_sim(R, P, K, Q, L) ep2_mul_sim_inter(R, P, K, Q, L)
Typedefs
typedef ep2_st ep2_t [1]
typedef ep3_st ep3_t [1]
Functions
void ep2_curve_init (void)
void ep2_curve_clean (void)
void ep2_curve_get_a (fp2_t a)
void ep2_curve_get_b (fp2_t b)
int ep2_curve_opt_a (void)
int ep2_curve_is_twist (void)
void ep2_curve_get_gen (ep2_t g)
ep2_t * ep2_curve_get_tab (void)
void ep2_curve_get_ord (bn_t n)
void ep2_curve_set (int twist)
int ep2_is_infty (ep2_t p)
void ep2_set_infty (ep2_t p)
void ep2_copy (ep2_t r, ep2_t p)
int ep2_cmp (ep2_t p, ep2_t q)
void ep2_rand (ep2_t p)
void ep2_rhs (fp2_t rhs, ep2_t p)
int ep2_is_valid (ep2_t p)
void ep2_tab (ep2_t *t, ep2_t p, int w)
void ep2_print (ep2_t p)
void ep2_neg_basic (ep2_t r, ep2_t p)
void ep2_neg_projc (ep2_t r, ep2_t p)
void ep2_add_basic (ep2_t r, ep2_t p, ep2_t q)
void ep2_add_slp_basic (ep2_t r, fp2_t s, ep2_t p, ep2_t q)
void ep2_sub_basic (ep2_t r, ep2_t p, ep2_t q)
void ep2_add_projc (ep2_t r, ep2_t p, ep2_t q)
void ep2_sub_projc (ep2_t r, ep2_t p, ep2_t q)
void ep2_dbl_basic (ep2_t r, ep2_t p)
void ep2_dbl_slp_basic (ep2_t r, fp2_t s, ep2_t p)
void ep2_dbl_projc (ep2_t r, ep2_t p)
void ep2_mul (ep2_t r, ep2_t p, bn_t k)
void ep2_mul_gen (ep2_t r, bn_t k)
void ep2_mul_pre_basic (ep2_t *t, ep2_t p)
void ep2_mul_pre_yaowi (ep2_t *t, ep2_t p)
void ep2_mul_pre_nafwi (ep2_t *t, ep2_t p)
void ep2_mul_pre_combs (ep2_t *t, ep2_t p)
void ep2_mul_pre_combd (ep2_t *t, ep2_t p)
void ep2_mul_pre_lwnaf (ep2_t *t, ep2_t p)
void ep2_mul_fix_basic (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_fix_yaowi (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_fix_nafwi (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_fix_combs (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_fix_combd (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_fix_lwnaf (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_sim_basic (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
void ep2_mul_sim_trick (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
void ep2_mul_sim_inter (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
void ep2_mul_sim_joint (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
void ep2_mul_sim_gen (ep2_t r, bn_t k, ep2_t q, bn_t l)
void ep2_mul_dig (ep2_t r, ep2_t p, dig_t k)
void ep2_norm (ep2_t r, ep2_t p)
void ep2_map (ep2_t p, unsigned char *msg, int len)
void ep2_frb (ep2_t r, ep2_t p, int i)
Detailed Description
Interface of the module for arithmetic on prime elliptic curves defined over extension fields.
Version
Id:
relic_pp.h 1148 2012-04-01 20:35:37Z dfaranha
Definition in file relic_epx.h.
Macro Definition Documentation
#define ep2_null (A) /* empty */
Initializes a point on a elliptic curve with a null value.
Parameters
[out] A - the point to initialize.
Definition at line 106 of file relic_epx.h.
Referenced by ep2_curve_set(), ep2_is_valid(), ep2_mul(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_nafwi(), ep2_mul_fix_yaowi(), ep2_mul_gen(), ep2_mul_sim_basic(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_ordin(), ep2_mul_sim_trick(), ep2_rand(), ep2_sub_basic(), ep2_sub_projc(), pp_add_k12_basic(), pp_dbl_k12_basic(), pp_fin_k12_oatep(), pp_map_oatep_k12(), pp_map_weilp_k12(), and pp_mil_sps_k12().
#define ep2_new (A) /* empty */
Calls a function to allocate a point on a elliptic curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 144 of file relic_epx.h.
Referenced by ep2_curve_set(), ep2_is_valid(), ep2_mul(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_nafwi(), ep2_mul_fix_yaowi(), ep2_mul_gen(), ep2_mul_sim_basic(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_ordin(), ep2_mul_sim_trick(), ep2_rand(), ep2_sub_basic(), ep2_sub_projc(), pp_add_k12_basic(), pp_dbl_k12_basic(), pp_fin_k12_oatep(), pp_map_oatep_k12(), pp_map_weilp_k12(), and pp_mil_sps_k12().
#define ep2_free (A) /* empty */
Calls a function to clean and free a point on a elliptic curve.
Parameters
[out] A - the point to free.
Definition at line 180 of file relic_epx.h.
Referenced by ep2_curve_set(), ep2_is_valid(), ep2_mul(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_nafwi(), ep2_mul_fix_yaowi(), ep2_mul_gen(), ep2_mul_sim_basic(), ep2_mul_sim_gen(), ep2_mul_sim_joint(), ep2_mul_sim_ordin(), ep2_mul_sim_trick(), ep2_rand(), ep2_sub_basic(), ep2_sub_projc(), pp_add_k12_basic(), pp_dbl_k12_basic(), pp_fin_k12_oatep(), pp_map_oatep_k12(), pp_map_weilp_k12(), pp_map_weilp_k2(), and pp_mil_sps_k12().
#define ep2_neg (R, P) ep2_neg_projc(R, P)
Negates a point in an elliptic curve over a quadratic extension field.
Parameters
[out] R - the result.
[in] P - the point to negate.
Definition at line 194 of file relic_epx.h.
Referenced by ep2_mul_cof_b12(), ep2_mul_cof_bn(), pp_fin_k12_oatep(), pp_map_oatep_k12(), and pp_mil_sps_k12().
#define ep2_add (R, P, Q) ep2_add_projc(R, P, Q);
Adds two points in an elliptic curve over a quadratic extension field. Computes R = P + Q.
Parameters
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add.
Definition at line 208 of file relic_epx.h.
Referenced by ep2_mul(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_nafwi(), ep2_mul_fix_ordin(), ep2_mul_fix_yaowi(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_ordin(), ep2_mul_sim_basic(), ep2_mul_sim_joint(), ep2_mul_sim_ordin(), ep2_mul_sim_trick(), and ep2_tab().
#define ep2_sub (R, P, Q) ep2_sub_projc(R, P, Q)
Subtracts a point in an elliptic curve over a quadratic extension field from another point in this curve. Computes R = P - Q.
Parameters
[out] R - the result.
[in] P - the first point.
[in] Q - the second point.
Definition at line 222 of file relic_epx.h.
Referenced by ep2_mul_cof_b12(), ep2_mul_fix_nafwi(), ep2_mul_fix_ordin(), ep2_mul_sim_joint(), and ep2_mul_sim_ordin().
#define ep2_dbl (R, P) ep2_dbl_projc(R, P);
Doubles a point in an elliptic curve over a quadratic extension field. Computes R = 2 * P.
Parameters
[out] R - the result.
[in] P - the point to double.
Definition at line 235 of file relic_epx.h.
Referenced by ep2_add_projc(), ep2_mul(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_ordin(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_nafwi(), ep2_mul_pre_ordin(), ep2_mul_sim_joint(), ep2_mul_sim_ordin(), ep2_mul_sim_trick(), and ep2_tab().
#define ep2_mul_pre (T, P) ep2_mul_pre_combs(T, P)
Builds a precomputation table for multiplying a fixed prime elliptic point over a quadratic extension.
Parameters
[out] T - the precomputation table.
[in] P - the point to multiply.
Definition at line 252 of file relic_epx.h.
Referenced by ep2_curve_set().
#define ep2_mul_fix (R, T, K) ep2_mul_fix_combs(R, T, K)
Multiplies a fixed prime elliptic point over a quadratic extension using a precomputation table. Computes R = kP.
Parameters
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer.
Definition at line 277 of file relic_epx.h.
Referenced by ep2_mul_gen().
#define ep2_mul_sim (R, P, K, Q, L) ep2_mul_sim_inter(R, P, K, Q, L)
Multiplies and adds two prime elliptic curve points simultaneously. Computes R = kP + lQ.
Parameters
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] L - the second integer,
Definition at line 302 of file relic_epx.h.
Referenced by ep2_mul_sim_gen().
Typedef Documentation
typedef ep2_st ep2_t[1]
Pointer to an elliptic curve point.
Definition at line 67 of file relic_epx.h.
typedef ep3_st ep3_t[1]
Pointer to an elliptic curve point.
Definition at line 91 of file relic_epx.h.
Function Documentation
void ep2_curve_init (void)
Initializes the elliptic curve over quadratic extension.
Definition at line 153 of file relic_ep2_curve.c.
References bn_init(), core_get(), _ctx_t::ep2_g, _ctx_t::ep2_pre, _ctx_t::ep2_ptr, _ctx_t::ep2_r, ep2_set_infty(), EP_TABLE, fp2_new, FP_DIGS, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by pp_map_init().
void ep2_curve_clean (void)
Finalizes the elliptic curve over quadratic extension.
Definition at line 193 of file relic_ep2_curve.c.
References bn_clean(), core_get(), _ctx_t::ep2_pre, _ctx_t::ep2_r, EP_TABLE, fp2_free, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by pp_map_clean().
void ep2_curve_get_a (fp2_t a)
Returns the a coefficient of the currently configured elliptic curve.
Parameters
[out] a - the a coefficient of the elliptic curve.
Definition at line 213 of file relic_ep2_curve.c.
References core_get(), _ctx_t::ep2_a, and fp_copy().
Referenced by ep2_rhs().
void ep2_curve_get_b (fp2_t b)
Returns the b coefficient of the currently configured elliptic curve.
Parameters
[out] b - the b coefficient of the elliptic curve.
Definition at line 219 of file relic_ep2_curve.c.
References core_get(), _ctx_t::ep2_b, and fp_copy().
Referenced by ep2_rhs(), pp_dbl_k12_projc_basic(), and pp_dbl_k12_projc_lazyr().
int ep2_curve_opt_a (void)
Returns a optimization identifier based on the coefficient a of the curve.
Returns
the optimization identifier.
int ep2_curve_is_twist (void)
Tests if the configured elliptic curve is a twist.
Returns
1 if the elliptic curve is a twist, 0 otherwise.
Definition at line 205 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_is_twist.
Referenced by ep2_dbl_basic_imp(), ep2_frb(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_lit_k12(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), and pp_dbl_lit_k12().
void ep2_curve_get_gen (ep2_t g)
Returns the generator of the group of points in the elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 209 of file relic_ep2_curve.c.
References core_get(), and ep2_copy().
Referenced by ep2_mul_gen(), ep2_mul_sim_gen(), and ep2_rand().
ep2_t* ep2_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 236 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_ptr.
Referenced by ep2_curve_set(), ep2_mul_gen(), and ep2_mul_sim_ordin().
void ep2_curve_get_ord (bn_t n)
Returns the order of the group of points in the elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 225 of file relic_ep2_curve.c.
References bn_copy(), core_get(), _ctx_t::ep2_is_twist, _ctx_t::ep2_r, and ep_curve_get_ord().
Referenced by ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_nafwi(), ep2_mul_pre_yaowi(), ep2_mul_sim_trick(), and ep2_rand().
void ep2_curve_set (int twist)
Configures a new elliptic curve by using the curve over the base prime field as a parameter.
Parameters
- the flag indicating that the curve is a twist.
Definition at line 246 of file relic_ep2_curve.c.
References ASSIGN, B12_P638, bn_copy(), bn_free, bn_new, bn_null, BN_P158, BN_P254, BN_P256, BN_P638, CATCH_ANY, core_get(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_copy(), ep2_curve_get_tab(), ep2_free, _ctx_t::ep2_g, _ctx_t::ep2_is_twist, ep2_mul_pre, ep2_new, ep2_null, _ctx_t::ep2_r, ep_param_get(), ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp2_free, fp2_new, fp2_null, fp2_zero(), FP_BYTES, fp_copy(), fp_prime_calc(), fp_set_dig(), THROW, and TRY.
Referenced by ep_param_set_any_pairf().
int ep2_is_infty (ep2_t p)
Tests if a point on a elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep2_util.c.
References fp2_is_zero().
Referenced by ep2_add_basic(), ep2_add_projc(), ep2_add_slp_basic(), ep2_dbl_basic(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_is_valid(), ep2_neg_basic(), ep2_neg_projc(), ep2_norm(), and pp_norm_k12().
void ep2_set_infty (ep2_t p)
Assigns a elliptic curve point to a point at the infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep2_util.c.
References fp2_zero().
Referenced by ep2_add_basic_imp(), ep2_add_projc_imp(), ep2_add_projc_mix(), ep2_curve_init(), ep2_dbl_basic(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_mul(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_nafwi(), ep2_mul_fix_ordin(), ep2_mul_fix_yaowi(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_sim_joint(), ep2_mul_sim_ordin(), ep2_mul_sim_trick(), ep2_neg_basic(), ep2_neg_projc(), ep2_norm(), ep2_sub_basic(), ep2_sub_projc(), and pp_norm_k12().
void ep2_copy (ep2_t r, ep2_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 49 of file relic_ep2_util.c.
References fp2_copy().
Referenced by ep2_add_basic(), ep2_add_projc(), ep2_add_slp_basic(), ep2_curve_get_gen(), ep2_curve_set(), ep2_mul(), ep2_mul_dig(), ep2_mul_fix_combs(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_nafwi(), ep2_mul_pre_ordin(), ep2_mul_pre_yaowi(), ep2_mul_sim_joint(), ep2_norm(), ep2_tab(), pp_add_k12_basic(), pp_dbl_k12_basic(), pp_mil_k12(), pp_mil_sps_k12(), and pp_norm_k12().
int ep2_cmp (ep2_t p, ep2_t q)
Compares two elliptic curve points.
Parameters
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Returns
CMP_EQ if p == q and CMP_NE if p != q.
Definition at line 56 of file relic_ep2_util.c.
References CMP_EQ, CMP_NE, and fp2_cmp().
void ep2_rand (ep2_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 72 of file relic_ep2_util.c.
References bn_bits(), bn_free, bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ep2_curve_get_gen(), ep2_curve_get_ord(), ep2_free, ep2_mul(), ep2_new, ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_rhs (fp2_t rhs, ep2_t p)
Computes the right-hand side of the elliptic curve equation at a certain elliptic curve point.
Parameters
[out] rhs - the result.
[in] p - the point.
Definition at line 103 of file relic_ep2_util.c.
References CATCH_ANY, ep2_curve_get_a(), ep2_curve_get_b(), ERR_CAUGHT, FINALLY, fp2_add, fp2_copy(), fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, THROW, and TRY.
Referenced by ep2_is_valid(), and ep2_map().
int ep2_is_valid (ep2_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 155 of file relic_ep2_util.c.
References CATCH_ANY, CMP_EQ, ep2_free, ep2_is_infty(), ep2_new, ep2_norm(), ep2_null, ep2_rhs(), ERR_CAUGHT, FINALLY, fp2_cmp(), fp2_sqr, THROW, and TRY.
void ep2_tab (ep2_t * t, ep2_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 136 of file relic_ep2_util.c.
References ep2_add, ep2_copy(), ep2_dbl, ep2_norm(), and EP_WIDTH.
Referenced by ep2_mul_sim_ordin().
void ep2_print (ep2_t p)
Prints a elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 178 of file relic_ep2_util.c.
References fp2_print().
void ep2_neg_basic (ep2_t r, ep2_t p)
Negates a point represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 41 of file relic_ep2_neg.c.
References ep2_is_infty(), ep2_set_infty(), fp2_copy(), and fp2_neg().
Referenced by ep2_sub_basic().
void ep2_neg_projc (ep2_t r, ep2_t p)
Negates a point represented in projective coordinates in an elliptic curve over a quadratic exyension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 61 of file relic_ep2_neg.c.
References ep2_is_infty(), ep2_set_infty(), fp2_copy(), and fp2_neg().
Referenced by ep2_sub_projc().
void ep2_add_basic (ep2_t r, ep2_t p, ep2_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 358 of file relic_ep2_add.c.
References ep2_add_basic_imp(), ep2_copy(), and ep2_is_infty().
Referenced by ep2_sub_basic().
void ep2_add_slp_basic (ep2_t r, fp2_t s, ep2_t p, ep2_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quadratic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 372 of file relic_ep2_add.c.
References ep2_add_basic_imp(), ep2_copy(), and ep2_is_infty().
Referenced by pp_add_k12_basic().
void ep2_sub_basic (ep2_t r, ep2_t p, ep2_t q)
Subtracts a points represented in affine coordinates in an elliptic curve over a quadratic extension from another point.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 386 of file relic_ep2_add.c.
References CATCH_ANY, ep2_add_basic(), ep2_free, ep2_neg_basic(), ep2_new, ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_add_projc (ep2_t r, ep2_t p, ep2_t q)
Adds two points represented in projective coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 416 of file relic_ep2_add.c.
References ep2_add_projc_imp(), ep2_copy(), ep2_dbl, and ep2_is_infty().
Referenced by ep2_sub_projc().
void ep2_sub_projc (ep2_t r, ep2_t p, ep2_t q)
Subtracts a points represented in projective coordinates in an elliptic curve over a quadratic extension from another point.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 436 of file relic_ep2_add.c.
References CATCH_ANY, ep2_add_projc(), ep2_free, ep2_neg_projc(), ep2_new, ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_dbl_basic (ep2_t r, ep2_t p)
Doubles a points represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
int] p - the point to double.
Definition at line 199 of file relic_ep2_dbl.c.
References ep2_dbl_basic_imp(), ep2_is_infty(), and ep2_set_infty().
Referenced by ep2_add_basic_imp(), and ep2_mul_pre_yaowi().
void ep2_dbl_slp_basic (ep2_t r, fp2_t s, ep2_t p)
Doubles a points represented in affine coordinates in an elliptic curve over a quadratic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 208 of file relic_ep2_dbl.c.
References ep2_dbl_basic_imp(), ep2_is_infty(), and ep2_set_infty().
Referenced by pp_dbl_k12_basic().
void ep2_dbl_projc (ep2_t r, ep2_t p)
Doubles a points represented in projective coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 221 of file relic_ep2_dbl.c.
References ep2_dbl_projc_imp(), ep2_is_infty(), and ep2_set_infty().
Referenced by ep2_add_projc_imp(), and ep2_add_projc_mix().
void ep2_mul (ep2_t r, ep2_t p, bn_t k)
Multiplies a point in a elliptic curve over a quadratic extension by an integer scalar.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the scalar.
Definition at line 39 of file relic_ep2_mul.c.
References bn_bits(), bn_test_bit(), CATCH_ANY, ep2_add, ep2_copy(), ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_gen(), ep2_mul_sim_basic(), and ep2_rand().
void ep2_mul_gen (ep2_t r, bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 72 of file relic_ep2_mul.c.
References CATCH_ANY, ep2_curve_get_gen(), ep2_curve_get_tab(), ep2_free, ep2_mul(), ep2_mul_fix, ep2_new, ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_pre_basic (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 112 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_pre_yaowi (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 154 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ep2_dbl_basic(), EP_DEPTH, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_pre_nafwi (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 219 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, EP_DEPTH, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_pre_combs (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 309 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), EP_DEPTH, EP_TABLE_COMBS, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_pre_combd (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 407 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), EP_DEPTH, EP_TABLE_COMBD, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_pre_lwnaf (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 512 of file relic_ep2_mul_fix.c.
References ep2_mul_pre_ordin().
void ep2_mul_fix_basic (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 135 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_test_bit(), ep2_add, ep2_norm(), and ep2_set_infty().
void ep2_mul_fix_yaowi (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 181 of file relic_ep2_mul_fix.c.
References bn_rec_win(), CATCH_ANY, CEIL, ep2_add, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), EP_DEPTH, ERR_CAUGHT, FINALLY, FP_BITS, THROW, and TRY.
void ep2_mul_fix_nafwi (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 248 of file relic_ep2_mul_fix.c.
References bn_rec_naf(), CATCH_ANY, ep2_add, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub, EP_DEPTH, ERR_CAUGHT, FINALLY, FP_BITS, THROW, and TRY.
void ep2_mul_fix_combs (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 351 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_test_bit(), CATCH_ANY, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), EP_DEPTH, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_fix_combd (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 456 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_test_bit(), CATCH_ANY, ep2_add, ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), EP_DEPTH, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_fix_lwnaf (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 516 of file relic_ep2_mul_fix.c.
References ep2_mul_fix_ordin().
void ep2_mul_sim_basic (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] l - the second integer,
Definition at line 128 of file relic_ep2_mul_sim.c.
References CATCH_ANY, ep2_add, ep2_free, ep2_mul(), ep2_new, ep2_norm(), ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_sim_trick (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] l - the second integer,
Definition at line 152 of file relic_ep2_mul_sim.c.
References bn_free, bn_new, bn_null, bn_rec_win(), CATCH_ANY, CEIL, ep2_add, ep2_curve_get_ord(), ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), EP_WIDTH, ERR_CAUGHT, FINALLY, FP_BITS, MAX, THROW, and TRY.
void ep2_mul_sim_inter (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] l - the second integer,
Definition at line 237 of file relic_ep2_mul_sim.c.
References ep2_mul_sim_ordin().
void ep2_mul_sim_joint (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] l - the second integer,
Definition at line 255 of file relic_ep2_mul_sim.c.
References bn_bits(), bn_rec_jsf(), CATCH_ANY, ep2_add, ep2_copy(), ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub, ERR_CAUGHT, FINALLY, FP_BITS, MAX, THROW, and TRY.
void ep2_mul_sim_gen (ep2_t r, bn_t k, ep2_t q, bn_t l)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = kG + lQ.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] l - the second integer,
Definition at line 317 of file relic_ep2_mul_sim.c.
References CATCH_ANY, ep2_curve_get_gen(), ep2_free, ep2_mul_sim, ep2_mul_sim_ordin(), ep2_new, ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_dig (ep2_t r, ep2_t p, dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 94 of file relic_ep2_mul.c.
References CATCH_ANY, ep2_add, ep2_copy(), ep2_dbl, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, TRY, and util_bits_dig().
void ep2_norm (ep2_t r, ep2_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 85 of file relic_ep2_norm.c.
References ep2_copy(), ep2_is_infty(), ep2_norm_imp(), and ep2_set_infty().
Referenced by ep2_is_valid(), ep2_mul(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_nafwi(), ep2_mul_fix_ordin(), ep2_mul_fix_yaowi(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_ordin(), ep2_mul_sim_basic(), ep2_mul_sim_joint(), ep2_mul_sim_ordin(), ep2_mul_sim_trick(), and ep2_tab().
void ep2_map (ep2_t p, unsigned char * msg, int len)
Maps a byte array to a point in an elliptic curve over a quadratic extension.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 163 of file relic_ep2_map.c.
References B12_P638, bn_free, bn_new, bn_null, BN_P158, BN_P254, BN_P256, BN_P638, bn_read_bin(), CATCH_ANY, ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_rhs(), ep_param_get(), ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, fp2_srt(), fp_add_dig(), FP_BYTES, fp_prime_conv(), fp_set_dig(), fp_zero(), MD_LEN, md_map, MIN, THROW, and TRY.
void ep2_frb (ep2_t r, ep2_t p, int i)
Computes a power of the Gailbraith-Lin-Scott homomorphism of a point represented in affine coordinates on a twisted elliptic curve over a quadratic exension. That is, Psi^i(P) = Twist(P)(Frob^i(unTwist(P)). On the trace-zero group of a quadratic twist, consists of a power of the Frobenius map of a point represented in affine coordinates in an elliptic curve over a quadratic exension. Computes Frob^i(P) = (p^i)P.
Parameters
[out] r - the result in affine coordinates.
[in] p - a point in affine coordinates.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_ep2_frb.c.
References ep2_curve_is_twist(), EP_MTYPE, fp2_frb(), fp2_mul_art(), fp2_mul_frb(), fp2_neg(), fp_copy(), fp_neg, fp_set_dig(), and fp_zero().
Referenced by ep2_mul_cof_b12(), ep2_mul_cof_bn(), and pp_fin_k12_oatep().