RELIC: src/fbx/relic_fb2_mul.c File Reference
relic_fb2_mul.c File Reference
Extensions of binary fields.
#include "relic_core.h"
#include "relic_fbx.h"
#include "relic_fb_low.h"
Functions
void fb2_mul (fb2_t c, fb2_t a, fb2_t b)
void fb2_mul_nor (fb2_t c, fb2_t a)
Detailed Description
Implementation of multiplication in quadratic extensions of binary fields.
Version
Id:
relic_fb2_mul.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_fb2_mul.c.
Function Documentation
void fb2_mul (fb2_t c, fb2_t a, fb2_t b)
Multiples two quadratic extension field elements. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the quadratic extension binary field element.
[in] b - the quadratic extension binary field element.
Definition at line 40 of file relic_fb2_mul.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_free, fb_mul, fb_new, fb_null, FINALLY, THROW, and TRY.
Referenced by etat_exp(), and fb4_inv().
void fb2_mul_nor (fb2_t c, fb2_t a)
Multiples a quadratic extension field element by a quadratic non-residue. Computes c = a * s.
Parameters
[out] c - the result.
[in] a - the quadratic extension binary field element.
[in] b - the quadratic extension binary field element.
Definition at line 70 of file relic_fb2_mul.c.
References CATCH_ANY, ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_new, fb_null, FINALLY, THROW, and TRY.