RELIC: src/epx/relic_ep2_map.c File Reference
relic_ep2_map.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_md.h"
Functions
void ep2_mul_cof_bn (ep2_t r, ep2_t p)
void ep2_mul_cof_b12 (ep2_t r, ep2_t p)
void ep2_map (ep2_t p, unsigned char *msg, int len)
Detailed Description
Implementation of hashing to a prime elliptic curve over a quadratic extension.
Version
Id:
relic_ep2_map.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_ep2_map.c.
Function Documentation
void ep2_mul_cof_bn (ep2_t r, ep2_t p)
Multiplies a point on a Barreto-Naehrig curve by the cofactor.
Parameters
[out] r - the result.
[in] p - the point to multiply.
Definition at line 46 of file relic_ep2_map.c.
References bn_free, BN_NEG, bn_new, bn_null, bn_sign(), CATCH_ANY, ep2_add, ep2_dbl, ep2_frb(), ep2_free, ep2_mul(), ep2_neg, ep2_new, ep2_norm(), ep2_null, ERR_CAUGHT, FINALLY, fp_param_get_var(), THROW, and TRY.
Referenced by ep2_map().
void ep2_mul_cof_b12 (ep2_t r, ep2_t p)
Multiplies a point on a Barreto-Lynn-Soctt curve by the cofactor.
Parameters
[out] r - the result.
[in] p - the point to multiply.
Definition at line 102 of file relic_ep2_map.c.
References bn_free, BN_NEG, bn_new, bn_null, bn_sign(), CATCH_ANY, ep2_add, ep2_dbl, ep2_frb(), ep2_free, ep2_mul(), ep2_neg, ep2_new, ep2_norm(), ep2_null, ep2_sub, ERR_CAUGHT, FINALLY, fp_param_get_var(), THROW, and TRY.
Referenced by ep2_map().
void ep2_map (ep2_t p, unsigned char * msg, int len)
Maps a byte array to a point in an elliptic curve over a quadratic extension.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 163 of file relic_ep2_map.c.
References B12_P638, bn_free, bn_new, bn_null, BN_P158, BN_P254, BN_P256, BN_P638, bn_read_bin(), CATCH_ANY, ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_rhs(), ep_param_get(), ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, fp2_srt(), fp_add_dig(), FP_BYTES, fp_prime_conv(), fp_set_dig(), fp_zero(), MD_LEN, md_map, MIN, THROW, and TRY.