RELIC: src/eb/relic_eb_hlv.c File Reference
relic_eb_hlv.c File Reference
Elliptic curves over binary fields.
#include "string.h"
#include "relic_core.h"
#include "relic_eb.h"
Functions
void eb_hlv (eb_t r, const eb_t p)
Detailed Description
Implementation of point doubling on binary elliptic curves.
Version
Id:
relic_eb_hlv.c 1573 2013-09-02 07:17:18Z dfaranha
Definition in file relic_eb_hlv.c.
Function Documentation
void eb_hlv (eb_t r, const eb_t p)
Halves a point represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to halve.
Definition at line 41 of file relic_eb_hlv.c.
References CATCH_ANY, eb_curve_get_a(), eb_curve_opt_a(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_free, fb_mul, fb_new, fb_null, fb_set_dig(), fb_slv, fb_srt, fb_trc, FINALLY, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by eb_mul_halve().