RELIC: src/fpx/relic_fp6_sqr.c File Reference
relic_fp6_sqr.c File Reference
Extensions of prime fields.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_pp_low.h"
Functions
void fp6_sqr_basic (fp6_t c, fp6_t a)
void fp6_sqr_unr (dv6_t c, fp6_t a)
void fp6_sqr_lazyr (fp6_t c, fp6_t a)
Detailed Description
Implementation of squaring in a sextic extension of a prime field.
Version
Id:
relic_fp6_sqr.c 1590 2013-09-03 08:20:00Z dfaranha
Definition in file relic_fp6_sqr.c.
Function Documentation
void fp6_sqr_basic (fp6_t c, fp6_t a)
Computes the squares of a sextic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 42 of file relic_fp6_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_add, fp2_dbl, fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_hlv, THROW, and TRY.
Referenced by fp12_inv().
void fp6_sqr_unr (dv6_t c, fp6_t a)
Computes the square of a sextic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 175 of file relic_fp6_sqr.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_addd_low(), fp2_addm_low(), fp2_dblm_low(), fp2_free, fp2_mulc_low(), fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_null, fp2_sqrn_low(), fp2_subc_low(), fp2_subm_low(), fp_hlvd_low(), THROW, and TRY.
Referenced by fp18_sqr_lazyr(), and fp6_sqr_lazyr().
void fp6_sqr_lazyr (fp6_t c, fp6_t a)
Computes the square of a sextic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 276 of file relic_fp6_sqr.c.
References CATCH_ANY, dv6_free, dv6_new, dv6_null, ERR_CAUGHT, FINALLY, fp2_rdcn_low(), fp6_sqr_unr(), THROW, and TRY.