RELIC: src/cp/relic_cp_bbs.c File Reference
relic_cp_bbs.c File Reference
Cryptographic protocols.
#include "relic.h"
#include "relic_test.h"
#include "relic_bench.h"
Functions
void cp_bbs_gen (bn_t d, g2_t q, gt_t z)
void cp_bbs_sig (g1_t s, unsigned char *msg, int len, int hash, bn_t d)
int cp_bbs_ver (g1_t s, unsigned char *msg, int len, int hash, g2_t q, gt_t z)
Detailed Description
Implementation of the Boneh-Lynn-Schacham short signature protocol.
Version
Id:
relic_cp_bbs.c 1505 2013-06-26 20:34:20Z conradoplg
Definition in file relic_cp_bbs.c.
Function Documentation
void cp_bbs_gen (bn_t d, g2_t q, gt_t z)
Generates a Boneh-Boyen key pair.
Parameters
[out] d - the private key.
[in] q - the first component of the public key.
[in] q - the second component of the public key.
Definition at line 40 of file relic_cp_bbs.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_get_gen, g1_new, g1_null, g2_get_gen, g2_get_ord, g2_mul_gen, g2_norm, pc_map, pc_param_level, THROW, and TRY.
void cp_bbs_sig (g1_t s, unsigned char * msg, int len, int hash, bn_t d)
Signs a message using Boneh-Boyen Short Signature.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] d - the private key.
Definition at line 76 of file relic_cp_bbs.c.
References bn_add(), bn_free, bn_gcd_ext, bn_mod, BN_NEG, bn_new, bn_null, bn_read_bin(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_get_ord, g1_mul_gen, MD_LEN, md_map, THROW, and TRY.
int cp_bbs_ver (g1_t s, unsigned char * msg, int len, int hash, g2_t q, gt_t z)
Verifies a message signed with BLS using the basic method.
Parameters
[in] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] q - the public key.
Returns
a boolean value indicating the verification result.
Definition at line 119 of file relic_cp_bbs.c.
References bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), CATCH_ANY, CMP_EQ, ERR_CAUGHT, FINALLY, g2_add, g2_free, g2_get_ord, g2_mul_gen, g2_new, g2_norm, g2_null, gt_cmp, gt_free, gt_new, gt_null, MD_LEN, md_map, pc_map, THROW, and TRY.