RELIC: src/fpx/relic_fp18_sqr.c File Reference
relic_fp18_sqr.c File Reference
Extensions of prime fields.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_pp_low.h"
Functions
void fp18_sqr_basic (fp18_t c, fp18_t a)
void fp18_sqr_lazyr (fp18_t c, fp18_t a)
void fp18_sqr_cyc (fp18_t c, fp18_t a)
void fp18_sqr_pck (fp18_t c, fp18_t a)
Detailed Description
Implementation of squaring in a octodecic extension of a prime field.
Version
Id:
relic_fp18_sqr.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_fp18_sqr.c.
Function Documentation
void fp18_sqr_basic (fp18_t c, fp18_t a)
Computes the square of a octodecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the octodecic extension field element to square.
Definition at line 42 of file relic_fp18_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_add(), fp6_dbl(), fp6_free, fp6_mul, fp6_mul_art(), fp6_new, fp6_null, fp6_sqr, fp6_sub(), fp_hlv, THROW, and TRY.
void fp18_sqr_lazyr (fp18_t c, fp18_t a)
Computes the square of a octodecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octodecic extension field element to square.
Definition at line 117 of file relic_fp18_sqr.c.
References CATCH_ANY, dv6_free, dv6_new, dv6_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp6_add(), fp6_free, fp6_mul_unr(), fp6_new, fp6_null, fp6_sqr_unr(), fp6_sub(), fp_hlvd_low(), THROW, and TRY.
void fp18_sqr_cyc (fp18_t c, fp18_t a)
Computes the square of a cyclotomic octodecic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 210 of file relic_fp18_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_add(), fp6_copy(), fp6_free, fp6_mul_art(), fp6_new, fp6_null, fp6_sqr, fp6_sub(), fp_neg, THROW, and TRY.
Referenced by fp18_exp_cyc().
void fp18_sqr_pck (fp18_t c, fp18_t a)
Computes the square of a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 268 of file relic_fp18_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_add(), fp6_copy(), fp6_free, fp6_mul_art(), fp6_new, fp6_null, fp6_sqr, fp6_sub(), fp_neg, THROW, and TRY.
Referenced by fp18_exp_cyc(), and fp18_exp_cyc_sps().