RELIC: src/eb/relic_eb_norm.c File Reference
relic_eb_norm.c File Reference
Elliptic curves over binary fields.
#include "string.h"
#include "relic_core.h"
#include "relic_eb.h"
Functions
static void eb_norm_ordin (eb_t r, const eb_t p, int flag)
static void eb_norm_super (eb_t r, const eb_t p, int flag)
static void eb_norm_halve (eb_t r, const eb_t p)
void eb_norm (eb_t r, const eb_t p)
void eb_norm_sim (eb_t *r, const eb_t *t, int n)
Detailed Description
Implementation of the point normalization on binary elliptic curves.
Version
Id:
relic_eb_norm.c 1566 2013-09-02 04:09:52Z dfaranha
Definition in file relic_eb_norm.c.
Function Documentation
static void eb_norm_ordin (eb_t r, const eb_t p, int flag) static
Normalizes a point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to normalize.
[in] flag - if the Z coordinate is already inverted.
Definition at line 52 of file relic_eb_norm.c.
References fb_copy(), fb_inv, fb_mul, fb_set_dig(), and fb_sqr.
Referenced by eb_norm(), and eb_norm_sim().
static void eb_norm_super (eb_t r, const eb_t p, int flag) static
Normalizes a point represented in projective coordinates.
Parameters
r - the result.
p - the point to normalize.
Definition at line 78 of file relic_eb_norm.c.
References fb_copy(), fb_inv, fb_mul, and fb_set_dig().
Referenced by eb_norm(), and eb_norm_sim().
static void eb_norm_halve (eb_t r, const eb_t p) static
Normalizes a point represented in lambda-coordinates.
Parameters
[out] r - the result.
[in] p - the point to normalize.
Definition at line 103 of file relic_eb_norm.c.
References fb_add(), fb_copy(), and fb_mul.
Referenced by eb_norm().
void eb_norm (eb_t r, const eb_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 114 of file relic_eb_norm.c.
References eb_copy(), eb_curve_is_super(), eb_is_infty(), eb_norm_halve(), eb_norm_ordin(), eb_norm_super(), and eb_set_infty().
Referenced by eb_curve_set_kbltz(), eb_curve_set_ordin(), eb_curve_set_super(), eb_is_valid(), eb_mul_basic(), eb_mul_dig(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_nafwi(), eb_mul_fix_ordin(), eb_mul_fix_yaowi(), eb_mul_frb(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), eb_mul_pre_combs(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_basic(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_ordin(), eb_mul_sim_trick(), eb_norm_sim(), and eb_tab().
void eb_norm_sim (eb_t * r, const eb_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 147 of file relic_eb_norm.c.
References CATCH_ANY, eb_curve_is_super(), eb_is_infty(), eb_norm(), eb_norm_ordin(), eb_norm_super(), ERR_CAUGHT, fb_copy(), fb_free, fb_inv_sim(), fb_new, fb_null, fb_set_dig(), FINALLY, THROW, and TRY.
Referenced by eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_pre_nafwi(), eb_mul_pre_yaowi(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_trick(), and eb_tab().