RELIC: src/fpx/relic_fpx_util.c File Reference
relic_fpx_util.c File Reference
Extensions of prime fields.
#include "relic_core.h"
#include "relic_pp_low.h"
Functions
void fp2_copy (fp2_t c, fp2_t a)
void fp2_zero (fp2_t a)
int fp2_is_zero (fp2_t a)
void fp2_rand (fp2_t a)
void fp2_print (fp2_t a)
void fp2_set_dig (fp2_t a, dig_t b)
void fp3_copy (fp3_t c, fp3_t a)
void fp3_zero (fp3_t a)
int fp3_is_zero (fp3_t a)
void fp3_rand (fp3_t a)
void fp3_print (fp3_t a)
void fp6_copy (fp6_t c, fp6_t a)
void fp6_zero (fp6_t a)
int fp6_is_zero (fp6_t a)
void fp6_rand (fp6_t a)
void fp6_print (fp6_t a)
void fp12_copy (fp12_t c, fp12_t a)
void fp12_zero (fp12_t a)
int fp12_is_zero (fp12_t a)
void fp12_rand (fp12_t a)
void fp12_print (fp12_t a)
void fp12_set_dig (fp12_t a, dig_t b)
void fp18_copy (fp18_t c, fp18_t a)
void fp18_zero (fp18_t a)
int fp18_is_zero (fp18_t a)
void fp18_rand (fp18_t a)
void fp18_print (fp18_t a)
void fp18_set_dig (fp18_t a, dig_t b)
Detailed Description
Implementation of utilities in extensions defined over prime fields.
Version
Id:
relic_fpx_util.c 1577 2013-09-03 06:01:36Z dfaranha
Definition in file relic_fpx_util.c.
Function Documentation
void fp2_copy (fp2_t c, fp2_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the quadratic extension field element to copy.
Definition at line 39 of file relic_fpx_util.c.
References fp_copy().
Referenced by ep2_add_basic_imp(), ep2_add_projc_mix(), ep2_copy(), ep2_dbl_basic_imp(), ep2_neg_basic(), ep2_neg_projc(), ep2_rhs(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_frb(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp2_calc(), fp2_exp(), fp2_exp_uni(), fp2_frb(), fp2_inv_sim(), fp6_copy(), fp6_frb(), fp6_mul0_basic(), fp6_mul1_basic(), fp6_mul_art(), fp6_mul_basic(), and fp6_mul_dxs().
void fp2_zero (fp2_t a)
Assigns zero to a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to zero.
Definition at line 44 of file relic_fpx_util.c.
References fp_zero().
Referenced by ep2_curve_set(), ep2_set_infty(), fp2_calc(), fp2_exp_uni(), fp6_zero(), pp_add_k2_basic(), pp_dbl_k2_basic(), and pp_mil_k2().
int fp2_is_zero (fp2_t a)
Tests if a quadratic extension field element is zero or not.
Parameters
[in] A - the quadratic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 49 of file relic_fpx_util.c.
References fp_is_zero().
Referenced by ep2_add_basic_imp(), ep2_add_projc_imp(), ep2_add_projc_mix(), ep2_is_infty(), fp12_cmp_dig(), fp18_cmp_dig(), and fp6_is_zero().
void fp2_rand (fp2_t a)
Assigns a random value to a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to assign.
Definition at line 53 of file relic_fpx_util.c.
References fp_rand().
Referenced by fp6_rand().
void fp2_print (fp2_t a)
Prints a quadratic extension field element to standard output.
Parameters
[in] A - the quadratic extension field element to print.
Definition at line 58 of file relic_fpx_util.c.
References fp_print().
Referenced by ep2_print(), and fp6_print().
void fp2_set_dig (fp2_t a, dig_t b)
Assigns a quadratic extension field element to a digit.
Parameters
[in] a - the quadratic extension field element.
[in] b - the digit.
Definition at line 63 of file relic_fpx_util.c.
References fp_set_dig(), and fp_zero().
void fp3_copy (fp3_t c, fp3_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the cubic extension field element to copy.
Definition at line 69 of file relic_fpx_util.c.
References fp_copy().
Referenced by fp3_exp(), fp3_frb(), fp3_inv_sim(), and fp3_mul_frb().
void fp3_zero (fp3_t a)
Assigns zero to a cubic extension field element.
Parameters
[out] A - the cubic extension field element to zero.
Definition at line 75 of file relic_fpx_util.c.
References fp_zero().
Referenced by fp3_calc().
int fp3_is_zero (fp3_t a)
Tests if a cubic extension field element is zero or not.
Parameters
[in] A - the cubic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 81 of file relic_fpx_util.c.
References fp_is_zero().
void fp3_rand (fp3_t a)
Assigns a random value to a cubic extension field element.
Parameters
[out] A - the cubic extension field element to assign.
Definition at line 85 of file relic_fpx_util.c.
References fp_rand().
void fp3_print (fp3_t a)
Prints a cubic extension field element to standard output.
Parameters
[in] A - the cubic extension field element to print.
Definition at line 91 of file relic_fpx_util.c.
References fp_print().
void fp6_copy (fp6_t c, fp6_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the sextic extension field element to copy.
Definition at line 98 of file relic_fpx_util.c.
References fp2_copy().
Referenced by fp12_copy(), fp12_inv_uni(), fp18_copy(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp18_sqr_cyc(), fp18_sqr_pck(), and fp6_exp().
void fp6_zero (fp6_t a)
Assigns zero to a sextic extension field element.
Parameters
[out] A - the sextic extension field element to zero.
Definition at line 104 of file relic_fpx_util.c.
References fp2_zero().
Referenced by fp12_zero(), and fp18_zero().
int fp6_is_zero (fp6_t a)
Tests if a sextic extension field element is zero or not.
Parameters
[in] A - the sextic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 110 of file relic_fpx_util.c.
References fp2_is_zero().
Referenced by fp12_cmp_dig(), fp12_is_zero(), fp18_cmp_dig(), and fp18_is_zero().
void fp6_rand (fp6_t a)
Assigns a random value to a sextic extension field element.
Parameters
[out] A - the sextic extension field element to assign.
Definition at line 114 of file relic_fpx_util.c.
References fp2_rand().
Referenced by fp12_rand(), and fp18_rand().
void fp6_print (fp6_t a)
Prints a sextic extension field element to standard output.
Parameters
[in] A - the sextic extension field element to print.
Definition at line 120 of file relic_fpx_util.c.
References fp2_print().
Referenced by fp12_print(), and fp18_print().
void fp12_copy (fp12_t c, fp12_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the dodecic extension field element to copy.
Definition at line 126 of file relic_fpx_util.c.
References fp6_copy().
Referenced by fp12_exp(), fp12_exp_cyc(), and fp12_exp_cyc_sps().
void fp12_zero (fp12_t a)
Assigns zero to a dodecic extension field element.
Parameters
[out] A - the dodecic extension field element to zero.
Definition at line 131 of file relic_fpx_util.c.
References fp6_zero().
Referenced by fp12_set_dig(), pp_dbl_k12_basic(), pp_fin_k12_oatep(), pp_mil_k12(), pp_mil_lit_k12(), and pp_mil_sps_k12().
int fp12_is_zero (fp12_t a)
Tests if a dodecic extension field element is zero or not.
Parameters
[in] A - the dodecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 136 of file relic_fpx_util.c.
References fp6_is_zero().
void fp12_rand (fp12_t a)
Assigns a random value to a dodecic extension field element.
Parameters
[out] A - the dodecic extension field element to assign.
Definition at line 140 of file relic_fpx_util.c.
References fp6_rand().
void fp12_print (fp12_t a)
Prints a dodecic extension field element to standard output.
Parameters
[in] A - the dodecic extension field element to print.
Definition at line 145 of file relic_fpx_util.c.
References fp6_print().
void fp12_set_dig (fp12_t a, dig_t b)
Assigns a dodecic extension field element to a digit.
Parameters
[in] a - the dodecic extension field element.
[in] b - the digit.
Definition at line 150 of file relic_fpx_util.c.
References fp12_zero(), and fp_set_dig().
void fp18_copy (fp18_t c, fp18_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the octodecic extension field element to copy.
Definition at line 155 of file relic_fpx_util.c.
References fp6_copy().
Referenced by fp18_back_cyc(), fp18_back_cyc_sim(), fp18_exp(), fp18_exp_cyc(), fp18_exp_cyc_sps(), and fp18_frb().
void fp18_zero (fp18_t a)
Assigns zero to a octodecic extension field element.
Parameters
[out] A - the octodecic extension field element to zero.
Definition at line 161 of file relic_fpx_util.c.
References fp6_zero().
Referenced by fp18_set_dig().
int fp18_is_zero (fp18_t a)
Tests if a octodecic extension field element is zero or not.
Parameters
[in] A - the octodecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 167 of file relic_fpx_util.c.
References fp6_is_zero().
void fp18_rand (fp18_t a)
Assigns a random value to a octodecic extension field element.
Parameters
[out] A - the octodecic extension field element to assign.
Definition at line 171 of file relic_fpx_util.c.
References fp6_rand().
void fp18_print (fp18_t a)
Prints a octodecic extension field element to standard output.
Parameters
[in] A - the octodecic extension field element to print.
Definition at line 177 of file relic_fpx_util.c.
References fp6_print().
void fp18_set_dig (fp18_t a, dig_t b)
Assigns a octodecic extension field element to a digit.
Parameters
[in] a - the octodecic extension field element.
[in] b - the digit.
Definition at line 183 of file relic_fpx_util.c.
References fp18_zero(), and fp_set_dig().