RELIC: src/eb/relic_eb_dbl.c File Reference
relic_eb_dbl.c File Reference
Elliptic curves over binary fields.
#include "string.h"
#include "relic_core.h"
#include "relic_eb.h"
Functions
static void eb_dbl_basic_ordin (eb_t r, const eb_t p)
static void eb_dbl_basic_super (eb_t r, const eb_t p)
static void eb_dbl_projc_ordin (eb_t r, const eb_t p)
static void eb_dbl_projc_super (eb_t r, const eb_t p)
void eb_dbl_basic (eb_t r, const eb_t p)
void eb_dbl_projc (eb_t r, const eb_t p)
Detailed Description
Implementation of point doubling on binary elliptic curves.
Version
Id:
relic_eb_dbl.c 1573 2013-09-02 07:17:18Z dfaranha
Definition in file relic_eb_dbl.c.
Function Documentation
static void eb_dbl_basic_ordin (eb_t r, const eb_t p) static
Doubles a point represented in affine coordinates on an ordinary binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 51 of file relic_eb_dbl.c.
References CATCH_ANY, eb_curve_get_a(), eb_curve_opt_a(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_sqr, FINALLY, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by eb_dbl_basic().
static void eb_dbl_basic_super (eb_t r, const eb_t p) static
Doubles a point represented in affine coordinates on a supersingular binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 123 of file relic_eb_dbl.c.
References CATCH_ANY, eb_curve_get_a(), eb_curve_get_c(), eb_curve_opt_a(), eb_curve_opt_c(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_sqr, FINALLY, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by eb_dbl_basic().
static void eb_dbl_projc_ordin (eb_t r, const eb_t p) static
Doubles a point represented in projective coordinates on an ordinary binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 217 of file relic_eb_dbl.c.
References CATCH_ANY, eb_curve_get_a(), eb_curve_opt_a(), ERR_CAUGHT, fb_add(), fb_copy(), fb_free, fb_mul, fb_mul_dig(), fb_new, fb_null, fb_sqr, FINALLY, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by eb_dbl_projc().
static void eb_dbl_projc_super (eb_t r, const eb_t p) static
Doubles a point represented in projective coordinates on an supersingular binary elliptic curve.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 298 of file relic_eb_dbl.c.
References fb_add(), fb_add_dig(), fb_copy(), and fb_sqr.
Referenced by eb_dbl_projc().
void eb_dbl_basic (eb_t r, const eb_t p)
Doubles a binary elliptic curve point represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 335 of file relic_eb_dbl.c.
References eb_curve_is_super(), eb_dbl_basic_ordin(), eb_dbl_basic_super(), eb_is_infty(), and eb_set_infty().
Referenced by eb_add_basic_ordin(), and eb_add_basic_super().
void eb_dbl_projc (eb_t r, const eb_t p)
Doubles a binary elliptic curve point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 356 of file relic_eb_dbl.c.
References eb_curve_is_super(), eb_dbl_projc_ordin(), eb_dbl_projc_super(), eb_is_infty(), and eb_set_infty().
Referenced by eb_add_projc_ordin(), eb_add_projc_ordin_mix(), eb_add_projc_super(), and eb_add_projc_super_mix().