RELIC: src/md/relic_md_kdf.c File Reference
relic_md_kdf.c File Reference
Hash functions.
#include <string.h>
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_util.h"
#include "relic_md.h"
Functions
void md_kdf1 (unsigned char *key, int key_len, const unsigned char *in, int in_len)
void md_kdf2 (unsigned char *key, int key_len, const unsigned char *in, int in_len)
Detailed Description
Implementation of a Key Derivation function.
Version
Id:
relic_md_kdf.c 1566 2013-09-02 04:09:52Z dfaranha
Definition in file relic_md_kdf.c.
Function Documentation
void md_kdf1 (unsigned char * key, int key_len, const unsigned char * in, int in_len)
Derives a key from shared secret material through the standardized KDF1 function.
Parameters
[out] key - the resulting key.
[in] key_len - the intended key length in bytes.
[in] in - the shared secret.
[in] in_len - the length of the shared secret in bytes.
Definition at line 43 of file relic_md_kdf.c.
References CEIL, MD_LEN, md_map, and util_conv_big().
Referenced by cp_sokaka_key(), and md_mgf1().
void md_kdf2 (unsigned char * key, int key_len, const unsigned char * in, int in_len)
Derives a key from shared secret material through the standardized KDF2 function.
Parameters
[out] key - the resulting key.
[in] key_len - the intended key length in bytes.
[in] in - the shared secret.
[in] in_len - the length of the shared secret in bytes.
Definition at line 62 of file relic_md_kdf.c.
References CEIL, MD_LEN, md_map, and util_conv_big().
Referenced by cp_ecdh_key(), and cp_ecmqv_key().