RELIC: src/fpx/relic_fp3_sqr.c File Reference
relic_fp3_sqr.c File Reference
Extensions of prime fields.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_pp_low.h"
Functions
void fp3_sqr_basic (fp3_t c, fp3_t a)
void fp3_sqr_integ (fp3_t c, fp3_t a)
Detailed Description
Implementation of squaring in a cubic extension of a prime field.
Version
Id:
relic_fp3_sqr.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_fp3_sqr.c.
Function Documentation
void fp3_sqr_basic (fp3_t c, fp3_t a)
Computes the square of a cubic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to square.
Definition at line 42 of file relic_fp3_sqr.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, FINALLY, fp_add, fp_addc_low(), fp_addd_low(), fp_dbl, fp_hlvd_low(), fp_muln_low(), fp_prime_get_cnr(), fp_rdc, fp_sqrn_low(), fp_sub, fp_subc_low(), THROW, and TRY.
void fp3_sqr_integ (fp3_t c, fp3_t a)
Computes the square of a cubic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to square.
Definition at line 121 of file relic_fp3_sqr.c.
References fp3_sqrm_low().