RELIC: src/epx/relic_ep2_mul_fix.c File Reference
relic_ep2_mul_fix.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep2_mul_pre_ordin (ep2_t *t, ep2_t p)
static void ep2_mul_fix_ordin (ep2_t r, ep2_t *table, bn_t k)
void ep2_mul_pre_basic (ep2_t *t, ep2_t p)
void ep2_mul_fix_basic (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_pre_yaowi (ep2_t *t, ep2_t p)
void ep2_mul_fix_yaowi (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_pre_nafwi (ep2_t *t, ep2_t p)
void ep2_mul_fix_nafwi (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_pre_combs (ep2_t *t, ep2_t p)
void ep2_mul_fix_combs (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_pre_combd (ep2_t *t, ep2_t p)
void ep2_mul_fix_combd (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_pre_lwnaf (ep2_t *t, ep2_t p)
void ep2_mul_fix_lwnaf (ep2_t r, ep2_t *t, bn_t k)
Detailed Description
Implementation of fixed point multiplication on a prime elliptic curve over a quadratic extension.
Version
Id:
relic_ep2_mul_fix.c 1550 2013-08-29 23:03:21Z dfaranha
Definition in file relic_ep2_mul_fix.c.
Function Documentation
static void ep2_mul_pre_ordin (ep2_t * t, ep2_t p) static
Precomputes a table for a point multiplication on an ordinary curve.
Parameters
[out] t - the destination table.
[in] p - the point to multiply.
Definition at line 47 of file relic_ep2_mul_fix.c.
References ep2_add, ep2_copy(), ep2_dbl, ep2_norm(), and EP_DEPTH.
Referenced by ep2_mul_pre_lwnaf().
static void ep2_mul_fix_ordin (ep2_t r, ep2_t * table, bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 79 of file relic_ep2_mul_fix.c.
References bn_rec_naf(), ep2_add, ep2_dbl, ep2_norm(), ep2_set_infty(), ep2_sub, EP_DEPTH, and FP_BITS.
Referenced by ep2_mul_fix_lwnaf().
void ep2_mul_pre_basic (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 112 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_fix_basic (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 135 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_test_bit(), ep2_add, ep2_norm(), and ep2_set_infty().
void ep2_mul_pre_yaowi (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 154 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ep2_dbl_basic(), EP_DEPTH, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_fix_yaowi (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 181 of file relic_ep2_mul_fix.c.
References bn_rec_win(), CATCH_ANY, CEIL, ep2_add, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), EP_DEPTH, ERR_CAUGHT, FINALLY, FP_BITS, THROW, and TRY.
void ep2_mul_pre_nafwi (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 219 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, EP_DEPTH, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_fix_nafwi (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 248 of file relic_ep2_mul_fix.c.
References bn_rec_naf(), CATCH_ANY, ep2_add, ep2_free, ep2_new, ep2_norm(), ep2_null, ep2_set_infty(), ep2_sub, EP_DEPTH, ERR_CAUGHT, FINALLY, FP_BITS, THROW, and TRY.
void ep2_mul_pre_combs (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 309 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), EP_DEPTH, EP_TABLE_COMBS, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_fix_combs (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 351 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_test_bit(), CATCH_ANY, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), EP_DEPTH, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_pre_combd (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 407 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep2_add, ep2_copy(), ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), EP_DEPTH, EP_TABLE_COMBD, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_fix_combd (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 456 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, bn_test_bit(), CATCH_ANY, ep2_add, ep2_curve_get_ord(), ep2_dbl, ep2_norm(), ep2_set_infty(), EP_DEPTH, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep2_mul_pre_lwnaf (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 512 of file relic_ep2_mul_fix.c.
References ep2_mul_pre_ordin().
void ep2_mul_fix_lwnaf (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 516 of file relic_ep2_mul_fix.c.
References ep2_mul_fix_ordin().