#!/bin/sh

export CPATH="$CPATH:$HOME/include"
export LIBRARY_PATH="$LIBRARY_PATH:$HOME/lib"

for f in `echo $HOME/supercop-20171020/bench/* $HOME/supercop-20170904/bench/*`
do
  [ -d "$f" ] && export CPATH="$CPATH:$f/include:$f/include/amd64"
  [ -d "$f" ] && export LIBRARY_PATH="$LIBRARY_PATH:$f/lib:$f/lib/amd64"
done

for f in `echo $HOME/supercop-data/*/amd64/include`
do
  [ -d "$f" ] && export CPATH="$CPATH:$f"
done

for f in `echo $HOME/supercop-data/*/amd64/lib`
do
  [ -d "$f" ] && export LIBRARY_PATH="$LIBRARY_PATH:$f"
done

gcc -O3 -march=native -mtune=native -Wall -I. -DKAT -DKATNUM=`cat KATNUM` -o kat nist/kat_kem.c nist/rng.c benes.c bm.c controlbits.c decrypt.c encrypt.c fft.c fft_tr.c gf.c operations.c pk_gen.c sk_gen.c transpose.c util.c vec128.c vec256.c  consts.S syndrome_asm.s transpose_64x128_sp_asm.s update_asm.s vec128_mul_asm.s vec256_ama_asm.s vec256_maa_asm.s vec256_mul_asm.s vec_reduce_asm.s    -lkeccak -lcrypto -ldl 
