RELIC: src/fb/relic_fb_shift.c File Reference
relic_fb_shift.c File Reference
Binary field arithmetic.
#include "relic_core.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
#include "relic_util.h"
Functions
void fb_lsh (fb_t c, const fb_t a, int bits)
void fb_rsh (fb_t c, const fb_t a, int bits)
Detailed Description
Implementation of the binary field multiplication by the basis.
Version
Id:
relic_fb_shift.c 1561 2013-09-02 00:01:53Z dfaranha
Definition in file relic_fb_shift.c.
Function Documentation
void fb_lsh (fb_t c, const fb_t a, int bits)
Shifts a binary field element to the left. Computes c = a * z^bits mod f(z).
Parameters
[out] c - the result.
[in] a - the binary field element to shift.
[in] bits - the number of bits to shift.
Definition at line 41 of file relic_fb_shift.c.
References fb_copy(), FB_DIG_LOG, fb_lsh1_low(), fb_lshb_low(), fb_lshd_low(), and SPLIT.
Referenced by fb_inv_bruch(), and fb_itr_pre_quick().
void fb_rsh (fb_t c, const fb_t a, int bits)
Shifts a binary field element to the right. Computes c = a / (z^bits).
Parameters
[out] c - the result.
[in] a - the binary field element to shift.
[in] bits - the number of bits to shift.
Definition at line 66 of file relic_fb_shift.c.
References fb_copy(), FB_DIG_LOG, fb_rsh1_low(), fb_rshb_low(), fb_rshd_low(), and SPLIT.
Referenced by fb_inv_bruch(), fb_size(), and find_solve().