RELIC: src/bn/relic_bn_smb.c File Reference
relic_bn_smb.c File Reference
Multiple precision integer arithmetic.
#include "relic_core.h"
Functions
void bn_smb_leg (bn_t c, const bn_t a, const bn_t b)
void bn_smb_jac (bn_t c, const bn_t a, const bn_t b)
Detailed Description
Implementation of Legendre and Jacobi symbols.
Version
Id:
relic_bn_smb.c 1542 2013-08-28 18:31:47Z dfaranha
Definition in file relic_bn_smb.c.
Function Documentation
void bn_smb_leg (bn_t c, const bn_t a, const bn_t b)
Computes the Legendre symbol c = (a|b), b prime.
Parameters
[out] c - the result.
[in] a - the first parameter.
[in] b - the second parameter.
Definition at line 38 of file relic_bn_smb.c.
References bn_cmp(), bn_free, bn_mxp, bn_neg(), BN_NEG, bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sign(), bn_sub_dig(), bn_zero(), CATCH_ANY, CMP_EQ, ERR_CAUGHT, ERR_NO_VALID, FINALLY, THROW, and TRY.
void bn_smb_jac (bn_t c, const bn_t a, const bn_t b)
Computes the Jacobi symbol c = (a|b).
Parameters
[out] c - the result.
[in] a - the first parameter.
[in] b - the second parameter.
Definition at line 77 of file relic_bn_smb.c.
References bn_add(), bn_cmp_dig(), bn_copy(), bn_free, bn_is_even(), bn_is_zero(), bn_mod, bn_mod_2b(), bn_neg(), BN_NEG, bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sign(), bn_zero(), CATCH_ANY, CMP_EQ, ERR_CAUGHT, ERR_NO_VALID, FINALLY, THROW, and TRY.
Referenced by bn_is_prime_solov().