RELIC: src/fbx/relic_fbx_exp.c File Reference
relic_fbx_exp.c File Reference
Extensions of binary fields.
#include "relic_core.h"
#include "relic_fbx.h"
Functions
void fb4_exp (fb4_t c, fb4_t a, bn_t b)
Detailed Description
Implementation of exponentiation in binary field extensions.
Version
Id:
relic_fbx_exp.c 1489 2013-06-02 18:33:31Z dfaranha
Definition in file relic_fbx_exp.c.
Function Documentation
void fb4_exp (fb4_t c, fb4_t a, bn_t b)
Computes a power of a quartic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the quartic extension element to exponentiate.
[in] b - the exponent.
Definition at line 39 of file relic_fbx_exp.c.
References bn_bits(), bn_test_bit(), CATCH_ANY, ERR_CAUGHT, fb4_copy, fb4_free, fb4_mul(), fb4_new, fb4_null, fb4_sqr(), FINALLY, THROW, and TRY.