/*
 * crypto_onetimeauth/try-notest.c version 20180223
 * D. J. Bernstein
 * Public domain.
 * Auto-generated by trygen-notest.py; do not edit.
 */

#include "crypto_onetimeauth.h"
#include "try.h"

const char *primitiveimplementation = crypto_onetimeauth_implementation;

#define TUNE_BYTES 1536
#ifdef SMALL
#define MAXTEST_BYTES 128
#else
#define MAXTEST_BYTES 4096
#endif
#ifdef SMALL
#define LOOPS 4096
#else
#define LOOPS 32768
#endif

static unsigned char *h;
static unsigned char *m;
static unsigned char *k;
static unsigned char *h2;
static unsigned char *m2;
static unsigned char *k2;
#define hlen crypto_onetimeauth_BYTES
unsigned long long mlen;
#define klen crypto_onetimeauth_KEYBYTES

void preallocate(void)
{
}

void allocate(void)
{
  unsigned long long alloclen = 0;
  if (alloclen < TUNE_BYTES) alloclen = TUNE_BYTES;
  if (alloclen < MAXTEST_BYTES) alloclen = MAXTEST_BYTES;
  if (alloclen < crypto_onetimeauth_BYTES) alloclen = crypto_onetimeauth_BYTES;
  if (alloclen < crypto_onetimeauth_KEYBYTES) alloclen = crypto_onetimeauth_KEYBYTES;
  h = alignedcalloc(alloclen);
  m = alignedcalloc(alloclen);
  k = alignedcalloc(alloclen);
  h2 = alignedcalloc(alloclen);
  m2 = alignedcalloc(alloclen);
  k2 = alignedcalloc(alloclen);
}

void predoit(void)
{
}

void doit(void)
{
  crypto_onetimeauth(h,m,TUNE_BYTES,k);
  crypto_onetimeauth_verify(h,m,TUNE_BYTES,k);
}
