RELIC: src/cp/relic_cp_sokaka.c File Reference
relic_cp_sokaka.c File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include <stdint.h>
#include "relic.h"
#include "relic_test.h"
#include "relic_bench.h"
Functions
void cp_sokaka_gen (bn_t master)
void cp_sokaka_gen_prv (sokaka_t k, char *id, int len, bn_t master)
void cp_sokaka_key (unsigned char *key, unsigned int key_len, char *id1, int len1, sokaka_t k, char *id2, int len2)
Detailed Description
Implementation of the Sakai-Ohgishi-Kasahara Identity-Based Non-Interactive Authenticated Key Agreement scheme.
Version
Id:
relic_cp_sokaka.c 1594 2013-09-03 14:08:13Z dfaranha
Definition in file relic_cp_sokaka.c.
Function Documentation
void cp_sokaka_gen (bn_t master)
Generates a master key for the SOK identity-based non-interactive authenticated key agreement protocol.
Parameters
[out] master - the master key.
Definition at line 47 of file relic_cp_sokaka.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_get_ord, THROW, and TRY.
void cp_sokaka_gen_prv (sokaka_t k, char * id, int len, bn_t master)
Generates a private key for the SOK protocol.
Parameters
[out] k - the private key.
[in] id - the identity.
[in] len - the length of identity in bytes.
[in] master - the master key.
Definition at line 70 of file relic_cp_sokaka.c.
References g1_map, g1_mul, g2_map, g2_mul, and pc_map_is_type1.
void cp_sokaka_key (unsigned char * key, unsigned int key_len, char * id1, int len1, sokaka_t k, char * id2, int len2)
Computes a shared key between two entities.
Parameters
[out] key - the shared key.
int] key_len - the intended shared key length in bytes.
[in] id1 - the first identity.
[in] len1 - the length of the first identity in bytes.
[in] k - the private key of the first identity.
[in] id2 - the second identity.
[in] len2 - the length of the second identity in bytes.
Definition at line 82 of file relic_cp_sokaka.c.
References bn_free, bn_new, bn_null, bn_size_bin(), bn_write_bin(), CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FB_BYTES, FINALLY, FP_BYTES, fp_prime_back(), g1_free, g1_map, g1_new, g1_null, g2_free, g2_map, g2_new, g2_null, gt_free, gt_new, gt_null, md_kdf1(), pc_map, pc_map_is_type1, THROW, and TRY.