RELIC: src/fpx/relic_fp3_mul.c File Reference
relic_fp3_mul.c File Reference
Extensions of prime fields.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_pp_low.h"
Functions
void fp3_mul_basic (fp3_t c, fp3_t a, fp3_t b)
void fp3_mul_integ (fp3_t c, fp3_t a, fp3_t b)
void fp3_mul_nor (fp3_t c, fp3_t a)
void fp3_mul_art (fp3_t c, fp3_t a)
void fp3_mul_frb (fp3_t c, fp3_t a, int i, int j, int k)
Detailed Description
Implementation of multiplication in a cubic extension of a prime field.
Version
Id:
relic_fp3_mul.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_fp3_mul.c.
Function Documentation
void fp3_mul_basic (fp3_t c, fp3_t a, fp3_t b)
Multiples two cubic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 42 of file relic_fp3_mul.c.
References CATCH_ANY, dv_free, dv_new, dv_null, ERR_CAUGHT, FINALLY, fp_add, fp_addc_low(), fp_addd_low(), fp_muln_low(), fp_prime_get_cnr(), fp_rdc, fp_subc_low(), THROW, and TRY.
void fp3_mul_integ (fp3_t c, fp3_t a, fp3_t b)
Multiples two cubic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 127 of file relic_fp3_mul.c.
References fp3_mulm_low().
void fp3_mul_nor (fp3_t c, fp3_t a)
Definition at line 133 of file relic_fp3_mul.c.
References fp_copy(), fp_dbl, and fp_neg.
Referenced by fp18_back_cyc(), fp18_back_cyc_sim(), and fp6_mul_dxs_basic().
void fp3_mul_art (fp3_t c, fp3_t a)
Multiplies a cubic extension field element by the adjoined cubic root. Computes c = a * u.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to multiply.
Definition at line 140 of file relic_fp3_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_copy(), fp_dbl, fp_free, fp_neg, fp_new, fp_null, THROW, and TRY.
Referenced by fp3_mul_frb().
void fp3_mul_frb (fp3_t c, fp3_t a, int i, int j, int k)
Multiplies a cubic extension field element by a power of the constant needed to compute a power of the Frobenius map. If the flag is zero, the map is computed on the cubic extension directly; otherwise the map is computed on a higher extension.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the flag to indicate the current extension.
[in] j - the power of the Frobenius map.
[in] k - the power of the constant.
Definition at line 163 of file relic_fp3_mul.c.
References core_get(), _ctx_t::fp3_base, fp3_copy(), fp3_mul_art(), _ctx_t::fp3_p, _ctx_t::fp3_p2, _ctx_t::fp3_p3, _ctx_t::fp3_p4, _ctx_t::fp3_p5, fp_copy(), and fp_mul.
Referenced by fp18_frb(), and fp3_frb().