RELIC: src/relic_rand.c File Reference
relic_rand.c File Reference
Pseudo-random number generator.
#include <stdlib.h>
#include <stdint.h>
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_label.h"
#include "relic_rand.h"
#include "relic_md.h"
#include "relic_err.h"
#include <string.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
Macros
#define RAND_PATH "/dev/random"
#define SEED_SIZE 20
Functions
void rand_init ()
void rand_clean ()
void rand_seed (unsigned char *buf, int size)
void rand_bytes (unsigned char *buf, int size)
Detailed Description
Implementation of the pseudo-random number generator.
Version
Id:
relic_rand.c 1522 2013-08-27 15:55:54Z dfaranha
Definition in file relic_rand.c.
Macro Definition Documentation
#define RAND_PATH "/dev/random"
The path to the char device that supplies entropy.
Definition at line 58 of file relic_rand.c.
Referenced by rand_init().
#define SEED_SIZE 20
Minimum size of the PRNG seed.
Definition at line 82 of file relic_rand.c.
Referenced by rand_bytes(), rand_init(), and rand_seed().
Function Documentation
void rand_init (void)
Initializes the pseudo-random number generator.
Definition at line 88 of file relic_rand.c.
References core_get(), ERR_NO_FILE, ERR_NO_READ, RAND_PATH, rand_seed(), RAND_SIZE, SEED_SIZE, and THROW.
Referenced by core_init().
void rand_clean (void)
Finishes the pseudo-random number generator.
Definition at line 149 of file relic_rand.c.
References core_get().
Referenced by core_clean().
void rand_seed (unsigned char * buf, int size)
Sets the initial state of the pseudo-random number generator.
Parameters
[in] buf - the buffer that represents the initial state.
[in] size - the number of bytes.
Definition at line 153 of file relic_rand.c.
References core_get(), ERR_NO_VALID, MIN, _ctx_t::rand, SEED_SIZE, and THROW.
Referenced by rand_init().
void rand_bytes (unsigned char * buf, int size)
Writes size pseudo-random bytes in the passed buffer.
Parameters
[out] buf - the buffer to write.
[in] size - the number of bytes to write.
Exceptions
ERR_NO_READ - it the pseudo-random number generator can't generate the specified number of bytes.
Definition at line 170 of file relic_rand.c.
References core_get(), MD_LEN_SHONE, md_map_shone_mid(), _ctx_t::rand, RAND_SIZE, and SEED_SIZE.
Referenced by bn_rand(), fb_rand(), fp_rand(), and pad_pkcs1().