RELIC: src/fb/relic_fb_cmp.c File Reference
relic_fb_cmp.c File Reference
Binary field arithmetic.
#include "relic_core.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
Functions
int fb_cmp_dig (const fb_t a, dig_t b)
int fb_cmp (const fb_t a, const fb_t b)
Detailed Description
Implementation of the binary field comparison functions.
Version
Id:
relic_fb_cmp.c 1561 2013-09-02 00:01:53Z dfaranha
Definition in file relic_fb_cmp.c.
Function Documentation
int fb_cmp_dig (const fb_t a, dig_t b)
Returns the result of a comparison between a binary field element and a small binary field element.
Parameters
[in] a - the binary field element.
[in] b - the small binary field element.
Returns
CMP_LT if a < b, CMP_EQ if a == b and CMP_GT if a > b.
Definition at line 40 of file relic_fb_cmp.c.
References CMP_GT, fb_cmp1_low(), and FB_DIGS.
Referenced by detect_opt(), and eb_curve_set_ordin().
int fb_cmp (const fb_t a, const fb_t b)
Returns the result of a comparison between two binary field elements.
Parameters
[in] a - the first binary field element.
[in] b - the second binary field element.
Returns
CMP_LT if a < b, CMP_EQ if a == b and CMP_GT if a > b.
Definition at line 50 of file relic_fb_cmp.c.
References fb_cmpn_low().
Referenced by eb_cmp(), and eb_is_valid().