RELIC: src/md/sha384-512.c File Reference
sha384-512.c File Reference
#include "sha.h"
Macros
#define SHA512_SHR(bits, word, ret)
#define SHA512_SHL(bits, word, ret)
#define SHA512_OR(word1, word2, ret)
#define SHA512_XOR(word1, word2, ret)
#define SHA512_AND(word1, word2, ret)
#define SHA512_TILDA(word, ret) ((ret)[0] = ~(word)[0], (ret)[1] = ~(word)[1])
#define SHA512_ADD(word1, word2, ret)
#define SHA512_ADDTO4(word1, word2)
#define SHA512_ADDTO2(word1, word2)
#define SHA512_ROTR(bits, word, ret)
#define SHA512_SIGMA0(word, ret)
#define SHA512_SIGMA1(word, ret)
#define SHA512_sigma0(word, ret)
#define SHA512_sigma1(word, ret)
#define SHA_Ch(x, y, z, ret)
#define SHA_Maj(x, y, z, ret)
#define SHA384_512AddLength(context, length)
Functions
static void SHA384_512Finalize (SHA512Context *context, uint8_t Pad_Byte)
static void SHA384_512PadMessage (SHA512Context *context, uint8_t Pad_Byte)
static void SHA384_512ProcessMessageBlock (SHA512Context *context)
static int SHA384_512Reset (SHA512Context *context, uint32_t H0[])
static int SHA384_512ResultN (SHA512Context *context, uint8_t Message_Digest[], int HashSize)
int SHA384Reset (SHA384Context *context)
int SHA384Input (SHA384Context *context, const uint8_t *message_array, unsigned int length)
int SHA384FinalBits (SHA384Context *context, const uint8_t message_bits, unsigned int length)
int SHA384Result (SHA384Context *context, uint8_t Message_Digest[SHA384HashSize])
int SHA512Reset (SHA512Context *context)
int SHA512Input (SHA512Context *context, const uint8_t *message_array, unsigned int length)
int SHA512FinalBits (SHA512Context *context, const uint8_t message_bits, unsigned int length)
int SHA512Result (SHA512Context *context, uint8_t Message_Digest[SHA512HashSize])
Variables
static uint32_t SHA384_H0 [SHA512HashSize/4]
static uint32_t SHA512_H0 [SHA512HashSize/4]
Macro Definition Documentation
#define SHA512_SHR (bits, word, ret)
Value:
(\
    /* (((uint64_t)((word))) >> (bits)) */                     \
    (ret)[0] = (((bits) < 32) && ((bits) >= 0)) ?              \
      ((word)[0] >> (bits)) : 0,                               \
    (ret)[1] = ((bits) > 32) ? ((word)[0] >> ((bits) - 32)) :  \
      ((bits) == 32) ? (word)[0] :                             \
      ((bits) >= 0) ?                                          \
        (((word)[0] << (32 - (bits))) |                        \
        ((word)[1] >> (bits))) : 0 )
Definition at line 54 of file sha384-512.c.
#define SHA512_SHL (bits, word, ret)
Value:
(\
    /* (((uint64_t)(word)) << (bits)) */                       \
    (ret)[0] = ((bits) > 32) ? ((word)[1] << ((bits) - 32)) :  \
         ((bits) == 32) ? (word)[1] :                          \
         ((bits) >= 0) ?                                       \
           (((word)[0] << (bits)) |                            \
           ((word)[1] >> (32 - (bits)))) :                     \
         0,                                                    \
    (ret)[1] = (((bits) < 32) && ((bits) >= 0)) ?              \
        ((word)[1] << (bits)) : 0 )
Definition at line 64 of file sha384-512.c.
#define SHA512_OR (word1, word2, ret)
Value:
(\
    (ret)[0] = (word1)[0] | (word2)[0],                        \
    (ret)[1] = (word1)[1] | (word2)[1] )
Definition at line 78 of file sha384-512.c.
#define SHA512_XOR (word1, word2, ret)
Value:
(\
    (ret)[0] = (word1)[0] ^ (word2)[0],                        \
    (ret)[1] = (word1)[1] ^ (word2)[1] )
Definition at line 85 of file sha384-512.c.
#define SHA512_AND (word1, word2, ret)
Value:
(\
    (ret)[0] = (word1)[0] & (word2)[0],                        \
    (ret)[1] = (word1)[1] & (word2)[1] )
Definition at line 92 of file sha384-512.c.
#define SHA512_TILDA (word, ret) ((ret)[0] = ~(word)[0], (ret)[1] = ~(word)[1])
Definition at line 99 of file sha384-512.c.
#define SHA512_ADD (word1, word2, ret)
Value:
(\
    (ret)[1] = (word1)[1], (ret)[1] += (word2)[1],             \
    (ret)[0] = (word1)[0] + (word2)[0] + ((ret)[1] < (word1)[1]) )
Definition at line 105 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
#define SHA512_ADDTO4 (word1, word2)
Value:
(\
    ADDTO4_temp = (word1)[3],                                  \
    (word1)[3] += (word2)[3],                                  \
    ADDTO4_temp2 = (word1)[2],                                 \
    (word1)[2] += (word2)[2] + ((word1)[3] < ADDTO4_temp),     \
    ADDTO4_temp = (word1)[1],                                  \
    (word1)[1] += (word2)[1] + ((word1)[2] < ADDTO4_temp2),    \
    (word1)[0] += (word2)[0] + ((word1)[1] < ADDTO4_temp) )
Definition at line 112 of file sha384-512.c.
#define SHA512_ADDTO2 (word1, word2)
Value:
(\
    ADDTO2_temp = (word1)[1],                                  \
    (word1)[1] += (word2)[1],                                  \
    (word1)[0] += (word2)[0] + ((word1)[1] < ADDTO2_temp) )
Definition at line 124 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
#define SHA512_ROTR (bits, word, ret)
Value:
(\
    SHA512_SHR((bits), (word), ROTR_temp1),                    \
    SHA512_SHL(64-(bits), (word), ROTR_temp2),                 \
    SHA512_OR(ROTR_temp1, ROTR_temp2, (ret)) )
Definition at line 132 of file sha384-512.c.
#define SHA512_SIGMA0 (word, ret)
Value:
(\
    SHA512_ROTR(28, (word), SIGMA0_temp1),                     \
    SHA512_ROTR(34, (word), SIGMA0_temp2),                     \
    SHA512_ROTR(39, (word), SIGMA0_temp3),                     \
    SHA512_XOR(SIGMA0_temp2, SIGMA0_temp3, SIGMA0_temp4),      \
    SHA512_XOR(SIGMA0_temp1, SIGMA0_temp4, (ret)) )
Definition at line 141 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
#define SHA512_SIGMA1 (word, ret)
Value:
(\
    SHA512_ROTR(14, (word), SIGMA1_temp1),                     \
    SHA512_ROTR(18, (word), SIGMA1_temp2),                     \
    SHA512_ROTR(41, (word), SIGMA1_temp3),                     \
    SHA512_XOR(SIGMA1_temp2, SIGMA1_temp3, SIGMA1_temp4),      \
    SHA512_XOR(SIGMA1_temp1, SIGMA1_temp4, (ret)) )
Definition at line 151 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
#define SHA512_sigma0 (word, ret)
Value:
(\
    SHA512_ROTR( 1, (word), sigma0_temp1),                     \
    SHA512_ROTR( 8, (word), sigma0_temp2),                     \
    SHA512_SHR( 7, (word), sigma0_temp3),                      \
    SHA512_XOR(sigma0_temp2, sigma0_temp3, sigma0_temp4),      \
    SHA512_XOR(sigma0_temp1, sigma0_temp4, (ret)) )
Definition at line 161 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
#define SHA512_sigma1 (word, ret)
Value:
(\
    SHA512_ROTR(19, (word), sigma1_temp1),                     \
    SHA512_ROTR(61, (word), sigma1_temp2),                     \
    SHA512_SHR( 6, (word), sigma1_temp3),                      \
    SHA512_XOR(sigma1_temp2, sigma1_temp3, sigma1_temp4),      \
    SHA512_XOR(sigma1_temp1, sigma1_temp4, (ret)) )
Definition at line 171 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
#define SHA_Ch (x, y, z, ret)
Value:
(\
    SHA512_AND(x, y, Ch_temp1),                                \
    SHA512_TILDA(x, Ch_temp2),                                 \
    SHA512_AND(Ch_temp2, z, Ch_temp3),                         \
    SHA512_XOR(Ch_temp1, Ch_temp3, (ret)) )
Definition at line 186 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
#define SHA_Maj (x, y, z, ret)
Value:
(\
    SHA512_AND(x, y, Maj_temp1),                               \
    SHA512_AND(x, z, Maj_temp2),                               \
    SHA512_AND(y, z, Maj_temp3),                               \
    SHA512_XOR(Maj_temp2, Maj_temp3, Maj_temp4),               \
    SHA512_XOR(Maj_temp1, Maj_temp4, (ret)) )
Definition at line 194 of file sha384-512.c.
Referenced by SHA384_512ProcessMessageBlock().
#define SHA384_512AddLength (context, length)
Value:
(\
    addTemp[3] = (length), SHA512_ADDTO4((context)->Length, addTemp), \
    (context)->Corrupted = (((context)->Length[3] == 0) &&            \
       ((context)->Length[2] == 0) && ((context)->Length[1] == 0) &&  \
       ((context)->Length[0] < 8)) ? 1 : 0 )
Definition at line 223 of file sha384-512.c.
Referenced by SHA512FinalBits(), and SHA512Input().
Function Documentation
static void SHA384_512Finalize (SHA512Context * context, uint8_t Pad_Byte) static
Definition at line 558 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Length, SHA512Context::Message_Block, SHA384_512PadMessage(), SHA512_Message_Block_Size, and USE_32BIT_ONLY.
Referenced by SHA384_512ResultN(), and SHA512FinalBits().
static void SHA384_512PadMessage (SHA512Context * context, uint8_t Pad_Byte) static
Definition at line 626 of file sha384-512.c.
References SHA512Context::Length, SHA512Context::Message_Block, SHA512Context::Message_Block_Index, SHA384_512ProcessMessageBlock(), and SHA512_Message_Block_Size.
Referenced by SHA384_512Finalize().
static void SHA384_512ProcessMessageBlock (SHA512Context * context) static
Definition at line 710 of file sha384-512.c.
References SHA512Context::Intermediate_Hash, SHA512Context::Message_Block, SHA512Context::Message_Block_Index, SHA512_ADD, SHA512_ADDTO2, SHA512_SIGMA0, SHA512_sigma0, SHA512_SIGMA1, SHA512_sigma1, SHA_Ch, and SHA_Maj.
Referenced by SHA384_512PadMessage(), and SHA512Input().
static int SHA384_512Reset (SHA512Context * context, uint32_t H0[]) static
Definition at line 955 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Corrupted, SHA512Context::Intermediate_Hash, SHA512Context::Length, SHA512Context::Message_Block_Index, SHA512HashSize, shaNull, and shaSuccess.
Referenced by SHA384Reset(), and SHA512Reset().
static int SHA384_512ResultN (SHA512Context * context, uint8_t Message_Digest[], int HashSize) static
Definition at line 1006 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Corrupted, SHA512Context::Intermediate_Hash, SHA384_512Finalize(), shaNull, and shaSuccess.
Referenced by SHA384Result(), and SHA512Result().
int SHA384Reset (SHA384Context * context)
Definition at line 318 of file sha384-512.c.
References SHA384_512Reset(), and SHA384_H0.
Referenced by md_map_sh384().
int SHA384Input (SHA384Context * context, const uint8_t * message_array, unsigned int length)
Definition at line 343 of file sha384-512.c.
References SHA512Input().
Referenced by md_map_sh384().
int SHA384FinalBits (SHA384Context * context, const uint8_t message_bits, unsigned int length)
Definition at line 369 of file sha384-512.c.
References SHA512FinalBits().
int SHA384Result (SHA384Context * context, uint8_t Message_Digest[SHA384HashSize])
Definition at line 394 of file sha384-512.c.
References SHA384_512ResultN().
Referenced by md_map_sh384().
int SHA512Reset (SHA512Context * context)
Definition at line 415 of file sha384-512.c.
References SHA384_512Reset(), and SHA512_H0.
Referenced by md_map_sh512().
int SHA512Input (SHA512Context * context, const uint8_t * message_array, unsigned int length)
Definition at line 440 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Corrupted, SHA512Context::Message_Block, SHA512Context::Message_Block_Index, SHA384_512AddLength, SHA384_512ProcessMessageBlock(), SHA512_Message_Block_Size, shaNull, shaStateError, and shaSuccess.
Referenced by md_map_sh512(), and SHA384Input().
int SHA512FinalBits (SHA512Context * context, const uint8_t message_bits, unsigned int length)
Definition at line 497 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Corrupted, SHA384_512AddLength, SHA384_512Finalize(), shaNull, shaStateError, and shaSuccess.
Referenced by SHA384FinalBits().
int SHA512Result (SHA512Context * context, uint8_t Message_Digest[SHA512HashSize])
Definition at line 595 of file sha384-512.c.
References SHA384_512ResultN().
Referenced by md_map_sh512().
Variable Documentation
uint32_t SHA384_H0[SHA512HashSize/4] static
Initial value:
= {
    0xCBBB9D5D, 0xC1059ED8, 0x629A292A, 0x367CD507, 0x9159015A,
    0x3070DD17, 0x152FECD8, 0xF70E5939, 0x67332667, 0xFFC00B31,
    0x8EB44A87, 0x68581511, 0xDB0C2E0D, 0x64F98FA7, 0x47B5481D,
    0xBEFA4FA4
}
Definition at line 240 of file sha384-512.c.
Referenced by SHA384Reset().
uint32_t SHA512_H0[SHA512HashSize/4] static
Initial value:
= {
    0x6A09E667, 0xF3BCC908, 0xBB67AE85, 0x84CAA73B, 0x3C6EF372,
    0xFE94F82B, 0xA54FF53A, 0x5F1D36F1, 0x510E527F, 0xADE682D1,
    0x9B05688C, 0x2B3E6C1F, 0x1F83D9AB, 0xFB41BD6B, 0x5BE0CD19,
    0x137E2179
}
Definition at line 247 of file sha384-512.c.
Referenced by SHA512Reset().