RELIC: src/md/sha.h File Reference
sha.h File Reference
#include <stdint.h>
Data Structures
struct SHA1Context
struct SHA256Context
struct SHA512Context
struct USHAContext
struct HMACContext
Macros
#define SHA_Ch(x, y, z) (((x) & (y)) ^ ((~(x)) & (z)))
#define SHA_Maj(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define SHA_Parity(x, y, z) ((x) ^ (y) ^ (z))
#define USE_32BIT_ONLY
#define _SHA_H_
#define _SHA_enum_
Typedefs
typedef enum SHAversion SHAversion
typedef struct SHA1Context SHA1Context
typedef struct SHA256Context SHA256Context
typedef struct SHA512Context SHA512Context
typedef struct SHA256Context SHA224Context
typedef struct SHA512Context SHA384Context
typedef struct USHAContext USHAContext
typedef struct HMACContext HMACContext
Enumerations
enum {
shaSuccess = 0, shaNull, shaInputTooLong, shaStateError,
shaBadParam
}
enum {
SHA1_Message_Block_Size = 64, SHA224_Message_Block_Size = 64, SHA256_Message_Block_Size = 64, SHA384_Message_Block_Size = 128,
SHA512_Message_Block_Size = 128, USHA_Max_Message_Block_Size = SHA512_Message_Block_Size, SHA1HashSize = 20, SHA224HashSize = 28,
SHA256HashSize = 32, SHA384HashSize = 48, SHA512HashSize = 64, USHAMaxHashSize = SHA512HashSize,
SHA1HashSizeBits = 160, SHA224HashSizeBits = 224, SHA256HashSizeBits = 256, SHA384HashSizeBits = 384,
SHA512HashSizeBits = 512, USHAMaxHashSizeBits = SHA512HashSizeBits
}
enum SHAversion {
SHA1, SHA224, SHA256, SHA384,
SHA512
}
Functions
int SHA1Reset (SHA1Context *)
int SHA1Input (SHA1Context *, const uint8_t *bytes, unsigned int bytecount)
int SHA1FinalBits (SHA1Context *, const uint8_t bits, unsigned int bitcount)
int SHA1Result (SHA1Context *, uint8_t Message_Digest[SHA1HashSize])
int SHA224Reset (SHA224Context *)
int SHA224Input (SHA224Context *, const uint8_t *bytes, unsigned int bytecount)
int SHA224FinalBits (SHA224Context *, const uint8_t bits, unsigned int bitcount)
int SHA224Result (SHA224Context *, uint8_t Message_Digest[SHA224HashSize])
int SHA256Reset (SHA256Context *)
int SHA256Input (SHA256Context *, const uint8_t *bytes, unsigned int bytecount)
int SHA256FinalBits (SHA256Context *, const uint8_t bits, unsigned int bitcount)
int SHA256Result (SHA256Context *, uint8_t Message_Digest[SHA256HashSize])
int SHA384Reset (SHA384Context *)
int SHA384Input (SHA384Context *, const uint8_t *bytes, unsigned int bytecount)
int SHA384FinalBits (SHA384Context *, const uint8_t bits, unsigned int bitcount)
int SHA384Result (SHA384Context *, uint8_t Message_Digest[SHA384HashSize])
int SHA512Reset (SHA512Context *)
int SHA512Input (SHA512Context *, const uint8_t *bytes, unsigned int bytecount)
int SHA512FinalBits (SHA512Context *, const uint8_t bits, unsigned int bitcount)
int SHA512Result (SHA512Context *, uint8_t Message_Digest[SHA512HashSize])
Macro Definition Documentation
#define SHA_Ch (x, y, z) (((x) & (y)) ^ ((~(x)) & (z)))
Definition at line 14 of file sha.h.
Referenced by SHA1ProcessMessageBlock(), and SHA224_256ProcessMessageBlock().
#define SHA_Maj (x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
Definition at line 15 of file sha.h.
Referenced by SHA1ProcessMessageBlock(), and SHA224_256ProcessMessageBlock().
#define SHA_Parity (x, y, z) ((x) ^ (y) ^ (z))
Definition at line 26 of file sha.h.
Referenced by SHA1ProcessMessageBlock().
#define USE_32BIT_ONLY
Definition at line 28 of file sha.h.
Referenced by SHA384_512Finalize().
#define _SHA_H_
Definition at line 35 of file sha.h.
#define _SHA_enum_
Definition at line 71 of file sha.h.
Typedef Documentation
typedef enum SHAversion SHAversion
typedef struct SHA1Context SHA1Context
typedef struct SHA256Context SHA256Context
typedef struct SHA512Context SHA512Context
typedef struct SHA256Context SHA224Context
Definition at line 170 of file sha.h.
typedef struct SHA512Context SHA384Context
Definition at line 176 of file sha.h.
typedef struct USHAContext USHAContext
typedef struct HMACContext HMACContext
Enumeration Type Documentation
anonymous enum
Enumerator
shaSuccess
shaNull
shaInputTooLong
shaStateError
shaBadParam
Definition at line 75 of file sha.h.
anonymous enum
Enumerator
SHA1_Message_Block_Size
SHA224_Message_Block_Size
SHA256_Message_Block_Size
SHA384_Message_Block_Size
SHA512_Message_Block_Size
USHA_Max_Message_Block_Size
SHA1HashSize
SHA224HashSize
SHA256HashSize
SHA384HashSize
SHA512HashSize
USHAMaxHashSize
SHA1HashSizeBits
SHA224HashSizeBits
SHA256HashSizeBits
SHA384HashSizeBits
SHA512HashSizeBits
USHAMaxHashSizeBits
Definition at line 88 of file sha.h.
enum SHAversion
Enumerator
SHA1
SHA224
SHA256
SHA384
SHA512
Definition at line 106 of file sha.h.
Function Documentation
int SHA1Reset (SHA1Context *)
Definition at line 75 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, SHA1Context::Intermediate_Hash, SHA1Context::Length_High, SHA1Context::Length_Low, SHA1Context::Message_Block_Index, shaNull, and shaSuccess.
Referenced by md_map_shone(), and md_map_shone_mid().
int SHA1Input (SHA1Context * , const uint8_t * bytes, unsigned int bytecount)
Referenced by md_map_shone(), and md_map_shone_mid().
int SHA1FinalBits (SHA1Context * , const uint8_t bits, unsigned int bitcount)
Definition at line 166 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, SHA1AddLength, SHA1Finalize(), shaNull, shaStateError, and shaSuccess.
int SHA1Result (SHA1Context * , uint8_t Message_Digest[SHA1HashSize])
Definition at line 223 of file sha1.c.
References SHA1Context::Computed, SHA1Context::Corrupted, SHA1Context::Intermediate_Hash, SHA1Finalize(), SHA1HashSize, shaNull, and shaSuccess.
Referenced by md_map_shone().
int SHA224Reset (SHA224Context *)
Definition at line 102 of file sha224-256.c.
References SHA224_256Reset(), and SHA224_H0.
Referenced by md_map_sh224().
int SHA224Input (SHA224Context * , const uint8_t * bytes, unsigned int bytecount)
Definition at line 127 of file sha224-256.c.
References SHA256Input().
Referenced by md_map_sh224().
int SHA224FinalBits (SHA224Context * , const uint8_t bits, unsigned int bitcount)
Definition at line 152 of file sha224-256.c.
References SHA256FinalBits().
int SHA224Result (SHA224Context * , uint8_t Message_Digest[SHA224HashSize])
Definition at line 176 of file sha224-256.c.
References SHA224_256ResultN().
Referenced by md_map_sh224().
int SHA256Reset (SHA256Context *)
Definition at line 196 of file sha224-256.c.
References SHA224_256Reset(), and SHA256_H0.
Referenced by md_map_sh256().
int SHA256Input (SHA256Context * , const uint8_t * bytes, unsigned int bytecount)
Definition at line 220 of file sha224-256.c.
References SHA256Context::Computed, SHA256Context::Corrupted, SHA256Context::Message_Block, SHA256Context::Message_Block_Index, SHA224_256AddLength, SHA224_256ProcessMessageBlock(), SHA256_Message_Block_Size, shaNull, shaStateError, and shaSuccess.
Referenced by md_map_sh256(), and SHA224Input().
int SHA256FinalBits (SHA256Context * , const uint8_t bits, unsigned int bitcount)
Definition at line 272 of file sha224-256.c.
References SHA256Context::Computed, SHA256Context::Corrupted, SHA224_256AddLength, SHA224_256Finalize(), shaNull, shaStateError, and shaSuccess.
Referenced by SHA224FinalBits().
int SHA256Result (SHA256Context * , uint8_t Message_Digest[SHA256HashSize])
Referenced by md_map_sh256().
int SHA384Reset (SHA384Context *)
Definition at line 318 of file sha384-512.c.
References SHA384_512Reset(), and SHA384_H0.
Referenced by md_map_sh384().
int SHA384Input (SHA384Context * , const uint8_t * bytes, unsigned int bytecount)
Definition at line 343 of file sha384-512.c.
References SHA512Input().
Referenced by md_map_sh384().
int SHA384FinalBits (SHA384Context * , const uint8_t bits, unsigned int bitcount)
Definition at line 369 of file sha384-512.c.
References SHA512FinalBits().
int SHA384Result (SHA384Context * , uint8_t Message_Digest[SHA384HashSize])
Definition at line 394 of file sha384-512.c.
References SHA384_512ResultN().
Referenced by md_map_sh384().
int SHA512Reset (SHA512Context *)
Definition at line 415 of file sha384-512.c.
References SHA384_512Reset(), and SHA512_H0.
Referenced by md_map_sh512().
int SHA512Input (SHA512Context * , const uint8_t * bytes, unsigned int bytecount)
Definition at line 440 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Corrupted, SHA512Context::Message_Block, SHA512Context::Message_Block_Index, SHA384_512AddLength, SHA384_512ProcessMessageBlock(), SHA512_Message_Block_Size, shaNull, shaStateError, and shaSuccess.
Referenced by md_map_sh512(), and SHA384Input().
int SHA512FinalBits (SHA512Context * , const uint8_t bits, unsigned int bitcount)
Definition at line 497 of file sha384-512.c.
References SHA512Context::Computed, SHA512Context::Corrupted, SHA384_512AddLength, SHA384_512Finalize(), shaNull, shaStateError, and shaSuccess.
Referenced by SHA384FinalBits().
int SHA512Result (SHA512Context * , uint8_t Message_Digest[SHA512HashSize])
Definition at line 595 of file sha384-512.c.
References SHA384_512ResultN().
Referenced by md_map_sh512().