RELIC: src/epx/relic_ep2_dbl.c File Reference
relic_ep2_dbl.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep2_dbl_basic_imp (ep2_t r, fp2_t s, ep2_t p)
static void ep2_dbl_projc_imp (ep2_t r, ep2_t p)
void ep2_dbl_basic (ep2_t r, ep2_t p)
void ep2_dbl_slp_basic (ep2_t r, fp2_t s, ep2_t p)
void ep2_dbl_projc (ep2_t r, ep2_t p)
Detailed Description
Implementation of doubling on elliptic prime curves over quadratic extensions.
Version
Id:
relic_ep2_dbl.c 1435 2013-05-06 06:08:32Z dfaranha
Definition in file relic_ep2_dbl.c.
Function Documentation
static void ep2_dbl_basic_imp (ep2_t r, fp2_t s, ep2_t p) static
Doubles a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the resulting slope.
[in] p - the point to double.
Definition at line 49 of file relic_ep2_dbl.c.
References CATCH_ANY, ep2_curve_is_twist(), ep_curve_get_a(), ep_curve_opt_a(), ERR_CAUGHT, FINALLY, fp2_add, fp2_copy(), fp2_dbl, fp2_free, fp2_inv(), fp2_mul, fp2_mul_art(), fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_copy(), fp_set_dig(), fp_zero(), OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by ep2_dbl_basic(), and ep2_dbl_slp_basic().
static void ep2_dbl_projc_imp (ep2_t r, ep2_t p) static
Doubles a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 143 of file relic_ep2_dbl.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_add, fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_sub, THROW, and TRY.
Referenced by ep2_dbl_projc().
void ep2_dbl_basic (ep2_t r, ep2_t p)
Doubles a points represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
int] p - the point to double.
Definition at line 199 of file relic_ep2_dbl.c.
References ep2_dbl_basic_imp(), ep2_is_infty(), and ep2_set_infty().
Referenced by ep2_add_basic_imp(), and ep2_mul_pre_yaowi().
void ep2_dbl_slp_basic (ep2_t r, fp2_t s, ep2_t p)
Doubles a points represented in affine coordinates in an elliptic curve over a quadratic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 208 of file relic_ep2_dbl.c.
References ep2_dbl_basic_imp(), ep2_is_infty(), and ep2_set_infty().
Referenced by pp_dbl_k12_basic().
void ep2_dbl_projc (ep2_t r, ep2_t p)
Doubles a points represented in projective coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 221 of file relic_ep2_dbl.c.
References ep2_dbl_projc_imp(), ep2_is_infty(), and ep2_set_infty().
Referenced by ep2_add_projc_imp(), and ep2_add_projc_mix().