RELIC: src/fp/relic_fp_param.c File Reference
relic_fp_param.c File Reference
Prime field arithmetic.
#include "relic_core.h"
#include "relic_fpx.h"
Functions
int fp_param_get (void)
void fp_param_get_var (bn_t x)
void fp_param_get_sps (int *s, int *len)
void fp_param_get_map (int *s, int *len)
void fp_param_set (int param)
int fp_param_set_any (void)
int fp_param_set_any_dense ()
int fp_param_set_any_pmers (void)
int fp_param_set_any_tower ()
void fp_param_print (void)
Detailed Description
Implementation of the prime field modulus manipulation.
Version
Id:
relic_fp_param.c 1558 2013-08-30 06:57:29Z dfaranha
Definition in file relic_fp_param.c.
Function Documentation
int fp_param_get (void)
Returns the prime field parameter identifier.
Returns
the parameter identifier.
Definition at line 50 of file relic_fp_param.c.
References core_get(), and _ctx_t::fp_id.
Referenced by fp_param_get_map(), fp_param_get_sps(), and fp_param_get_var().
void fp_param_get_var (bn_t x)
Returns the variable used to parameterize the given prime modulus.
Parameters
[out] x - the integer parameter.
Definition at line 54 of file relic_fp_param.c.
References B12_638, B24_477, BN_158, BN_254, BN_256, BN_638, bn_add(), bn_add_dig(), bn_free, bn_lsh(), bn_neg(), bn_new, bn_null, bn_set_2b(), bn_set_dig(), bn_sub(), CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_param_get(), KSS_508, SS_1536, THROW, and TRY.
Referenced by ep2_mul_cof_b12(), ep2_mul_cof_bn(), fp_param_get_sps(), fp_param_set(), pp_exp_b12(), pp_exp_bn(), and pp_map_oatep_k12().
void fp_param_get_sps (int * s, int * len)
Returns the absolute value of the variable used to parameterize the currently configured prime modulus in sparse form. The first argument must be an array of size (MAX_TERMS + 1).
Parameters
[out] s - the parameter in sparse form.
[out] len - the length of the parameter in sparse form.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
ERR_NO_VALID - if the current configuration is invalid.
Returns
the integer parameter in sparse form.
Definition at line 149 of file relic_fp_param.c.
References B12_638, B24_477, BN_158, BN_254, BN_256, BN_638, bn_bits(), bn_free, bn_ham(), bn_neg(), BN_NEG, bn_new, bn_null, bn_sign(), bn_test_bit(), CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_VALID, FINALLY, fp_param_get(), fp_param_get_var(), KSS_508, MAX_TERMS, SS_1536, THROW, and TRY.
Referenced by pp_exp_b12(), and pp_exp_bn().
void fp_param_get_map (int * s, int * len)
Returns the value of the parameter used to construct the optimal ate pairing on the currently configured elliptic curve. The first argument must be an array of size FP_BITS.
Parameters
[out] s - the parameter in sparse form.
[out] len - the length of the parameter in sparse form.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
ERR_NO_VALID - if the current configuration is invalid.
Definition at line 225 of file relic_fp_param.c.
References B12_638, B24_477, BN_158, BN_254, BN_256, BN_638, ERR_NO_BUFFER, ERR_NO_VALID, FP_BITS, fp_param_get(), KSS_508, SS_1536, and THROW.
Referenced by pp_map_oatep_k12().
void fp_param_set (int param)
Assigns a prime modulus based on its identifier.
Definition at line 277 of file relic_fp_param.c.
References B12_638, B24_477, BN_158, BN_254, BN_256, BN_638, bn_add(), bn_add_dig(), bn_dbl(), bn_div_dig(), bn_free, bn_gen_prime, bn_mul, bn_mul_dig(), bn_new, bn_null, bn_read_str(), bn_set_dig(), bn_sqr, bn_sub(), bn_sub_dig(), CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, FP_BITS, _ctx_t::fp_id, fp_param_get_var(), fp_prime_set_dense(), fp_prime_set_pmers(), KSS_508, NIST_192, NIST_224, NIST_256, NIST_384, NIST_521, SECG_160, SECG_160D, SECG_192, SECG_224, SECG_256, SS_1536, SS_P1536, THROW, and TRY.
Referenced by fp_param_set_any(), fp_param_set_any_pmers(), and fp_param_set_any_tower().
int fp_param_set_any (void)
Assigns any pre-defined parameter as the prime modulus.
Returns
STS_OK if no errors occurred; STS_ERR otherwise.
Definition at line 574 of file relic_fp_param.c.
References B12_638, B24_477, BN_158, BN_254, BN_256, fp_param_set(), fp_param_set_any_dense(), KSS_508, NIST_192, NIST_224, NIST_384, NIST_521, SECG_160, SECG_256, SS_1536, and STS_OK.
int fp_param_set_any_dense (void)
Assigns the order of the prime field to any non-sparse prime.
Returns
STS_OK if no errors occurred; STS_ERR otherwise.
Definition at line 609 of file relic_fp_param.c.
References bn_free, bn_gen_prime, bn_is_prime(), bn_new, bn_null, CATCH_ANY, ERR_CAUGHT, FINALLY, FP_BITS, fp_prime_set_dense(), STS_ERR, STS_OK, THROW, and TRY.
Referenced by fp_param_set_any(), and fp_param_set_any_tower().
int fp_param_set_any_pmers (void)
Assigns the order of the prime field to any sparse prime.
Returns
STS_OK if no errors occurred; STS_ERR otherwise.
Definition at line 633 of file relic_fp_param.c.
References fp_param_set(), NIST_192, NIST_224, NIST_256, NIST_384, NIST_521, SECG_160, STS_ERR, and STS_OK.
int fp_param_set_any_tower (void)
Assigns the order of the prime field to any towering-friendly prime.
Returns
STS_OK if no errors occurred; STS_ERR otherwise.
Definition at line 652 of file relic_fp_param.c.
References B12_638, B24_477, BN_158, BN_254, BN_256, fp_param_set(), fp_param_set_any_dense(), fp_prime_get_mod8(), KSS_508, SS_1536, and STS_OK.
void fp_param_print (void)
Prints the currently configured prime modulus.
Definition at line 677 of file relic_fp_param.c.
References fp_prime_get(), fp_print(), util_banner, and util_print.