RELIC: include/relic_bn.h File Reference
relic_bn.h File Reference
Multiple precision integer arithmetic.
#include "relic_conf.h"
#include "relic_types.h"
#include "relic_label.h"
Data Structures
struct bn_st
Macros
#define BN_BITS ((int)BN_PRECI)
#define BN_DIGIT ((int)DIGIT)
#define BN_DIG_LOG ((int)DIGIT_LOG)
#define BN_DIGS ((int)((BN_BITS)/(BN_DIGIT) + (BN_BITS % BN_DIGIT > 0)))
#define BN_BYTES ((int)((BN_BITS)/8 + ((BN_BITS % 8) > 0)))
#define BN_SIZE ((int)(2 * BN_DIGS + 2))
#define BN_POS (0)
#define BN_NEG (1)
#define bn_null(A) /* empty */
#define bn_new(A) bn_init(A, BN_SIZE); \
#define bn_new_size(A, D) bn_init(A, D); \
#define bn_free(A) /* empty */ \
#define bn_mul(C, A, B) bn_mul_comba(C, A, B)
#define bn_sqr(C, A) bn_sqr_comba(C, A)
#define bn_mod_pre(U, M) bn_mod_pre_monty(U, M)
#define bn_mod(C, A,...) CAT(bn_mod, OPT(__VA_ARGS__))(C, A, __VA_ARGS__)
#define bn_mod_imp(C, A, M, U) bn_mod_monty(C, A, M, U)
#define bn_mod_monty(C, A, M, U) bn_mod_monty_comba(C, A, M, U)
#define bn_mxp(C, A, B, M) bn_mxp_slide(C, A, B, M)
#define bn_gcd(C, A, B) bn_gcd_basic(C, A, B)
#define bn_gcd_ext(C, D, E, A, B) bn_gcd_ext_basic(C, D, E, A, B)
#define bn_gen_prime(A, B) bn_gen_prime_basic(A, B)
Typedefs
typedef bn_st bn_t [1]
Functions
void bn_init (bn_t a, int digits)
void bn_clean (bn_t a)
void bn_grow (bn_t a, int digits)
void bn_trim (bn_t a)
void bn_copy (bn_t c, const bn_t a)
void bn_abs (bn_t c, const bn_t a)
void bn_neg (bn_t c, const bn_t a)
int bn_sign (const bn_t a)
void bn_zero (bn_t a)
int bn_is_zero (const bn_t a)
int bn_is_even (const bn_t a)
int bn_bits (const bn_t a)
int bn_test_bit (const bn_t a, int bit)
int bn_get_bit (const bn_t a, int bit)
void bn_set_bit (bn_t a, int bit, int value)
int bn_ham (const bn_t a)
void bn_get_dig (dig_t *digit, const bn_t a)
void bn_set_dig (bn_t a, dig_t digit)
void bn_set_2b (bn_t a, int b)
void bn_rand (bn_t a, int sign, int bits)
void bn_print (const bn_t a)
void bn_size_str (int *size, const bn_t a, int radix)
void bn_read_str (bn_t a, const char *str, int len, int radix)
void bn_write_str (char *str, int len, const bn_t a, int radix)
void bn_size_bin (int *size, const bn_t a)
void bn_read_bin (bn_t a, const unsigned char *bin, int len)
void bn_write_bin (unsigned char *bin, int len, const bn_t a)
void bn_size_raw (int *size, const bn_t a)
void bn_read_raw (bn_t a, const dig_t *raw, int len)
void bn_write_raw (dig_t *raw, int len, const bn_t a)
int bn_cmp_abs (const bn_t a, const bn_t b)
int bn_cmp_dig (const bn_t a, dig_t b)
int bn_cmp (const bn_t a, const bn_t b)
void bn_add (bn_t c, const bn_t a, const bn_t b)
void bn_add_dig (bn_t c, const bn_t a, dig_t b)
void bn_sub (bn_t c, const bn_t a, const bn_t b)
void bn_sub_dig (bn_t c, const bn_t a, const dig_t b)
void bn_mul_dig (bn_t c, const bn_t a, dig_t b)
void bn_mul_basic (bn_t c, const bn_t a, const bn_t b)
void bn_mul_comba (bn_t c, const bn_t a, const bn_t b)
void bn_mul_karat (bn_t c, const bn_t a, const bn_t b)
void bn_sqr_basic (bn_t c, const bn_t a)
void bn_sqr_comba (bn_t c, const bn_t a)
void bn_sqr_karat (bn_t c, const bn_t a)
void bn_dbl (bn_t c, const bn_t a)
void bn_hlv (bn_t c, const bn_t a)
void bn_lsh (bn_t c, const bn_t a, int bits)
void bn_rsh (bn_t c, const bn_t a, int bits)
void bn_div (bn_t c, const bn_t a, const bn_t b)
void bn_div_rem (bn_t c, bn_t d, const bn_t a, const bn_t b)
void bn_div_dig (bn_t c, const bn_t a, dig_t b)
void bn_div_rem_dig (bn_t c, dig_t *d, const bn_t a, const dig_t b)
void bn_mod_2b (bn_t c, const bn_t a, int b)
void bn_mod_dig (dig_t *c, const bn_t a, dig_t b)
void bn_mod_basic (bn_t c, const bn_t a, const bn_t m)
void bn_mod_pre_barrt (bn_t u, const bn_t m)
void bn_mod_barrt (bn_t c, const bn_t a, const bn_t m, const bn_t u)
void bn_mod_pre_monty (bn_t u, const bn_t m)
void bn_mod_monty_conv (bn_t c, const bn_t a, const bn_t m)
void bn_mod_monty_back (bn_t c, const bn_t a, const bn_t m)
void bn_mod_monty_basic (bn_t c, const bn_t a, const bn_t m, const bn_t u)
void bn_mod_monty_comba (bn_t c, const bn_t a, const bn_t m, const bn_t u)
void bn_mod_pre_pmers (bn_t u, const bn_t m)
void bn_mod_pmers (bn_t c, const bn_t a, const bn_t m, const bn_t u)
void bn_mxp_basic (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_slide (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_monty (bn_t c, const bn_t a, const bn_t b, const bn_t m)
void bn_mxp_dig (bn_t c, const bn_t a, dig_t b, const bn_t m)
void bn_gcd_basic (bn_t c, const bn_t a, const bn_t b)
void bn_gcd_lehme (bn_t c, const bn_t a, const bn_t b)
void bn_gcd_stein (bn_t c, const bn_t a, const bn_t b)
void bn_gcd_dig (bn_t c, const bn_t a, dig_t b)
void bn_gcd_ext_basic (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
void bn_gcd_ext_lehme (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
void bn_gcd_ext_stein (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
void bn_gcd_ext_mid (bn_t c, bn_t d, bn_t e, bn_t f, const bn_t a, const bn_t b)
void bn_gcd_ext_dig (bn_t c, bn_t d, bn_t e, const bn_t a, dig_t b)
void bn_lcm (bn_t c, const bn_t a, const bn_t b)
void bn_smb_leg (bn_t c, const bn_t a, const bn_t b)
void bn_smb_jac (bn_t c, const bn_t a, const bn_t b)
dig_t bn_get_prime (int pos)
int bn_is_prime (const bn_t a)
int bn_is_prime_basic (const bn_t a)
int bn_is_prime_rabin (const bn_t a)
int bn_is_prime_solov (const bn_t a)
void bn_gen_prime_basic (bn_t a, int bits)
void bn_gen_prime_safep (bn_t a, int bits)
void bn_gen_prime_stron (bn_t a, int bits)
int bn_factor (bn_t c, const bn_t a)
int bn_is_factor (bn_t c, const bn_t a)
void bn_rec_win (unsigned char *win, int *len, const bn_t k, int w)
void bn_rec_slw (unsigned char *win, int *len, const bn_t k, int w)
void bn_rec_naf (signed char *naf, int *len, const bn_t k, int w)
void bn_rec_tnaf (signed char *tnaf, int *len, const bn_t k, const bn_t vm, const bn_t s0, const bn_t s1, signed char u, int m, int w)
void bn_rec_reg (signed char *naf, int *len, const bn_t k, int n, int w)
void bn_rec_jsf (signed char *jsf, int *len, const bn_t k, const bn_t l)
void bn_rec_glv (bn_t k0, bn_t k1, const bn_t k, const bn_t n, const bn_t v1[], const bn_t v2[])
Detailed Description
Interface of the module for multiple precision integer arithmetic.
Version
Id:
relic_bn.h 1581 2013-09-03 08:15:50Z dfaranha
Definition in file relic_bn.h.
Macro Definition Documentation
#define BN_BITS ((int)BN_PRECI)
Precision in bits of a multiple precision integer.
If the library is built with support for dynamic allocation, this constant represents the size in bits of the memory block allocated each time a multiple precision integer must grow. Otherwise, it represents the fixed fixed precision.
Definition at line 55 of file relic_bn.h.
Referenced by bn_mxp_slide(), and conf_print().
#define BN_DIGIT ((int)DIGIT)
Size in bits of a digit.
Definition at line 60 of file relic_bn.h.
Referenced by bn_bits(), bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_stron(), bn_grow(), bn_lsh(), bn_mod_2b(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_conv(), bn_mod_pre_barrt(), bn_mul_karat_imp(), bn_mxp_monty(), bn_print(), bn_rand(), bn_read_bin(), bn_size_bin(), bn_sqr_karat_imp(), bn_write_bin(), eb_map(), ep_map(), ep_mul_monty(), fp_prime_set(), and get_bits().
#define BN_DIG_LOG ((int)DIGIT_LOG)
Logarithm of the digit size in base 2.
Definition at line 65 of file relic_bn.h.
Referenced by bn_get_bit(), bn_lsh(), bn_mod_2b(), bn_rand(), bn_rsh(), bn_set_2b(), bn_set_bit(), bn_test_bit(), and get_bits().
#define BN_DIGS ((int)((BN_BITS)/(BN_DIGIT) + (BN_BITS % BN_DIGIT > 0)))
Size in digits of a block sufficient to store the required precision.
Definition at line 70 of file relic_bn.h.
Referenced by conf_print().
#define BN_BYTES ((int)((BN_BITS)/8 + ((BN_BITS % 8) > 0)))
Size in bytes of a block sufficient to store the required precision.
Definition at line 75 of file relic_bn.h.
#define BN_SIZE ((int)(2 * BN_DIGS + 2))
Size in digits of a block sufficient to store a multiple precision integer.
Definition at line 81 of file relic_bn.h.
Referenced by bn_grow(), and bn_init().
#define BN_POS (0)
Positive sign of a multiple precision integer.
Definition at line 91 of file relic_bn.h.
Referenced by bn_abs(), bn_add_dig(), bn_clean(), bn_cmp(), bn_div_imp(), bn_gen_prime_basic(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_init(), bn_is_prime_solov(), bn_lcm(), bn_read_bin(), bn_read_raw(), bn_read_str(), bn_set_2b(), bn_set_dig(), bn_size_str(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_sub(), bn_sub_dig(), bn_trim(), bn_write_str(), bn_zero(), cp_bbs_gen(), cp_bls_gen(), cp_ecdh_gen(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecmqv_gen(), cp_ecss_gen(), cp_ecss_sig(), cp_ecss_ver(), cp_sokaka_gen(), eb_mul_halve(), eb_rand(), ep2_rand(), ep_curve_set_kbltz(), ep_mul_combs_kbltz(), ep_mul_glv_imp(), ep_mul_sim_kbltz(), ep_rand(), fp_prime_back(), and pp_exp_k2().
#define BN_NEG (1)
Negative sign of a multiple precision integer.
Definition at line 96 of file relic_bn.h.
Referenced by bn_add_dig(), bn_cmp(), bn_cmp_dig(), bn_div_imp(), bn_is_prime_solov(), bn_mod_barrt(), bn_mod_monty_conv(), bn_print(), bn_read_str(), bn_rec_tnaf(), bn_size_str(), bn_smb_jac(), bn_smb_leg(), bn_sub(), bn_sub_dig(), bn_write_str(), cp_bbs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_rabin_dec(), cp_rsa_dec_quick(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_quick(), eb_tab(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep_mul_combs_kbltz(), ep_mul_sim_kbltz(), fp_inv_binar(), fp_inv_exgcd(), fp_param_get_sps(), pp_exp_b12(), pp_exp_bn(), pp_map_oatep_k12(), and tnaf_mod().
#define bn_null (A) /* empty */
Initializes a multiple precision integer with a null value.
Parameters
[out] A - the multiple precision integer to initialize.
Definition at line 144 of file relic_bn.h.
Referenced by bn_div_dig(), bn_div_imp(), bn_div_rem_dig(), bn_factor(), bn_gcd_basic(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_lehme(), bn_gcd_stein(), bn_gen_prime_stron(), bn_is_factor(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lcm(), bn_mod_barrt(), bn_mod_monty_back(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_mul_basic(), bn_mul_comba(), bn_mul_karat_imp(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_tnaf(), bn_size_str(), bn_smb_jac(), bn_smb_leg(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_write_str(), compute_kbltz(), cp_bbs_gen(), cp_bbs_sig(), cp_bbs_ver(), cp_bls_gen(), cp_ecdh_gen(), cp_ecdh_key(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecmqv_gen(), cp_ecmqv_key(), cp_ecss_gen(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), cp_rabin_enc(), cp_rabin_gen(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), cp_sokaka_gen(), cp_sokaka_key(), eb_map(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_halve(), eb_mul_ltnaf_imp(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_pre_nafwi(), eb_mul_pre_yaowi(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), eb_mul_sim_trick(), eb_param_set(), eb_rand(), ep2_curve_set(), ep2_map(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_nafwi(), ep2_mul_pre_yaowi(), ep2_mul_sim_trick(), ep2_rand(), ep_map(), ep_mul_combs_kbltz(), ep_mul_combs_ordin(), ep_mul_fix_combd(), ep_mul_glv_imp(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_pre_nafwi(), ep_mul_pre_yaowi(), ep_mul_sim_kbltz(), ep_mul_sim_trick(), ep_param_set(), ep_rand(), fp2_calc(), fp2_mul_nor_basic(), fp3_calc(), fp3_srt(), fp_inv_basic(), fp_inv_binar(), fp_inv_exgcd(), fp_inv_monty(), fp_param_get_sps(), fp_param_get_var(), fp_param_set(), fp_param_set_any_dense(), fp_prime_conv(), fp_prime_conv_dig(), fp_prime_set(), fp_prime_set_pmers(), fp_print(), fp_read(), fp_size(), fp_srt(), fp_write(), pad_pkcs1(), pp_exp_b12(), pp_exp_bn(), pp_exp_k2(), pp_map_oatep_k12(), pp_map_tatep_k12(), pp_map_tatep_k2(), pp_map_weilp_k12(), pp_map_weilp_k2(), and tnaf_mod().
#define bn_new (A) bn_init(A, BN_SIZE); \
Calls a function to allocate and initialize a multiple precision integer.
Parameters
[in,out] A - the multiple precision integer to initialize.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 172 of file relic_bn.h.
Referenced by bn_div_dig(), bn_div_imp(), bn_div_rem_dig(), bn_factor(), bn_gcd_basic(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_lehme(), bn_gcd_stein(), bn_gen_prime_stron(), bn_is_factor(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lcm(), bn_mod_barrt(), bn_mod_monty_back(), bn_mod_pmers(), bn_mul_karat_imp(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_tnaf(), bn_size_str(), bn_smb_jac(), bn_smb_leg(), bn_sqr_karat_imp(), bn_write_str(), compute_kbltz(), cp_bbs_gen(), cp_bbs_sig(), cp_bbs_ver(), cp_bls_gen(), cp_ecdh_gen(), cp_ecdh_key(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecmqv_gen(), cp_ecmqv_key(), cp_ecss_gen(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), cp_rabin_enc(), cp_rabin_gen(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), cp_sokaka_gen(), cp_sokaka_key(), eb_map(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_halve(), eb_mul_ltnaf_imp(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_pre_nafwi(), eb_mul_pre_yaowi(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), eb_mul_sim_trick(), eb_param_set(), eb_rand(), eb_tab(), ep2_curve_set(), ep2_map(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_nafwi(), ep2_mul_pre_yaowi(), ep2_mul_sim_trick(), ep2_rand(), ep_map(), ep_mul_combs_kbltz(), ep_mul_combs_ordin(), ep_mul_fix_combd(), ep_mul_glv_imp(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_pre_nafwi(), ep_mul_pre_yaowi(), ep_mul_sim_kbltz(), ep_mul_sim_trick(), ep_param_set(), ep_rand(), fp2_calc(), fp2_mul_nor_basic(), fp3_calc(), fp3_srt(), fp_inv_basic(), fp_inv_binar(), fp_inv_exgcd(), fp_inv_monty(), fp_param_get_sps(), fp_param_get_var(), fp_param_set(), fp_param_set_any_dense(), fp_prime_conv(), fp_prime_set(), fp_prime_set_pmers(), fp_print(), fp_read(), fp_size(), fp_srt(), fp_write(), pad_pkcs1(), pp_exp_b12(), pp_exp_bn(), pp_exp_k2(), pp_map_oatep_k12(), pp_map_tatep_k12(), pp_map_tatep_k2(), pp_map_weilp_k12(), pp_map_weilp_k2(), and tnaf_mod().
#define bn_new_size (A, D) bn_init(A, D); \
Calls a function to allocate and initialize a multiple precision integer with the required precision in digits.
Parameters
[in,out] A - the multiple precision integer to initialize.
[in] D - the precision in digits.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
ERR_PRECISION - if the required precision cannot be represented by the library.
Definition at line 209 of file relic_bn.h.
Referenced by bn_div_imp(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mul_basic(), bn_mul_comba(), bn_sqr_basic(), and bn_sqr_comba().
#define bn_free (A) /* empty */ \
Calls a function to clean and free a multiple precision integer.
Parameters
[in,out] A - the multiple precision integer to free.
Definition at line 240 of file relic_bn.h.
Referenced by bn_div_dig(), bn_div_imp(), bn_div_rem_dig(), bn_factor(), bn_gcd_basic(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_lehme(), bn_gcd_stein(), bn_gen_prime_stron(), bn_is_factor(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lcm(), bn_mod_barrt(), bn_mod_monty_back(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_mul_basic(), bn_mul_comba(), bn_mul_karat_imp(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_tnaf(), bn_size_str(), bn_smb_jac(), bn_smb_leg(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_write_str(), compute_kbltz(), cp_bbs_gen(), cp_bbs_sig(), cp_bbs_ver(), cp_bls_gen(), cp_ecdh_gen(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecmqv_gen(), cp_ecmqv_key(), cp_ecss_gen(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), cp_rabin_enc(), cp_rabin_gen(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), cp_sokaka_gen(), cp_sokaka_key(), eb_map(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_halve(), eb_mul_ltnaf_imp(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_pre_nafwi(), eb_mul_pre_yaowi(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), eb_mul_sim_trick(), eb_param_set(), eb_rand(), ep2_curve_set(), ep2_map(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_nafwi(), ep2_mul_pre_yaowi(), ep2_mul_sim_trick(), ep2_rand(), ep_map(), ep_mul_combs_kbltz(), ep_mul_combs_ordin(), ep_mul_fix_combd(), ep_mul_glv_imp(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_pre_nafwi(), ep_mul_pre_yaowi(), ep_mul_sim_kbltz(), ep_mul_sim_trick(), ep_param_set(), ep_rand(), fp2_calc(), fp2_mul_nor_basic(), fp3_calc(), fp3_srt(), fp_inv_basic(), fp_inv_binar(), fp_inv_exgcd(), fp_inv_monty(), fp_param_get_sps(), fp_param_get_var(), fp_param_set(), fp_param_set_any_dense(), fp_prime_conv(), fp_prime_set(), fp_prime_set_pmers(), fp_print(), fp_read(), fp_size(), fp_srt(), fp_write(), pad_pkcs1(), pp_exp_b12(), pp_exp_bn(), pp_exp_k2(), pp_map_oatep_k12(), pp_map_tatep_k12(), pp_map_tatep_k2(), pp_map_weilp_k12(), pp_map_weilp_k2(), and tnaf_mod().
#define bn_mul (C, A, B) bn_mul_comba(C, A, B)
Multiples two multiple precision integers. Computes c = a * b.
Parameters
[out] C - the result.
[in] A - the first multiple precision integer to multiply.
[in] B - the second multiple precision integer to multiply.
Definition at line 260 of file relic_bn.h.
Referenced by bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gen_prime_stron(), bn_lcm(), bn_mod_barrt(), bn_mod_pmers(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), bn_rec_glv(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecmqv_key(), cp_ecss_sig(), cp_rabin_dec(), cp_rabin_gen(), cp_rsa_dec_quick(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_quick(), ep_curve_set_kbltz(), fp_inv_exgcd(), fp_param_set(), and tnaf_mod().
#define bn_sqr (C, A) bn_sqr_comba(C, A)
Computes the square of a multiple precision integer. Computes c = a * a.
Parameters
[out] C - the result.
[in] A - the multiple precision integer to square.
Definition at line 274 of file relic_bn.h.
Referenced by bn_gcd_ext_mid(), bn_is_prime_rabin(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), cp_rabin_enc(), and fp_param_set().
#define bn_mod_pre (U, M) bn_mod_pre_monty(U, M)
Computes the auxiliar value derived from the modulus to be used during modular reduction.
Parameters
[out] U - the result.
[in] M - the modulus.
Definition at line 291 of file relic_bn.h.
Referenced by bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), and bn_mxp_slide().
#define bn_mod (C, A, ...) CAT(bn_mod, OPT(__VA_ARGS__))(C, A, __VA_ARGS__)
Reduces a multiple precision integer modulo another integer. If the number of arguments is 3, then simple division is used. If the number of arguments is 4, then a modular reduction algorithm is used and the fourth argument is an auxiliary value derived from the modulus. The variant with 4 arguments should be used when several modular reductions are computed with the same modulus. Computes c = a mod m.
Parameters
[out] C - the result.
[in] A - the multiple precision integer to reduce.
[in] ... - the modulus and an optional argument.
Definition at line 308 of file relic_bn.h.
Referenced by bn_gcd_basic(), bn_gcd_lehme(), bn_is_factor(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_monty_conv(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), bn_smb_jac(), cp_bbs_gen(), cp_bbs_sig(), cp_bbs_ver(), cp_bls_gen(), cp_ecdh_gen(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecmqv_gen(), cp_ecmqv_key(), cp_ecss_gen(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec_quick(), cp_rsa_gen_quick(), cp_rsa_sig_quick(), cp_sokaka_gen(), eb_mul_halve(), eb_rand(), ep2_rand(), ep_rand(), fp_prime_conv(), and fp_prime_set().
#define bn_mod_imp (C, A, M, U) bn_mod_monty(C, A, M, U)
Reduces a multiple precision integer modulo another integer. This macro should not be called directly. Use bn_mod with 4 arguments instead.
Parameters
[out] C - the result.
[in] A - the the multiple precision integer to reduce.
[in] M - the modulus.
[in] U - the auxiliar value derived from the modulus.
Definition at line 324 of file relic_bn.h.
#define bn_mod_monty (C, A, M, U) bn_mod_monty_comba(C, A, M, U)
Reduces a multiple precision integer modulo a modulus using Montgomery reduction. Computes c = a * u^(-1) (mod m).
Parameters
[out] C - the result.
[in] A - the multiple precision integer to reduce.
[in] M - the modulus.
[in] U - the reciprocal of the modulus.
Definition at line 341 of file relic_bn.h.
Referenced by bn_mod_monty_back().
#define bn_mxp (C, A, B, M) bn_mxp_slide(C, A, B, M)
Exponentiates a multiple precision integer modulo another multiple precision integer. Computes c = a^b mod m. If Montgomery reduction is used, the basis must not be in Montgomery form.
Parameters
[out] C - the result.
[in] A - the basis.
[in] B - the exponent.
[in] M - the modulus.
Definition at line 357 of file relic_bn.h.
Referenced by bn_factor(), bn_gen_prime_stron(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_smb_leg(), cp_rabin_dec(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), and cp_rsa_ver().
#define bn_gcd (C, A, B) bn_gcd_basic(C, A, B)
Computes the greatest common divisor of two multiple precision integers. Computes c = gcd(a, b).
Parameters
[out] C - the result;
[in] A - the first multiple precision integer.
[in] B - the second multiple precision integer.
Definition at line 371 of file relic_bn.h.
Referenced by bn_factor(), and bn_lcm().
#define bn_gcd_ext (C, D, E, A, B) bn_gcd_ext_basic(C, D, E, A, B)
Computes the extended greatest common divisor of two multiple precision integers. This function can be used to compute multiplicative inverses. Computes c = gcd(a, b) and c = a * d + b * e.
Parameters
[out] C - the result;
[out] D - the cofactor of the first operand, cannot be NULL.
[out] E - the cofactor of the second operand, can be NULL.
[in] A - the first multiple precision integer.
[in] B - the second multiple precision integer.
Definition at line 390 of file relic_bn.h.
Referenced by cp_bbs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_rabin_gen(), cp_rsa_gen_basic(), and cp_rsa_gen_quick().
#define bn_gen_prime (A, B) bn_gen_prime_basic(A, B)
Generates a probable prime number.
Parameters
[out] A - the result.
[in] B - the length of the number in bits.
Definition at line 404 of file relic_bn.h.
Referenced by cp_rabin_gen(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), fp_param_set(), and fp_param_set_any_dense().
Typedef Documentation
typedef bn_st bn_t[1]
Pointer to a multiple precision integer structure.
Definition at line 129 of file relic_bn.h.
Function Documentation
void bn_init (bn_t a, int digits)
Initializes a previously allocated multiple precision integer.
Parameters
[out] a - the multiple precision integer to initialize.
[in] digits - the required precision in digits.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
ERR_PRECISION - if the required precision cannot be represented by the library.
Definition at line 44 of file relic_bn_mem.c.
References ALIGN, BN_POS, BN_SIZE, ERR_NO_MEMORY, ERR_NO_PRECI, ERR_NO_VALID, and THROW.
Referenced by eb_curve_init(), ep2_curve_init(), ep_curve_init(), and fp_prime_init().
void bn_clean (bn_t a)
Cleans a multiple precision integer.
Parameters
[out] a - the multiple precision integer to free.
Definition at line 95 of file relic_bn_mem.c.
References BN_POS.
Referenced by eb_curve_clean(), ep2_curve_clean(), ep_curve_clean(), and fp_prime_clean().
void bn_grow (bn_t a, int digits)
Checks the current precision of a multiple precision integer and optionally expands its precision to a given size in digits.
Parameters
[out] a - the multiple precision integer to expand.
[in] digits - the number of digits to expand.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
ERR_PRECISION - if the required precision cannot be represented by the library.
Definition at line 121 of file relic_bn_mem.c.
References BN_DIGIT, BN_SIZE, ERR_NO_MEMORY, ERR_NO_PRECI, and THROW.
Referenced by bn_add_dig(), bn_add_imp(), bn_copy(), bn_dbl(), bn_hlv(), bn_lsh(), bn_mul_dig(), bn_rand(), bn_read_bin(), bn_read_raw(), bn_set_2b(), bn_sub_dig(), bn_sub_imp(), and fp_prime_back().
void bn_trim (bn_t a)
Adjust the number of valid digits of a multiple precision integer.
Parameters
[out] a - the multiple precision integer to adjust.
Definition at line 144 of file relic_bn_mem.c.
References BN_POS.
Referenced by bn_add_dig(), bn_add_imp(), bn_div_dig(), bn_div_imp(), bn_div_rem_dig(), bn_hlv(), bn_lsh(), bn_mod_2b(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mul_basic(), bn_mul_comba(), bn_mul_dig(), bn_mul_karat_imp(), bn_mxp_slide(), bn_rand(), bn_read_bin(), bn_read_raw(), bn_rsh(), bn_set_bit(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_sub_dig(), bn_sub_imp(), fp_inv_monty(), fp_prime_back(), and fp_prime_set().
void bn_copy (bn_t c, const bn_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to copy.
Definition at line 40 of file relic_bn_util.c.
References bn_grow().
Referenced by bn_abs(), bn_div_dig(), bn_div_imp(), bn_div_rem_dig(), bn_factor(), bn_gcd_basic(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_lehme(), bn_gcd_stein(), bn_is_prime_solov(), bn_lsh(), bn_mod_2b(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_monty_conv(), bn_mod_pmers(), bn_mul_basic(), bn_mul_comba(), bn_mul_karat_imp(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), bn_neg(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_tnaf(), bn_rsh(), bn_size_str(), bn_smb_jac(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_write_str(), compute_kbltz(), cp_rabin_gen(), cp_rsa_dec_quick(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_quick(), eb_curve_get_cof(), eb_curve_get_ord(), eb_curve_get_s0(), eb_curve_get_s1(), eb_curve_get_vm(), eb_curve_set_kbltz(), eb_curve_set_ordin(), eb_curve_set_super(), eb_tab(), ep2_curve_get_ord(), ep2_curve_set(), ep_curve_get_cof(), ep_curve_get_ord(), ep_curve_get_v1(), ep_curve_get_v2(), ep_curve_set_kbltz(), ep_curve_set_ordin(), ep_curve_set_super(), fp_inv_binar(), fp_inv_exgcd(), and fp_prime_set().
void bn_abs (bn_t c, const bn_t a)
Returns the absolute value of a multiple precision integer.
Parameters
[out] c - the result.
[in] a - the argument of the absolute function.
Definition at line 56 of file relic_bn_util.c.
References bn_copy(), and BN_POS.
Referenced by bn_div_imp(), bn_gcd_basic(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_lehme(), bn_gcd_stein(), ep_mul_combs_kbltz(), ep_mul_glv_imp(), and ep_mul_sim_kbltz().
void bn_neg (bn_t c, const bn_t a)
Inverts the sign of a multiple precision integer.
Parameters
[out] c - the result.
[out] a - the multiple precision integer to negate.
Definition at line 63 of file relic_bn_util.c.
References bn_copy(), and bn_is_zero().
Referenced by bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_rec_glv(), bn_smb_jac(), bn_smb_leg(), compute_kbltz(), eb_tab(), ep_curve_set_kbltz(), fp_param_get_sps(), and fp_param_get_var().
int bn_sign (const bn_t a)
Returns the sign of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
BN_POS if the argument is positive and BN_NEG otherwise.
Definition at line 72 of file relic_bn_util.c.
Referenced by bn_is_prime_solov(), bn_mod_barrt(), bn_mod_monty_conv(), bn_rec_tnaf(), bn_smb_jac(), bn_smb_leg(), cp_bbs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_ver(), cp_rabin_dec(), cp_rsa_dec_quick(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_quick(), eb_tab(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep_curve_set_kbltz(), ep_mul_combs_kbltz(), ep_mul_glv_imp(), ep_mul_sim_kbltz(), fp_inv_binar(), fp_inv_exgcd(), fp_param_get_sps(), pp_exp_b12(), pp_exp_bn(), pp_map_oatep_k12(), and tnaf_mod().
void bn_zero (bn_t a)
Assigns zero to a multiple precision integer.
Parameters
[out] a - the multiple precision integer to assign.
Definition at line 76 of file relic_bn_util.c.
References BN_POS, and dv_zero().
Referenced by bn_div_imp(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_mod_2b(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mul_basic(), bn_read_bin(), bn_read_str(), bn_set_dig(), bn_smb_jac(), bn_smb_leg(), bn_sqr_basic(), compute_kbltz(), cp_rabin_enc(), cp_rsa_enc(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), eb_curve_get_s0(), eb_curve_get_s1(), eb_curve_get_vm(), fp_inv_binar(), fp_inv_exgcd(), fp_inv_monty(), and pad_pkcs1().
int bn_is_zero (const bn_t a)
Tests if a multiple precision integer is zero or not.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 82 of file relic_bn_util.c.
Referenced by bn_div(), bn_div_dig(), bn_div_rem(), bn_div_rem_dig(), bn_gcd_basic(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_lehme(), bn_gcd_stein(), bn_is_even(), bn_is_factor(), bn_mod_pmers(), bn_mxp_basic(), bn_neg(), bn_rec_jsf(), bn_rec_naf(), bn_rec_tnaf(), bn_size_str(), bn_smb_jac(), bn_write_str(), cp_bbs_gen(), cp_bls_gen(), cp_ecdh_gen(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecmqv_gen(), cp_ecss_gen(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), cp_sokaka_gen(), eb_mul_basic(), eb_mul_fix_yaowi(), eb_tab(), ep_mul_basic(), fp_inv_monty(), fp_prime_conv(), fp_read(), and pad_pkcs1().
int bn_is_even (const bn_t a)
Tests if a multiple precision integer is even or odd.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 92 of file relic_bn_util.c.
References bn_is_zero().
Referenced by bn_factor(), bn_gcd_ext_stein(), bn_gcd_stein(), bn_is_prime_rabin(), bn_rec_naf(), bn_smb_jac(), fp12_exp_cyc(), fp18_exp_cyc(), and fp_srt().
int bn_bits (const bn_t a)
Returns the number of bits of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
number of bits.
Definition at line 102 of file relic_bn_util.c.
References BN_DIGIT, and util_bits_dig().
Referenced by bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_gen_prime_basic(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_ham(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lsh(), bn_mod_pmers(), bn_mod_pre_pmers(), bn_mxp_basic(), bn_mxp_slide(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_slw(), bn_rec_tnaf(), bn_rec_win(), bn_size_str(), cp_ecdh_gen(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecmqv_gen(), cp_ecmqv_key(), cp_ecss_gen(), cp_ecss_sig(), cp_ecss_ver(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), cp_sokaka_gen(), eb_map(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_halve(), eb_mul_lodah(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_pre_nafwi(), eb_mul_pre_yaowi(), eb_mul_sim_joint(), eb_rand(), ep2_mul(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_nafwi(), ep2_mul_pre_yaowi(), ep2_mul_sim_joint(), ep2_rand(), ep_curve_set_kbltz(), ep_map(), ep_mul_basic(), ep_mul_combs_kbltz(), ep_mul_combs_ordin(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_pre_nafwi(), ep_mul_pre_yaowi(), ep_mul_sim_joint(), ep_rand(), fb4_exp(), fb_exp_basic(), fp12_exp(), fp12_exp_cyc(), fp18_exp(), fp18_exp_cyc(), fp2_exp(), fp3_exp(), fp6_exp(), fp_exp_basic(), fp_param_get_sps(), pp_mil_k12(), pp_mil_k2(), and pp_mil_lit_k12().
int bn_test_bit (const bn_t a, int bit)
Tests the bit in the given position on a multiple precision integer.
Parameters
[in] a - the multiple precision integer to test.
[in] bit - the bit position.
Returns
0 is the bit is zero, not zero otherwise.
Definition at line 115 of file relic_bn_util.c.
References BN_DIG_LOG, and SPLIT.
Referenced by bn_ham(), bn_mxp_basic(), bn_rec_slw(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_lodah(), ep2_mul(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep_mul_basic(), ep_mul_combs_kbltz(), ep_mul_combs_ordin(), ep_mul_fix_basic(), ep_mul_fix_combd(), fb4_exp(), fb_exp_basic(), fp12_exp(), fp12_exp_cyc(), fp18_exp(), fp18_exp_cyc(), fp2_exp(), fp3_exp(), fp6_exp(), fp_exp_basic(), fp_param_get_sps(), pp_mil_k12(), pp_mil_k2(), and pp_mil_lit_k12().
int bn_get_bit (const bn_t a, int bit)
Reads the bit stored in the given position on a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
[in] bit - the bit position to read.
Returns
the bit value.
Definition at line 127 of file relic_bn_util.c.
References BN_DIG_LOG, and SPLIT.
Referenced by bn_rec_glv().
void bn_set_bit (bn_t a, int bit, int value)
Stores a bit in a given position on a multiple precision integer.
Parameters
[out] a - the multiple precision integer.
[in] bit - the bit position to store.
[in] value - the bit value.
Definition at line 139 of file relic_bn_util.c.
References BN_DIG_LOG, bn_trim(), and SPLIT.
Referenced by cp_ecmqv_key().
int bn_ham (const bn_t a)
Returns the Hamming weight of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
the number of non-zero bits.
Definition at line 155 of file relic_bn_util.c.
References bn_bits(), and bn_test_bit().
Referenced by fp12_exp_cyc(), fp18_exp_cyc(), and fp_param_get_sps().
void bn_get_dig (dig_t * digit, const bn_t a)
Reads the first digit in a multiple precision integer.
Parameters
[out] digit - the result.
[in] a - the multiple precision integer.
Definition at line 167 of file relic_bn_util.c.
Referenced by bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), and tnaf_mod().
void bn_set_dig (bn_t a, dig_t digit)
Assigns a small positive constant to a multiple precision integer.
The constant must fit on a multiple precision digit, or dig_t type using only the number of bits specified on BN_DIGIT.
Parameters
[out] a - the result.
[in] digit - the constant to assign.
Definition at line 171 of file relic_bn_util.c.
References BN_POS, and bn_zero().
Referenced by bn_factor(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_is_prime_rabin(), bn_mod_barrt(), bn_mod_pre_monty(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), bn_smb_jac(), bn_smb_leg(), compute_kbltz(), eb_tab(), fp_inv_binar(), fp_inv_exgcd(), fp_inv_monty(), fp_param_get_var(), fp_param_set(), and fp_prime_set().
void bn_set_2b (bn_t a, int b)
Assigns a multiple precision integer to 2^b.
Parameters
[out] a - the result.
[in] b - the power of 2 to assign.
Definition at line 178 of file relic_bn_util.c.
References BN_DIG_LOG, bn_grow(), BN_POS, and SPLIT.
Referenced by bn_mod_pre_barrt(), bn_mod_pre_pmers(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), fp_inv_monty(), fp_param_get_var(), fp_prime_set_pmers(), and tnaf_mod().
void bn_rand (bn_t a, int sign, int bits)
Assigns a random value to a multiple precision integer.
Parameters
[out] a - the multiple precision integer to assign.
[in] sign - the sign to be assigned (BN_NEG or BN_POS).
[in] bits - the number of bits.
Definition at line 191 of file relic_bn_util.c.
References BN_DIG_LOG, BN_DIGIT, bn_grow(), bn_trim(), rand_bytes(), and SPLIT.
Referenced by bn_gen_prime_basic(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_is_prime_solov(), cp_bbs_gen(), cp_bls_gen(), cp_ecdh_gen(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecmqv_gen(), cp_ecss_gen(), cp_ecss_sig(), cp_sokaka_gen(), eb_mul_halve(), eb_rand(), ep2_rand(), and ep_rand().
void bn_print (const bn_t a)
Prints a multiple precision integer to standard output.
Parameters
[in] a - the multiple precision integer to print.
Definition at line 210 of file relic_bn_util.c.
References BN_DIGIT, BN_NEG, and util_print.
void bn_size_str (int * size, const bn_t a, int radix)
Returns the number of digits in radix necessary to store a multiple precision integer. The radix must be included in the interval [2, 64].
Parameters
[out] size - the result.
[in] a - the multiple precision integer.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Definition at line 236 of file relic_bn_util.c.
References bn_bits(), bn_copy(), bn_div_dig(), bn_free, bn_is_zero(), BN_NEG, bn_new, bn_null, BN_POS, CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FINALLY, THROW, and TRY.
Referenced by bn_write_str(), and fp_size().
void bn_read_str (bn_t a, const char * str, int len, int radix)
Reads a multiple precision integer from a string in a given radix. The radix must be included in the interval [2, 64].
Parameters
[out] a - the result.
[in] str - the string.
[in] len - the size of the string.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Definition at line 285 of file relic_bn_util.c.
References bn_add_dig(), bn_mul_dig(), BN_NEG, BN_POS, bn_zero(), ERR_NO_VALID, THROW, TOUPPER, and util_conv_char().
Referenced by fp_param_set(), and fp_read().
void bn_write_str (char * str, int len, const bn_t a, int radix)
Writes a multiple precision integer to a string in a given radix. The radix must be included in the interval [2, 64].
Parameters
[out] str - the string.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
[in] radix - the radix.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
ERR_NO_VALID - if the radix is invalid.
Definition at line 323 of file relic_bn_util.c.
References bn_copy(), bn_div_rem_dig(), bn_free, bn_is_zero(), BN_NEG, bn_new, bn_null, BN_POS, bn_size_str(), CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_VALID, FINALLY, THROW, TRY, and util_conv_char().
Referenced by fp_write().
void bn_size_bin (int * size, const bn_t a)
Returns the number of bytes necessary to store a multiple precision integer.
Parameters
[out] size - the result.
[in] a - the multiple precision integer.
Definition at line 390 of file relic_bn_util.c.
References BN_DIGIT.
Referenced by bn_write_bin(), cp_ecdh_key(), cp_ecmqv_key(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), and cp_sokaka_key().
void bn_read_bin (bn_t a, const unsigned char * bin, int len)
Reads a positive multiple precision integer from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Definition at line 404 of file relic_bn_util.c.
References BN_DIGIT, bn_grow(), BN_POS, bn_trim(), and bn_zero().
Referenced by cp_bbs_sig(), cp_bbs_ver(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), eb_map(), ep2_map(), ep_map(), and pad_pkcs1().
void bn_write_bin (unsigned char * bin, int len, const bn_t a)
Writes a positive multiple precision integer to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 434 of file relic_bn_util.c.
References BN_DIGIT, bn_size_bin(), ERR_NO_BUFFER, and THROW.
Referenced by cp_ecdh_key(), cp_ecmqv_key(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), and cp_sokaka_key().
void bn_size_raw (int * size, const bn_t a)
Returns the number of digits necessary to store a multiple precision integer.
Parameters
[out] size - the result.
[in] a - the multiple precision integer.
Definition at line 464 of file relic_bn_util.c.
void bn_read_raw (bn_t a, const dig_t * raw, int len)
Reads a positive multiple precision integer from a digit vector.
Parameters
[out] a - the result.
[in] raw - the digit vector.
[in] len - the size of the string.
Definition at line 468 of file relic_bn_util.c.
References bn_grow(), BN_POS, bn_trim(), and dv_copy().
void bn_write_raw (dig_t * raw, int len, const bn_t a)
Writes a positive multiple precision integer to a byte vector.
Parameters
[out] raw - the digit vector.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
[in] sign - the sign.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 476 of file relic_bn_util.c.
References ERR_NO_BUFFER, and THROW.
int bn_cmp_abs (const bn_t a, const bn_t b)
Returns the result of an unsigned comparison between two multiple precision integers.
Parameters
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Returns
CMP_LT if a < b, CMP_EQ if a == b and CMP_GT if a > b.
Definition at line 39 of file relic_bn_cmp.c.
References bn_cmpn_low(), CMP_GT, and CMP_LT.
Referenced by bn_add(), bn_cmp(), bn_div_imp(), bn_gcd_ext_mid(), bn_lcm(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), and bn_sub().
int bn_cmp_dig (const bn_t a, dig_t b)
Returns the result of a signed comparison between a multiple precision integer and a digit.
Parameters
[in] a - the multiple precision integer.
[in] b - the digit.
Returns
CMP_LT if a < b, CMP_EQ if a == b and CMP_GT if a > b.
Definition at line 51 of file relic_bn_cmp.c.
References bn_cmp1_low(), BN_NEG, CMP_GT, and CMP_LT.
Referenced by bn_factor(), bn_is_prime_basic(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_smb_jac(), cp_rabin_gen(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), eb_mul_halve(), fp_inv_binar(), fp_inv_exgcd(), and tnaf_mod().
int bn_cmp (const bn_t a, const bn_t b)
Returns the result of a signed comparison between two multiple precision integers.
Parameters
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Returns
CMP_LT if a < b, CMP_EQ if a == b and CMP_GT if a > b.
Definition at line 63 of file relic_bn_cmp.c.
References bn_cmp_abs(), BN_NEG, BN_POS, CMP_GT, and CMP_LT.
Referenced by bn_factor(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_lehme(), bn_gcd_stein(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_barrt(), bn_smb_leg(), cp_ecdsa_ver(), cp_ecss_ver(), cp_rabin_dec(), cp_rabin_gen(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), fp_inv_binar(), and fp_inv_monty().
void bn_add (bn_t c, const bn_t a, const bn_t b)
Adds two multiple precision integers. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to add.
[in] b - the second multiple precision integer to add.
Definition at line 101 of file relic_bn_add.c.
References bn_add_imp(), bn_cmp_abs(), bn_sub_imp(), and CMP_LT.
Referenced by bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_lehme(), bn_gen_prime_stron(), bn_is_prime_solov(), bn_mod_barrt(), bn_mod_monty_conv(), bn_mod_pmers(), bn_mul_karat_imp(), bn_rec_glv(), bn_rec_tnaf(), bn_smb_jac(), bn_sqr_karat_imp(), cp_bbs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecmqv_key(), cp_ecss_sig(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), eb_tab(), ep_curve_set_kbltz(), fp_inv_binar(), fp_inv_exgcd(), fp_inv_monty(), fp_param_get_var(), fp_param_set(), fp_prime_set_pmers(), pad_pkcs1(), and tnaf_mod().
void bn_add_dig (bn_t c, const bn_t a, dig_t b)
Adds a multiple precision integers and a digit. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to add.
[in] b - the digit to add.
Definition at line 127 of file relic_bn_add.c.
References bn_add1_low(), bn_grow(), BN_NEG, BN_POS, bn_sub1_low(), and bn_trim().
Referenced by bn_gen_prime_safep(), bn_gen_prime_stron(), bn_read_str(), bn_rec_glv(), bn_rec_naf(), bn_rec_reg(), bn_rec_tnaf(), compute_kbltz(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), eb_map(), eb_tab(), fp_param_get_var(), fp_param_set(), fp_prime_set_pmers(), fp_srt(), pad_pkcs1(), pp_exp_k2(), and tnaf_mod().
void bn_sub (bn_t c, const bn_t a, const bn_t b)
Subtracts a multiple precision integer from another, that is, computes c = a - b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer.
[in] b - the multiple precision integer to subtract.
Definition at line 160 of file relic_bn_add.c.
References bn_add_imp(), bn_cmp_abs(), BN_NEG, BN_POS, bn_sub_imp(), and CMP_LT.
Referenced by bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_stein(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_pmers(), bn_mod_pre_pmers(), bn_mul_karat_imp(), bn_rec_glv(), bn_rec_tnaf(), bn_sqr_karat_imp(), compute_kbltz(), cp_ecss_sig(), cp_rabin_dec(), cp_rsa_dec_quick(), cp_rsa_sig_quick(), eb_tab(), ep_curve_set_kbltz(), fp_inv_binar(), fp_inv_exgcd(), fp_param_get_var(), fp_param_set(), fp_prime_set_pmers(), and tnaf_mod().
void bn_sub_dig (bn_t c, const bn_t a, const dig_t b)
Subtracts a digit from a multiple precision integer. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer.
[in] b - the digit to subtract.
Definition at line 187 of file relic_bn_add.c.
References bn_add1_low(), bn_grow(), BN_NEG, BN_POS, bn_sub1_low(), and bn_trim().
Referenced by bn_factor(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_rec_naf(), bn_rec_reg(), bn_rec_tnaf(), bn_smb_leg(), compute_kbltz(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), eb_tab(), fp2_calc(), fp3_calc(), fp3_srt(), fp_inv_basic(), fp_param_set(), fp_prime_set_pmers(), pp_map_tatep_k2(), pp_map_weilp_k2(), and tnaf_mod().
void bn_mul_dig (bn_t c, const bn_t a, dig_t b)
Multiplies a multiple precision integer by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to multiply.
[in] b - the digit to multiply.
Definition at line 177 of file relic_bn_mul.c.
References bn_grow(), bn_mul1_low(), and bn_trim().
Referenced by bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_stron(), bn_mod_pmers(), bn_read_str(), and fp_param_set().
void bn_mul_basic (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Schoolbook multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 193 of file relic_bn_mul.c.
References bn_copy(), bn_free, bn_mula_low(), bn_new_size, bn_null, bn_trim(), bn_zero(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by bn_mul_karat_imp().
void bn_mul_comba (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Comba multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 228 of file relic_bn_mul.c.
References bn_copy(), bn_free, bn_muld_low(), bn_muln_low(), bn_new_size, bn_null, bn_trim(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by bn_mul_karat_imp(), and bn_sqr_karat_imp().
void bn_mul_karat (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 269 of file relic_bn_mul.c.
References BN_KARAT, and bn_mul_karat_imp().
void bn_sqr_basic (bn_t c, const bn_t a)
Computes the square of a multiple precision integer using Schoolbook squaring.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to square.
Definition at line 160 of file relic_bn_sqr.c.
References bn_copy(), bn_free, bn_new_size, bn_null, BN_POS, bn_sqra_low(), bn_trim(), bn_zero(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by bn_sqr_karat_imp().
void bn_sqr_comba (bn_t c, const bn_t a)
Computes the square of a multiple precision integer using Comba squaring.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to square.
Definition at line 193 of file relic_bn_sqr.c.
References bn_copy(), bn_free, bn_new_size, bn_null, BN_POS, bn_sqrn_low(), bn_trim(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by bn_sqr_karat_imp().
void bn_sqr_karat (bn_t c, const bn_t a)
Computes the square of a multiple precision integer using Karatsuba squaring.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to square.
Definition at line 223 of file relic_bn_sqr.c.
References BN_KARAT, and bn_sqr_karat_imp().
void bn_dbl (bn_t c, const bn_t a)
Doubles a multiple precision. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to double.
Definition at line 39 of file relic_bn_shift.c.
References bn_grow(), and bn_lsh1_low().
Referenced by bn_gen_prime_stron(), compute_kbltz(), ep_curve_set_kbltz(), fp_inv_monty(), fp_param_set(), and tnaf_mod().
void bn_hlv (bn_t c, const bn_t a)
Halves a multiple precision. Computes c = floor(a / 2)
Parameters
[out] c - the result.
[in] a - the multiple precision integer to halve.
Definition at line 56 of file relic_bn_shift.c.
References bn_grow(), bn_rsh1_low(), and bn_trim().
Referenced by bn_gcd_ext_stein(), bn_gcd_stein(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_tnaf(), eb_tab(), ep_curve_set_kbltz(), and fp_inv_binar().
void bn_lsh (bn_t c, const bn_t a, int bits)
Shifts a multiple precision number to the left. Computes c = a * 2^bits. c = a * 2^bits.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] bits - the number of bits to shift.
Definition at line 66 of file relic_bn_shift.c.
References bn_bits(), bn_copy(), BN_DIG_LOG, BN_DIGIT, bn_grow(), bn_lshb_low(), bn_lshd_low(), bn_trim(), and SPLIT.
Referenced by bn_gcd_ext_stein(), bn_gcd_stein(), bn_gen_prime_safep(), bn_is_prime_rabin(), bn_mod_barrt(), bn_mod_monty_conv(), bn_mul_karat_imp(), bn_sqr_karat_imp(), cp_rabin_enc(), eb_mul_halve(), ep_curve_set_kbltz(), fp_param_get_var(), fp_prime_conv(), fp_prime_set(), fp_srt(), and pad_pkcs1().
void bn_rsh (bn_t c, const bn_t a, int bits)
Shifts a multiple precision number to the right. Computes c = floor(a / 2^bits).
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] bits - the number of bits to shift.
Definition at line 105 of file relic_bn_shift.c.
References bn_copy(), BN_DIG_LOG, bn_rshb_low(), bn_rshd_low(), bn_trim(), and SPLIT.
Referenced by bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_safep(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_pmers(), bn_rec_glv(), bn_rec_reg(), bn_smb_jac(), bn_smb_leg(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), fp_srt(), pad_pkcs1(), and tnaf_mod().
void bn_div (bn_t c, const bn_t a, const bn_t b)
Divides a multiple precision integer by another multiple precision integer without computing the remainder. Computes c = floor(a / b).
Parameters
[out] c - the resultint quotient.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 113 of file relic_bn_div.c.
References bn_div_imp(), bn_is_zero(), ERR_NO_VALID, and THROW.
Referenced by bn_gcd_ext_lehme(), bn_lcm(), bn_mod_pre_barrt(), ep_curve_set_kbltz(), and pp_exp_k2().
void bn_div_rem (bn_t c, bn_t d, const bn_t a, const bn_t b)
Divides a multiple precision integer by another multiple precision integer. Computes c = floor(a / b) and d = a mod b.
Parameters
[out] c - the resulting quotient.
[out] d - the remainder.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 120 of file relic_bn_div.c.
References bn_div_imp(), bn_is_zero(), ERR_NO_VALID, and THROW.
Referenced by bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_mod_basic(), and fp_inv_exgcd().
void bn_div_dig (bn_t c, const bn_t a, dig_t b)
Divides a multiple precision integers by a digit without computing the remainder. Computes c = floor(a / b).
Parameters
[out] c - the resulting quotient.
[out] d - the remainder.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 127 of file relic_bn_div.c.
References bn_copy(), bn_div1_low(), bn_free, bn_is_zero(), bn_new, bn_null, bn_trim(), CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FINALLY, THROW, and TRY.
Referenced by bn_size_str(), fp2_calc(), fp3_calc(), fp3_srt(), and fp_param_set().
void bn_div_rem_dig (bn_t c, dig_t * d, const bn_t a, const dig_t b)
Divides a multiple precision integers by a digit. Computes c = floor(a / b) and d = a mod b.
Parameters
[out] c - the resulting quotient.
[out] d - the remainder.
[in] a - the dividend.
[in] b - the divisor.
Exceptions
ERR_NO_VALID - if the divisor is zero.
Definition at line 166 of file relic_bn_div.c.
References bn_copy(), bn_div1_low(), bn_free, bn_is_zero(), bn_new, bn_null, bn_trim(), CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FINALLY, THROW, and TRY.
Referenced by bn_mod_dig(), and bn_write_str().
void bn_mod_2b (bn_t c, const bn_t a, int b)
Reduces a multiple precision integer modulo a power of 2. Computes c = a mod 2^b.
Parameters
[out] c - the result.
[in] a - the dividend.
[in] b - the exponent of the divisor.
Definition at line 40 of file relic_bn_mod.c.
References bn_copy(), BN_DIG_LOG, BN_DIGIT, bn_trim(), bn_zero(), MASK, and SPLIT.
Referenced by bn_mod_barrt(), bn_mod_pmers(), bn_smb_jac(), cp_ecmqv_key(), cp_rabin_dec(), cp_rabin_enc(), cp_rabin_gen(), eb_map(), and pad_pkcs1().
void bn_mod_dig (dig_t * c, const bn_t a, dig_t b)
Reduces a multiple precision integer modulo a digit. Computes c = a mod b.
Parameters
[out] c - the result.
[in] a - the dividend.
[in] b - the divisor.
Definition at line 66 of file relic_bn_mod.c.
References bn_div_rem_dig().
Referenced by bn_gcd_dig(), bn_is_prime_basic(), and fp_prime_set().
void bn_mod_basic (bn_t c, const bn_t a, const bn_t m)
Reduces a multiple precision integer modulo a modulus using straightforward division.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
Definition at line 70 of file relic_bn_mod.c.
References bn_div_rem().
void bn_mod_pre_barrt (bn_t u, const bn_t m)
Computes the reciprocal of the modulus to be used in the Barrett modular reduction algorithm.
Parameters
[out] u - the result.
[in] m - the modulus.
Definition at line 76 of file relic_bn_mod.c.
References BN_DIGIT, bn_div(), and bn_set_2b().
void bn_mod_barrt (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a modulus using Barrett reduction.
Parameters
[out] c - the result.
[in] a - the the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the reciprocal of the modulus.
Definition at line 81 of file relic_bn_mod.c.
References bn_add(), bn_cmp(), bn_copy(), BN_DIGIT, bn_free, bn_lsh(), bn_mod_2b(), bn_mul, bn_muld_low(), BN_NEG, bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sign(), bn_sub(), bn_trim(), bn_zero(), CATCH_ANY, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_mod_pre_monty (bn_t u, const bn_t m)
Computes the reciprocal of the modulus to be used in the Montgomery reduction algorithm.
Parameters
[out] u - the result.
[in] m - the modulus.
Exceptions
ERR_NO_VALID - if the modulus is even.
Definition at line 155 of file relic_bn_mod.c.
References bn_set_dig(), ERR_NO_VALID, and THROW.
Referenced by bn_mod_monty_back(), and fp_prime_set().
void bn_mod_monty_conv (bn_t c, const bn_t a, const bn_t m)
Converts a multiple precision integer to Montgomery form.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to convert.
[in] m - the modulus.
Definition at line 178 of file relic_bn_mod.c.
References bn_add(), bn_copy(), BN_DIGIT, bn_lsh(), bn_mod, BN_NEG, and bn_sign().
Referenced by bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), and fp_inv_monty().
void bn_mod_monty_back (bn_t c, const bn_t a, const bn_t m)
Converts a multiple precision integer from Montgomery form.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to convert.
[in] m - the modulus.
Definition at line 188 of file relic_bn_mod.c.
References bn_free, bn_mod_monty, bn_mod_pre_monty(), bn_new, bn_null, CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), and fp_inv_monty().
void bn_mod_monty_basic (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a modulus using Montgomery reduction with Schoolbook multiplication.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the reciprocal of the modulus.
Definition at line 207 of file relic_bn_mod.c.
References bn_add1_low(), bn_cmp_abs(), bn_copy(), BN_DIGIT, bn_free, bn_mula_low(), bn_new_size, bn_null, bn_rsh(), bn_sub(), bn_trim(), bn_zero(), CATCH_ANY, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_mod_monty_comba (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a modulus using Montgomery reduction with Comba multiplication.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the reciprocal of the modulus.
Definition at line 249 of file relic_bn_mod.c.
References bn_cmp_abs(), bn_copy(), bn_free, bn_modn_low(), bn_new_size, bn_null, bn_sub(), bn_trim(), bn_zero(), CATCH_ANY, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_mod_pre_pmers (bn_t u, const bn_t m)
Computes u if the modulus has the form 2^b - u.
Parameters
[out] u - the result.
[in] m - the modulus.
Definition at line 283 of file relic_bn_mod.c.
References bn_bits(), bn_set_2b(), and bn_sub().
void bn_mod_pmers (bn_t c, const bn_t a, const bn_t m, const bn_t u)
Reduces a multiple precision integer modulo a modulus using Pseudo-Mersenne modular reduction.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to reduce.
[in] m - the modulus.
[in] u - the auxiliar value derived from the modulus.
Definition at line 292 of file relic_bn_mod.c.
References bn_add(), bn_bits(), bn_cmp_abs(), bn_copy(), bn_free, bn_is_zero(), bn_mod_2b(), bn_mul, bn_mul_dig(), bn_new, bn_null, bn_rsh(), bn_sub(), CATCH_ANY, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_mxp_basic (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a modulus using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 49 of file relic_bn_mxp.c.
References bn_bits(), bn_copy(), bn_free, bn_is_zero(), bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sqr, bn_test_bit(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_mxp_slide (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a modulus using the sliding window method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 108 of file relic_bn_mxp.c.
References BN_BITS, bn_bits(), bn_copy(), bn_free, bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_rec_slw(), bn_set_dig(), bn_sqr, bn_trim(), CATCH_ANY, ERR_CAUGHT, FINALLY, TABLE_SIZE, THROW, TRY, and util_bits_dig().
void bn_mxp_monty (bn_t c, const bn_t a, const bn_t b, const bn_t m)
Exponentiates a multiple precision integer modulo a modulus using a constant-time Montgomery powering ladder method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 204 of file relic_bn_mxp.c.
References bn_copy(), BN_DIGIT, bn_free, bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sqr, CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_mxp_dig (bn_t c, const bn_t a, dig_t b, const bn_t m)
Exponentiates a multiple precision integer by a small power modulo a modulus using the binary method.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
[in] m - the modulus.
Definition at line 274 of file relic_bn_mxp.c.
References bn_copy(), bn_free, bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sqr, CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, TRY, and util_bits_dig().
void bn_gcd_basic (bn_t c, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using the standard Euclidean algorithm.
Parameters
[out] c - the result;
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 40 of file relic_bn_gcd.c.
References bn_abs(), bn_copy(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_gcd_lehme (bn_t c, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using Lehmer's GCD algorithm.
Parameters
[out] c - the result;
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 169 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_bits(), bn_cmp(), bn_copy(), BN_DIGIT, bn_free, bn_gcd_ext_dig(), bn_is_zero(), bn_mod, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_rsh(), CATCH_ANY, CMP_GT, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_gcd_stein (bn_t c, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using Stein's binary GCD algorithm.
Parameters
[out] c - the result;
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 602 of file relic_bn_gcd.c.
References bn_abs(), bn_cmp(), bn_copy(), bn_free, bn_hlv(), bn_is_even(), bn_is_zero(), bn_lsh(), bn_new, bn_null, bn_sub(), CATCH_ANY, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_gcd_dig (bn_t c, const bn_t a, dig_t b)
Computes the greatest common divisor of a multiple precision integer and a digit.
Parameters
[out] c - the result;
[in] a - the multiple precision integer.
[in] b - the digit.
Definition at line 945 of file relic_bn_gcd.c.
References bn_abs(), bn_is_zero(), bn_mod_dig(), and bn_set_dig().
Referenced by bn_gcd_ext_dig().
void bn_gcd_ext_basic (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
Computes the extended greatest common divisor of two multiple precision integer using the Euclidean algorithm.
Parameters
[out] c - the result.
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 77 of file relic_bn_gcd.c.
References bn_abs(), bn_copy(), bn_div_rem(), bn_free, bn_is_zero(), bn_mul, bn_new, bn_null, bn_set_dig(), bn_sub(), bn_zero(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_gcd_ext_lehme (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using Lehmer's algorithm.
Parameters
[out] c - the result;
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 350 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_bits(), bn_cmp(), bn_copy(), BN_DIGIT, bn_div(), bn_div_rem(), bn_free, bn_gcd_ext_dig(), bn_is_zero(), bn_mul, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sub(), bn_zero(), CATCH_ANY, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_gcd_ext_stein (bn_t c, bn_t d, bn_t e, const bn_t a, const bn_t b)
Computes the greatest common divisor of two multiple precision integers using Stein's binary algorithm.
Parameters
[out] c - the result;
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 662 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_cmp(), bn_copy(), bn_free, bn_hlv(), bn_is_even(), bn_is_zero(), bn_lsh(), bn_new, bn_null, bn_set_dig(), bn_sub(), bn_zero(), CATCH_ANY, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_gcd_ext_mid (bn_t c, bn_t d, bn_t e, bn_t f, const bn_t a, const bn_t b)
Computes the extended greatest common divisor of two multiple precision halfway through the algorithm returning also two short vectors v1 = (c, d), v2 = (-d, e) useful to decompose an integer k into k0, k1 such that k = k_0 + k_1 * a (mod b).
Parameters
[out] c - the first component of the first vector.
[out] d - the second component of the first vector.
[out] e - the first component of the second vector.
[out] f - the second component of the second vector.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
Definition at line 833 of file relic_bn_gcd.c.
References bn_abs(), bn_add(), bn_bits(), bn_cmp(), bn_cmp_abs(), bn_copy(), bn_div_rem(), bn_free, bn_is_zero(), bn_mul, bn_neg(), bn_new, bn_null, bn_set_dig(), bn_sqr, bn_sub(), bn_zero(), CATCH_ANY, CMP_GT, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by ep_curve_set_kbltz().
void bn_gcd_ext_dig (bn_t c, bn_t d, bn_t e, const bn_t a, dig_t b)
Computes the extended greatest common divisor of a multiple precision integer and a digit.
Parameters
[out] c - the result.
[out] d - the cofactor of the first operand, can be NULL.
[out] e - the cofactor of the second operand, can be NULL.
[in] a - the multiple precision integer.
[in] b - the digit.
Definition at line 969 of file relic_bn_gcd.c.
References bn_abs(), bn_copy(), bn_div_rem(), bn_free, bn_gcd_dig(), bn_is_zero(), bn_mul, bn_mul_dig(), bn_new, bn_null, bn_set_dig(), bn_sub(), bn_zero(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by bn_gcd_ext_lehme(), and bn_gcd_lehme().
void bn_lcm (bn_t c, const bn_t a, const bn_t b)
Computes the last common multiple of two multiple precision integers. Computes c = lcm(a, b).
Parameters
[out] c - the result.
[in] a - the first integer.
[in] b - the second integer.
Definition at line 38 of file relic_bn_lcm.c.
References bn_cmp_abs(), bn_div(), bn_free, bn_gcd, bn_mul, bn_new, bn_null, BN_POS, CATCH_ANY, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_smb_leg (bn_t c, const bn_t a, const bn_t b)
Computes the Legendre symbol c = (a|b), b prime.
Parameters
[out] c - the result.
[in] a - the first parameter.
[in] b - the second parameter.
Definition at line 38 of file relic_bn_smb.c.
References bn_cmp(), bn_free, bn_mxp, bn_neg(), BN_NEG, bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sign(), bn_sub_dig(), bn_zero(), CATCH_ANY, CMP_EQ, ERR_CAUGHT, ERR_NO_VALID, FINALLY, THROW, and TRY.
void bn_smb_jac (bn_t c, const bn_t a, const bn_t b)
Computes the Jacobi symbol c = (a|b).
Parameters
[out] c - the result.
[in] a - the first parameter.
[in] b - the second parameter.
Definition at line 77 of file relic_bn_smb.c.
References bn_add(), bn_cmp_dig(), bn_copy(), bn_free, bn_is_even(), bn_is_zero(), bn_mod, bn_mod_2b(), bn_neg(), BN_NEG, bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sign(), bn_zero(), CATCH_ANY, CMP_EQ, ERR_CAUGHT, ERR_NO_VALID, FINALLY, THROW, and TRY.
Referenced by bn_is_prime_solov().
dig_t bn_get_prime (int pos)
Returns a small precomputed prime from a given position in the list of prime numbers.
Parameters
[in] pos - the position in the prime sequence.
Returns
a prime if the position is lower than 512, 0 otherwise.
Definition at line 173 of file relic_bn_prime.c.
References BASIC_TESTS, and primes.
int bn_is_prime (const bn_t a)
Tests if a number is a probable prime.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if a is prime, 0 otherwise.
Definition at line 180 of file relic_bn_prime.c.
References bn_is_prime_basic(), and bn_is_prime_rabin().
Referenced by bn_gen_prime_basic(), bn_gen_prime_safep(), bn_gen_prime_stron(), and fp_param_set_any_dense().
int bn_is_prime_basic (const bn_t a)
Tests if a number is prime using a series of trial divisions.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 197 of file relic_bn_prime.c.
References BASIC_TESTS, bn_cmp_dig(), bn_mod_dig(), CMP_EQ, and primes.
Referenced by bn_is_prime().
int bn_is_prime_rabin (const bn_t a)
Tests if a number a > 2 is prime using the Miller-Rabin test with probability 2^(-80) of error.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 218 of file relic_bn_prime.c.
References bn_bits(), bn_cmp(), bn_cmp_dig(), bn_free, bn_is_even(), bn_lsh(), bn_mod, bn_mxp, bn_new, bn_null, bn_rsh(), bn_set_dig(), bn_sqr, bn_sub_dig(), CATCH_ANY, CMP_EQ, ERR_CAUGHT, FINALLY, primes, THROW, and TRY.
Referenced by bn_is_prime().
int bn_is_prime_solov (const bn_t a)
Tests if a number a > 2 is prime using the Solovay-Strassen test with probability 2^(-80) of error.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 326 of file relic_bn_prime.c.
References bn_add(), bn_bits(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_mod, bn_mxp, BN_NEG, bn_new, bn_null, BN_POS, bn_rand(), bn_rsh(), bn_sign(), bn_smb_jac(), bn_sub_dig(), CATCH_ANY, CMP_EQ, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_gen_prime_basic (bn_t a, int bits)
Generates a probable prime number.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 392 of file relic_bn_prime.c.
References bn_bits(), bn_is_prime(), BN_POS, and bn_rand().
void bn_gen_prime_safep (bn_t a, int bits)
Generates a probable prime number a with (a - 1)/2 also prime.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 407 of file relic_bn_prime.c.
References bn_add_dig(), bn_bits(), bn_is_prime(), bn_lsh(), BN_POS, bn_rand(), bn_rsh(), and bn_sub_dig().
void bn_gen_prime_stron (bn_t a, int bits)
Generates a probable prime number with (a - 1)/2, (a + 1)/2 and ((a - 1)/2 - 1)/2 also prime.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 431 of file relic_bn_prime.c.
References bn_add(), bn_add_dig(), bn_bits(), bn_dbl(), BN_DIGIT, bn_free, bn_is_prime(), bn_mul, bn_mul_dig(), bn_mxp, bn_new, bn_null, BN_POS, bn_rand(), bn_sub_dig(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
int bn_factor (bn_t c, const bn_t a)
Tries to factorize an integer using Pollard (p - 1) factoring algorithm. The maximum length of the returned factor is 16 bits.
Parameters
[out] c - the resulting factor.
[in] a - the integer to fatorize.
Returns
1 if a factor is found and stored into c; 0 otherwise.
Definition at line 38 of file relic_bn_factor.c.
References bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd, bn_is_even(), bn_mxp, bn_new, bn_null, bn_set_dig(), bn_sub_dig(), CATCH_ANY, CMP_GT, CMP_LT, ERR_CAUGHT, FINALLY, THROW, and TRY.
int bn_is_factor (bn_t c, const bn_t a)
Tests if an integer divides other integer.
Parameters
[in] c - the factor.
[in] a - the integer.
Returns
1 if the first integer is a factor; 0 otherwise.
Definition at line 85 of file relic_bn_factor.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
void bn_rec_win (unsigned char * win, int * len, const bn_t k, int w)
Recodes an integer in window form.
Parameters
[out] win - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 288 of file relic_bn_rec.c.
References bn_bits(), CEIL, ERR_NO_BUFFER, get_bits(), and THROW.
Referenced by eb_mul_fix_yaowi(), eb_mul_sim_trick(), ep2_mul_fix_yaowi(), ep2_mul_sim_trick(), ep_mul_fix_yaowi(), and ep_mul_sim_trick().
void bn_rec_slw (unsigned char * win, int * len, const bn_t k, int w)
Recodes an integer in sliding window form.
Parameters
[out] win - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 305 of file relic_bn_rec.c.
References bn_bits(), bn_test_bit(), CEIL, ERR_NO_BUFFER, get_bits(), MAX, and THROW.
Referenced by bn_mxp_slide(), ep_mul_slide(), fb_exp_slide(), and fp_exp_slide().
void bn_rec_naf (signed char * naf, int * len, const bn_t k, int w)
Recodes an integer in width-w Non-Adjacent Form.
Parameters
[out] naf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 332 of file relic_bn_rec.c.
References bn_add_dig(), bn_bits(), bn_copy(), bn_free, bn_get_dig(), bn_hlv(), bn_is_even(), bn_is_zero(), bn_new, bn_null, bn_sub_dig(), CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, MASK, THROW, and TRY.
Referenced by eb_mul_fix_nafwi(), eb_mul_fix_ordin(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_rnaf_imp(), eb_mul_sim_ordin(), ep2_mul_fix_nafwi(), ep2_mul_fix_ordin(), ep2_mul_sim_ordin(), ep_mul_fix_nafwi(), ep_mul_fix_ordin(), ep_mul_glv_imp(), ep_mul_naf_imp(), ep_mul_sim_kbltz(), ep_mul_sim_ordin(), and fp2_exp_uni().
void bn_rec_tnaf (signed char * tnaf, int * len, const bn_t k, const bn_t vm, const bn_t s0, const bn_t s1, signed char u, int m, int w)
Recodes an integer in width-w t-NAF.
Parameters
[out] tnaf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] vm - the V_m curve parameter.
[in] s0 - the S_0 curve parameter.
[in] s1 - the S_1 curve parameter.
[in] u - the u curve parameter.
[in] m - the extension degree of the binary field.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 402 of file relic_bn_rec.c.
References bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_free, bn_hlv(), bn_is_zero(), BN_NEG, bn_new, bn_null, bn_sign(), bn_sub(), bn_sub_dig(), CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, MASK, THROW, tnaf_mod(), and TRY.
Referenced by eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), and eb_mul_sim_kbltz().
void bn_rec_reg (signed char * naf, int * len, const bn_t k, int n, int w)
Recodes an integer in regular fixed-length width-w NAF.
Parameters
[out] naf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] n - the length of the recoding.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 657 of file relic_bn_rec.c.
References bn_add_dig(), bn_copy(), bn_free, bn_get_dig(), bn_hlv(), bn_new, bn_null, bn_rsh(), bn_sub_dig(), CATCH_ANY, CEIL, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, MASK, THROW, and TRY.
Referenced by ep_mul_reg_imp().
void bn_rec_jsf (signed char * jsf, int * len, const bn_t k, const bn_t l)
Recodes a pair of integers in Joint Sparse Form.
Parameters
[out] jsf - the recoded pair of integers.
[out] len - the number of bytes written.
[in] k - the first integer to recode.
[in] l - the second integer to recode.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 712 of file relic_bn_rec.c.
References bn_bits(), bn_copy(), bn_free, bn_get_dig(), bn_hlv(), bn_is_zero(), bn_new, bn_null, CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, MASK, MAX, THROW, and TRY.
Referenced by eb_mul_sim_joint(), ep2_mul_sim_joint(), and ep_mul_sim_joint().
void bn_rec_glv (bn_t k0, bn_t k1, const bn_t k, const bn_t n, const bn_t v1[], const bn_t v2[])
Recodes an integer in two parts such that k = k0 + phi(k1), where phi is the efficient curve endomorphism.
Parameters
[out] k0 - the first part of the result.
[out] k1 - the second part of the result.
[in] k - the integer to recode.
[in] n - the group order.
[in] v1 - the set of parameters v1 for the GLV method.
[in] v2 - the set of parameters v2 for the GLV method.